### ISSUE TITLE
Ticket Template

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Feedback#1]
Creating this ticket to track discussion/ideas on how we should structure our tickets in this repo, what information they should include, and how to distribute the task of ingesting data if a new source is found.  To my mind, the minimum information we would need would be

1. What type of data is missing?
2. What would those data allow us to do if we had it?  A specific use case being helpful here.
3. What are the requirements for those data? (e.g must have chemical structure in SMILES format)

**Comment by sstemann** [comment]
OBE
