### ISSUE TITLE
When I search for "Biermer anemia" (a synonym of "pernicious anemia" in MONDO:0008228), I get the official name of the MONDO term back in the autocomplete.  But, as a user, it would be helpful to see the synonym somehow in the autocomplete.  

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#10]

**Comment by sierra-moxon** [comment]
Seeing the synonym would help me have trust that my mental model matched the terms I was getting back. 

zfin.org has an autocomplete sort of like this:
<img width="795" alt="Screen Shot 2022-09-29 at 10 39 16 AM" src="https://user-images.githubusercontent.com/4561292/193103555-42895af8-2777-4548-b6c1-03dbb0b606c6.png">

**Comment by sierra-moxon** [comment]
Note: this is now an issue for "Addisons Disease" as well - we no longer see it in the UI autocomplete (as its only a synonym in MONDO now).  
See https://github.com/NCATSTranslator/Feedback/issues/8

**Comment by sierra-moxon** [comment]
Another example is in ticket https://github.com/NCATSTranslator/Feedback/issues/39 

`Chrug-Strauss Syndrome (CSS) is not found by the search. If I try "CSS" as a search term, unrelated disorders are suggested. If remove the hyphen then the new name for Chrug-Strauss is suggested "eosinophilic granulomatosis with polyangiitis"`

**Comment by sierra-moxon** [comment]
this was split into three independently actionable tickets:
- dashes complicate autocomplete #42 
- https://github.com/hrshdhgd/mondo/issues/36 - add CSS as a synonym in MONDO (which will get picked up by Babel and Node Norm I believe)
- show synonym or match text in autocomplete #44
