### ISSUE TITLE
Nodes in Paths look like Buttons to Click

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#101]
NCATS Users (Steve P)  were frustrated that when they clicked on the nodes in the path display nothing additional happens

![image](https://user-images.githubusercontent.com/38321826/217062907-ad8647b9-f8b3-440f-b8e5-11d879aa07f8.png)

we're aware of the effort to standardize attributes, but are logging this to determine if there is a design issue that should be considered for the node "buttons"

**Comment by Genomewide** [comment]
This is something that has been discussed.  It is likely a compound problem where the nodes look like buttons but are not clickable AND the edges don't and are clickable.  There are questions that have been included in the current general usability testing to look at this and see what the expectations are.

**Comment by sstemann** [comment]
there was some feedback from NCATS that the UI does not indicate that clicking the edge (button) will provide more information.  I believe this is back to @Genomewide however the gist of the ticket is in CI and works as designed

**Comment by gprice1129** [comment]
This is done. Closing.
