### ISSUE TITLE
What is meant by Path?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#102]
NCATS User (Steve P) need orientation about what is meant by a path.  While we are aware that additional non-path displays are undergoing research, could something be added to explain what a path to better orient a new user

![image](https://user-images.githubusercontent.com/38321826/217064132-a7c6da6a-bc88-4ab5-a786-a1e9f0755bbd.png)

**Comment by Genomewide** [comment]
A more info icon will be added to paths to explain what they are.

**Comment by sierra-moxon** [comment]
@gprice1129  @Genomewide - can this be closed?

**Comment by rhubal** [comment]
Think can be closed; more relevant to UCWG as it relates to instructions to give to end users.
