### ISSUE TITLE
Pubmed Links Missing from ARA to UI

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#105]
https://ui.transltr.io/results?q=9a7d6b1c-422f-4010-be69-0add97b34fb3

Result for Zinc in the UI has no publication link between Zinc and Hyperactivity.  Result for Zinc in ARAX UI, BTE results has attribute_type_id: publications, value: PMID:2394661.  

![image](https://user-images.githubusercontent.com/38321826/217069669-93b3dce7-d797-491e-a052-7e4c2579b604.png)

Other paths for Zinc result have links to the publications (ex: Epilepsy):
![image](https://user-images.githubusercontent.com/38321826/217069827-23c35e82-ecc9-4ccb-bdf1-5276059dbcc0.png)

**Comment by sierra-moxon** [comment]
from the TAQA: can be closed.

**Comment by sstemann** [comment]
i'm re-opening with screenshots in order:

1. UI > search for Phelan McDermin Syndrome results: https://ui.transltr.io/results?q=3b414af4-d0e2-4bc2-a22d-96e37d4c4cdc
2. use the entity search for "Zinc"
3. Expand the Zinc result (3rd down for me) with the 8 Paths
![image](https://user-images.githubusercontent.com/38321826/218163480-565a7af6-9da1-4eee-99e3-d0ce545cc87c.png)
4. Click the link between Zinc and Hyperactivity - note there is only path with Zinc/Hyperactivity in the UI
![image](https://user-images.githubusercontent.com/38321826/218163755-75d6c250-6d83-493b-a3cb-a250d271a437.png)

5. View the individual ARA responses in theARAX UI here:  https://arax.ncats.io/?r=3b414af4-d0e2-4bc2-a22d-96e37d4c4cdc
6. This path is not in ARAGORN results
7. Zinc is not in ARAX results
8. Zinc is result 339 in BTE, with the path, Zinc > hyperactivity > Phelan-McDermid syndrome

![image](https://user-images.githubusercontent.com/38321826/218164517-aa2943b8-f44b-4086-ae7b-a443c439e8cb.png)

**Comment by gprice1129** [comment]
We looked into this issue and we found that we are not exactly missing publications, but are only assigning publications to a single edge in a result.

In the case above it turns out that PMID:23946661 appears on the edge for both Hyperactivity and Autism Spectrum Disorder and it happens to be assigned to Autism Spectrum Disorder.

We will work on more accurately assigning publications to all edges where they appear.

**Comment by sstemann** [comment]
i retested this, as of 3/9 Zinc is no longer a result, in todays 3/9 run, serotonin agents from BTE is a valid example of this issue:

https://ui.ci.transltr.io/results?l=Phelan-mcdermid%20Syndrome&t=0&q=5354e308-c6db-4e8b-9229-21f4b0cec433
https://arax.ncats.io/?r=5354e308-c6db-4e8b-9229-21f4b0cec433
![image](https://user-images.githubusercontent.com/38321826/224082340-c04b8c7c-103a-40b3-9ca9-72f926d38043.png)
