### ISSUE TITLE
There was an error when processing your query. Please try again.

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#106]
I got this page, and the share button was active and gave me this link:  https://ui.transltr.io/results?q=0cd93863-d307-4e45-9428-f43afb0d1cfe

I tried using that URL directly and it gave me the same screen as below:
![image](https://user-images.githubusercontent.com/38321826/217077927-3ae285c8-c833-4f3c-b660-37b38ac809a4.png)

The ARAX UI displays that there are results https://arax.ncats.io/?r=0cd93863-d307-4e45-9428-f43afb0d1cfe from three ARAs. 

![image](https://user-images.githubusercontent.com/38321826/217078832-14ee7cbe-2d77-47d2-9e14-c71b30ced931.png)

**Comment by Genomewide** [comment]
Assigned to David and Gus for review.

**Comment by gprice1129** [comment]
It looks like ara-improving agent returned a corrupted KG. The message returned has a reference to MONDO:0005258 in all of its result node bindings but no such reference in its KG.

If you click on ara-improving agent on the ARAX UI you can see that despite showing that there are 994 results available, when you go to look at them the page is blank. A little digging in the browser shows that the missing MONDO:0005258 causes this problem.
![ara-improving](https://user-images.githubusercontent.com/27593697/217398987-1e0caeec-5f0d-4bb7-90af-9e8100c6c533.png)

As of right now it doesn't seem like this issue is happening anymore.

**Comment by sstemann** [comment]
@MarkDWilliams is this something the ARS could have caught?

**Comment by sierra-moxon** [comment]
from TAQA:
- "something corrupted in the KP" - Mark needs to take a closer look.

**Comment by MarkDWilliams** [comment]
I checked on the ARS backend and @gprice1129 is correct.  MONDO:0005258 appears in all of the Results but there is no corresponding entry in the Knowledge Graph.  @sstemann The ARS could conceivably check for this kind of thing, but ultimately I believe the error is with Improving.  I'm not sure if this would sneak through the automated TRAPI validator, but it's out of spec as far as I can tell:
`    NodeBinding:
      type: object
      description: >-
          An instance of NodeBinding is a single KnowledgeGraph Node mapping,
          **identified by the corresponding 'id' object key identifier of the
          Node within the Knowledge Graph**. Instances of NodeBinding may
          include extra annotation in the form of additional properties.
          (such annotation is not yet fully standardized).`
Emphasis mine.  The formatting is all valid, but there's no corresponding id in the KG.  I suspect there was an internal error in Improve that omitted the bound node from the query from their kg.  Looking at the response, it seems to be all chemicals and no Disease/Phenotypes.
https://ars-prod.transltr.io/ars/api/messages/d10008fb-248e-4b4c-b359-fa22354ab5ad

**Comment by sstemann** [comment]
@gprice1129 @Genomewide could we also consider that the UI display valid KGs? i'm having the same issue with Neurofibromatosis 

https://ui.transltr.io/results?q=5d7a0544-006d-4693-af0b-74c47e26eea3

where in the ARAX UI you can see that other ARAs (ARAX, BTE, Robokop, Unsecret) are responding (and i assume are valid)

https://arax.ncats.io/?r=5d7a0544-006d-4693-af0b-74c47e26eea3

**Comment by gprice1129** [comment]
@sstemann the rewrite of the server already does this. So this will be handled on the next release to Production.

**Comment by brettasmi** [comment]
Thanks @MarkDWilliams for tagging me. @gprice1129 let me know about this in January, but I didn't realize that it was so destructive to the frontend. I implemented a fix off the biolink 3 working branch at the time, but it wasn't deployed alongside that release.

I have now deployed this fix to the dev and CI environments. Unfortunately, it won't go to test/staging and prod until those environments are moved to Biolink 3.x and creative mode 2. I don't see a timeline for that on the progress tracker sheet, so I can't give an estimate on the timing.

**Comment by sstemann** [comment]
@brettasmi thanks!  looks resolved in CI.  for Test/Prod that plan was discussed on the architecture call yesterday and after Link Brokers met with ITRB, we'll provide the details shortly.

**Comment by gprice1129** [comment]
Can we close this?

**Comment by sstemann** [comment]
this is working now.
