### ISSUE TITLE
Imrecoxib treats X-linked Opitz G/bbb Syndrome by causing Gastroesophageal Reflux Disease ?

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#107]
What chemicals may treat "X-linked Opitz G/BBB syndrome": 

on dev (with ARA ranking taken into account, I think?), Imrecoxib shows as the top result, after waiting for all results to come back: (http://transltr-bma-ui-dev.ncats.io/results?q=ed27f0f0-05cf-49f0-9979-7f71a996d53f)

<img width="1584" alt="Screen Shot 2023-02-09 at 2 06 42 PM" src="https://user-images.githubusercontent.com/4561292/217952508-e759528b-8aef-4bd1-a39a-9b79a89a48bb.png">

The paths that come back seem to indicate that this drug causes Gastroesophageal Reflux Disease which is tagged as a subclass_of Opitz G/bbb Syndrome.  This is surprising to me as I understand it, GARD might be a symptom of G/BBB in some cases (but I am not an expert):

<img width="1417" alt="Screen Shot 2023-02-09 at 2 06 26 PM" src="https://user-images.githubusercontent.com/4561292/217952518-38af3bdd-f04b-46b0-96b6-6278191227ba.png">

I can't find "subclass of" relation between the two diseases in OLS, and it is not in Ubergraph.  I see the only infores record on that edge coming from RTX-KG2, but maybe it comes from another source internally? : 

<img width="617" alt="Screen Shot 2023-02-09 at 2 22 05 PM" src="https://user-images.githubusercontent.com/4561292/217952721-0c696c97-75c6-4713-b093-684e662637c4.png">

<img width="1423" alt="Screen Shot 2023-02-09 at 2 31 07 PM" src="https://user-images.githubusercontent.com/4561292/217954086-2d899cd0-b7f9-464f-ba75-123d9a93695f.png">

**Comment by sierra-moxon** [comment]
from TAQA:
- should we remove subclass of
- subclass of might be wrong here between acid (as "stomach acid" vs. "acid as a chemical") and GARD.  Also between GARD and the disease (GARD is a phenotype and disease is a disease).

@amykglen any chance we could chat about this at the next TAQA?

**Comment by amykglen** [comment]
hi @sierra-moxon - sorry, just got back from a few days of vacation. yes, happy to chat about it at the next TAQA!

**Comment by amykglen** [comment]
this has been fixed in the latest version of RTX-KG2 (see this update: https://github.com/RTXteam/RTX-KG2/issues/267#issuecomment-1587858522). 

it will likely be a few weeks until that is deployed to CI/Test. should we close this issue now, or wait until it's rolled out?

**Comment by saramsey** [comment]
Alas, I believe the fix only addressed the issue with edges with source relation `OMIM:manifestation_of`. That left the edges with source relation `OMIM:has_manifestation` unfixed. I have just committed the fix for those (see [RTXteam/RTX-KG2 issue 267](https://github.com/RTXteam/RTX-KG2/issues/267) for details).

**Comment by saramsey** [comment]
This should be fixed in RTX-KG2.8.6 (2.8.5 never got released, and instead got skipped). We are anticipating another two weeks to get RTX-KG2.8.6 released.
