### ISSUE TITLE
CI - Results Node - Giant Text Block

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#112]
Steps:

1. Using the CI UI - ask the question "What gene is upregulated by [Lovastatin]?
2. Expand path for Ldlr (its the first while the results are still loading) https://ui.ci.transltr.io/results?q=7b4a9c2a-5f60-4c5a-9187-3c46519efa44
3. View this giant text block that looks like evidence maybe?
![image](https://user-images.githubusercontent.com/38321826/218555086-5541b686-213b-4d14-a0b4-d4dfdaa00685.png)

4.  View the results in ARAX UI:  https://arax.ncats.io/?r=7b4a9c2a-5f60-4c5a-9187-3c46519efa44
5. ARAX and BTE return done with results, ARAGORN is running, remainder are done/0 results
![image](https://user-images.githubusercontent.com/38321826/218555821-ba25fb11-d2ef-40ab-bc36-0030521d220f.png)

6. Not very clear what attribute the UI uses, but it doesn't match the description for ARAX's ldlr result
![image](https://user-images.githubusercontent.com/38321826/218555568-c37b1aeb-511f-4b68-ae84-1d099dc49af4.png)

7. BTE has LDLR as an intermediate node for LDLRAP1 and LDLAD4 none of these nodes have descriptions like what is shown in the UI.

**Comment by gprice1129** [comment]
@sstemann I think you may have been accidentally looking at the incorrect node. If I go to https://arax.ncats.io/?r=7b4a9c2a-5f60-4c5a-9187-3c46519efa44 and look at LDLR in ARAX results the description is as follows:

<img width="1485" alt="Screen Shot 2023-02-13 at 2 25 31 PM" src="https://user-images.githubusercontent.com/27593697/218588517-c6d91b7a-c10f-406d-a153-8d210cc9ec29.png">
<img width="1485" alt="Screen Shot 2023-02-13 at 2 26 46 PM" src="https://user-images.githubusercontent.com/27593697/218588781-e502613f-20f2-4a7a-9d60-71eef2355386.png">
<img width="1485" alt="Screen Shot 2023-02-13 at 2 26 57 PM" src="https://user-images.githubusercontent.com/27593697/218588800-bc0a4927-63ec-4b31-89cf-fb2a14660de4.png">

**Comment by sstemann** [comment]
@gprice1129 thank you for taking a look.  

@edeutsch is this description block (in Gus's screenshots above) intended to display this level of detail? i'm sure ARAX isnt the only ARA doing this, i will look for other examples as well.

**Comment by edeutsch** [comment]
I suspect this may be an ingest parsing issue. I seem to recall that we worked on fixing this once before, but maybe this one wasn't fixed?  Appealing to @saramsey for more info on this RTX-KG2 issue.

**Comment by sierra-moxon** [comment]
from TAQA: @amykglen - any ideas here? :) thanks!

**Comment by amykglen** [comment]
that super long description is coming from the RTX-KG2 KP; ARAX just leaves that attribute on the node returned from RTX-KG2 KP.

and it is intended - it's the information RTX-KG2 extracted from UniProt about the node, loaded into a `biolink:description` attribute. 

**is the problem that it is unsightly? or that the UI wasn't indicating the attribute type (i.e., description)?**

from RTX-KG2.8.1pre backend:
![Screen Shot 2023-05-05 at 10 33 17 AM](https://user-images.githubusercontent.com/49423686/236527297-ee1b30fe-c1ed-4674-8590-36c3ed92192c.png)

**Comment by gprice1129** [comment]
@amykglen the problem is that its unsightly. Technically it is a description but I think we can agree its not something that is really user readable.

**Comment by amykglen** [comment]
ok, got it, sounds good. if needed we can see about excluding such descriptions from KG2 or trying to use different descriptions. but we'll stand by for now.

**Comment by sierra-moxon** [comment]
reassigning so we can remember this issue in the attribute server (BTE annotator) discussions

**Comment by sierra-moxon** [comment]
another good example of the big text block: https://ui.ci.transltr.io/results?l=Triclopyr&t=3&q=1ff3508e-78ac-4f68-a89c-f42bf0daaad2

**Comment by dkoslicki** [comment]
More evidence that this is still a problem: https://ui.test.transltr.io/results?l=Valproic%20Acid&t=3&q=a080dccc-66b2-4c08-9d66-443c593a8e9b
Abat description: `4-aminobutyrate aminotransferase`
Cdkn1a description: 
<img width="1512" alt="Screenshot 2023-06-05 at 1 03 34 PM" src="https://github.com/NCATSTranslator/Feedback/assets/6362936/097361c2-c6e4-4358-9072-f925b80b1a94">
Both BTE and ARAX look to have both returned this result

**Comment by saramsey** [comment]
@gprice1129 thank you for the feedback. I have updated the code to significantly shorten these ultra-long Uniprot descriptions and to de-uglify them (removing the brace-delimited cross-references, etc.). Details in the [RTX-KG2 issue](https://github.com/RTXteam/RTX-KG2/issues/279). Slated for inclusion in the KG2.8.4 build.

**Comment by saramsey** [comment]
@sstemann we have a bugfix for the "giant text block" issue committed into the RTX-KG2 code-base and it is slated for inclusion in the KG2.8.4 build. See [RTX-KG2 issue 279](https://github.com/RTXteam/RTX-KG2/issues/279) for details

**Comment by sstemann** [comment]
thanks @saramsey i dont see a change in this specific example when i re-test it in CI, i assume its still pending a build to NCATS

**Comment by sstemann** [comment]
restested in Test today 7/14 and these examples seem much better.  thank you!

<img width="940" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/226bd3af-c2ec-40ad-b2fa-9b5bc98c3389">

<img width="867" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/4bda9f67-a10e-450c-b93b-6f179bd84c13">
