### ISSUE TITLE
Pages of UMLS[#] in the the results

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#113]
Similar to #103 but I think it's coming back from BTE and it's UMLS not CHEMBL.  Feel free to consolidate with the other ticket.

1. Ask What drugs may treat Zellweger Syndrome
CI: https://ui.ci.transltr.io/results?q=43487c3e-ec4e-4af3-8fe6-482a96afaf81
Prod:  https://ui.transltr.io/results?q=44690dd4-2c1e-465b-ba93-bd24de9edb9c

2.  Sort by name, in reverse order around page 5, there are about 60 results that are "Umcls:c[#]"
![image](https://user-images.githubusercontent.com/38321826/218559951-41e00c92-9207-4527-9805-5f064e745f06.png)

3. Check ARAX UI:  https://arax.ncats.io/?r=43487c3e-ec4e-4af3-8fe6-482a96afaf81
4. Looks like the majority of these are coming back from BTE, a few from ARAGORN, tagging these teams leads.

**Comment by cbizon** [comment]
There has been significant improvement here in dev/ci.  I think @gaurav is ready to push to test/prod after the relay, which should alleviate much of this problem.

**Comment by gaurav** [comment]
The "new" (2022dec2) Babel is up at RENCI and on CI/test on ITRB. There's a pretty large downtime (~8 hours) when we upgrade NodeNorm, so I'm waiting until after the relay to push from CI/test --> prod. I'm also working on a new Babel that fixes some of the UMLS issues that have been reported with 2022dec2 that I hope to push out by end-March.

**Comment by sierra-moxon** [comment]
@gaurav - I'll leave it to you to close when ready :)

**Comment by sstemann** [comment]
i'm not seeing this anymore so i'm gonna close this one.
