### ISSUE TITLE
CI UI - Looks like Unsecret Results are Excluded

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#114]
Steps to recreate:

1.  use the CI UI to search for what drugs may treat Alpha Thalassemia:  https://ui.ci.transltr.io/results?q=10cfe4ff-7a4b-4803-9303-29beab8eedbb
2. In the entity search type dexamethasone.  It has one result with seven paths
![image](https://user-images.githubusercontent.com/38321826/218569915-927a5694-8313-43d5-a347-51f6311282c1.png)

3. Expand the paths, including Show More to see all 7
![image](https://user-images.githubusercontent.com/38321826/218570042-c4c73df5-800b-4856-bc3c-e79b2d452f62.png)

4.   use the ARAX UI to view results for unsecret agent:  https://arax.ncats.io/?r=10cfe4ff-7a4b-4803-9303-29beab8eedbb

5. use find to locate dexamethasone in the results (should be 194)
![image](https://user-images.githubusercontent.com/38321826/218570436-4006d264-ee15-4e84-8ffc-62501b24e01b.png)

6.  notice it's path through COL2A1 is not represented in the UI screenshot (step 3 above).  

7.  maybe its path is circular and can't be displayed in the UI, but ARAX UI renders it as a two hop?
 
![image](https://user-images.githubusercontent.com/38321826/218571954-944f6542-e438-4e22-9900-2aec7827cb30.png)

9. you can also clear your entity search and try COL2A1 and that entity is not in the UI Results (but if you look for a different intermediate node like "Jaundice" in the entity search you can verify that the entity search does look at intermediate nodes)

**Comment by gprice1129** [comment]
Hi Sarah, the predicate "biolink:entity_positively_regulates_entity" is not a valid biolink predicate for biolink 3.1.2 (the version the UI is using). So we ignore this path.

**Comment by sstemann** [comment]
@sierra-moxon i made a duplicate in issue #118 - it is actually relevant to ARAX and potentially ARAGORN in the one example i had time for today so not sure if we should close this one and use #118 ?

**Comment by sierra-moxon** [comment]
closing in favor of #118
