### ISSUE TITLE
CI UI - 7 Second "No results available" before results are displayed.

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#116]
steps:

1. search "what chemicals downregulate ECHS1?" https://ui.ci.transltr.io/results?q=56886352-22db-47ac-96ee-96dee6b7b8b4
2. wait 18 min (or watch video and skip to min 18) 
https://drive.google.com/file/d/121OOgK_IrcCJ6D_ngjwwgwH-iUfpKDmK/view?usp=share_link
3. initially it shows "no results available" and after about 7 seconds it shows results

**Comment by sstemann** [comment]
UI team is working to recreate.

**Comment by sierra-moxon** [comment]
@gprice1129 - maybe this is already closeable! :) apologies if I missed closing it.

**Comment by sstemann** [comment]
yep can't recreate so closing.
