### ISSUE TITLE
ARAs are returning results with predicates that are not supported by Biolink Model 3.1.2

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#118]
The UI does not display results when predicates are not compliant with Biolink Model 3.1.2 (in CI).  

steps:
1. in the CI UI query "what drugs may treat Meniere Disease" https://ui.ci.transltr.io/results?q=cccb6699-29f4-492b-9733-ab77bd1a8261
2. Expand result for Gentamycin - there are 14 paths 
![image](https://user-images.githubusercontent.com/38321826/219145796-ab8a69fa-6c07-4f09-8564-d6abb973c90f.png)

3. View this result set in ARAX UI https://arax.ncats.io/?r=cccb6699-29f4-492b-9733-ab77bd1a8261
4. Example of missing paths, bold predicate is not compliant with 3.1.2 ARAX: Meniere Disease [gene_associated_with_condition] KCNH3 **[increases_activity_of]** Gentamycin 
![image](https://user-images.githubusercontent.com/38321826/219145391-2cf02d75-3ed1-481f-900a-f203ddec2faa.png)
 
5. Unsecret, I think all of the results use out of compliance predicates and therefore none of the unsecret results are in the UI
![image](https://user-images.githubusercontent.com/38321826/219146136-ae387b38-a660-47d8-89b5-9810fb309c66.png)

6. It looks like ARAGORN has a few out of compliance in this example:  decreases_localization_of, decreases_molecular_modification_to, decreases_stability_of
![image](https://user-images.githubusercontent.com/38321826/219149406-7f564f38-c1f5-49c0-ba4b-c7f4fcabbc2d.png)

7. This is only one example, there are probably others.

**Comment by sierra-moxon** [comment]
related: #114 (as duplicate).

**Comment by gprice1129** [comment]
@edeutsch I posted an update for review last night to transform deprecated predicates to qualified predicates when the UI is processing a result based on a mapping file provided by @sierra-moxon.

**Comment by saramsey** [comment]
@sstemann can you tell us approximately when that query was run through the `ui.ci.transltr.io` interface?  We have been researching the issue with the `biolink:increases_activity_of` predicate and we think somewhere "under the hood", our older RTX-KG2 graph (version RTX-KG2.7.6c) was getting queried. We're pretty certain that predicate is not in the current graph, RTX-KG2.8.0c. If we could have some info on _when_ that query was run (and the results cached) that would be helpful. Thanks.

**Comment by saramsey** [comment]
I've confirmed that the `biolink:increases_activity_of` predicate is not present in RTX-KG2.8.0c, but it is (for that specific triple involving promethazine and KCNH3) present in RTX-KG2.7.6c. We are working on trying to ascertain why a RTX-KG2.7.6c triple is showing up in that cached set of query results.

**Comment by sstemann** [comment]
@saramsey i need to fix my github email notifications, i'm just seeing this, do you need the specifics you asked for above?
