### ISSUE TITLE
How to display EPC attributes - missing primary and original KS as well as unknown data

### ISSUE THREAD

**Issue by Genomewide** [NCATSTranslator/Feedback#121]
Example result set pk 20e96d9c-8b3a-4aec-8479-7d1c94e5390c
Huntington Disease

Some have primary and some have original KS. Original is being deprecated and primary will remain. The UI is planning to use these tags to know which infoRes website to point to.  
Issue 1 - Many don't have either primary or original KS. 
Issue 2 - some have original or primary, but also aggregate KS that have their own web site.  
Issue 3 - some have data and it is not clear what or how to display it
Summary and counts here
![image](https://user-images.githubusercontent.com/55069176/219464598-d05d7c92-249d-4fe2-b0d5-3409947f5e6d.png)

Full slide deck of examples can be found here: https://docs.google.com/presentation/d/1t5GrBHxZs0QXqoXFIlpcjDr0RVcStSgm5Gr-5bSoyJQ/edit#slide=id.g1b62adc7398_0_617

**Comment by Genomewide** [comment]
These were found as aggregator:

infores:biothings-explorer
infores:aragorn
infores:biothings-semmeddb
infores:automat-ctd
infores:automat-biolink
infores:sri-reference-kg
infores:automat-robokop
infores:spoke
infores:mesh
infores:chembl
infores:mychem-info
infores:molepro
infores:automat-hetio
infores:automat-drug-central
infores:openpredict
infores:biothings-idisk
infores:arax
infores:rtx-kg2
infores:improving-agent
infores:drugcentral
infores:pharos
infores:unsecret-agent
infores:semmeddb
infores:disgenet

**Comment by sierra-moxon** [comment]
From TAQA:
Andy's team will use primary_knowledge_source first, if its not there, then will use aggregator_knowledge_source.
It would be helpful if people just put in primary_knowledge_source ASAP.
It would be helpful to have a list of KPs that don't have primary_knowledge_source so we can check in

**Comment by Genomewide** [comment]
Order of priority will be:
1. If primary KS - use that
2. If no primary, but original KS, then use original
3. If no primary or original, then check aggregator - ignore ARAs and KPs - if there are KS as aggregators then we will use that. 

Going forward Andy will check on his data sources to see if he can determine which sources that are not compliant.

**Comment by bill-baumgartner** [comment]
Update: TMKP has replaced its use of `biolink:original_knowledge_source` with `biolink:primary_knowledge_source`. This change has been deployed to CI.
