### ISSUE TITLE
Wrong direction on 'affects' edge

### ISSUE THREAD

**Issue by mbrush** [NCATSTranslator/Feedback#122]
The diagram below shows the support graph for an Explanatory Agent CM tool answer for what may treat Alzheimer's:

![image](https://user-images.githubusercontent.com/5184212/219518527-cc09d2c2-a750-46ef-9ec3-a85b5aef62a7.png)

The highlighted edge states that PSN1 gene affects (q:decreases activity of) pubchem.compound:73441863.  But tracing back to the original source (Chembl, via TCRD) - the original assertion seems to be that pubchem.compound:73441863 affects (decreases) the activity of the PSN1 gene.  See https://pubchem.ncbi.nlm.nih.gov/compound/73441863#section=Biological-Test-Results.

### To do:
- Reach out to Explanatory Agent to review/address how they ingest/represent this data
- More generally, review ETL process for this data source with Explanatory Agent (and coordinate with MolePro who handles most chemical sources)
- labels needed on pubchem compounds
- Also discuss the retrieval provenance on this edge (there is no primary source annotation - see below) - and discuss if/how chembl might be cited as primary rther than TCRD.
![image](https://user-images.githubusercontent.com/5184212/219518688-da700bf3-f8ba-40a8-a946-5b47dfe59993.png)

**Comment by sandrine-m** [comment]
@mbrush do you have PK for this query by any chance? I tried to reproduce issue:
here is my PK : [51efe187-d1cf-43f1-8499-50e6b30c7ad7](https://ui.ci.transltr.io/results?l=Alzheimer%20Disease&t=0&q=51efe187-d1cf-43f1-8499-50e6b30c7ad7)
I could not find the compound easily. 
Through ARAX-UI I performed the following query (to query the particular offending edge) 
[PK= c9ed99c6-32b4-4b1e-8cd1-04222d476b71](https://arax.ncats.io/?r=c9ed99c6-32b4-4b1e-8cd1-04222d476b71):
```
{
  "edges": {
    "e00": {
      "attribute_constraints": [],
      "object": "n01",
      "predicates": [
        "biolink:affects"
      ],
      "qualifier_constraints": [],
      "subject": "n00"
    }
  },
  "nodes": {
    "n00": {
      "constraints": [],
      "ids": [
        "PUBCHEM.COMPOUND:73441863"
      ],
      "is_set": false,
      "fulltextname": "n00"
    },
    "n01": {
      "constraints": [],
      "ids": [
        "UniProtKB:P49768"
      ],
      "is_set": false,
      "fulltextname": "n01"
    }
  }
}
```
From the response, I could find 2 agents returning data on this edge (independent of direction):
- ARAGORN : reports the unqualified `biolink:activity_affected_by`
- MOLEPRO: reports the node but no edges, which is accurate with current implementation of MolePro ingests from PubChem (compounds information, and compounds similarity information)

**Comment by cbizon** [comment]
I ran the following query in CI:
```
qg = {
  "edges": {
    "e00": {
      "object": "n01",
      "subject": "n00"
    }
  },
  "nodes": {
    "n00": {
      "constraints": [],
      "ids": [
        "PUBCHEM.COMPOUND:73441863"
      ],
    },
    "n01": {
      "constraints": [],
      "ids": [
        "UniProtKB:P49768"
      ],
    }
  }
}
```

Only 1 edge was returned (by 3 ARAs) - a "physically interacts with" coming from bindingdb via service provider.

The original issue is from Feb, so I suspect that this is no longer relevant.   @mbrush can you confirm and close?

https://arax.ncats.io/beta/?source=ARS&id=c6563a84-ac7e-4404-a071-ffd89958cab0

**Comment by mbrush** [comment]
Yes, looks like this has been addressed since I posted in Feb . . . .closing issue.
