### ISSUE TITLE
Compounds used in clinical trials wrongly associated with "treats"

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#123]
This example has been found through ARAX (query not suitable via UI):
PK: 56965cb7-d4c7-455a-8ff6-6ad762a73b24
Associated query:
```
{
  "edges": {
    "N1": {
      "attribute_constraints": [],
      "object": "n01",
      "predicates": [
        "biolink:has_normalized_google_distance_with"
      ],
      "qualifier_constraints": [],
      "subject": "n00"
    },
    "e00": {
      "attribute_constraints": [],
      "object": "n01",
      "predicates": [
        "biolink:related_to"
      ],
      "qualifier_constraints": [],
      "subject": "n00"
    }
  },
  "nodes": {
    "n00": {
      "constraints": [],
      "ids": [
        "CHEMBL.COMPOUND:CHEMBL1201867"
      ],
      "is_set": false,
      "fulltextname": "n00"
    },
    "n01": {
      "categories": [
        "biolink:NamedThing"
      ],
      "constraints": [],
      "is_set": false,
      "fulltextname": "n01"
    }
  }
}
```

The second result from BTE is (original source "Clinical trials") :
CHEMBL.COMPOUND:CHEMBL1201867----biolink:treats----MONDO:0005233

attribute_type_id: | biolink:aggregator_knowledge_source
value_type_id: | biolink:InformationResource
value: | infores:biothings-explorer
 
attribute_type_id: | biolink:primary_knowledge_source
value_type_id: | biolink:InformationResource
value: | infores:chembl
 
attribute_type_id: | biolink:aggregator_knowledge_source
value_type_id: | biolink:InformationResource
value: | infores:mychem-info
 
attribute_type_id: | biolink:source_web_page
value: | https://clinicaltrials.gov/search?id=%22NCT03325166%22
 
attribute_type_id: | chembl_source
value: | ClinicalTrials
 
attribute_type_id: | max_clinical_phase_for_indication
value: | 2
 
attribute_type_id: | year_first_approved
value: | 2009

Id: 29f6e2fbced0422d32b93c193ccfd847
attribute_type_id:	biolink:aggregator_knowledge_source
value_type_id:	biolink:InformationResource
value:	infores:biothings-explorer
attribute_type_id:	biolink:primary_knowledge_source
value_type_id:	biolink:InformationResource
value:	infores:chembl
attribute_type_id:	biolink:aggregator_knowledge_source
value_type_id:	biolink:InformationResource
value:	infores:mychem-info
attribute_type_id:	biolink:source_web_page
value:	https://clinicaltrials.gov/search?id=%22NCT03325166%22
attribute_type_id:	chembl_source
value:	ClinicalTrials
attribute_type_id:	max_clinical_phase_for_indication
value:	2
attribute_type_id:	year_first_approved
value:	2009

This result is result 34 from ARAX supported by 3 edges ("Clinical trials" from BTE, Google distance from ARAX, and another from Spoke).

This compound is a contrast agent used in MRI and has been used in a [clinical trial](https://clinicaltrials.gov/ct2/show/NCT03325166?id=%22NCT03325166%22&draw=2&rank=1) together with another compound pembrolizumab to measure (through contrast-enhanced imaging) the effect of pembrolizumab in these patient in the context of non-small cell lung cancer (NSCLC).

This compound is not a treatment it is a contrast agent and contrast agents might be used for disease follow up without treating the disease. Can we say that because Ferumoxytol is used for treatment (follow up imaging) in NSCLC that it actually treats the disease?
FWIW, Ferumoxytol is quite wide-spread contrast agent used in contrast MR-imaging in many diseases so could potentially linked by treats with a lot of disease. 

If we are still considering that any compound used in a clinical trial related to a particular disease treats it, could it be possible to filter such compounds? (not sure they have attributed chemical roles though).

Thank you!

**Comment by andrewsu** [comment]
Very interesting example!  **TLDR:** My assessment is that this is an issue with ChEMBL (or possibly a data source even further upstream) being loose with semantics, not an error that is being introduced within Translator. My recommendation would be to open an issue with ChEMBL and close this issue.

-----

More details:
* The BTE result is drawn from mychem.info (http://mychem.info/v1/chem/CHEMBL1201867?fields=chembl.drug_indications).  There are six entries under `drug_indications`, mirroring the six entries under "Drug Indications" on the [ChEMBL page for ferumoxytol](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1201867/).
* I'm pretty confident that the underlying data was downloaded from the `DRUG_INDICATION` table described in the [ChEMBL schema documentation](https://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/schema_documentation.html), which is described as "Table storing indications for drugs from a variety of sources (e.g., ATC, DailyMed, ClinicalTrials.gov)".
* The [BioLink Model entry for treats](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml#L3237) lists `indicated for` as an alias, so I think this is the correct biolink predicate for what is described in the ChEMBL documentation.

**Comment by sandrine-m** [comment]
Thank you @andrewsu. Yes, you are completely right ChEMBL simply joins compounds to diseases from clinical trials and other sources (see in [their documentation](https://chembl.gitbook.io/chembl-interface-documentation/web-services/chembl-data-web-services) under Ressources>Drug Indication as listed [here](https://www.ebi.ac.uk/chembl/api/data/drug_indication)). 
ChEMBL is a secondary source of information for their drug indication table. 

I agree with Andrew that the ChEMBL integration of clinical trials is rather liberate in the semantics:
In clinical trials compounds are listed under "intervention" and does not ensure the chemical intervention treats the disease or is an indication for the disease, it can be a mean to get measurements. I check both the clinical trials' version ChEMBL is using as well as the newer one, and both original sources do not make any distinction whether the chemical intervention is a treatment or a agent or other cases (chemical interactions...etc.). 

I will follow Andrew's advice and post an issue to ChEMBL. Could the Translator do better than ChEMBL and make a rule to distinguish chemical interventions that treats versus the others? Maybe a question of ARA's? or @sierra-moxon  should we be more inclusive semantically in the definition of treats then?

**Comment by sandrine-m** [comment]
As a side note, clinical trials clemical interventions groups (from only me testing the source) at list 4 cases in which the data do not support "treats" or "indicated":
- contrast agents (e.g. Gadolinium, Ferumoxytol...)
- chemical inducing functions/impairments (e.g. psychedelics such as MDMA...etc.)
- drug interactions
- toxicity

**Comment by vdancik** [comment]
@sandrine-m I think it may be OK to use `treat` predicate as long as we include a qualifier like **`subject_role_qualifier:imaging_agent`**

**Comment by sierra-moxon** [comment]
Discussed at predicates call 3/3/23:
- we should not need a qualifier here
- use chemical role and a less specific treats predicate like 'in clinical trials for'

**Comment by sstemann** [comment]
@sierra-moxon i assume this is going to be resolved with the treats refactor?

**Comment by sierra-moxon** [comment]
I believe this is one of the use cases @gglusman  is taking into account when creating the DailyMed ingest to the clinical KP.  @gglusman  - is this ticket helpful or shall we close? 

I believe the Chembl ingests from MolePro have been updated to reflect the new treats hierarchy.
