### ISSUE TITLE
getting more original sources from Spoke

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#125]
This example has been found through ARAX (query not suitable via UI):
PK: 56965cb7-d4c7-455a-8ff6-6ad762a73b24
Associated query:
```
{
  "edges": {
    "N1": {
      "attribute_constraints": [],
      "object": "n01",
      "predicates": [
        "biolink:has_normalized_google_distance_with"
      ],
      "qualifier_constraints": [],
      "subject": "n00"
    },
    "e00": {
      "attribute_constraints": [],
      "object": "n01",
      "predicates": [
        "biolink:related_to"
      ],
      "qualifier_constraints": [],
      "subject": "n00"
    }
  },
  "nodes": {
    "n00": {
      "constraints": [],
      "ids": [
        "CHEMBL.COMPOUND:CHEMBL1201867"
      ],
      "is_set": false,
      "fulltextname": "n00"
    },
    "n01": {
      "categories": [
        "biolink:NamedThing"
      ],
      "constraints": [],
      "is_set": false,
      "fulltextname": "n01"
    }
  }
}
```
The result from Spoke is really interesting for me has it goes in line with my current hypothesis and knowledge about this compound. I would liek to check the sources on which Spoke made its predictions in order to understand if I can get something interesting from it. 

CHEMBL.COMPOUND:CHEMBL1201867----biolink:treats----MONDO:0004992

--
attribute_source: | infores:spoke
attribute_type_id: | biolink:aggregator_knowledge_source
original_attribute_name: | source
value_type_id: | biolink:InformationResource
value: | infores:chembl
 
attribute_source: | infores:spoke
attribute_type_id: | biolink:aggregator_knowledge_source
value_type_id: | biolink:InformationResource
value: | infores:spoke
 
attribute_source: | infores:chembl
attribute_type_id: | biolink:has_confidence_level
original_attribute_name: | phase
value: | 1
 
attribute_source: | infores:arax
attribute_type_id: | biolink:aggregator_knowledge_source
value_type_id: | biolink:InformationResource
value: | infores:arax

Id: infores:spoke:PUBCHEM.COMPOUND:14789-biolink:treats-MONDO:0004992
attribute_source:	infores:spoke
attribute_type_id:	biolink:aggregator_knowledge_source
original_attribute_name:	source
value_type_id:	biolink:InformationResource
value:	infores:chembl
attribute_source:	infores:spoke
attribute_type_id:	biolink:aggregator_knowledge_source
value_type_id:	biolink:InformationResource
value:	infores:spoke
attribute_source:	infores:chembl
attribute_type_id:	biolink:has_confidence_level
original_attribute_name:	phase
value:	1
attribute_source:	infores:arax
attribute_type_id:	biolink:aggregator_knowledge_source
value_type_id:	biolink:InformationResource
value:	infores:arax

**Comment by sierra-moxon** [comment]
Hi @karthiksoman - do you know if SPOKE provides more EPC metadata (incl publication?) than what is currently showing up in ARAX on an edge? (see example above).  :)

**Comment by karthiksoman** [comment]
Hi Sierra,

With regard to the specific edge shown in the example (i.e. Compound-TREATS-Disease), SPOKE fetches this edge from ChEMBL. This edge has two attributes in SPOKE:
1. phase: These are ChEMBL indications, annotated with maximum phase (0 preclinical, 1-3 clinical trials, 4 approved)
2. sources: provenance information, which is ChEMBL for this edge.

SPOKE provides other EPC information too (such as p-value, z-score, co-occurrence score etc), but that is edge type dependent. EPC information annotated on TREATS edge type are the above mentioned "phase" and "sources".

If you have any more questions on this, I am happy to answer.

**Comment by sandrine-m** [comment]
Hi @karthiksoman 
Thanks for the answer. I was not sure I was getting the proper source info on ChEMBL, I could retrieve:
<html>
<body>


MESH ID | MESH ID |   | MESH Heading | MESH Heading |   | EFO IDs | EFO IDs |   | EFO Terms | EFO Terms |   | Max Phase for Indication | Max Phase for Indication |   | First Approval | First Approval |   | References | References |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
D000740 | Anemia | EFO:0004272, MONDO:0002280 | anemia (phenotype), anemia | 4 | 2009 | ClinicalTrials, DailyMed
D002289 | Carcinoma, Non-Small-Cell Lung | EFO:0003060 | non-small cell lung carcinoma | 2 | 2009 | ClinicalTrials
D005909 | Glioblastoma | EFO:0000519 | glioblastoma multiforme | 2 | 2009 | ClinicalTrials
D009369 | Neoplasms | EFO:0000616 | neoplasm | 1 | 2009 | ClinicalTrials
D015526 | AIDS Dementia Complex | EFO:0002608 | AIDS dementia | 2 | 2009 | ClinicalTrials
D018798 | Anemia, Iron-Deficiency | HP:0001891 | Iron deficiency anemia | 3 | 2009 | ClinicalTrials


</body>
</html>

If I checked up correctly, it is only in max phase 1 for Neoplasms (that could be benign and not malign) and the drug usage in clinical trials reported by ChEMBL is not supporting the statement. The only sources I could find on ChEMBL that supports the statement are row 2 and 3 of that table (that are max phase >1) so I thought there might be additional sources on which SPOKE is basing their prediction. 
I am not familiar with edge dependent EPC (p-value, z-score, co-occurrence score), is it possible to access this in some way?

Thank you!

**Comment by karthiksoman** [comment]
Hi @sandrine-m and @sierra-moxon 

Sorry for the late response. 
As mentioned in my previous response, SPOKE integrates "Compound-TREATS-Disease" edges from ChEMBL. In ChEMBL, disease id comes as MESH id as shown in the table shared by Sandrine. In SPOKE, primary identifier for a disease node is Disease Ontology Identifier (DOID) with cross-reference to MESH ID. Hence, the MESH ids in the TREATS edges from ChEMBL is mapped to DOID during the integration process in SPOKE. So , as you can see in the table, "neoplasms" has a mesh id "D009369" which can be mapped to a disease node in SPOKE with identifier as "DOID:162". This way we create the edge between that disease node and compound node from the ChEMBL table.

Below given is the URI to SPOKE neighborhood explorer for the given compound in the question (chembl.compound:CHEMBL1201867). And from the explorer, you can see the edges that this Compound make with other Disease nodes in SPOKE and the respective attributes hanging from those edges.

https://spoke.rbvi.ucsf.edu/neighborhood/Compound/identifier/chembl.compound:CHEMBL1201867

Please let me know if you have any further questions on this and am happy to answer.

**Comment by sandrine-m** [comment]
Thank you @karthiksoman that is exactly the piece of info I was looking for! I'll close the issue.

Sandrine
