### ISSUE TITLE
Return both the canonical label and the synonym searched to the user in the autocomplete.

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#127]
Sometimes searching for something (e.g. "Addison's disease") will result in an unintuitive, very different result ("adrenal insufficiency").

This is because searching for Addison's disease in NameRes results in a CURIE, but looking that CURIE up in NodeNorm results in a very different canonical label.

To fix this: The UI will return both parts of this search to the user (maybe something like "Addison's disease is a synonym of adrenal insufficiency") so they understand how they got there.
UI will attempt to get this information from mygene.info or another Biothings service.

**Comment by sierra-moxon** [comment]
please see #44 for additional context (it was split into two tickets, this being one of them).

**Comment by cbizon** [comment]
In this case, I don't think that another service is needed.  The mismatch is just between what the user asks for and what we call it.  I'm not sure what another service would tell us?

**Comment by sstemann** [comment]
the UI team has a fix for this, for their next major release

**Comment by sierra-moxon** [comment]
@gprice1129 - maybe this can already be closed? :) apologies if I forgot.

**Comment by gprice1129** [comment]
This is done. Closing.
