### ISSUE TITLE
Investigate adding a taxon to canonical labels in NodeNorm and/or reprioritize labels that include taxon (short term)

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#128]
Sometimes the labels returned by both NameRes and NodeNorm are insufficient to fully understand which concept is being referenced.
e.g. searching from "FGF8" matches synonyms of "FGF8" in NameRes, all of which have a canonical name of "FGF8" in NodeNorm, but no information on which species this protein is from.
Eventually, the property server will help with this, by being able to provide additional metadata on each identifier ([identifier] found_in: [mouse], say).

- [ ] As a short-term fix, UI will attempt to get this information from mygene.info or another Biothings service.
- [ ] If this doesn't work, NodeNorm might need to reprioritize our canonical labels so that we choose one that includes a taxon ("Mmus", "Mouse") or even just look for brackets so we know that the label will be informative about some sort of subset (e.g. "FGF8 - Human", "FGF8 (Hsap)", etc.). This is a very fragile way of doing this, so we don't want to try this until we've tried everything else first.

**Comment by sierra-moxon** [comment]
please see #44  for more context, it was split into two issues to help with assignments. :)

**Comment by sstemann** [comment]
no development effort from the UI team on this one, removed the devs

**Comment by sierra-moxon** [comment]
06/22/23 - retesting; I see species in the autocomplete!  closing as complete.
