### ISSUE TITLE
investigate adding model organism data, in particular knock-out mutants and treatment in disease models

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#130]
This is a topic that was brought up in the Drug Repurposing for Rare Disease (hosted by Alex Trophsa).
We know we have model organism data in Translator.  From testing, this is mostly exposed via SEMMEDDB and text mining.  
Monarch-initiative does incorporate curated model organism gene to disease and phenotype data from MGI, ZFIN, RGD, and other models systems as well as non-model animal systems.

We know that model organism databases like ZFIN, do capture amelioration of disease or phenotype models via chemical/drug treatments: https://zfin.org/downloads/ameliorated_phenotype_fish.txt

Can we bring in more model organism data, can we support variants/genotypes/environmental conditions that affect these amelioration statements?   Or, if we have all the model data that we need, how do we make it more visible (without overstating the data, e.g.: x treats y in a model system must be contextualized for the user) in results?

**Comment by andrewsu** [comment]
I'm not sure I knew about that zfin resource that relates compounds to diseases/phenotypes. Are there similar files from other model organisms?

Regardless, I can see a relatively straightforward path to incorporating these data into creative mode responses (1: annotate API using SmartAPI --OR-- create a BioThings API, then 2: edit [BTE's create mode templates](https://github.com/biothings/bte_trapi_query_graph_handler/tree/main/data/templates/Drug-treats-Disease)), so adding myself to this issue...
