### ISSUE TITLE
Facet - Exclude

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#137]
Consider adding a facet that excludes FDA approved drugs,  GSRS does a form of this

https://gsrs.ncats.nih.gov/ginas/app/beta/browse-substance

![image](https://user-images.githubusercontent.com/38321826/220975547-42f24277-8efa-4c21-89a7-607e4f5d0233.png)

**Comment by sstemann** [comment]
targeting for June Release

**Comment by dnsmith124** [comment]
This feature is live on CI, here's an example: https://ui.ci.transltr.io/results?l=Heart%20Disorder&i=MONDO:0005267&t=0&q=3c7e1e6a-662e-4e08-a4c2-2004efac046f

Closing.

**Comment by sstemann** [comment]
@dnsmith124 i see Not FDA Approved and Not Indicated for a disease - is that the final design?  the intent of the ticket is to include some facets and not others within the same filtering session - so some CHebi Roles but Exclude other Chebi roles and I dont see a way to do that.

**Comment by dnsmith124** [comment]
Currently this is the final design. Implementing an exclusion state for every facet was beyond what we were able to achieve by September.

Ultimately I believe what you're requesting is part of our plan for facets post-September.
