### ISSUE TITLE
Some approved drugs are not included in the "FDA Approved" Filter

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#138]
Steps:

1. UI CI > what drugs may treat Takayasu Arteritis:
https://ui.ci.transltr.io/results?q=c5002e23-c011-49f8-b74f-dc19f4bd1779

2.  First result is Nebivolol, when you click FDA Approved and sort by name, you can see it's not in the list
![image](https://user-images.githubusercontent.com/38321826/220976726-0bec59d1-a9e7-4891-b931-8f961c2190e8.png)

![image](https://user-images.githubusercontent.com/38321826/220976448-879da7da-5f2e-4426-84db-0d2e7cae2c2f.png)

4.  according to GSRS and DrugBank it is approved
https://gsrs.ncats.nih.gov/ginas/app/beta/substances/e933eb1a-38e7-4873-aea6-f2e21fdbf8b7
https://go.drugbank.com/drugs/DB04861

In this same result set, from the first page of results you can try it with 

Bromocriptine
Iodixanol
Frovatriptan 
Exenatide

**Comment by sstemann** [comment]
@sierra-moxon UI Team reviewed and this is not an issue for their team.  Is this something that MolePro (who provides the annotation service) should review?  or should we review at TAQA?

**Comment by sierra-moxon** [comment]
From TAQA:
it was where the FDA status was coming from - was provided on nodes but not on all nodes, but now getting it from the edges.  This is resolved.
