### ISSUE TITLE
http://transltr-bma-ui-dev.ncats.io/results?q=aba4a3f7-0732-4dd3-ae6e-08d4e0202912

This is probably universal and any results that have 0 evidence will be filtered and not return if they have 0 evidence.  

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#14]
## Steps to reproduce:
Search Acute Adrenal Insufficiency
64 results are shown
None currently show evidence
Slide the evidence filter to any number and then back to 1
BC none of the results have evidence = 1 they all disapp

**Comment by sstemann** [comment]
@Genomewide this looks like it's resolved, i used this result link:  https://ui.transltr.io/results?q=a9efb05f-0625-4f8f-b5dd-f3c82a986fa4

and there's also minimum number checkbox

**Comment by sierra-moxon** [comment]
I'm going to close this as done! :) please reopen if I got this wrong.
