### ISSUE TITLE
from Bridget Wagner, Broad Institute.

The "type 2 diabetes mellitus" results have no scores attached to them: https://ui.transltr.io/results?q=26394fad-bfd9-4e32-bb90-ef9d5044f593

I also don't know what "type 2 diabetes mellitus 2" and so on mean.

Searching for diseases that don't have preset buttons (like "type 1 diabetes mellitus") returns an error.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#140]

**Comment by sierra-moxon** [comment]
the need for consistent node attributes is documented in a related issue:  #92 
the need for link outs to more information on subject/object nodes is documented in a related issue: #91 

It is unclear why `type 1 Diabetes Mellitus` was not returning for the user?  Just now, I was able to see the autocomplete performing as expected.  

<img width="776" alt="Screen Shot 2023-02-28 at 4 12 34 PM" src="https://user-images.githubusercontent.com/4561292/222012116-0bf18042-d3bc-48e7-8f68-75bc579725cc.png">

**Comment by sierra-moxon** [comment]
If I don't select a autocompleted term immediately, I do have issues with my session (the autocomplete stops working, even on reload of the page). 

<img width="985" alt="Screen Shot 2023-02-28 at 4 14 39 PM" src="https://user-images.githubusercontent.com/4561292/222012370-dc4224e5-3308-4d18-b734-a64c0601cd0f.png">

**Comment by sierra-moxon** [comment]
can close! :)
