### ISSUE TITLE
ImProve - Needs Primary Knowledge Source

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#142]
NCATS would like data evidence to be displayed to the UI.  Since ARAs are the aggregator, the primary knowledge source needs to be populated

UI:  https://ui.ci.transltr.io/results?l=Fuchs%27%20Endothelial%20Dystrophy&t=0&q=30fa40cd-e74d-4532-ada1-9914c87db20a
ARAX UI:  https://arax.ncats.io/?r=30fa40cd-e74d-4532-ada1-9914c87db20a

![image](https://user-images.githubusercontent.com/38321826/221973630-be671368-bc46-470e-b313-86aa61c24caa.png)

**Comment by sierra-moxon** [comment]
when rerunning this afternoon, I get one path from Aragorn for netarsudil and it has infores.  @sstemann @suihuang-ISB - should improving-agent still be returning this result? 


![Image](https://github.com/NCATSTranslator/Feedback/assets/4561292/7b8e2e62-9c0b-4f92-b2a4-3cb8d47a7f0a)

**Comment by sierra-moxon** [comment]
06/22/23 - tried to recreate on ci (the links in the original ticket are no longer working)
https://arax.ncats.io/?r=532d62b1-d87b-4a30-8af6-5725c39eebb1

Improving does not have primary knowledge source.

**Comment by brettasmi** [comment]
@sierra-moxon , can you point to a specific answer / result that doesn't have a primary knowledge source? When I expand the raw JSON, all 300 results have a primary knowledge source. Many are "improving agent", which we were told was permissible provided it is actually our tool that is making the assertion.

The original issue in this ticket was that, for some edges, we had no primary knowledge source at all (see Sarah's screenshot), only aggregator sources.

**Comment by sierra-moxon** [comment]
@brettasmi - thanks for checking!  I misread the UI (I was used to seeing TRAPI 1.3 layout and my eyes told me that the red here was complaining about primary knowledge source, but it is complaining about upstream resource ids).  This looks fixed :) I will close.  

<img width="919" alt="Screen Shot 2023-06-22 at 5 10 44 PM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/3b45bcd1-b241-4016-a9c5-637403b472ff">
