### ISSUE TITLE
UI - Display PMC Links for Publications

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#143]
TMKP provides links to PMC IDs. These links should be displayed in the UI.

UI:  https://ui.ci.transltr.io/results?l=Fuchs%27%20Endothelial%20Dystrophy&t=0&q=30fa40cd-e74d-4532-ada1-9914c87db20a
ARAX UI:  https://arax.ncats.io/?r=30fa40cd-e74d-4532-ada1-9914c87db20a

ARAGORN > Menadione > FED treated by Menadione edge 

![image](https://user-images.githubusercontent.com/38321826/221974480-4bbf5858-e808-40a2-a5b8-d38acd66ff93.png)

**Comment by sierra-moxon** [comment]
related: #91

**Comment by gprice1129** [comment]
Closing because this is now working on CI
