### ISSUE TITLE
UI: Use ChEBI classifications (facet values) as tooltip on results

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#146]
Although facets allows for filtering results by ATC classification, it would be useful to access this information in a quicker way and without filtering, by exposing it as a tooltip on results. As an example, if I'm quickly trying to grasp what type of drug "Phenytoin" is (see attached), I have 3 options:
1. Filter using the ACT facets at random until I find the right category
2. Follow the link for Phenotoin which takes me to Chembl
3. Google....

A quick tooltip when hovering over the result name would be very handy.

![Screen Shot 2023-03-13 at 3 38 38 PM](https://user-images.githubusercontent.com/1442197/224848155-54bff6b9-e4ea-4b45-87a1-a0ddb9767753.png)

**Comment by sierra-moxon** [comment]
From TAQA:
on the results, we want to see which of the filters that chemical belongs to without clicking the checkbox on the left side facet bar. 
Tyler: nice to have but not a high priority.  
Andy: we get the info from MolePro and we like it; we're going to have a lot of facets, can't have a hover for every one of them, but incorporating it into the UI would be good in some way.  
Andrew: there is a question about how to prioritize - its not something to jump in and implement immediately.

**Comment by gprice1129** [comment]
The UI team is switching to ChEBI Roles instead of ATC classifications for now. However the core of the issue still applies to ChEBI roles. Not sure if we should make a new issue or just keep this one open. @sierra-moxon

**Comment by sierra-moxon** [comment]
I'm going to just change the title on this one.   @gprice1129  @khanspers

**Comment by sstemann** [comment]
@khanspers i think this is resolved by the new pill labels, sometimes you have to expand the result to see all of the labels, which i logged #527 to hopefully have addressed.  but what do you think, can we close this one?

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/bffbde5b-a3da-437b-8c5f-373ddd450cea)

**Comment by gprice1129** [comment]
Can we close this? @sstemann @khanspers

**Comment by gprice1129** [comment]
Closing, reopen if more discussion is needed.
