### ISSUE TITLE
The top answers are drugs that treat diseases that are in no way associated with NGLY1 (eg. multiple osteochondromas). Might be a MolePro issue with their "superclass reasoning"

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#148]
## Steps to reproduce:
Select "what drugs may treat NGLY1 deficiency" (one of the default questions).

**Comment by sierra-moxon** [comment]
Hi @sandrine-m - maybe this can be closed? :) apologies if I missed that...

**Comment by sandrine-m** [comment]
I think so, I am closing it. @TranslatorIssueCreator, pleas let us know if you wnat us to reopen the ticket.

**Comment by vdancik** [comment]
Hi @saramsey , the fix was deployed at all levels.
