### ISSUE TITLE
Infores - URL Links to smart-api and others (HPO annotations) are sometimes "broken" 

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#151]
While this issue is surfaced in the UI, its the same issue if you just use the URL from the infores catalog. 

Steps:
1. Run MVP1 for Stromme Syndrome in the CI UI: https://ui.ci.transltr.io/results?l=Stromme%20Syndrome&t=0&q=acbbc8ba-ff1d-4d40-990e-17deb36ba569
2. Search for result "Corticotropin".  
3. On the Path from Corticotropin "treats" West Syndome, click the Treats Edge.  
4. In the Evidence pop-up click the Sources tab
![image](https://user-images.githubusercontent.com/38321826/226935469-3e9e0ad2-5022-4d57-8de9-0c295043f150.png)

5. Click the link provided for SRI Reference Knowledge Graph API http://smart-api.info/registry?q=1a41e3cd15f2b3bfa21c99900bfa1720
![image](https://user-images.githubusercontent.com/38321826/226935549-0919c726-3587-4479-8381-f85317e6c0fe.png)

6.  This URL is the same as here:  https://github.com/biolink/biolink-model/blob/master/infores_catalog_nodes.tsv
![image](https://user-images.githubusercontent.com/38321826/226935917-e2f94c2a-63ba-4544-968f-ce4410ee03ed.png)

7. It looks like it works for some (Biothings, TMKP) but not others (Automats, SRI) .  
8. Also seems inconsistent what page in SmartAPI it's going to which is very different experiences
- infores: cord19 https://smart-api.info/api/metadata/fc8245e92c970298449294fc04211869
- infores:biothings-multiomics-clinicaltrials https://smart-api.info/registry?q=08a5ddcde71b4bf838327ef469076acd
- infores:biothings-dgidb https://smart-api.info/ui/e3edd325c76f2992a111b43a907a4870
10. Can we ask for the teams to QC their infores before the data evidence deadline (3/24)? @cbizon @sierra-moxon @mbrush @cartmanbeck

**Comment by sstemann** [comment]
Also the HPO Link does not work in the UI.  it matches the infores page, so i assume this is an infores issue.

![image](https://user-images.githubusercontent.com/38321826/228635252-1e055afa-41ad-41ed-8497-02e9f81d819c.png)

![image](https://user-images.githubusercontent.com/38321826/228635669-8ec08395-7c7d-466a-b118-08671e8eeb1b.png)

![image](https://user-images.githubusercontent.com/38321826/228635738-68030196-1f2f-4665-8c19-d7e7796d3bc1.png)

**Comment by sierra-moxon** [comment]
from TAQA:
URLs need to be updated and working! :)

**Comment by sierra-moxon** [comment]
fixed hpo url https://github.com/biolink/biolink-model/pull/1266
