### ISSUE TITLE
Should the literature used in co-occurance calculations be returned to the user?  And, should we show infores identifiers for ARAs in the UI? 

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#152]
From TACT meeting:
  - Tyler -  edges that are returning are from ARAs only. What could be done to have more details about which underlying primary knowledge source these are coming from? Maybe a sub-property that defines when something is a literature co-occurrence so UI can show. 
  - Chris B mentioned that we need to understand where the information is coming from and make sure that we have EPC infrastructure to be able to properly show the details. Maybe having just a primary knowledge source is not enough. 
  - Rosina: Text mining can provide details on literature co-occurrence.
  - Andy: We don't want to confuse anyone, we will need to show some way to describe how we got the information about the edge so people understand and have peace of mind about how the edge was brought up.
  - Christine: Clarification, when Aragorn finds something and then there, is also a literature co-occurrence, is this not going to show up on its own? A user would want to see the names (PMED IDs) of the literature co-occurrence. Andy mentioned that this is something that does not exist.
  - Tyler: the path with literature co-occurrence should be hidden as those nodes were connected after the fact and will confuse the user.
  - Matt: there could be thousands of Pubmed IDs.
  - Matt: Suggest making all of the tools that are creating results known to the users and not hide them, maybe give them better names and educate the user so they understand how the results are generated and what happens. 
  - Tyler: the reason we kept it quiet about the tools is to present Translator as one tool for the marketing perspective. Users may question the purpose of Translator if they see and recognize the tools as their own pieces. 
  - Chris B: agree with Matt, if there are Translator tools creating new edges, users might want to know how things work. 
  - Andy: UI should be a place where there are dedicated pages that explain how the parts of Translator work and also point to the tools.

**Comment by sierra-moxon** [comment]
from TAQA:

- literature co-occurrence came up again. 
- many come from ARAX, but doesn't tell the users anything to follow up on?
- so literature co-occurrence is an example of the kinds of evidence that needs more information than just the infores; a list of PMIDs for this isn't a good second option.  We need to tell the user _how_ the relationship was created, but this might still not be helpful if we just display the "algorithmic solution" that created this.  Might need to tell them to go do a PubMed search on their own (if we tell them what to search at PubMed to replicate the algorithm)
  - can we fill in with TMKP "additional" reasons why this came about?  - this might help with the secondary PubMed search (at least guiding the user with a first try here).  
  - Gustavo: could be a LLM application… “summarize how this list of PMIDs are relevant to X and Y”? 
  - Amy: ARAX does include PMIDs on co-occurrence edges (or should - if some edges don’t have those, that’s a bug).
     -  Sarah: in this result set:  https://arax.ncats.io/?r=a0074db3-557d-4ab2-b221-4250241417fb > ARAX > Gonadorelin Hydrochloride > to Follitropin shows ARAX only
     - Amy: that one isn’t a co-occurrence edge - it’s produced by our creative mode. That’s a known bug. I’ll check on that issue…
     - Sarah: in UI only see inferred 

![Image](https://user-images.githubusercontent.com/4561292/233686641-81d5da83-f8d4-48d6-8f3f-a27b1d9892d9.png)

- When you look at the source of the edge; zero lit shows up, the sources show ARAX  
- Matt: does the evidence for the co-occurrence clutter the UI?  maybe we should separate the results. 
- Andy: sounds like we should not display at all. 
- Tyler: Did find these in the UI this morning in the "sources" tab.  
- Christine: Lose confidence in the system when the sources tab tells me its literature (this is a co-occurs in lit together), click on the source, and end up on ARAX landing page.  (infores URL is the ARAX "homepage").  
- Andy: is this the _only_ edge that connects these nodes?  No other edge between nodes?  Tyler: there is also a treats edge. 
- Christine: PMID search on the two terms returns nothing.  This feels like a "made-up" connection. 
- Matt: ARAX adds to every edge no matter what? 
- Andy & Tyler: we should just exclude the lit co-occurrence edges from the sources tab and there should always be another edge in the same graph that shows the same connection.  Leave the one that is "treats" in this example.  (e.g. [if you entity-search on gonadorelin it's in there with the two edges](https://ui.transltr.io/results?l=Primary%20Ciliary%20Dyskinesia&t=0&q=a0074db3-557d-4ab2-b221-4250241417fb)).

Tyler: Still see infores: ARA's in the results - not sure what to do with this one. 
Matt: If this is provenance for the creative mode algorithm/tool, then some argue to keep that/show that to users.  
Andy: the missing piece is "how its done" -- a landing page in the wiki that describes the algorithm might be better than the URL for the ARAX UI?
Tyler: but when that is the only edge, an explanation of the tool might not be enough for users to boost their confidence/for user understanding.   
Matt: two scenarios that this might happen for: 
- no explanation graph, maybe it can't explain it - bug? (ARAX)
- maybe it retrieved it from an external source but failed to show it - bug? (ARAX - is this _only_ ARAX?)
Amy: likely there are no results with a missing explanation graph (Need to ping David K on creative mode expertise. Andy: it seems like a baked-in requirement that if no explanation, then no result), but we do have a bug where when pulling from RTX-KG2, they are missing EPC attributes.   

Christine: would CO ever appear in the evidence graph?  
Sarah: suppression in the UI would mean no. 
GG: still most researchers would make a distinction between ‘this paper supports A treats B’ and ‘this paper mentions both A and B’.. (in other words - moving the CO paper to ‘literature support’ might be misleading)

Christine: infores: ARAs are good for debugging, but researchers won't tolerate it -- have to get these out for September. 

Sarah: in the Gonadorelin example, the other 29 paths in the UI, show only ARAX in the source.  Is that what we want? 

Actionable items:
1) suppress the co-occurrence source in the UI. 
2) address the known issue from Amy: add EPC properties as RTX-KG2 updates. 
3) validate: there should never be an infores for an ARA as the _only_ knowledge_source on an edge returned to the user.  caveat: Matt: this assumes that all ARAs can return their evidence for creative mode answers in the form of a support graph.  (TODO: follow up with Chris B, David, Andrew at architecture). 
4) change URLs for all ARAs to a wiki page about the ARA's creative mode algorithm instead of github pages/ARAX interface.  (Christine: from there, it can go to the tech details like github/ARAX UI, Andy & Kara: I want the wiki to be reformatted in the UI itself.)

**Comment by gglusman** [comment]
Re: the LLM direction, looks like there's a lot of activity in this direction - see this commentary in Nature: https://www.nature.com/articles/d41586-023-01273-w

**Comment by amykglen** [comment]
action item 2 in [this comment](https://github.com/NCATSTranslator/Feedback/issues/152#issuecomment-1518102547) (missing EPC on KG2 edges) has been fixed in ARAX/KG2 dev/ci instances

**Comment by sierra-moxon** [comment]
06/22/23 - retested on CI https://ui.ci.transltr.io/results?l=Primary%20Ciliary%20Dyskinesia&t=0&q=85bc81ef-5723-40b7-b1a0-7e5c2b1e9010

I see publications on the return, I see sources on the return.  I don't see lit cooccurrence edges.
I think we can close this, but I am not sure if I am testing to completion or the definition of done here.

**Comment by dnsmith124** [comment]
@sierra-moxon the UI is not removing any lit cooccurrence edges and do not plan to do so, but according to @gprice1129 we aren't processing the auxiliary graphs that usually have those edges.

**Comment by sierra-moxon** [comment]
Possibly related: (-)-epigallocatechin gallate in this query: https://ui.ci.transltr.io/results?l=Familial%20Pityriasis%20Rubra%20Pilaris&i=MONDO:0008251&t=0&q=137ebbb1-fd80-45a4-8382-edb5ccd70117 still shows "occurs together in the literature with" edges from Aragorn (_I think_) @cbizon 

Is this intended

**Comment by cbizon** [comment]
Hm, I think you're right. Thanks Sierra.  We must have an overeager rule pulling in some of these edges.

**Comment by sierra-moxon** [comment]
from TAQA:
- we don't want to see co-occurrence edges that are part of the reasoning - this is fixed.
- we see some still - Chris has taken them out in Aragorn CI yesterday
- is it ok to use these in a result?  (in this case, we are removing them, it is a problem). 
- lit-co-occur is a sub predicate of co-occur so entailment brings these in. We may need to move this out of the correlated hierarchy.  maybe not. 
- if we remove these, this will remove good results too.

**Comment by sierra-moxon** [comment]
I think this issue is closable: we've removed co-occurrence edges from the UI as they were displaying before.  Please of course reopen if I am mistaken. :)
