### ISSUE TITLE
Find Lormetazepam (score=100)

Open it, there is an edge "has adverse events + 3 more"

But when you open the edge, there seems to be evidence for only one of the 4 predicates (ameliorates).

Also, the ameliorates seems to be a bad read of the paper, which is more like "causes".  

Also, the source listed is the journal... should it be semmedb or text mined KP?

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#155]
## Steps to reproduce:
What drugs may treat Rhabdomyolysis?

**Comment by sierra-moxon** [comment]
Summary of the issue:

- [ ] opposite answer for the question asked, e.g: asked for "treats" got "causes" from the paper reading. 
- [ ] evidence is inconsistent between "summary view" and "detail view"
- [ ] evidence says "journal" but it is from a text-mined source really (either SEMMEDDB or TextMining KP).

**Comment by capasfield** [comment]
Link is broken. 
Andy to re-run and report back.

**Comment by Genomewide** [comment]
I can load the results from the link above.

**Comment by cbizon** [comment]
Further review - 

1. The ameliorates edge is coming from CTD.  There is a single curated paper listed as supporting the annotation, and it is correctly shown in the UI.    As far as I can tell, the paper is in spanish, and the only thing that you can get from pubmed is this title: "[Paroxetine-induced severe hyponatremic rhabdomyolisis]". Which contains nothing either way about Lormetazepam.  So I don't know if the user tracked down the spanish language paper and found support for this or not?

2 & 3, I think that there was confusion here about source vs paper.  The paper is not coming from text mining, but from CTD.

There is perhaps a question of whether the scoring is too high here.

**Comment by cbizon** [comment]
Also, I think that the SRI ref graph should not be assigning treats to CTD edges -it's too strong IMO.  @sierra-moxon ?

**Comment by sierra-moxon** [comment]
@putmantime - SRI ref graph does not create "treats" edges from CTD, does it?

**Comment by putmantime** [comment]
We do have "treats" edges from CTD but are certainly willing to review.
From our ingest [documentation](https://monarch-initiative.github.io/monarch-ingest/Sources/CTD/):

_"If the direct evidence field is 'marker/mechanism' the biolink:biomarker_for predicate is used along with the "is marker for" relation from RO. If the direct evidence field is 'therapeutic' the biolink:treats predicate is used along with the "is substance that treats" relation from RO."_

CTD calls these chemicals "therapeutic"

**Comment by cbizon** [comment]
Yeah @putmantime perhaps with the new treats hierarchy coming there will be a good match.   FWIW, we also did a CTD ingest and felt that the therapeutic marker in CTD was very broad, including a lot of things like "x showed a reduction in some biomarker in some animal cell based model".  Certainly interesting, but far from treats IMO.

**Comment by sstemann** [comment]
@sierra-moxon i dont see this happening any longer for this example (adverse events + treats edges)

@cbizon @putmantime i do still see Treats edges from CTD (via MolePro) and from the SRI Ref KG - will that change?  should it be a different ticket to track?

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/4068ffb9-9b20-4804-bba6-41b799731acc)


![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/9f681dd1-7f61-4947-8013-537225a980b2)

**Comment by sstemann** [comment]
seems resolved in this specific example:

https://ui.transltr.io/main/results?l=Rhabdomyolysis&i=MONDO:0005290&t=0&q=1b954852-802c-4693-b795-0c185646968f
https://arax.ncats.io/beta/?r=1b954852-802c-4693-b795-0c185646968f

The edges do not have support graphs
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/82fe9684-9e56-43dc-9e93-4a34284b3f27)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/a05c401a-58c4-4b37-b145-53220559e321)

**Comment by Genomewide** [comment]
There seems to be more to this than the UI issue of what to display, but I agree the UI issue seems to be resolved.

**Comment by mbrush** [comment]
@putmantime  another issue this surfaces is that SRI Reference KG should not be the primary source for edges that it ingests from other sources.  I've asked Kevin S about this, and I think he says that the SRI Ref KG data does indicate the primary external source.  But perhaps the ARA that is retrieving the edge from the Ref KG is not finding this info in the SRI Ref KG message, and thus not correctly attributing the true source (CTD in this case) as the primary source.
