### ISSUE TITLE
Request for Visual Indicator that there is something on the Evidence > Sources tab

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#156]
Steps to reproduce:

1. Run MVP1 for Stromme Syndrome in the UI: https://ui.transltr.io/results?l=Stromme%20Syndrome&t=0&q=24cd1899-ee25-4267-b63b-8bccc15ff1c4
2. View "Cosyntropin" may or may not be your first result
![image](https://user-images.githubusercontent.com/38321826/228624559-4648b44f-1dcf-445b-b415-d70fa9d56a82.png)

3. View All Evidence (0)
4. Click Has Part link
![image](https://user-images.githubusercontent.com/38321826/228624691-ed577433-d319-48ed-8db7-d212d50b2916.png)

5. User has to know there could still be something in the sources tab.  
![image](https://user-images.githubusercontent.com/38321826/228624740-55277333-6e4f-42ba-bbbe-08350d850302.png)

6. I realize this screen is being evaluated but if we could throw a count in there somehow short term and in the View All Evidence - include count for data evidence - it would be really helpful.

**Comment by sierra-moxon** [comment]
from TAQA:
some indication in step 4 (in the tab header) would be helpful so the user knows to click on "sources" to see step 5 above. 

- [ ] evidence should not be 0; should pub counts be different than other kinds of source counts?
  - [ ] summary of types of evidence?, e.g. "0 pubs, 3 other sources"?  or "1 source, 5 publications", "4 sources, 5 publications" 
  - [ ] figure out how to disambiguate "sources" from pubs. 
- [ ] in addition, there should be an indication of "where" to click on to get the actual evidence.

**Comment by sstemann** [comment]
UI team is working on this.

**Comment by gprice1129** [comment]
I think this has been addressed. Can we close this @sierra-moxon ?

**Comment by dnsmith124** [comment]
Can confirm this has been addressed by the following changes:
- Both publication and source count are listed under 'view all evidence'
- Publications tab no longer shows in the evidence modal when no publications are available
- Edges in the path view now feature an icon denoting whether they have any publications or sources

**Comment by dnsmith124** [comment]
marking complete
