### ISSUE TITLE
Node Norm Question - Ebselen

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#157]
I believe this page shows that there are synonyms for C0058903 that do not show up in Node Norm

![image](https://user-images.githubusercontent.com/38321826/229222088-15629edf-c7a2-4658-a84f-064aacd0b9e7.png)

https://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&type=synonym&code=C0058903

But that in Node Norm its not mapping synonyms for UMLS
![image](https://user-images.githubusercontent.com/38321826/229220698-bbfeb03f-1b8b-43f4-a776-f5e3fbb3aba2.png)

I believe that is the reason for two Ebselen's in the UI for MVP1 for "meniere disease"
- BTE is using UMLS:C0058903
- Improve is using PUBCHEM.COMPOUND:3194 which returns synonyms (UNII and DrugBank) that match the UMLS synonyms, but it does not return the UMLS for the substance 

![image](https://user-images.githubusercontent.com/38321826/229222579-97976533-f021-4791-b002-6d84a18f1752.png)

https://ui.transltr.io/results?l=Meniere%20Disease&t=0&q=c2d14b2b-8f15-4b7e-adef-6792de35fa81

![image](https://user-images.githubusercontent.com/38321826/229220790-d783944e-bc34-4a11-9783-2c9ff5a7d3b0.png)

**Comment by bill-baumgartner** [comment]
Just to add to Sarah's comments above, the mappings that would link the UMLS id for `Ebselen` to other identifiers exists in the NCI Thesaurus as she pointed out. Based on the [Babel configuration file](https://github.com/TranslatorSRI/Babel/blob/master/config.json), it looks as though NCIT is used for some mappings but not for chemical mappings (if I'm reading it correctly). Perhaps adding the NCIT mappings for chemicals would be of help here?

**Comment by sierra-moxon** [comment]
It looks like there is a ticket in the Babel repo for this issue, so setting this ticket to "in progress". @gaurav please of course correct me if I got this wrong :)

**Comment by sstemann** [comment]
@gaurav while this specific search in UI is not happening (BTE now returns a pubchem) its entry isn't updated in Node Norm and I'm seeing similar behavior for dexamethasone - test 7/14

<img width="935" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/4a9d11ff-a978-4acb-884e-a624f42c26b6">

<img width="875" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/d8aa189e-0769-4731-bc09-579cb4ae2a69">

<img width="874" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/c3e273e7-d1ed-4adf-979e-617e2910ee60">

{
  "UMLS:C0011777": {
    "id": {
      "identifier": "UMLS:C0011777",
      "label": "dexamethasone"
    },
    "equivalent_identifiers": [
      {
        "identifier": "UMLS:C0011777",
        "label": "dexamethasone"
      }
    ],
    "type": [
      "biolink:ChemicalEntity",
      "biolink:NamedThing",
      "biolink:Entity",
      "biolink:PhysicalEssence",
      "biolink:ChemicalOrDrugOrTreatment",
      "biolink:ChemicalEntityOrGeneOrGeneProduct",
      "biolink:ChemicalEntityOrProteinOrPolypeptide",
      "biolink:PhysicalEssenceOrOccurrent"
    ]
  }
}

**Comment by gaurav** [comment]
The next version of NodeNorm has [both UMLS:C0058903 and UMLS:C0011777](https://nodenormalization-dev.apps.renci.org/1.3/get_normalized_nodes?curie=UMLS%3AC0058903&curie=UMLS%3AC0011777&conflate=true) mapped to PUBCHEM.COMPOUND:3194 and PUBCHEM.COMPOUND:5743 respectively, so that should fix this duplication issue. I can close this issue once this NodeNorm has been deployed.

**Comment by sierra-moxon** [comment]
@gaurav - maybe this one can be closed already? :)
