### ISSUE TITLE
Terms with a lot of words will exceed the bounds of node display. See "Antirheumatic Drugs, Disease-Modifying" in the attached image

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#162]
## Steps to reproduce:
Search a term that will return a node with a lot of words in it, and view the graph.

## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20230418174220396271.jpeg)

**Comment by sierra-moxon** [comment]
@dnsmith124 - has fixed already! :)

**Comment by dnsmith124** [comment]
As Sierra said above, the fix has been implemented and merged into the FE's `develop` branch. Once a build to the development environment has occurred I'll close this one out!

**Comment by dnsmith124** [comment]
Confirmed this is resolved on dev, closing.
