### ISSUE TITLE
Evidence pages (which publication goes with which source with which edge?)

### ISSUE THREAD

**Issue by cbizon** [NCATSTranslator/Feedback#165]
Today in TAQA we were looking at edge evidence.  The graph shows "ameliorates +2 more".  Clicking that brings up the evidence box:
![image](https://user-images.githubusercontent.com/10744350/235211547-c24a6a11-9954-4ac3-8c1e-5e37961ce5d4.png)
![image](https://user-images.githubusercontent.com/10744350/235211615-014000e4-cc4e-432e-8c3c-350e1e4b5e35.png)

Based on the discussion and watching people use it, I think that this page is somewhat confusing.

Part of it comes, I think because sources and publications are separated out, but a single edge can appear in both tables.  So people had trouble matching which source had produced the publication.

Also, IMO it's not very clear that the "publications" and "sources" are click-able items.

**Comment by sierra-moxon** [comment]
from TAQA:
which "source" is providing which "publication" - some indication in the UI would be a nice feature.  Making table headers into "buttons" or a visual queue that we want to be able to click on those would be helpful. 
David: all UI testing issues are good ones!  We can do more user testing for this.  Is this a "debugging" issue or a "user" issue?  
Chris: It's a user-level concern; we want to see what the source of the evidence is (e.g. is it a curated source or a text-mined source?)
David: especially if you are looking at an evidence tag with > 10 - it would be hard.  In the meantime, when you mouse over a particular edge; there is a tooltip with each predicate listed, if you click there, you get sources and pubs for just that predicate.  👍 
Andy: Do we need to disambiguate between sources that have pubs listed and those that just point to a website that may have pubs but not necessarily?  Need a mockup to decide here if disambiguating these two cases is important.  Matt: "sources" means "pubs" to some folks.  Other ideas: a references tab?

**Comment by sierra-moxon** [comment]
06/22/23 - restest on ci - still happening as described in the ticket.

**Comment by dnsmith124** [comment]
I've implemented Desi's new design for the tab headings in the evidence modal, which she user tested and were shown to be much more 'clickable', here's what they look like now: 

![Screen Shot 2023-06-26 at 2 02 13 PM](https://github.com/NCATSTranslator/Feedback/assets/54226761/6de0aed1-fade-4234-910b-7928cd8b9feb)

We can consider that portion of this issue resolved, confirmed that the change is live on CI.  

Each publication has an edge listed, and to view the publications for just a particular edge (not a group of edges), the user can hover over a set of grouped predicates and click on the individual one they're looking for to view evidence for just that predicate. That seems to address that issue. 

The only possible remaining item is notating somehow what source a publication came from. @sierra-moxon Do you think this is this a serious need, or just a recommendation?

**Comment by cbizon** [comment]
I do think that this looks nice & makes the tabs much more clickable looking.  On the question of noting what source a publication came from, I think it's actually a serious need.  I watched a TAQA meeting stumble over this question and end up assigning the incorrect source to a publication.

**Comment by Genomewide** [comment]
So, then a tag or some indicator that a publication is from seemed or textminer or drugbank. This would be something that was integrated into the publication table. Is that what you mean?

**Comment by cbizon** [comment]
yeah, right now theres a table showing relationship-pub and a different table showing relationship-source.  And you have to mentally do the join on relationship (while looking at only one of the two tables) to figure out which pub came from which source.  And in the case where the same relationship has multiple sources and multiple pubs, there's no way to disentangle them (not sure how often that happens though).

**Comment by sierra-moxon** [comment]
@Genomewide - Is it possible to figure out if this is a fixable issue for September (I think there are other tickets that mention the confusion between sources and publications tabs here).? 

Ideas that I've heard tossed around -

- add a column to the publications tab that reveals the Translator source (in addition to the journal in a separate column) that provides it, and on the "sources" tab, add a column that holds a linked count of the number of publications provided by each source for this edge -- the link should go to the "publications" tab 🥴 ?). 

- combine sources and publications into one single tab styled after the current "publications" tab.  when there are no publications, just show the `relationship` and `source` columns, but populate the `source` column with the Translator source URL.

**Comment by sierra-moxon** [comment]
from TAQA: 
putting the PKS into the "source" column of the publications tab (or something like this with plenty of mockups and review) is something that UI will continue working on for September.

other UI brainstorming ideas:

- This might mean we need to refactor the evidence to be something other than a table of evidence - maybe a report, or a list of evidences that have different attributes?  
- Report on one tab, table below
- We have two different evidence displays, one for "everything" and one for each edge.  
- pubs in sections per "source" (where source is the PKS).

**Comment by Genomewide** [comment]
There are plans for this to change post-September.  Web design UX suggests that separating things out into the type of action makes sense. Nothing will change related to this prior to September though.

**Comment by sierra-moxon** [comment]
@Genomewide - I think I read in another ticket that this isn't coming for September, is that right?  (I made that assumption and moved this to "Fall") -- please correct me if I made a bad assumption.

**Comment by sierra-moxon** [comment]
closing as completed.
