### ISSUE TITLE
Botulinum toxin type a shows up twice in the result set for "What treats Cerebral Palsy", one page apart with different scores for each result

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#167]
https://ui.test.transltr.io/results?l=&t=&q=c572dfd1-1a94-4074-bb5a-6bd0b27cc045

page 1 result with 30 evidence
<img width="1439" alt="Screen Shot 2023-05-01 at 4 13 41 PM" src="https://user-images.githubusercontent.com/4561292/235547258-7201f37f-8737-43cc-ae1e-d22dad03ae77.png">

page 2 result with 1 evidence 

<img width="1091" alt="Screen Shot 2023-05-01 at 4 14 00 PM" src="https://user-images.githubusercontent.com/4561292/235547308-27e9cd8c-f8c0-4d31-a146-f434958b1821.png">

<img width="1128" alt="Screen Shot 2023-05-01 at 4 15 52 PM" src="https://user-images.githubusercontent.com/4561292/235547540-8659d931-d757-4d01-9efc-5ce40dd3590f.png">

papers do not appear to overlap

**Comment by sierra-moxon** [comment]
from TAQA:  
behind the scenes, these have different identifiers (different curies) - so UI can't merge.  
Chris B: could be a mistake in NN, they should be synonymous, or they could be really different and people give them the same name.  That would take some more work, could be a "conflation", etc.

**Comment by sierra-moxon** [comment]
from TAQA: this could be a NN issue. 
http://identifiers.org/umls/C0006050
http://identifiers.org/unii/E211KPY694

**Comment by gaurav** [comment]
[MESH:D019274](https://uts.nlm.nih.gov/uts/umls/vocabulary/MSH/D019274) should connect these two cliques together (since it is connected to [UMLS:C0006050](https://uts.nlm.nih.gov/uts/umls/concept/C0006050) in the first clique and is itself part of the second clique), so yup, it does look like a NodeNorm issue. Let me look into what's going wrong here.

**Comment by gaurav** [comment]
I think the issue here is that we don't currently use MeSH identifiers when combining protein identifiers -- we only use NCIT, UMLS, UniProtKB and the protein ontology. I worry that doing that might overcombine concepts -- I'll discuss this with @cbizon and get back to you.

**Comment by sierra-moxon** [comment]
@gaurav - is this one closeable? :) (of course reopen if not)
