### ISSUE TITLE
Evidence for "Fohl1 causes Spastic Diplegia" does not seem correct (paper talks about tannins and cold weather affecting liver function in wood rats)?

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#171]
https://ui.test.transltr.io/results?l=Cerebral%20Palsy&t=0&q=7a3c44d2-784f-4561-bcc7-6ef9154087f4

<img width="1122" alt="Screen Shot 2023-05-03 at 10 56 39 AM" src="https://user-images.githubusercontent.com/4561292/236003511-d15a7d66-e6a8-4f3e-a771-7e6e610b4196.png">
<img width="1130" alt="Screen Shot 2023-05-03 at 10 56 52 AM" src="https://user-images.githubusercontent.com/4561292/236003551-63cd3dc2-34d8-4216-b8d6-a778a74db38b.png">

https://pubmed.ncbi.nlm.nih.gov/31580494/

<img width="743" alt="Screen Shot 2023-05-03 at 10 57 08 AM" src="https://user-images.githubusercontent.com/4561292/236003608-27a8eed9-cc95-4969-843c-29bf15516be5.png">

on ARAX, a completely different pub is listed, but it too doesn't speak at all about this gene->disease relationship? :

<img width="1255" alt="Screen Shot 2023-05-03 at 10 59 51 AM" src="https://user-images.githubusercontent.com/4561292/236004246-7e931223-9ce5-4486-aedc-5808f0acae6a.png">

https://pubmed.ncbi.nlm.nih.gov/34533422/

<img width="727" alt="Screen Shot 2023-05-03 at 11 01 02 AM" src="https://user-images.githubusercontent.com/4561292/236004468-d58c7bcd-810b-40ef-a8ce-77a69663e9f2.png">

This result is also very low ranked for Aragorn (0.538) but is the second result in the UI with a score of 100.0?

**Comment by sierra-moxon** [comment]
possibly related to : https://github.com/NCATSTranslator/Feedback/issues/165

**Comment by sierra-moxon** [comment]
from TAQA:
the edge in the ARAX screen shot is for treated_by not the causes edge for Fohl1

**Comment by gprice1129** [comment]
Verified that the PMID attached to the Folh1 -causes-> Spastic Diplegia edge is the only PMID attached to the edge from the raw data. The edge is coming from BTE and is likely a SemmedDB issue.

**Comment by andrewsu** [comment]
Agreed, this is a semmeddb issue.  This is the link with more information:

https://biothings.ncats.io/semmeddb2/query?q=predication.pmid:31580494%20AND%20subject.umls:C1333570

This is the lone supporting sentence:

> "Ambient temperature has been shown to alter liver function in rodents and the toxicity of some PSMs, but little is known about the physiological and nutritional consequences of consuming PSMs at different ambient temperatures."

PSM is a synonym for [FOHL1](https://www.ncbi.nlm.nih.gov/gene/2346). "Little's disease" is a synonym for [Spastic Diplegia](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0001167).

In terms of potential solutions to this problem, we have two filters that are still being explored:
* filtering by # of PMIDs in support ([issue](https://github.com/NCATSTranslator/Feedback/issues/100))
* filtering by NER scores (adding that info to the API is [in progress](https://github.com/biothings/biothings_explorer/issues/606))

It seems likely that either/both of the solutions above would catch this bad semmeddb predication...

**Comment by sierra-moxon** [comment]
Is it possible to show the matching sentence in the UI for SEMMEDDB edges @gprice1129?

**Comment by andrewsu** [comment]
Just noting that thanks to @erikyao in https://github.com/biothings/biothings_explorer/issues/606, the semmddb NER stats are now available in the biothings SemMedDB API.  For example, for the "Fohl1 causes Spastic Diplegia" edge mentioned above, here is the new semmeddb record: https://biothings.ncats.io/semmeddb2/association/C1333570-CAUSES-C0023882

```
{
  "_id": "C1333570-CAUSES-C0023882",
  "_version": 1,
  "object": {
    "name": "Little's Disease",
    "novelty": 1,
    "semantic_type_abbreviation": "dsyn",
    "semantic_type_name": "Disease or Syndrome",
    "umls": "C0023882"
  },
  "pmid_count": 1,
  "predicate": "CAUSES",
  "predication": [
    {
      "object_score": 1000,
      "object_text": "little",
      "pmid": 31580494,
      "predication_id": 182378913,
      "sentence": "Ambient temperature has been shown to alter liver function in rodents and the toxicity of some PSMs, but little is known about the physiological and nutritional consequences of consuming PSMs at different ambient temperatures.",
      "sentence_id": 342370606,
      "subject_score": 827,
      "subject_text": "PSMs"
    }
  ],
  "predication_count": 1,
  "subject": {
    "name": "FOLH1 gene",
    "novelty": 1,
    "semantic_type_abbreviation": "gngm",
    "semantic_type_name": "Gene or Genome",
    "umls": "C1333570"
  }
}
```

See the new keys for `subject_score` and `object_score` -- values range between 0 and 1000 where a higher number is meant to indicate a higher confidence in the NER.  Unfortunately, SemMedDB appares to be very confident in this case (even though both the subject and object are NER errors).  :(

**Comment by andrewsu** [comment]
Abiraterone no longer appears in my latest test results: https://ui.test.transltr.io/results?l=Cerebral%20Palsy&t=0&q=f8607753-b9ed-4034-8abd-8fb4b3170659

Possibly at least in part because the erroneous edge mentioned in this issue was filtered out by the PMID count threshold on SemMedDB that was described in https://github.com/NCATSTranslator/Feedback/issues/100#issuecomment-1564988010. 

Unless there are other issues to discuss here, I recommend closing this issue.

**Comment by erikyao** [comment]
@andrewsu just an FYI that the original NER record is

```txt
"182380054","182378913","PSMs","1","2","412","416","827","NOM","386","398","little","2","7","330","336","1000","2020-01-21 15:54:19"
```

from SemMedDB file `semmedVER43_2023_R_PREDICATION_AUX.116080.csv`. 

-----

`182378913` is the predication ID associated with above NER record, whose original data are

```txt
"182378913","342370606","31580494","CAUSES","C1333570|2346","FOLH1 gene|FOLH1","gngm","1","C0023882","Little's Disease","dsyn","1",\N,\N,\N
```

from SemMedDB file `semmedVER43_2023_R_PREDICATION.116080.csv`.
