### ISSUE TITLE
Insulin treats functional disorder

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#176]
## Steps to reproduce:
query: what drugs may treat Autism?

## Screenshots:
Failed to upload screenshot.

**Comment by sandrine-m** [comment]
<img width="1070" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/d16ec551-0f3a-4829-abca-6c81cd362aab">

Can ARAX Translator Reasoner remove Pathological processes that are high in the ontology hierarchy such as Functional disorder ?

**Comment by edeutsch** [comment]
From TAQA: Unable to reproduce with existing link or redoing the query.
Please re-open if still a problem
