### ISSUE TITLE
Source for Edge with Primary KS not Displayed

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#178]
I think this issue is because of a mismatch between the primary KS value tag "hetio" and the infores catalog, which is automat-hetio or hetionet
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/949787b0-b5da-473f-a21d-b165b11f6fd1)
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/409609ae-9a7f-4bb2-a0c2-57bf57923ca7)
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/d374da9c-aa40-4b41-9f1c-e472ae32639f)
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/8748fad9-081f-4c11-91a6-bb3608c5b5c4)

Steps:

1. Use the Test UI > What gene is upregulated by "lisdexamfetamine"
2. View the first result slc6a3
3. on the first/shortest result, click the edge "Affected by +5"
4. note that the "showing evidence for" lists Slc6a3 Directly Physically Interacts With Lisdexamfetamine
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/439f652e-8fe0-4602-9641-ff50e18511f6)

5. Note:  the publications tab does not have relationship Directly Physically Interacts With, neither does the Sources tab
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/cec48e42-481b-495c-aa01-c2f629a3dff4)

6.  In ARAX UI, it looks like this edge is coming from BTE> primary KS > Hetio: https://arax.ncats.io/?r=761ba21f-3935-479a-85c4-c8384264adc6
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/8355537d-d6f9-45ec-8e45-246cf48c4cab)

7. It's also coming back from Robokop:
 
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/94fd4d68-7ccb-4c80-915c-b014f026a4fb)

**Comment by sierra-moxon** [comment]
from TAQA:
mismatch between infores:hetio and infores:automat-hetio.
hetio is a source should be the primary, automat should be the aggregator
should be fixed in test; but we will check.
infores:hetio-net and infores:automat-hetio-net
Sierra: infores catalog is broken AGAIN.  <fix>

**Comment by sierra-moxon** [comment]
update: infores catalog has been migrated to YAML (old TSV is still in the repository to help folks transition without breaking BMT installations).  https://github.com/biolink/biolink-model/pull/1318 addresses the hetio-net consistency issue brought up last time.

**Comment by sierra-moxon** [comment]
retested - 06/22/23 on ci. 
https://ui.ci.transltr.io/results?l=Lisdexamfetamine&t=3&q=37271f9d-7cb9-48b9-aed3-d12f2915197b
https://arax.ncats.io/?r=37271f9d-7cb9-48b9-aed3-d12f2915197b

No longer seeing "affects 5+" in the slc6a3 result. 
![Image](https://github.com/NCATSTranslator/Feedback/assets/4561292/1c0953c0-d4e1-4d19-9a64-dc0a8946473d)

I see the "directly physically interacts with" predicate in the evidence display for the first, direct edge. 

I think this is working now :) closing as complete.
