### ISSUE TITLE
Publication URLs not always working?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#180]
In the Test UI, I ran what chemical upregulates MC1R:  https://ui.test.transltr.io/results?l=MC1R&t=1&q=79f89222-75a3-48f8-88a3-0027c6dd758d

Expand the results for FOS > click the edge JUN <upregulates> Mc1r.  

Notice the publication entry has no info

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/40b9397d-fe3f-4413-a53b-a0141de1376c)

Click the Read More Link:  https://www.ncbi.nlm.nih.gov/pmc/PMC:5133840 > takes you to a 404

View the results for BTE in the ARAX UI https://arax.ncats.io/?r=79f89222-75a3-48f8-88a3-0027c6dd758d

The link to the pub:  https://pubmed.ncbi.nlm.nih.gov/27827925/ works

If you change the "read more link" but removing the semicolon between C and 5 - then it works https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5133840/

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/0ef9afd0-a691-4099-9956-38501c9dd0d0)

**Comment by gprice1129** [comment]
This is now fixed. Closing.
