### ISSUE TITLE
The purple arrow just spins for hours and rarely if ever actually produces any results.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#182]
## Steps to reproduce:
Go to this URL: https://ui.test.transltr.io/results?l=Autism&t=0&q=920ada2c-6a4c-4562-b697-06e481adfb0b
OR
just about anything else, such as selecting a query like "What drugs may treat autism"

**Comment by gprice1129** [comment]
This was likely due to a bug in the UI that has been addressed. It is the UI team's opinion that this issue should be closed.
