### ISSUE TITLE
Every score is coming back as 50.2

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#186]
https://ui.transltr.io/results?l=MET&t=2&q=14da9c39-1dc2-41db-b60c-938ea98073e6

![Image](https://user-images.githubusercontent.com/55069176/239586287-cd3ed9d8-52b9-40d0-b8b8-2eab3e23739c.png)

**Comment by Genomewide** [comment]
Reran - scores are still 50.2



![Image](https://github.com/NCATSTranslator/Feedback/assets/55069176/66c030d9-076e-4454-a7ad-d8f482a8a227)

**Comment by sierra-moxon** [comment]
from TAQA:
we expect the score to differ between each result because they are supposed to be ranked percentiles. 
not every ARA has to return, but ARS re-ranks to fit scores between 0 and 1 and then turns into a precentile.
the main concern is that 50.2 is very specific and seems like it should fluctuate between results.

**Comment by gprice1129** [comment]
This issue linked is from TRAPI 1.3. Should we close this issue as irrelevant?

**Comment by ShervinAbd92** [comment]
hi @gprice1129, yes i believe we can close it. I reran the query and the initial Pubchem response' scores that @sierra-moxon posted, have improved and not stuck at 50.2 anymore
