### ISSUE TITLE
UI did not send "ids" parameter with query - could be user error (not selecting autocomplete) 

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#187]
http://transltr-bma-ui-dev.ncats.io/results?l=Pertussis&t=0&q=7c08b464-dc2c-4018-8fbf-e01a383d24bb
https://arax.ncats.io/?r=7c08b464-dc2c-4018-8fbf-e01a383d24bb

ARS also has no ids: https://ars-dev.transltr.io/ars/api/messages/7c08b464-dc2c-4018-8fbf-e01a383d24bb?trace=y

To see the JSON missing identifiers on ARAX UI:
click on ARAX in the Queries view,
click on JSON in the top tab in the ARAX UI
```
{
  "edges": {
    "t_edge": {
      "attribute_constraints": [],
      "knowledge_type": "inferred",
      "object": "on",
      "predicates": [
        "biolink:treats"
      ],
      "qualifier_constraints": [],
      "subject": "sn"
    }
  },
  "nodes": {
    "on": {
      "categories": [
        "biolink:Disease"
      ],
      "constraints": [],
      "is_set": false,
      "fulltextname": "on"
    },
    "sn": {
      "categories": [
        "biolink:ChemicalEntity"
      ],
      "constraints": [],
      "is_set": false,
      "fulltextname": "sn"
    }
  }
}
```

prod does have results: https://ui.transltr.io/results?l=Pertussis&t=0&q=3c4b7d45-ac58-44fe-acd9-3cef240b3c88
We did retry with the autocomplete completed for sure, and we are still seeing some issues ("Calculating")

**Comment by Genomewide** [comment]
Gus found bug and fixed it.
