### ISSUE TITLE
Can we "kill" processes submitted when the user moves on from their query.

### ISSUE THREAD

**Issue by sharatisrani** [NCATSTranslator/Feedback#189]
When UI gets a Q, it spawns off calls to ARAs etc.  But if the user does wait for the execution to complete, and either issues another Q or kills the window, the spawned off processes should be terminated.  This will be important for the system to scale.

**Comment by sierra-moxon** [comment]
From TAQA:
we would need discussion from ARS/ARAs/TRAPI to declare a "stop background processes" flag or some sort of coordination from federated services under the UI.

**Comment by gglusman** [comment]
There's literature on **orphan processes in distributed systems**, mostly paywalled.

This is accessible: https://www.iosrjournals.org/iosr-jce/papers/Vol5-issue1/C0511216.pdf

**Comment by sierra-moxon** [comment]
update from TAQA:
@MarkDWilliams is currently implementing this; the ARS will no longer continue to accumulate additional results past the 5 min timeout.

**Comment by gglusman** [comment]
Realizing that this change would preclude one use case that I used last week... I queried Translator for one of the rare diseases on the list, and as soon as it offered the stable URL, copied that, saved it, and moved on to the next rare disease, on the assumption the results would be there later on.

**Comment by sierra-moxon** [comment]
closing as completed; ARS will no longer accept results past the 5 min cutoff.  please of course reopen if I got this wrong. :)
