### ISSUE TITLE
Generic results for MVP2 queries

### ISSUE THREAD

**Issue by cartmanbeck** [NCATSTranslator/Feedback#191]
I have run a few queries and the highest-rated results are very generic concepts that will be hard for a user to follow up on. It would be great to find a way to filter out these kinds of results.

One Example:
"What chemical dupregulates FREM1 (Human)?" - PK: fa3435ec-fb9b-49a8-93f5-81a4561699c2
https://ui.transltr.io/results?l=FREM1&t=1&q=fa3435ec-fb9b-49a8-93f5-81a4561699c2
Problem result: "Promoter regions, genetic", "Consensus sequence"
Note: The 3rd result, Chloride Ion, is excellent. :)

**Comment by dnsmith124** [comment]
While the functionality that is being requested is a great idea (add ability to filter out overly generic results), the UI has no way that I'm aware of to determine the genericness of any particular result programmatically. 

Is there an attribute that conveys this in the data currently?

**Comment by andrewsu** [comment]
Just to add some info from https://arax.ci.transltr.io/?r=fa3435ec-fb9b-49a8-93f5-81a4561699c2

![image](https://github.com/NCATSTranslator/Feedback/assets/2635409/9e9cffb8-2502-49ff-a1a4-670494e99cbf)

Both aragorn and ARAX return "Promoter Regions, Genetic" as a result based on Semmeddb ingested through RTX-KG2.  (I'm pretty sure it doesn't come back from the BioThings SemMedDB API because we use the `novelty` filter, which I think does a reasonable job of removing very generic concepts.)

I also think something weird is going on with score normalization.  ARAX reports a score of 1.0, and aragorn reports 0.409.  UI normalizes/combines that into a score of 100, which would not be my expectation personally...

**Comment by ShervinAbd92** [comment]
@andrewsu I am trying to look into the score normalization for your pk. normally i can curl individual ARA's response and look into their results & scores but for this pk, the provided arax and aragorn's pk is unknown. was this submitted on the CI environment?

**Comment by andrewsu** [comment]
I was able to retrieve them using https://arax.ci.transltr.io/api/arax/v1.4/response/a9eb462e-e7b8-440b-ae91-083ee71c7b24 (ARAX) and https://arax.ci.transltr.io/api/arax/v1.4/response/119f95b8-de9f-4809-9cac-ea9cb52f5946 (aragorn).

**Comment by edeutsch** [comment]
Side note: when you requests PKs from ARAX, it fetches them from the ARSes (it tries all of them!) and then also puts the document through some validation (although still turned off) and some basic stats calculation, i.e. this:
```
  "validation_result": {
    "message": "Validation disabled. too many dependency failures",
    "n_edges": 8,
    "n_nodes": 5,
    "provenance_summary": {
      "n_sources": 0,
      "predicate_counts": {
        "biolink:affects": 1,
        "biolink:occurs_together_in_literature_with": 4,
        "biolink:regulates": 3
      },
      "provenance_counts": {
        "biolink:affects --> no provenance": [
          "biolink:affects",
          "-",
          "no provenance",
          1
        ],
        "biolink:occurs_together_in_literature_with --> no provenance": [
          "biolink:occurs_together_in_literature_with",
          "-",
          "no provenance",
          4
        ],
        "biolink:regulates --> no provenance": [
          "biolink:regulates",
          "-",
          "no provenance",
          3
        ]
      }
    },
    "size": "213 kB",
    "status": "PASS",
    "validation_messages": {
      "errors": [],
      "information": [
        "Validation has been temporarily disabled due to problems with dependencies. Will return again soon."
      ],
      "warnings": []
    }
```

is injected into the TRAPI by the ARAX system. You could not see that if you requested the PK directly from the ARS.

**Comment by sierra-moxon** [comment]
@MarkDWilliams - from your last analysis, this looks like a post-september item, is that right?
