### ISSUE TITLE
"What chemical downregulates" returns non-chemicals including genetic elements, proteins 

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#193]
Query: What chemical downregulates RUNX2 (human)? 
Results: 7 of 10 on the first page are not chemicals, similar for page 2. Looking at the results in the left side bar, they include 281 genes, 409 proteins for example. 
http://transltr-bma-ui-dev.ncats.io/results?l=RUNX2&t=2&q=71832317-8485-42b3-b850-0f60a1839b83

I know I can filter on chemical but shouldn't this query do this automatically, based on how its phrased? 

Somewhat similar to https://github.com/NCATSTranslator/Feedback/issues/191.

**Comment by Genomewide** [comment]
There are two different things that were confused here.  the 7 chemicals that look like they may not be chemicals have very long names. The groups in the facets that are mentioned are from the wrong set of facets as far as I can tell. 



![Image](https://github.com/NCATSTranslator/Feedback/assets/55069176/bf1f941e-c8c6-4b54-a888-615a63dce619)

I am closing unless this comes back up. We will listen for additional confusion about the facets
