### ISSUE TITLE
FDA approved ChemicalEntities still have long chemical names.  

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#196]
From TAQA, via Andy: 
Reran this and get names now https://ui.transltr.io/results?l=MET&t=2&q=9408a551-bfea-4ec7-a5dd-a60ded6f6aa6

However, there are some unexpected names when the FDA filter is on now:

Not sure if:
- is actually FDA approved?  If its FDA approved, then this can be closed, its just a long name.
- just has a long name and is FDA approved? 

see: https://github.com/NCATSTranslator/Feedback/issues/185
Andy went to pubchem and can't find the FDA approval.   MolePro gets FDA approval from multiple sources.  

Should be from NN; according to NN this is the name, and b/c PUBCHEM is the source of names, its right.
UNII has the name from https://gsrs.ncats.nih.gov/ginas/app/beta/substances/3DGD69C6PV

Sarah: I think Improving is returning it as PUBCHEM.COMPOUND:57390074
https://gsrs.ncats.nih.gov/ginas/app/beta/substances/3DGD69C6PV

Vlado: when annotating in MolePro they do not change the names.

**Comment by Genomewide** [comment]
https://pubchem.ncbi.nlm.nih.gov/compound/57390074

**Comment by sierra-moxon** [comment]
#259  is another instance.
