### ISSUE TITLE
"Cyclosporin A treats rhabdomyolysis" but actually increases risk for it

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#197]
## Steps to reproduce:
Asked for drugs that may treat rhabdomyolysis. Quickly got just 7 hits from ARAX, with zero publications and no further evidence. Other ARAs produced no further results. The top result from ARAX was cyclosporin A, which is known to increase risk for rhabdo in interaction with other drugs.

**Comment by gglusman** [comment]
(In case it's needed - I created this one, not sure I have more info to provide beyond what's written though.)

**Comment by cbizon** [comment]
I wonder if there's a general strategy in running treats for a bunch of things that can be adverse events and making sure we don't provide results that make things worse...

**Comment by sierra-moxon** [comment]
From TAQA:
Eric thinks we have fixed this in the last week! :)

**Comment by sstemann** [comment]
re-tested and its working much better now:
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/53020ecb-7478-4fdf-8dd4-0c2b6261a1e3)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/c5d48ba5-b398-48d1-acc5-a76daf8a3c3b)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/ba07d1f6-262e-4105-96c3-faa5a585e230)
