### ISSUE TITLE
Name Display - can we use the name that the node links to?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#200]
MVP 1 > X Factor Deficiency: https://ui.ci.transltr.io/results?l=Factor%20X%20Deficiency&t=0&q=4be1a709-da5b-45c9-943a-68f6a911ce38

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/05c9f03a-fa12-4d2d-9d8c-fd780a07faa3)

(2r,4r)-1-[(2s)-5-(diaminomethylideneamino)-2-[(3-methyl-1,2,3,4-tetrahydroquinolin-8-yl)sulfonylamino]-1-oxopentyl]-4-methyl-2-piperidinecarboxylic Acid

using the link in the UI I end up here:  https://pubchem.ncbi.nlm.nih.gov/compound/92722

Would be much nicer to display the Pubchem name and consistent when linking out to node information

while that was a crazy name example, in that same data set - you can see the UI display "all-trans-retinol" and it links out to retinol
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/87899bb4-bd5c-496d-b810-7740298d5b7a)

**Comment by andrewsu** [comment]
> Sierra: its not clear why the attribute server would have a different name for a PUBCHEM identifier than NN.

This is the call to the attribute server for information on `PUBCHEM.COMPOUND:92722`: https://biothings.ncats.io/annotator/PUBCHEM.COMPOUND:92722

![image](https://github.com/NCATSTranslator/Feedback/assets/2635409/0a8397cd-774e-4f81-a952-2bdbf9bd9c72)

It looks like the UI is grabbing the name from the `chebi.name` field.  I'm guessing the attribute server could also be convinced to return the human-readable pubchem name as well ("Argatroban"), though it's not currently being returned.  But just following up to note that it's not the case where NN and attribute server are disagreeing...

... and regardless of all that I agree with the conclusion on the call that **the ARS should call NN to get the name, and so the UI should use the name as given**.  (bolded so the main point doesn't get lost; @cbizon please correct me if I misstated what I think you said.)

**Comment by gprice1129** [comment]
Reverted the change I had made to get the names from the attribute server. Verified on CI, closing.
