### ISSUE TITLE
Search what drugs may treat Alternating Hemiplegia of Childhood and get as top result what drug may treat acute hepatitis C

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#201]
Both have AHC acronyms, is it a NN issue?

see issue #198 for more details ([PK](https://ui.ci.transltr.io/results?l=Alternating%20Hemiplegia%20Of%20Childhood&t=0&q=160e3c60-7479-4bdb-939f-97dea5dc08b5))
<img width="573" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/79b64d25-397e-485f-9e03-b3ac5e664637">

**Comment by sierra-moxon** [comment]
from TAQA: 
AHC is an acronym for two diseases, text mining identifies this incorrectly.

**Comment by cbizon** [comment]
@EvanDietzMorris it looks maybe like there are TM edges coming through robokop that are missing a Primary KS.  Can you investigate?

**Comment by EvanDietzMorris** [comment]
Our parsing of textminingkp should have infores:textminingkp as the primary knowledge source on every edge. I can't find any examples otherwise.

**Comment by gglusman** [comment]
The mixing of the two meanings of AHC continues to happen, and now it's also pulling in X-linked Adrenal Hypoplasia Congenita (XL-AHC).
![Screenshot 2023-07-03 at 08 56 49](https://github.com/NCATSTranslator/Feedback/assets/3977332/1ecc9b32-d607-415a-a5cc-b71d94fedb91)

Looking for XL-AHC shows the mixup already in the drop-down selector:
![Screenshot 2023-07-03 at 08 58 32](https://github.com/NCATSTranslator/Feedback/assets/3977332/4ca2eee4-298d-4f1a-bf1e-3219221f1b33)
"**Alternating Hemiplegia Of Childhood** _(matched on Adrenal Hypoplasia Congenita)_"

**Comment by sandrine-m** [comment]
Thank you @gglusman for the retest! Could you please confirm the UI environment you are using and append your PK (for testing purposes)? 
Appending [here](https://ui.test.transltr.io/results?l=Alternating%20Hemiplegia%20Of%20Childhood&t=0&q=c067d938-2f99-4b54-9b02-af659636cb27) the UI test PK. 
Confirmed that the issue is still present (on test, see link above).

**Comment by gglusman** [comment]
@sandrine-m I'm finding this in both the following, under the (rather generic) result 'Agonists':
https://ui.ci.transltr.io/results?l=Alternating%20Hemiplegia%20Of%20Childhood&i=MONDO:0016241&t=0&q=863bdb5b-141e-4ef0-a0ae-784472272f00
https://ui.test.transltr.io/results?l=Alternating%20Hemiplegia%20Of%20Childhood&t=0&q=cff4518e-3514-46bf-9834-e41853abc1e1

**Comment by sandrine-m** [comment]
Thank you @gglusman ! This reminded me to triage this ticket also in the result too generic. 
@gprice1129 @bill-baumgartner Please do not hesitate to let us know when it is a good time for retesting. Thank you!

**Comment by gaurav** [comment]
It's true that both `Alternating Hemiplegia Of Childhood (matched on Ahc)` and `X-linked Adrenal Hypoplasia Congenita (matched on Ahx)` are returned by the autocomplete when searching for `AHC-XL`, but I think this what it is supposed to happen -- both these concepts have synonyms containing `AHC`, and so the autocomplete ought to provide both options to the user to disambiguate. Is that correct and, if so, may I remove the `autocomplete` tag from this issue?

One minor thing I noticed @dnsmith124 is that the "matched on" text doesn't find "AHC-XL", but "Ahc" and "Ahx" -- is UI currently using the first synonym for the clique as the default matched on text? It might be more accurate to look for the synonym that is most similar to the searched text (I think both concepts have "AHC" in the synonyms, so they should be in that list somewhere). If that's something you'd like NameRes to do, please let me know!

**Comment by sandrine-m** [comment]
@gaurav I remember really well this issue/query. I searched _explicitely_ for `Alternating Hemiplegia Of Childhood` ( **not** matched on AHC) but got results (papers mainly) on other diseases that have the same accronym. My hypothesis was that TMKP is using the acronym AHC to collect papers but the fact that a multi-mapping exists between the acronym and other diseases makes it inacurate. This issue is not IMO an autocomplete issue.

**Comment by sandrine-m** [comment]
I suggest we do a retest when new infores is pushed.

**Comment by sandrine-m** [comment]
Reviving this ticket with a RETEST on [UI CI ](https://ui.ci.transltr.io/main/results?l=Alternating%20Hemiplegia%20Of%20Childhood&i=MONDO:0016241&t=0&q=3869c310-7d76-4370-afb0-c7013f62c79f)today.
I followed @sierra-moxon's great idea to use the video snipping tool to illustrate the issue:
[AHC-acronyms.zip](https://github.com/NCATSTranslator/Feedback/files/12500835/AHC-acronyms.zip)

From the results it looks like the acronym mixing happens only for unsecret (same query on [ARAX CI UI](https://arax.ci.transltr.io/?r=3869c310-7d76-4370-afb0-c7013f62c79f)) and I looked at the aux graph just to see if there was a link between the 2 diseases but that is not clear:
<img width="866" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/34670e39-2778-4fec-b4a0-b0c053aba29f">

**Comment by sierra-moxon** [comment]
we no longer return any results on PROD - does this solve the issue?

https://ui.transltr.io/main/results?l=Alternating%20Hemiplegia%20Of%20Childhood&i=MONDO:0016241&t=0&r=0&q=2a8d0828-9a20-4387-a348-1835b081010f

**Comment by dnsmith124** [comment]
@sierra-moxon it may be worth retesting this sometime next week, as no MVP1 queries are currently returning no results due to what I believe is a TRAPI validation issue

**Comment by bill-baumgartner** [comment]
FWIW - The TMKP acronym issue reported here has been fixed in a past release. I have manually checked the errors pointed out above by @sandrine-m and @gglusman. I think this issue can be closed.

**Comment by sstemann** [comment]
in Test and Prod, i no longer see references to Acute Hepatitis C in the UI.  I do not get ribavirin in the [Prod ](https://ui.transltr.io/main/results?l=Alternating%20Hemiplegia%20Of%20Childhood&i=MONDO:0016241&t=0&r=0&q=031be57c-2a85-4439-ab67-8abb98dee2b8) results.  I am able to verify ribaviri is in the [Test ](https://ui.test.transltr.io/main/results?l=Alternating%20Hemiplegia%20Of%20Childhood&i=MONDO:0016241&t=0&r=0&q=378e6c0f-d8fe-4b8c-8d93-83de768a88c7 )results and does not indicate its a treatment for Acute Hepatitis C.
