### ISSUE TITLE
Disable in-window scrolling of graph view? 

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#202]
I love the new graph viewer!!  

I have noticed that when I am trying to scroll through the page of results, my scroll "gets stuck" on the first graph viewer window and minimizes the graph in that window but stops me from scrolling further.

**Comment by gglusman** [comment]
ARAX interface does the same. ;)
I agree, it is disconcerting every time it happens.

**Comment by sierra-moxon** [comment]
Fixed in CI! :) thanks @dnsmith124
