### ISSUE TITLE
Autocomplete for Text Filter

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#204]
Definitely a feature request, but I find myself hoping for an autocomplete over the result set chemicals in the "Filter" menu text box. 

<img width="1059" alt="Screen Shot 2023-06-01 at 4 28 45 PM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/262286e5-7660-43d5-9365-6ff650bcbf27">

**Comment by gglusman** [comment]
Autocomplete, or dynamically filter the results as one types?

**Comment by sierra-moxon** [comment]
my use case was simpler, to look up results with the subject 'antioxidants'.  
I can imagine grouping by chemical role and providing a drop-down to select results by role as an alternative to autocomplete being helpful as well!

**Comment by dnsmith124** [comment]
This will not be possible with our current implementation of facets, but could be possible as part of our planned expansion to a server-side faceting engine. 

That expansion is not currently part of our plans for the September deadline. @sierra-moxon should we remove the milestone in that case? Or leave it as is?

**Comment by sstemann** [comment]
@dnsmith124 @gprice1129 do you think this could be part of an upcoming release?

**Comment by gprice1129** [comment]
@sstemann we are not considering it for the (upcoming) Lobster release. We will discuss internally if we want to consider it for the Octopus release.

**Comment by sierra-moxon** [comment]
@gprice1129 - should we close this issue?

**Comment by gprice1129** [comment]
@sierra-moxon I do not think its something we will be implementing soon.
