### ISSUE TITLE
publications appear duplicated in evidence popup

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#205]
<img width="1180" alt="Screen Shot 2023-06-01 at 4 52 46 PM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/70c3ddc0-3ba7-4ff5-940d-79f700b2c382">

https://ui.ci.transltr.io/results?l=Fuchs%27%20Endothelial%20Dystrophy&t=0&q=b6ffbedb-a02c-4e57-ad67-dd9b78fd0d00

**Comment by gprice1129** [comment]
This issue is due to getting a PMID and PMC for the same publication. We will look into how we can dedup in this case.

**Comment by sierra-moxon** [comment]
restest this morning; still showing seemingly duplicate publications.  @gaurav - is this something NN can help with?

**Comment by sstemann** [comment]
@gprice1129 I checked with Christine and Tyler, during that check it looks like Robokop is sending both pub IDs

@sierra-moxon we don't think this is priority for the UI to code around for Sept.  

<img width="355" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/2fb89d0b-0a1a-4b92-898b-437298ea45f7">

<img width="931" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/7da0f326-9862-4ef6-a6bd-e5dd8dfbabf9">

**Comment by gaurav** [comment]
> restest this morning; still showing seemingly duplicate publications. @gaurav - is this something NN can help with?

We don’t currently have PMIDs or PMCs in NodeNorm, but we could try to pull that in if that would be helpful! /cc @cbizon

**Comment by sierra-moxon** [comment]
@gaurav - there is also this service: https://www.ncbi.nlm.nih.gov/pmc/tools/id-converter-api/ 
I think this is one of those decisions we need input from @cbizon @cartmanbeck on.  If we need a vote to fix for September, I can give one :) -- but there are a lot of competing tasks!

**Comment by cartmanbeck** [comment]
After talking to Christine and Sara about it, this isn't a super high priority for us for September, so I'd say it can go in the back-burner pile.

**Comment by sierra-moxon** [comment]
closing for now as not prioritized; we can revisit if we need this if it comes up again.
