### ISSUE TITLE
UI search for Parkinson disease is confusing

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#208]
Using ui.translator.io, I have been searching for Parkinson disease. The first search I get (see screenshot for ref) is "Parkinson disease (matched on lewy Body Parkinson disease)" which is I think much broader in term of disease that just Parkinson disease. It is not clear to me what I should use to have a union of Parkinson Disease 1,2,...
It might be nice to give the user a visualization of the disease ontology hierarchy as a helper without having to search on google for that.

<img width="422" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/90f3d1e5-5cd9-4637-9a4b-f098e68c7345">

**Comment by gglusman** [comment]
Would all these potentially lead to different results? Or would several (all?) of these be funneled to the same query by the node normalizer?
If two or more options essentially lead to the same downstream process and results, it might make sense to combine them in the dropdown.

**Comment by sandrine-m** [comment]
I have not tried but from what I saw on searches with diabetes milletus vs. diabetes milletus I, those queries lead to different results for sure. Intuitively, diabetes milletus has more results than diabetes milletus I which I always understood has : when you search diabetes milletus it gives you the union of all diabetes milletus types. Is this reasoning correct to assume?
Parkinson disease used to be in the drop down (I got it from a past query of ~2months ago) but it is not there anymore...

**Comment by sandrine-m** [comment]
after discussion with @webyrd , ARAs should use ontology hierarchy in their reasoning (requirement) and they should lead to the same output. Also, we've checked the test environment and the issue was fixed there, so I'll close the issue.
