### ISSUE TITLE
UI query lost in Translation

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#209]
I have been launching a bunch of queries using the UI for testing purposes and I noticed that ~1/6 queries the query get stuck in the initial phase like that:
<img width="768" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/c593aa53-4703-4d17-9ee4-17fe6251d5cc">
if I close the page and retry I might get luckier. It seemed to me that the waiting time in this initial phase is somewhat dependent on "how known is the disease" (it happens more frequently for rare diseases). What is frustrating is that I cannot leave the page to get a pk attributed. Could we attribute a PK (and pake it visible to the user) during that phase if the wait has been > to ...sec? If the pk never shows up after ... sec there is a change indicating something might have been wrong?
So that a user can record the pk and leave the page or close the window and rerun?

**Comment by Genomewide** [comment]
The PK is shown as soon as any results come back. So, usually, it is not a long time for that first set from any ARA, but you are saying that for some diseases it is and that if you could get the PK before that, it would help you?

Also, you are fine to leave the page. It will continue to search.

**Comment by dnsmith124** [comment]
@sandrine-m I'll take a look today and figure out if displaying the pk before results are returned is a possibility, but in the meantime you can access it by inspecting the page to open up your browser tools, then checking the console tab. 

There will be a variety of messages there, but look for one that begins with `ARA status:`. There should be a data object there that you can click to expand, and an attribute called `qid` that contains the pk. You can then copy/paste it into arax.

**Comment by Genomewide** [comment]
Even if the link in the url bar changed, that would be helpful for out testers, but if that is a bid distraction from other things then we can leave it in the console and tell the focused list of TAQA testers where that it.

**Comment by dnsmith124** [comment]
@sandrine-m @Genomewide I've implemented a change locally that makes the URL in the address bar update as soon as the query is submitted, I'll mark this complete once it's been deployed.

**Comment by sandrine-m** [comment]
Thank you so much @dnsmith124 !!!

**Comment by dnsmith124** [comment]
Confirmed this is resolved on the dev site, closing!
