### ISSUE TITLE
Ordering of Query Selection

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#215]
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/6fa04f15-6119-4545-8705-75f52661556b)

1. change results to always be Canavan Disease, severe - so that it orders
2. determine and result why there are two Sever Canavan Disease
3. one is: https://monarchinitiative.org/disease/MONDO:0017830
4. the other is:  https://uts.nlm.nih.gov/uts/umls/concept/C5575558
- node norm says the UMLS identifier is on it's own
{
  "UMLS:C5575558": {
    "id": {
      "identifier": "UMLS:C5575558",
      "label": "Severe Canavan disease"
    },
    "equivalent_identifiers": [
      {
        "identifier": "UMLS:C5575558",
        "label": "Severe Canavan disease"
      }
    ],
    "type": [
      "biolink:DiseaseOrPhenotypicFeature",
      "biolink:BiologicalEntity",
      "biolink:NamedThing",
      "biolink:Entity",
      "biolink:ThingWithTaxon",
      "biolink:Disease"
    ]
  }
}

Steps:
1. https://ui.test.transltr.io/
2. type "canavan"

**Comment by dnsmith124** [comment]
I believe this has been resolved after the change to the autocomplete to only return MONDOs for this query type. TAQA please review. 

Here's a screenshot of the new terms returned on CI:
![Screen Shot 2023-06-09 at 1 17 18 PM](https://github.com/NCATSTranslator/Feedback/assets/54226761/dc64e000-d83a-4e25-b256-2f91d281bca3)

**Comment by sstemann** [comment]
this looks better, only using MONDO.  thanks!
