### ISSUE TITLE
Disclaimer says "feedback form linked here" but doesn't say where "here" is

### ISSUE THREAD

**Issue by nlharris** [NCATSTranslator/Feedback#217]
Minor issue: when I go to https://ui.test.transltr.io/, I have to accept a disclaimer, which ends with the text:
> we ask that you provide feedback through the feedback form linked here.

but "here" is not hyperlinked. It's probably problematic to put a hyperlink in the disclaimer text (you don't want people to leave the disclaimer before they've accepted it), so instead I'd replace "here" with "using the 'Send Feedback' link at the top of the page".

**Comment by dnsmith124** [comment]
Great catch here! I've updated the verbiage to point the user to the send feedback link in the main navigation, which resolves this issue. 

Confirmed live on dev, closing.
