### ISSUE TITLE
Does not work well on mobile screens

### ISSUE THREAD

**Issue by vemonet** [NCATSTranslator/Feedback#218]
The Translator UI does not work well on small screens, such as mobile screens: https://ui.test.transltr.io

A usable mobile interface will be important when we will want to grow the user base.

Nowadays people uses a lot their phone, especially if you are just sending them the link through a chat or email, they will might click on it with their phone first

It would be nice if they could start to discover the Translator tool on their mobile phone, before switching to their laptop when they want to get serious

**Comment by dnsmith124** [comment]
This is a known issue with the UI, from the very beginning given the nature of translator we decided to target desktop screen widths as this was the only way to properly convey the information within the time and scope allotted to us at the time. 

I don't think any sort of mobile version of the UI will be possible for September, but is definitely part of our long term plans. 

Ultimately we do need to resolve the issue of the UI simply appearing broken on smaller screen widths, and we'll be discussing ways to resolve that in the meantime (meaning, before we implement a full-scale mobile version of the UI).

**Comment by sierra-moxon** [comment]
@sstemann - based on David's feedback; I'm going to move this to the "Fall" milestone for now.  Ok with NCATs?

**Comment by dnsmith124** [comment]
As a stopgap I've implemented an overlay that will appear on devices with screen widths below 1024px, as that's the width where the functionality starts to break down. It essentially explains that the UI is intended to be used in a tablet or desktop environment, and instructs the user to check out the site on a larger device (or rotate their tablet to landscape mode).

Getting the UI to be functional on mobile by September is nigh on impossible, considering much of the functionality would require a complete redesign to work on a screen size so small. Possible for year 3 though, should we decide that it's a priority.

**Comment by sierra-moxon** [comment]
@Genomewide - what should we do with this ticket?

**Comment by Genomewide** [comment]
There is very little desire to make it work on mobile from NCATS. We have been told not to focus on that now.  So, we should close this.  We will not need this as reminder when we get to the point of moving to mobile (if we do).
