### ISSUE TITLE
Query hung on the "Calculating" screen and then returned an error message.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#219]
## Steps to reproduce:
Selected "What drugs may treat" query type.  Typed in "acute COVID" and selected the "Acute COVID-19" autofill.

**Comment by sstemann** [comment]
posting the corresponding views of the results in ARARX:  

Hashimoto thyroiditis with hyperthyroidism without thyrotoxic crisis or storm (UMLS:C4064966) https://arax.ci.transltr.io/?r=05dfaaa8-0f92-433f-ad17-e0971b5263ae

Acute COVID-19 (UMLS:C5439524) https://arax.ci.transltr.io/?r=be0a5e68-cc0a-459c-b0a4-c3c1fa7030f8

I'm not sure if this is a UMLS node norm issue

**Comment by sstemann** [comment]
also related to #253

**Comment by gprice1129** [comment]
Just an update. This is on my radar but I haven't had a chance to look into it yet.

**Comment by sstemann** [comment]
related to #528, the UMLS diseases in this ticket are no longer selectable via the UI (Which is restricted to MONDO). 

I was able to run Hashimoto Thyroidits but it ran fine https://ui.transltr.io/main/results?l=Hashimoto%20Thyroiditis&i=MONDO:0007699&t=0&q=4e578fb9-bab5-46bb-832b-ca373af7fd4d

so for now i'll close this one and we should use #528 to track this issue
