### ISSUE TITLE
Nodes in paths display should have display node details intuatively

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#220]
Nodes are not clickable: some of them link out, but it would be nice to have a box pop up (similar as for the edges) that contained descriptions, links out, etc. That way you don't need to leave to a different site just to figure out what a certain drug is. Eg. https://ui.test.transltr.io/results?l=Neutropenia&t=0&q=47d22bc2-3f4f-4375-98e0-e43e3a044936, look at ARAX only results, and try to figure out what Fluconazole is

**Comment by sstemann** [comment]
I think this is a suggestion that the mouseover-tooltip to get the info on the node is too/more buried than clicking the predicate button

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/e6398398-02da-42e6-9c4a-6775959c0b4f)

**Comment by sandrine-m** [comment]
I think (could be wrong though) that the user meant something like that (which we often see in the genomics field tools and that I find useful - to some extent)
[Example 1 from STRING](https://version-11-5.string-db.org/cgi/network?networkId=bnTpwcGYd8qZ): 
<img width="461" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/6b267500-362e-4077-8d52-361d0c065d62">

**Comment by gprice1129** [comment]
We have discussed this and will be targeting this feature for the September relay.

**Comment by dnsmith124** [comment]
@desiyopp  @Genomewide 

I've improved the node tooltips to show the node's description (when available). Here's what it looks like: 
![Screen Shot 2023-08-10 at 11 29 09 AM](https://github.com/NCATSTranslator/Feedback/assets/54226761/60efc53f-0cb5-4050-a2c3-7bfc1452462d)

My concern with implementing a modal window for nodes is the relative lack of information we have available for them. Many (if not most) are only a name and a type, while a few have a description. Right now that's all the information we reliably have for nodes, and I'm not sure it warrants an entire modal window. 

Of course in the future we'll ideally have access to a wide variety of data on each node, which we can then display in a verbose and detailed modal, but right now I'm not sure that's in the cards. Does adding the description to the tooltips resolve this issue, at least in the meantime?

**Comment by sstemann** [comment]
@sierra-moxon @sandrine-m i think this addition is fine.  i'm not sure we know the original user intent or that the description (especially when truncated) is the issue so i dont think we should do much more here until we get more feedback on this feature.

**Comment by sandrine-m** [comment]
+1 @sstemann I am closing. :)
