### ISSUE TITLE
"Active ingredient" may treat 

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#221]
Query: what drugs may treat Psoriasis of Scalp.
The 13th result shown is Umls:c1372955 linking to http://linkedlifedata.com/resource/umls/id/C1372955 which tells me this means "active ingredient", a generic term.
This seems to come from semmeddb.

**Comment by andrewsu** [comment]
"psoriasis of the scalp" no longer appears as an option in the UI autocomplete, presumably because it is now restricted to MONDO.  I suggest closing this issue. @gglusman do you agree?
