### ISSUE TITLE
Curiously, other antihelminthic drugs (such as albendazole) did show up in the hits.  So, getting into the right pathogen neighborhood, but missed the known target (see https://www.cdc.gov/parasites/onchocerciasis/treatment.html for summary of treatment recs).

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#222]
## Steps to reproduce:
Selected "What drugs may treat" query type.  Selected "Onchocerciasis" as disease.  300 hits returned, which did not appear to include the well-established and recommended treatment for onchocerciasis, which is ivermectin.

**Comment by sstemann** [comment]
i notice that using the link now, (351pm ET on Monday) Ivermectin does return, in two forms.  

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/fd9a6ce8-064c-40c4-9c89-7f905ad9da23)

The ask here instead may be that known treatments be returned in the first results loading set - but not sure we can force the fastest returning ARAs to do this.

**Comment by sstemann** [comment]
@sierra-moxon i'm seeing ivermectin in CI, the scoring isnt in quite yet so if this ticket is about it being scored low, then i dont know yet, i did create #469 for a normalization issue but other than that not sure what else needs to be done on this one.

**Comment by sstemann** [comment]
adding @sharatisrani, this is a potential use case for testing scoring but its not a UI issue
