### ISSUE TITLE
Instead of “Select Query”, consider using “Select exploratory input” or “Select association” or “Select input”. So users no longer build a mental model based on the notion of queries.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#223]

**Comment by sstemann** [comment]
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/2a4ba010-5bb9-429f-92a8-8f08a09c8cd7)

**Comment by Genomewide** [comment]
This is under design review and can change it to something that is not even a drop-down.  I am going to adjust status here to under design.
