### ISSUE TITLE
Should the query box be grayed out till the user has selected the templated query? It can reduce confusion about what the user needs to do first.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#224]

**Comment by sstemann** [comment]
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/e689a51a-5ca8-4078-87ab-fcbe107f3e41)

**Comment by dnsmith124** [comment]
This will be resolved in our redesign/reimplementation of the query submission process!

**Comment by sierra-moxon** [comment]
Thank you @dnsmith124 - that is fantastic as usual. 😁   - do you have a sense of which month this might be released?  (June or July or August?) -- then I can set a milestone.

**Comment by dnsmith124** [comment]
Designs have yet to be completed for it, but it's high priority so I'd set it for July!

**Comment by dnsmith124** [comment]
Our reimplementation of the query submission process (which resolves this problem) is complete and live on CI. We're waiting on some work from ITRB to be able to deploy it along with some other changes to test. 

@sierra-moxon is this sufficient to close this one, or do we need to wait until it reaches the test environment?

**Comment by sstemann** [comment]
deployed to prod as of 9/6
