### ISSUE TITLE
When Improve Returns Results with N/A - it reads 50.2

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#226]
You can only see this behavior BEFORE all of the results load, so while this is the link (https://ui.test.transltr.io/results?l=SMARCE1&t=2&q=9a96226b-4705-4528-8737-737656866afe), you won't see it unless you rerun it like this:

1.  Go to Test > Select What Chemicals Down Regulate SMARCE1
2.  The first results returned are Robokop (3) and Improving (297)
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/7b8605f8-fb54-4db9-bf9a-8db3e26a3d98)
3.  Because Improving Agent is returning n/a, after the first 3 results, are the results are scored 50.2
https://arax.ncats.io/beta/?r=166a5a5f-af49-4c04-a00c-b35e1851cda5
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/0209871d-8eaa-4bd0-936b-221c451cd4da)

**Comment by sstemann** [comment]
@brettasmi are there scores from Improve Agent on MVP2?

**Comment by brettasmi** [comment]
Yes, but not always. We are hoping to have complete scoring coverage for the MVP queries within the next month or so, hopefully sooner.

**Comment by sierra-moxon** [comment]
@brettasmi - can this be closed now? :)

**Comment by sstemann** [comment]
this is still a problem, there is a fix in CI

**Comment by sierra-moxon** [comment]
from TAQA: 
this is fixed in CI.  
@suihuang-ISB will ask why 0.52 always comes back as the score @brettasmi
