### ISSUE TITLE
multiple entries for different preparations of the same drug

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#227]
Query: what drugs may treat Psoriasis of Scalp.

Results 1, 2 and 4 are all "Clobetasol propionate 0.5 mg/ml" in different preparations ("topical foam", "topical solution", "medicated shampoo"). They have publications supporting.
Result 30 is just "Clobetasol", with zero publications, coming from drugcentral.org.

**Comment by sstemann** [comment]
https://ui.test.transltr.io/results?l=Psoriasis%20Of%20Scalp&t=0&q=4dc11d93-4517-4ca2-9715-70d1c404ad58

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/b1942d89-d1f1-496c-bb5e-242746971ee4)

**Comment by dkoslicki** [comment]
And to loop around, the conflator has been passed to the SRI team (CC @cbizon ) so now it's up to the NN team to integrate and deploy. Removing Amy from this issue

**Comment by gaurav** [comment]
@cbizon's code has produced a set of conflations -- I should be able to deploy this today and then we can play around with it and see how it's doing.

**Comment by gaurav** [comment]
We still have some bugs to work out of drug conflation before we can push it up to ITRB, but NodeNorm Dev [does correctly conflate](https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=UMLS%3AC0691824&curie=UMLS%3AC0981379&curie=UMLS%3AC0358131&curie=UMLS%3AC0792229&conflate=false&drug_chemical_conflate=true&description=false) Clobetasol as well as some other chemicals [on the first page](https://ui.ci.transltr.io/main/results?l=Scalp%20Dermatosis&i=MONDO:0006605&t=0&q=c71e43a4-39b2-4ce8-afec-f117438dfc7d) of the query "What drugs may treat: [Scalp Dermatosis](http://purl.obolibrary.org/obo/MONDO_0006605)". Once we push that to CI, we can recheck this ticket and then hopefully close it.

**Comment by mbrush** [comment]
Still finding lots of examples of drugs/chemical variations that seem like they should get conflated.  Will add more here as I find them to test if the conflator is working.

1. **Dantrolene and Dantrolene Sodium as treatments for Cerebral Palsy** (https://ui.test.transltr.io/main/results?l=Cerebral%20Palsy&i=MONDO:0006497&t=0&q=52bea588-5893-48b2-8561-16309ab0a1ed)
![image](https://github.com/NCATSTranslator/Feedback/assets/5184212/65763f05-9590-4028-8022-fe646c8316cf)

**Comment by cbizon** [comment]
As per @gaurav 's note above, this conflation has not been pushed to Test, so this is expected.   You would need to run in dev at the moment for there to be any chance of it working.

**Comment by mbrush** [comment]
Yep - I did see that.  Just capturing a few more examples here to test once it gets pushed into test.

**Comment by sierra-moxon** [comment]
close as complete.
