### ISSUE TITLE
FDA Approved - Missing some approvals

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#228]
Steps:
1. Select What chemicals may down regulate and EGFR
2. https://ui.test.transltr.io/results?l=EGFR&t=2&q=166a5a5f-af49-4c04-a00c-b35e1851cda5

Lapatinib (ARAX and BTE are using PUBCHEM.COMPOUND:208908)- FDA Approved https://gsrs.ncats.nih.gov/ginas/app/beta/substances/c05e9a9d-e7b6-4411-a271-89b2a513dc18, https://go.drugbank.com/drugs/DB01259
Gefitinib (ARAX and BTE are using PUBCHEM.COMPOUND:123631) - FDA Approved https://gsrs.ncats.nih.gov/ginas/app/beta/substances/0f331611-3703-477a-a771-8a7934049700, https://go.drugbank.com/drugs/DB00317

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/551d84f5-7573-47c2-a565-5ff8827acf32)

Filtered with FDA Approved (in alpha order)
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/38c133d0-49a7-48cd-aa19-7e891e448bd9)

**Comment by gprice1129** [comment]
There was a bug on the attribute server for the Test environment going into the relay that caused this issue. This does not happen on CI.
![fda_approval](https://github.com/NCATSTranslator/Feedback/assets/27593697/743d3697-b08d-42e7-b53b-408a583ca7d7)

@newgene

**Comment by newgene** [comment]
@gprice1129 we will follow up with ITRB team for the test/prod deployment.

**Comment by gprice1129** [comment]
@sstemann please re-test and close if the issue no longer appears.

**Comment by sstemann** [comment]
looks better!  thanks!
