### ISSUE TITLE
SmallMolecule CHEMBL.COMPOUND:CHEMBL1881825 related to NamedThing causes timeouts

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#23]
I am currently working on a use case on CHEMBL.COMPOUND:CHEMBL1881825. My collaborators working on that project published several papers ([Chou DH-C et al., ACS Med Chem Lett 2011, PMID: 21927648](https://pubmed.ncbi.nlm.nih.gov/21927648/),[Chou DH-C et al., J Am Chem Soc 2015, PMID: 26042473](https://pubmed.ncbi.nlm.nih.gov/26042473/),[Vetere, Amedeo, et al., Nature reviews Drug discovery, PMID: 24525781](https://pubmed.ncbi.nlm.nih.gov/24525781/)) regarding this compound and its relationships to pathways, cellular processes, and cellular phenotypes. 

Running the query below through ARAX, I only get edges from MolePro (chemically_similar_to and correlated_with). ars-default-agent and arax-ara are running for ever without ending and ara-aragorn returns Error 504. I do not see any information related to this compound that I would expect to see coming from those publications.

Thank you for your help!

Query ID: 385f6c86-9c1f-48ee-a859-ea9aae336f46
```
{
  "edges": {
    "e00": {
      "object": "n01",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n00"
    }
  },
  "nodes": {
    "n00": {
      "categories": [
        "biolink:SmallMolecule"
      ],
      "ids": [
        "CHEMBL.COMPOUND:CHEMBL1881825"
      ]
    },
    "n01": {
      "categories": [
        "biolink:NamedThing"
      ]
    }
  }
}
```

Results:
<img width="495" alt="image" src="https://user-images.githubusercontent.com/66342541/196989371-d852f295-4bbd-4067-928c-ddd1374cc46f.png">

**Comment by marcdubybroad** [comment]
@sandrine-m Attached is the information I'm pulling for the three pubmed IDs included from a script that uses the service 
`https://biothings.ncats.io/semmeddb/query?q=pmid:21927648&size=30`

[sandrinePapersSenmedDbUmls.csv](https://github.com/NCATSTranslator/Feedback/files/10043765/sandrinePapersSenmedDbUmls.csv)

**Comment by bill-baumgartner** [comment]
Text Mining Provider currently uses CHEBI and Drugbank as its source for chemicals. [CHEMBL.COMPOUND:CHEMBL1881825](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1881825/) does not appear in Drugbank as far as I can tell, and while it does appear in CHEBI ([CHEBI:92195](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:92195)), the CHEBI record is not associated with the `BRD0476` synonym used in the papers linked above. Because of this, I would not expect to find it in our KGs at this point. It looks like the synonym is specified in the corresponding [PubChem record](https://pubchem.ncbi.nlm.nih.gov/compound/46907798), so I will note that as a potential target for improving our chemical entity recognition.

**Comment by sandrine-m** [comment]
Hi @marcdubybroad 
This is exactly the type of information I expecting to see Translator returns. Are this info available to Translator? If so, which biolink predicates/categories does it map to? 

Thanks!

**Comment by sierra-moxon** [comment]
also split into a ticket for architecture group:
- #41

**Comment by sandrine-m** [comment]
Thank you @bill-baumgartner ! MolePro has worked on a chemical synonym reconciliation and could help on the chemical name mapping when you get a chance to revisit the info.

**Comment by marcdubybroad** [comment]
Hi @sandrine-m, 
  I believe the BTE team is maintaining the `infores:biothings-semmeddb` resource from the infores catalog Google sheet, so I would ask Colleen who the contact is for the work. While I can search what triples get associated with each pubmed id paper, I don't know to what edges they are being linked.

**Comment by sandrine-m** [comment]
Thank you so much @marcdubybroad ! I'll get in touch with Colleen!

**Comment by sandrine-m** [comment]
Got back from BTE, semmeddb does not relate the papers with any chemical.

**Comment by bill-baumgartner** [comment]
Assuming I'm querying it correctly, the SRI name resolver does not seem to have the chemical name (`BRD0476`) that @sandrine-m is looking for, so it may be that for chemicals the TMKP should see if MolePro can provide a mapping from CURIEs to synonyms.

```
curl -X 'POST' \
  'https://name-lookup.test.transltr.io/lookup?string=BRD0476&offset=0&limit=10' \
  -H 'accept: application/json' \
  -d ''
```

**Comment by cbizon** [comment]
Hmm, that's correct - where does that BRD0476 term come from?

**Comment by bill-baumgartner** [comment]
So far, I've found it listed in the [PubChem record](https://pubchem.ncbi.nlm.nih.gov/compound/46907798).

**Comment by sandrine-m** [comment]
It is the public Broad name ID, MolePro knows about that compound name. @cbizon would you be interested with MolePro synonym list to incorporate into SRI or shall I just work with Bill separately?

**Comment by cbizon** [comment]
I looked into this - we do get some terms from pubchem, but we don't use the user-deposited synonyms.  In the past we have found them way too messy and error prone, so we took them out.   I'm certainly interested in the MolePro synonym list, but also it'll take a while to get that incorporated, so it makes sense in my mind to work with Bill directly.

**Comment by bill-baumgartner** [comment]
I share your concerns regarding user-submitted synonyms, Chris. @sandrine-m, do you know if there are synonym sources that we might trust more than others; for instance, would it be sufficient to import just the Broad IDs?

@sandrine-m - If MolePro can provide a file that maps from some canonical identifier to synonyms, then we can begin to incorporate these synonyms into our NLP pipelines. It would be nice to evaluate this change somehow, so perhaps we can think about how best to do that as well. Let me know how you'd like to proceed. Thanks.

**Comment by sandrine-m** [comment]
@bill-baumgartner I will double check with Vlado but I believe what we have is a curated list. It contains as well manually corrected compound structures where they were incorrectly entered. I'll keep you posted. Thank you all!

**Comment by sierra-moxon** [comment]
@vdancik @sandrine-m  - do we have a list that @bill-baumgartner  can use from MolePro?

**Comment by sierra-moxon** [comment]
from TAQA:
list is coming in the next MolePro release.

**Comment by sierra-moxon** [comment]
Hi @sandrine-m - is the next release of MolePro out? :) Can we close this or pass it on?

**Comment by sandrine-m** [comment]
Hi @sierra-moxon I do not think so, I'll let @vdancik confirm

**Comment by sstemann** [comment]
i ran this query via ARS Test and received results.  @sandrine-m can you take a look?

https://arax.ncats.io/?r=0781b532-5d31-4905-8da5-02b6bc20fbdf

```yaml
{
  "edges": {
    "e00": {
      "object": "n01",
      "predicates": [
        "biolink:related_to"
      ],
      "subject": "n00"
    }
  },
  "nodes": {
    "n00": {
      "categories": [
        "biolink:SmallMolecule"
      ],
      "ids": [
        "CHEMBL.COMPOUND:CHEMBL1881825"
      ]
    },
    "n01": {
      "categories": [
        "biolink:NamedThing"
      ]
    }
  }
}

**Comment by sierra-moxon** [comment]
closing as completed; please reopen if necessary.
