### ISSUE TITLE
Evidence points to irrelevant paper (on a different drug, not the one in the query)

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#230]
## Steps to reproduce:
Query: What drug downregulates 'ATXN3' returns:
Valproic acid.  
But EVIDENCE points to paper about Disulfiram potentiating toxicity of ATXN3.  (PMID: 31378764).     Disulfiram is linked to Valproic acid via one case report of drug-drug interaction.

**Comment by sandrine-m** [comment]
I have difficulties to reproduce, from UI (PK shared) I see this:
<img width="842" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/da1ec1df-eab4-4063-bb20-c7120de6b970">
The specific paper the user is referring to is not in that list. 
I tried to query the particular offending edge (largest scope predicate) through ARAX using the following query
[PK = aea654a8-9a6d-47d5-9b70-53941b7f4bdb](https://arax.ncats.io/?r=aea654a8-9a6d-47d5-9b70-53941b7f4bdb):
```
{
   "edges": {
      "e00": {
         "subject":   "n00",
         "object":    "n01",
         "predicates": ["biolink:related_to"]
      }
   },
   "nodes": {
      "n00": {
         "ids":        ["CHEMBL.COMPOUND:CHEMBL2105613"]
      },
      "n01": {
         "categories":  ["NCBIGene:4287"]
      }
   }
}
```
ARS shows no results. Closing this issue. Please reopen if any questions.
