### ISSUE TITLE
UI Slider for Number of Evidence Hardcapped

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Feedback#232]
For the query below, the slider for minimum number of evidence seems fixed at 0-99 while there are nine results with a value of greater than 100.  Would it be useful to have the bounds of this slider determined by the max/min number present in the current results rather than 0-99 for all queries?

https://ui.test.transltr.io/results?l=Raynaud%20Disease&t=0&q=e897ac27-e19e-44bc-a857-d1eaf176aee1

**Comment by gprice1129** [comment]
There is a planned redesign for the evidence filter that should address this issue.

**Comment by dnsmith124** [comment]
This is a duplicate of https://github.com/NCATSTranslator/Feedback/issues/270 

closing.
