### ISSUE TITLE
For the "source" link for KP-provided result edges in Translator, provide the link to the KP's definitive documentation page in the Translator readthedocs developer documentation (rather than a GitHub project area which may be kind of a dead-end for most users).

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#234]
## Steps to reproduce:
Go to this translator query result:
https://ui.test.transltr.io/results?l=Alzheimer%27s&t=0&q=fa8a1e75-dd48-45cf-920c-9614e2950377

Scroll down to "Tanakan" and click on "Treats" and click on the "Source" tab. Look at the hyperlink.  The hyperlink goes to a GitHub repo:
https://github.com/UCDenver-ccp/text-mining-provider-trapi

It might instead be better to use a link to the appropriate KP page on the readthedocs Translator documentation area. Not all KPs have pages on that documentation area yet, but presumably they will soon. 
For KG2, here is the KP-specific page page, as an example:
https://translator-developer-documentation.readthedocs.io/en/latest/architecture/kp/rtx-kg2/

**Comment by saramsey** [comment]
For the "source" link for KP-provided result edges in Translator, provide the link to the KP's definitive documentation page in the Translator readthedocs developer documentation (rather than a GitHub project area which may be kind of a dead-end for most users).

**Comment by sierra-moxon** [comment]
Further progress:
the team met on Friday to update URLs to Translator Wiki URLs wherever possible.  We also tried to give URLs to any sources that didn't already have them.  Curation was captured in these spreadsheets, https://docs.google.com/spreadsheets/d/1eLaj21m8jq26-pK2JvIeFdjcv06XnOL5ugwDEGBEDus/edit#gid=1940732560 and then transferred into Biolink-Model release 3.5.0 (released on Friday), here: https://github.com/biolink/biolink-model/blob/v3.5.0/infores_catalog.yaml.
