### ISSUE TITLE
Page scrolls behind the Result Evidence modal

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#238]
## Steps to reproduce:
Go to https://ui.test.transltr.io/results?l=Ebola%20Hemorrhagic%20Fever&t=0&q=04a50a06-5d81-47ed-b477-e007b87b3994 and click on the "View All Evidence" of the first result. This will pop up a modal. But if you scroll, the page behind the modal scrolls. This is counterintuitive.

**Comment by dnsmith124** [comment]
Implemented a solution that prevents scrolling of the main page whenever a modal window is opened. 

Confirmed live on dev, closing.
