### ISSUE TITLE
what treat's Huntington's Disease, returns Cisplatin which positively regulates a gene associated with HD (exacerbates?)

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#24]
## Steps to reproduce:
Search for Huntington's Disease answers.
Look at Cisplatin (1st result)
Second answer row shown - look at therelationship of first two boxes (cisplatin positively regulates EGFR)
- SEE in the comments

**Comment by sierra-moxon** [comment]
coming from BTE, ranked 400 out of 1000
positively regulates might be right here, but we can't tell from the UI?
are paths here better than linear results?

**Comment by colleenXu** [comment]
Actually, BTE gets Cisplatin through phenotype/disease intermediates (see the screenshot below). So it is not the ARA that is providing the "Huntington's Disease -> Genes -> Cisplatin" information...

Andrew says that ARAX may be the ARA providing this info...

![Screen Shot 2022-12-01 at 9 51 37 PM](https://user-images.githubusercontent.com/43731687/205224468-a7e5dc3f-3654-473f-9991-675edf1202c6.png)

(CC @khanspers @andrewsu)

**Comment by sierra-moxon** [comment]
From TAQA: 
- we can't immediately say this is a bad result.
- ClinVar also would return "associated with"  (don't include "loss of function", sometimes they do have evidence if there are functional studies performed, but depends on the submitter) - ClinGen might have curated results.

**Comment by sierra-moxon** [comment]
@bill-baumgartner also has work done to pull out 'loss of function' from text. 
@marcdubybroad has all the variant data - not sure if this would overwhelm Translator use cases.

**Comment by marcdubybroad** [comment]
Aim to add qualifiers to our some of our gene/disease association data (where available) indicating direction of effect for loss of function gene coding variants on diseases. Timeline is asap after June 2023 relay freeze, so June 30th.

**Comment by bill-baumgartner** [comment]
Update from TMKP - my understanding was that we are providing qualified representations of `gene contributes_to disease via loss of function` and `gene contributes_to disease via gain of function`. However, the queries I have used to test this in the past have failed this morning, so I will look into this further and report back.

**Comment by sierra-moxon** [comment]
@bill-baumgartner - I am closing this as "won't do" - please of course reopen or note if it should instead be "closed as completed" :)
