### ISSUE TITLE
The share button looks more like an upload/download button.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#244]
## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20230605170600328172.jpeg)

**Comment by dnsmith124** [comment]
Needs user testing @desiyopp

**Comment by Desipaw** [comment]
Conducted the user testing, the results were to change simple circle icon, into a button with text labeling the button as "export results": (new design)
<img width="941" alt="Screenshot 2023-08-11 at 12 05 21 PM" src="https://github.com/NCATSTranslator/Feedback/assets/92289208/edff1bfc-68a2-4087-8e00-3440fe061feb">  
<img width="983" alt="Screenshot 2023-08-11 at 12 05 29 PM" src="https://github.com/NCATSTranslator/Feedback/assets/92289208/14f43fb3-fd82-42fe-a2f2-7bc622c3b5c4">


Tested old circle Icon and testers thought the circle button was to "upload documents" not export results:
<img width="981" alt="Screenshot 2023-08-11 at 12 05 05 PM" src="https://github.com/NCATSTranslator/Feedback/assets/92289208/268c9265-6404-42bf-915f-d445eca8643a">


Link to user test results: https://app.usabilityhub.com/tests/4036dd1e61cd/results/60d6ff2631ce

**Comment by gglusman** [comment]
For what it's worth, it's the same icon as used in -for example- Safari on iOS.
A google images search for 'share button' shows variations on an arrow going out of a box (like the current icon), while 'upload button' typically shows an arrow going up from a tray.

**Comment by sierra-moxon** [comment]
@gprice1129 - anything to do here, or shall we close?

**Comment by dnsmith124** [comment]
@sierra-moxon currently the result export button has been disabled, so there's no action item here right now. Once we're ready to reenable that functionality in the future we can revisit. 

Closing.
