### ISSUE TITLE
Empty scroll bar shows up when hovering over the result graph mini-map.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#245]
## Steps to reproduce:
Click on a result and then hover over the graph mini-map. An empty scroll bar appears and shifts many of the UI components over.

**Comment by dnsmith124** [comment]
I've tested this in all major browser and on multiple machines, and I've been unable to recreate the issue. If it comes up again hopefully we can get some more information. 

Closing.
