### ISSUE TITLE
Property chain explanations are not shown

### ISSUE THREAD

**Issue by cmungall** [NCATSTranslator/Feedback#247]
I am experimenting with comparing two queries

> What gene is [upregulated/downregulated] by Valproic acid

The results are close but not identical. I assume there is some logic happening involving chains of positives and negatives? Though I am not so sure

up, Abat has 14 paths:

<img width="1021" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/50745/cdb58df9-cca4-49cb-879e-d26cbf3ae948">

down, Abat has 18 paths:

<img width="996" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/50745/63aad796-2470-4f08-b3de-ed45483a3613">

or perhaps the directionality is not used and up/down are equivalent queries? But why are the numbers different?

The exact query-answer logic in what was included *and what was excluded* should be shown

**Comment by sstemann** [comment]
closing because more recent conversations about this are in #843
