### ISSUE TITLE
Accepted treatment for dopamine beta-hydroxylase deficiency is droxidopa, also called L-DOPS or L-threo-3,4-dihydroxyphenylserine.  Dopamine beta-hydroxylase deficiency is a (very) rare disease.  The treatment, droxidopa, has a fairly large footprint in the literature, but a relatively small footprint (30 hits) in the literature for DBH deficiency.  And it looks as though the literature signal is probably getting drowned out by the larger neuroscience literature on dopamine and acetylcholine.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#249]
## Steps to reproduce:
"What drugs may treat" query with "Dopamine beta-hydroxylase deficiency" as disease.

**Comment by sierra-moxon** [comment]
from TAQA:
this rare disease does have a treatment; couldn't find the answer in Translator, went to PUBMED, found that there were 
~ 30 pubs so its not an n of one problem.  There is plenty of evidence here.  
In Translator we see a lot of neuroscience pubs returning 

We do see droxidopa in the list today; this could be a timeout issue.
Note: the score is 49 in this context however. 

filtering by "FDA Approved" does not return this treatment either.
note: FDA-approved means "approved at all" not "approved for this disease" -- can we have an "approved for this disease?"

**Comment by sierra-moxon** [comment]
@gglusman - from your work parsing DailyMed on the clinical-trials KP, do we see any additional results in your KP that we can expect to help solve this issue?

**Comment by gglusman** [comment]
Yes, this is reflected in the current version of CTKP, with six CTs supporting `CHEBI:31524 biolink:in_clinical_trials_for MONDO:0009123`. All at phase 3 except one phase 2-to-3. The MONDO's preferred name is "orthostatic hypotension 1", and "dopamine beta-hydroxylase deficiency" is an exact synonym.

It is also in the drug_approvals KP, with `CHEBI:31524 biolink:treats MONDO:0005469`. Different MONDO, with preferred name "orthostatic hypotension"... which is more of a symptom/phenotype than a disease. No explicit link between the two MONDOs, but there probably should be...
