### ISSUE TITLE
Changing question type but not bioentity causes error

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#252]
## Steps to reproduce:
https://ui.test.transltr.io/results?l=Montelukast&t=3&q=47dedbca-c9ac-4657-a7e0-800b084c9ea6
Select "what gene is upregulated by"
Enter a drug (like Montelukast)
Change to "what gene is downregulated by" 
Try to hit search and be met with the error "No term selected, please select a valid term."

## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20230605171850939389.jpeg)

**Comment by dnsmith124** [comment]
This is because selecting a new query type usually wipes out the search bar, but because the user is on a results page it instantly repopulates the search bar with the currently queried for entity.

Great find! Assigning this one to myself.

**Comment by dnsmith124** [comment]
This has been resolved by the recent change which properly clears out the search bar when a new query type is selected. If the query type is not changed by the user the query can still be submitted and will open up a new instance of the current query in a new tab. 

Marking complete.
