### ISSUE TITLE
When query finishes running, it does not automatically load the results from the last returning agent, and the "load new results" button does not appear, nor is it readily apparent that there are more new results available from the last returning agent. To access it, you have to either refresh the page or go to search history, but the fact that you have to do that isn't obvious.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#253]

**Comment by Genomewide** [comment]
The load more results option should show.  We don't autoload things because it will change the order of results.

**Comment by edeutsch** [comment]
I wonder if a small but animated non-modal popup to alert the user that there are new results would be appropriate? kinda like Slack alerts where a little window briefly scoots in to let the user know that there are new results to be had with a refresh.

**Comment by dnsmith124** [comment]
We've added a sticky toolbar which shows the user the status of the results at all times, which should resolve this issue. Here's what it looks like:

<img width="629" alt="Screen Shot 2023-08-11 at 11 49 10 AM" src="https://github.com/NCATSTranslator/Feedback/assets/54226761/b785dec3-f88c-43ee-ac91-3d05d664cc12">

Will close this ticket once it's deployed.

**Comment by sstemann** [comment]
deployed to prod 9/6
