### ISSUE TITLE
Not only do the example search tags still list diseases, if you click on one of those disease tags it changes the query type from gene regulation back to "What drug treats this disease."

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#255]
## Steps to reproduce:
Select one of the query types for what regulates a gene.  The examples displayed below the search box still refers to diseases.

**Comment by dnsmith124** [comment]
This is a feature we intend to implement, though it is going to take some work to do so.

Our current process for updating the pks for the example diseases is entirely manual, making updating 5 example diseases across each environment (dev, ci, test, prod) already a bit tedious, but if we open that up to all 4 query types it will become a rather large task to update all of them.

So the current plan now is for @gprice1129 to write a script that will automate this process. Once he's done so it will be relatively easy for me to update which examples are shown based on the selected query type.

Assigning Gus to this and updating the milestone to July 31.

**Comment by sierra-moxon** [comment]
Hi @dnsmith124 - I think we can close this ticket as you all are refactoring the example disease significantly and that work is documented by ticket #460 (at least the work being done for September)?  
of course reopen if I am mistaken :)
