### ISSUE TITLE
Static pages describing data and KPs in the system

### ISSUE THREAD

**Issue by flannick** [NCATSTranslator/Feedback#257]
We should have overview pages on the UI that users can go to to see what data is in the system, how it is ingested and integrated within KPs, and then how each ARAs work. This would be unconnected to a query; for example, our Genetics KP could have a page that described how we have downloaded 400 GWAS, harmonized them, run them through statistical methods, and produced linkages between genes and diseases.

This would:
1. Be a logical starting point to explain how certain edges are generated
2. Highlight how much data is in the system, in particular data that are not publicly available through PubMed or Google
3. In the future help define filters for the providers or ARAs they want to see more of

**Comment by sstemann** [comment]
@Genomewide @dnsmith124 at the UCWG we discussed linking out to the Developer Documentation coordinated by the SRI, which lives here:  https://ncatstranslator.github.io/translator-developer-documentation/

can you please find a spot in the Help to add this?

**Comment by Genomewide** [comment]
We can. The FAQs here seem to missing?

![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/fdabab68-75d6-42ae-8dc9-cdec3585538e)

**Comment by sstemann** [comment]
yep, its something we can loop @RichardBruskiewich or @karafecho on, when we discussed at UCWG I did note its not complete, but neither is Translator.

**Comment by dnsmith124** [comment]
@Genomewide was this information included in the recent update to the help section, or is there still more we need to add?

@sstemann I could add a link to the developer documentation in the sidebar of the help pages under "About Translator", would that complete this ticket?

**Comment by karafecho** [comment]
@flannick : The UI landing page includes links to the Translator papers, which describe the Translator system in a (mostly) user-friendly, albeit high-level, manner. I believe the [Translator wiki pages](https://github.com/NCATSTranslator/Translator-All/wiki) are intended to capture the more granular information you describe, but on an edge-by-edge basis and in a team-agnostic, user-friendly manner. The [developer documentation]( https://ncatstranslator.github.io/translator-developer-documentation/) is incomplete and probably should be cleaned up a bit (e.g., there are comments calling out specific team members to add sections), but that documentation does provide a bigger picture than the individual wiki pages. However, it is also very technical.

I guess I'm inclined to suggest that you make sure that your team has an up-to-date wiki page for any infores resources listed as a primary knowledge source (examples: https://github.com/NCATSTranslator/Translator-All/wiki/DDInter, https://github.com/NCATSTranslator/Translator-All/wiki/BindingDB, https://github.com/NCATSTranslator/Translator-All/wiki/Exposures-Provider-ICEES) and then wait for feedback from users as to whether the existing documentation is sufficient. That said, I guess we could also provide a link to the developer documentation, but I kind of think it needs to first get cleaned up a bit.

**Comment by Genomewide** [comment]
I am closing this but will reopen if @flannick contests. We just need additional papers to link to.  Many are on the front page.
