### ISSUE TITLE
The literature matched used the name "Crambescin B carboxylic acid", which is probably more user friendly than the name that the Node Normalizer chose to display, "(5r,6s,7r)-9-amino-7-decyl-1-oxa-8,10-diazaspiro[4.5]dec-8-ene-6-carboxylic acid"

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#259]
## Steps to reproduce:
https://ui.test.transltr.io/results?l=SCN2A&t=1&q=2ebcba5f-c367-4c49-936c-f98f06ac8286

**Comment by sierra-moxon** [comment]
https://github.com/NCATSTranslator/Feedback/issues/196 is another instance that was determined to be "ok" as it was the chemical name.

**Comment by jeffhhk** [comment]
I was the opener of this case with the feedback tool, and the creator of the query that led to it.

Today I was trying to beautify a drug list using names available in rtx-kg2c.  This was the heuristic for name beauty that I could quickly scrape together.

    # name is a string.  Lower score is better
    def name_score(name):
        if len(name)<=2:                # protect against degenerate names
            return 100                  # 100 is bad
        cDigits = 0
        for i in range(len(name)):
            ch=name[i]
            if ch >= '0' and ch <= '9':
                cDigits += 1
        cNondigits = len(name)-cDigits  # "CANDOXATRIL" is preferred to "Uk 79300"
        return cNondigits+8*cDigits     # "Delta-Tocopherol" is preferred to "E309"
    
    # Here, n is a structured node object.  It has a method .name with 
    # the primary name and .names() with secondary names.
    def best_name(n):
        if n is None:
            return None
        nameSm = n.name
        scoreSm = name_score(nameSm)
        for name in n.names():
            if name_score(name) < scoreSm:
                nameSm = name
                scoreSm = name_score(name)
        return nameSm

So in names, shorter is usually better, but not always.

Food for thought.

**Comment by sierra-moxon** [comment]
@jeffhhk - I reran this on CI this morning: 
https://ui.ci.transltr.io/results?l=SCN2A&i=NCBIGene:6326&t=1&q=4d96ff0c-c677-4ddf-b767-6cc148c638fb

I no longer see either of these two name forms in the results.

@gaurav - what should we make of this result? :)
