### ISSUE TITLE
Can only submit a single bug per session(?)

### ISSUE THREAD

**Issue by Genomewide** [NCATSTranslator/Feedback#26]
Once a bug is submitted, clicking the feedback link takes you to the modal that has a link to that bug.  However, this means that there is no way to submit a second bug in that session.  Going to a new tab did allow another bug to be submitted. 

Not sure what the right fix is though bc going to see the bugs is nice. Maybe the modal would offer both new and review last submitted.

**Comment by dnsmith124** [comment]
Thanks for submitting this! I resolved it by adding a "Submit More Feedback" button underneath the link to the bug that allows you to reset the form to submit again within the same session. It does then remove the link to the previously submitted bug, but if the user needs to save the original link they can open it before they click the new button and bookmark it.

The change will go live on the site after the next build, pending the situation with ITRB being resolved.
