### ISSUE TITLE
Still lots of no score results from ImProving

### ISSUE THREAD

**Issue by sharatisrani** [NCATSTranslator/Feedback#265]
<img width="1152" alt="image" src="https://github.com/NCATSTranslator/TranslatorArchitecture/assets/5649839/e37c8823-68d4-4fd0-85d2-973ce3bd6a80">

**Comment by sierra-moxon** [comment]
@brettasmi - can this ticket be closed?

**Comment by sharatisrani** [comment]
It should have been closed, but now there's a descendant issue :-) Appraiser returns all zero scores for improving.  Reassigning.

**Comment by brettasmi** [comment]
This has a fix in CI; see here. I have a deployment request in, but I'm not sure when it will actually get deployed due to the rules surrounding deployment to other environments.

**Comment by sierra-moxon** [comment]
closing as completed; please reopen if necessary.
