### ISSUE TITLE
Takes longer than expected to load a shared link

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#266]
(fishbowl) users were surprised how long it takes to load the results of a shared link/search history link

In this recording, I refreshed a set of results, it ended up being about 20 seconds to load results that were already calculated

https://drive.google.com/file/d/1oGPBe3z8TvC_wuHc5OOXx5NbN_B2-jZZ/view?usp=sharing

took about 16 seconds when I clicked the shared link https://ui.test.transltr.io/results?l=EGFR&t=1&q=f7d83d65-8fab-48d4-8f62-978207ee50dd

**Comment by dnsmith124** [comment]
Unfortunately the vast majority of the time it takes for a shared link to load is out of my hands. 

@gprice1129 can you provide some detail here with regard to how the timing breaks down for a typical query? What processes exactly make up the wait time when loading a cached query in the UI?

**Comment by gprice1129** [comment]
Update: haven't forgotten about this but haven't gotten around to it yet.

**Comment by sstemann** [comment]
@gprice1129 any update on this?

**Comment by Genomewide** [comment]
@gprice1129 aren't there 4 places that add up to total time? Or most of it?

I expect that the amount of data that is being downloaded is a significant part.  When I have downloaded completed pk as json it takes many seconds and seems like it should not.  

1. Is that something the ARS can push faster? 
2. Is there a significant transit time from the BE to the FE? 
3. After that I think it is the processing time on the back end.
4. FE processing to display.

**Comment by gprice1129** [comment]
Just as a reminder of what it means for a "shared link" to load, the overall process is:
1. UI downloads each ARA result from the ARS
2. UI backend processes and merges results once they are all received
3. UI backend calls out to annotation server to annotate the final message
4. UI frontend downloads final message from the UI backend
5. UI processes the final message and displays the results

The following is only based on our observations when using the system. I have yet to find the time to do a thorough test where I can present metrics, so take everything here with a grain of salt.
1. Backend processing: There are definitely improvements we can make here that will improve the system under heavy load. There is also some low hanging fruit that should speed things up a bit, but right now this isn't where the bulk of the time comes from.
2. Annotation server: The annotation server sometimes does take quite a while to come back, this is dependent on how many nodes there are in the result and load on the system. I believe the annotation server has a new feature where it is possible to only grab attributes we care about which we have not implemented yet. I suspect this will also improve performance. Please confirm @newgene 
3. Frontend processing: I am not sure how long it takes to process the message from the UI backend once the frontend application receives it. @dnsmith124 would probably have more insight here.
4. Download size: The TRAPI messages we are sending around can be as high as ~200 megabytes in aggregate sometimes which will definitely increase the time it takes for data to come back. This could be where the bulk of the time is spent. Addressing this issue needs to be brought up on the architecture call. Specifically we may need to think about how to encode TRAPI in a highly compressed way.

Other things to consider
1. ARS merging: We have noticed significant increases in performance after switching back to the UI merging which we found surprising. @MarkDWilliams probably has better insight for why this would be the case.
2. Scoring pipeline: The scoring pipeline was adding significant delays to getting results back. It is unclear to me whether it was the scoring services or the ARS. Others may have more insight.

**Comment by newgene** [comment]
>Annotation server: The annotation server sometimes does take quite a while to come back, this is dependent on how many nodes there are in the result and load on the system. I believe the annotation server has a new feature where it is possible to only grab attributes we care about which we have not implemented yet. I suspect this will also improve performance. Please confirm @newgene

@gprice1129 yes, I confirm you can use `fields` parameter to limit the annotation fields returned and that should increase the performance. ITRB team is also working on scaling up the deployment behind the annotator service.

One question though, I know **ARS** also calls annotator before it passes the TRAPI response to UI. Are these two annotation steps doing different things? @gprice1129 @MarkDWilliams

**Comment by dnsmith124** [comment]
Re: 3. The FE's formatting of the data sent by the backend takes anywhere from 10-300ms in my testing, generally only nearing the top end of that range with the largest result sets.

**Comment by gprice1129** [comment]
@newgene we think its wise to call the annotation server twice for each call:
1. From the ARS, which I believe needs some annotation information to correctly score
2. From the UI, which needs some annotation information for faceting

While it would be possible for the ARS to handle both, we are one of possibly many clients so it makes sense to us separate the annotation server calls.

**Comment by gprice1129** [comment]
@sstemann do we have criteria for testing this? The system does seem significantly faster on the current production.

**Comment by newgene** [comment]
@gprice1129 👍 makes sense. Optimizing the specifical fields returned from annotator can still improve the efficiency of the overall process, e.g. no need to return annotation fields already included from the ARS's annotation step.

**Comment by gprice1129** [comment]
It is unclear what the definition of done for this ticket is. Is there a specific amount of time we're looking for on average?

**Comment by gglusman** [comment]
The URL in the top post doesn't seem to work anymore.
Just tested with [a recent one](https://ui.test.transltr.io/main/results?l=CARD14%20(Human)&i=NCBIGene:79092&t=2&r=0&q=d5ae3303-360b-42c5-bde3-705e81de8d5c) and the results were displayed after 18 seconds.
I'd suggest 5-10 seconds would be desirable.

**Comment by sstemann** [comment]
@gprice1129 is improving this on deck for lobster UI?

**Comment by gprice1129** [comment]
@sstemann the UI team does not plan on working on this issue for the lobster cycle. It is our stance that this issue is not something we have the ability to address efficiently. I'm not saying our code is perfectly optimized, but the amount of time we can squeeze out of it is not going to be on the order of seconds without a huge amount of work.

I also want to stress that the time taken to load shared links is currently completely dominated by the network time it takes to transfer the ARS merged TRAPI results. It would be most beneficial to put efforts towards finding a solution to this problems first.

**Comment by gprice1129** [comment]
The UI team will be working with @MarkDWilliams to use a compressed version of the merged ARS message to speed up query time.

**Comment by gprice1129** [comment]
The UI now handles ARS merged result compression. It is in CI.

**Comment by sstemann** [comment]
In test, it seems to take less than a minute for these two:  https://ui.test.transltr.io/main/results?l=Breast%20Cancer&i=MONDO:0007254&t=0&r=0&q=d801ad16-3c05-44fb-bef9-5ed989fee85e

https://ui.test.transltr.io/main/results?l=Hutchinson-gilford%20Progeria%20Syndrome&i=MONDO:0008310&t=0&r=0&q=03921ea2-0b3d-4a94-a8c2-3afa55c82e3e

**Comment by Genomewide** [comment]
Do we close this?
