### ISSUE TITLE
Sometimes the network zoom box overlaps the network nodes

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#268]
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/bcc61f01-d272-45fc-9266-ac85170ea568)

https://ui.test.transltr.io/results?l=Sickle%20Cell%20Anemia&t=0&q=5b4a4d73-e5d7-49af-aec0-7720e1119d03
- expand the first result Erythropoietin

**Comment by sstemann** [comment]
@dnsmith124 i'd like to re-test this with the graph updates expected into test week of 7/17 (based on our status call)

**Comment by dnsmith124** [comment]
I've implemented some major changes to the graph display that should resolve this problem in all but the wildest edge cases. Right now I'm not sure if it will make it to test this week due to some changes to the BE waiting on ITRB approval before we can push.

**Comment by sierra-moxon** [comment]
@dnsmith124 - I think I saw this fixed on CI (but I can't retest atm) - did you happen to retest and can we close this one?  (sorry for all the tickets, I'm prepping for a meeting tomorrow).

**Comment by dnsmith124** [comment]
Retested on CI and can confirm that out of the 30+ results I checked, only 1 had a node that was partially covered by the network navigation box. That's _vastly_ reduced from how it was before, so I'm going to close this out. 

Closing.
