### ISSUE TITLE
"biolink:genetic_association" truncated to 'Tic Association' in the UI

### ISSUE THREAD

**Issue by Genomewide** [NCATSTranslator/Feedback#27]
Search for Huntington's disease results returns 'Tobacco smoke pollution' and the second predicate of the second path has 'Tic Association' - Is this a real predicate. I have not heard of it before, but it could be from the exposures KP that is not used very often?
<img width="1792" alt="Screen Shot 2022-10-24 at 12 38 04 PM" src="https://user-images.githubusercontent.com/55069176/197592061-2b3fb45f-9331-4cfe-a0a2-b6fd37969cf7.png">

**Comment by sierra-moxon** [comment]
@Genomewide - I have a feeling after consulting the record in ARAX, that "Tic Association" is really "genetic association" which is a predicate in Biolink.  Is it at all possible that this predicate is getting weirdly truncated in the UI?  

<img width="485" alt="Screen Shot 2022-11-30 at 4 45 19 PM" src="https://user-images.githubusercontent.com/4561292/204938669-2239a25b-f2e2-4fad-b6e0-e01fb01548e7.png">

In ARAX, I see "genetic association" as expected. 
<img width="870" alt="Screen Shot 2022-11-30 at 4 45 59 PM" src="https://user-images.githubusercontent.com/4561292/204938775-507e5196-4bbf-4374-ac06-49942fd71ffa.png">

However, beyond `Tic Association` it might be good to understand how the "increases response to" predicate is being used in creative mode.  

@cbizon - if I look at the associated metadata in Biolink for "increases response to" in biolink, this use in Robokop is not technically an error or violation of the model.  But if I read the definition of the predicate, its tricky to insert a chemical for the domain and a gene for the range.  For this triple, are we trying to say "tobacco smoke exacerbates the effects (increases the response to) of _mutations_ in GSTP1? 

<img width="658" alt="Screen Shot 2022-11-30 at 4 49 41 PM" src="https://user-images.githubusercontent.com/4561292/204939374-efd1967a-6d35-424e-af63-45f4d9945527.png">

**Comment by sierra-moxon** [comment]
I split this ticket into the UI issue and the underlying data issue.  This issue will remain for UI to investigate (the truncation of the predicate in the display)

**Comment by dnsmith124** [comment]
@sierra-moxon You're absolutely right, the UI truncates biolink predicates in order to make them more readable, and the code to replace the word 'gene' in terms like 'gene_associated_with_condition' was also improperly truncating terms like 'genetic_condition' into 'tic_condition'

I've pushed a change to fix this to the frontend repo and it will go out in the next deployment!
