### ISSUE TITLE
minimum number of evidence slider non-intuitive

### ISSUE THREAD

**Issue by remontoire-pac** [NCATSTranslator/Feedback#270]
(2) “Minimum Number of Evidence” slider only goes from 1-99 despite the range of the data being larger; use whole range.

(3) “Minimum Number of Evidence” slider only allows sliding from one end (and it changed from the left to right end during use!); needs to be slidable from both ends and stop on the values that actually occur in the data.

![image](https://github.com/NCATSTranslator/Feedback/assets/2120526/1c705dba-3f9c-4931-8031-356ac5a8b47f)

**Comment by Genomewide** [comment]
Tagging UI team - we should look at what this looks like for the max or maybe we should have a different max where it tops out at 1000.

**Comment by remontoire-pac** [comment]
I'm proposing not to use an arbitrary max at all, but rather to set the
range from the data (as well as the intermediate "stops").

**Comment by dnsmith124** [comment]
I think if we're going to increase the value we'll need to possibly redesign the interaction. Having more than 100 points on that line will quickly become untenable if we want the user to be able to finely control the value. 

If we're comfortable loosening those controls we could have the 'stops' calculated at something like 5% of the maximum value per tick along with an arbitrary max value determined by the result with the most evidence. 

One thing that gives me pause with this change though is the vast difference in amount of evidence returned among results for most queries. A lot of the time I'm seeing upwards of 1000 (sometimes 5000+, or even 8000+) publications on just a few results, with the rest having far less. With the proposed change the user hitting even the first tick mark would remove the vast majority of results, making the rest of the ticks sort of meaningless. 

Still, it's worth testing. Another approach could be to get rid of the sliding input and go with another approach, like just having the user input an integer.

**Comment by remontoire-pac** [comment]
This one is worth an interactive discussion. How could we make that happen?

**Comment by remontoire-pac** [comment]
Sorry all - I had a medical emergency that caused me to miss the 2nd half
of the meeting. Please let me know which upcoming Zoom meeting at which we
could spend 10 minutes on this topic. Best, Paul

**Comment by dnsmith124** [comment]
The fix it meeting tomorrow or the TAQA meeting Friday?

**Comment by remontoire-pac** [comment]
Could you add me to the calendar invite for Friday's TAQA meeting (or next
Friday if we are skipping this week)? Best, Paul

**Comment by dnsmith124** [comment]
@sierra-moxon see above, I don't see how I can add anyone on my calendar!

**Comment by sierra-moxon** [comment]
done; Paul you are added now - look for two invites! :)

**Comment by sierra-moxon** [comment]
from TAQA:
we're trying to solve two use cases with one slider - we might need two sliders.
1) require that two or three evidence pieces are available before I consider results.
2) only want to see the results with highest level of evidence. 

Andy: we can also filter by number of evidences.  
right end- percentile?
left end- integer?   

David: this might be hard to implement and communicate to the user.  Sticking to the slider might be the issue, we need to find a different way to express that.

**Comment by sstemann** [comment]
@Genomewide any update on this?

**Comment by Genomewide** [comment]
No. We need to add this to the feature request and evaluate it with the others for prioritization.  I would also like to hear from other users if this is an issue.  I think that we are about to a point where we will be getting that kind of feedback from outside users if it is an issue for many.  

I changed the project to reflect that.

**Comment by sierra-moxon** [comment]
@Genomewide - I am closing this as "won't do" - please reopen if it is on your priority list.
