### ISSUE TITLE
need text style guides for labels, titles, etc.

### ISSUE THREAD

**Issue by remontoire-pac** [NCATSTranslator/Feedback#271]
(4) Style guides for the text on the website: capitalization – I suggest that we only capitalize a label if you would capitalize it in the middle of an English sentence (like the word “English” in the italicized clause”; punctuation – we should be consistent throughout, especially with labels and descriptive text.

**Comment by Genomewide** [comment]
Style guide is being produced for rules sitewide. Will log this as part to consider.

**Comment by sstemann** [comment]
@dnsmith124 @desiyopp has this happened?

**Comment by sierra-moxon** [comment]
@Genomewide - closing this as "completed" - but please reopen if we need it.
