### ISSUE TITLE
long-form descriptions have redundant, ugly elements

### ISSUE THREAD

**Issue by remontoire-pac** [NCATSTranslator/Feedback#272]
(5) How are we dealing with duplication of information within the long-form description? For example, the following description for “miglitol” seems to have 2 paragraphs that are essentially redundant.

(6) In the following description for “miglitol”, there is a textualized (“ugly”) version of a pointer URL, which should be presented as a clickable “pretty” URL.

![image](https://github.com/NCATSTranslator/Feedback/assets/2120526/7ed45187-7c08-4ce1-a23a-6123fe82d8f4)

**Comment by Genomewide** [comment]
This is being fixed by the attribute server. closing
