### ISSUE TITLE
network zoom awesome, but too sensitive

### ISSUE THREAD

**Issue by remontoire-pac** [NCATSTranslator/Feedback#274]
(8) Mouse wheel for zoom in/out on network diagram is awesome, but way too sensitive.

**Comment by remontoire-pac** [comment]
also, maybe require explicitly clicking into the network box to activate, since the more common expected effect is just to scroll down on the page

**Comment by Genomewide** [comment]
David, is this adjustable? what about the idea of activating it prior to use. 

Desi, can we test what people like for this?

**Comment by dnsmith124** [comment]
There is a property we can use to adjust the sensitivity of the scrolling, shouldn't difficult to adjust at all.

Regarding the activation, that's the frontrunner in my mind in terms of adjusting the graph zoom functionality. The feedback has been pretty much universal that it needs adjustment, we'll just need to brainstorm and test with users to find the ultimate solution (select graph to zoom, hold key down to zoom, +/- buttons, some combination of these, etc.)

**Comment by edeutsch** [comment]
Holding down control as implemented here seems like a nice solution:
https://aqicn.org/map/northamerica/

**Comment by sierra-moxon** [comment]
I didn't find it to be too onerous to zoom in out nor was it over sensitive today on retest - closing.  @dnsmith124 - of course I am an "n" of 1.  Please reopen if need be?
