### ISSUE TITLE
always have unambiguous sort tie-breakers

### ISSUE THREAD

**Issue by remontoire-pac** [NCATSTranslator/Feedback#275]
(9) In several of the network diagrams (circle is most obvious) there is not a clear tie-breaker governing the sort order of items with equivalent connectivity  avoid being arbitrary; use alphabetical within entity type if nothing else is available for tiebreaking.

![image](https://github.com/NCATSTranslator/Feedback/assets/2120526/772f0edf-f197-4b39-a91c-e79c7d5ed22b)

**Comment by remontoire-pac** [comment]
another more specific example
![image](https://github.com/NCATSTranslator/Feedback/assets/2120526/c6efbe16-4055-4ed4-ab4b-c193ef2065e7)
in this one "INS" should be at the bottom of column 2 because its connectivity is different, but the 5 items above it are all equivalently connected and therefore could/should be alphabetized

**Comment by Genomewide** [comment]
I don't think this is an easy option.  David? If huge effort then close this for now.

**Comment by dnsmith124** [comment]
This is going to come down to the layout algorithm used, and short of writing our own I'm not sure how we'd be able to implement this. Don't close it yet, I'd like to do a bit of research first.
