### ISSUE TITLE
Where results are predicted/inferred, "Source" in results can be just just ARA site links

### ISSUE THREAD

**Issue by sharatisrani** [NCATSTranslator/Feedback#279]
Today this is an issue at least with BTE, Unsecret, ImProving

Some day soon we need short simple explanations.

**Comment by gaurav** [comment]
An example: when searching for PTSD (https://ui.test.transltr.io/results?l=Post-traumatic%20Stress%20Disorder&i=MONDO:0005146&t=0&q=dd7fe89e-81b6-4a0f-864d-977d59ae3041), one of the results is "ethylene", but the only source provided is ChEMBL (https://www.ebi.ac.uk/chembl/).

**Comment by sierra-moxon** [comment]
removing myself as assignee and moving to Fall milestone.  I think changing infores at this point is too late, and it would be a KP/ARA task.

**Comment by sierra-moxon** [comment]
this was the focus of the infores wiki effort - I believe a lot of great short explanations were added (more are always welcome).  closing ticket as completed.
