### ISSUE TITLE
"multiplication" directions should be different result sets

### ISSUE THREAD

**Issue by remontoire-pac** [NCATSTranslator/Feedback#283]
In this case we have a mixture of "increases" and "decreases" evidence. These should be separate paths.
![image](https://github.com/NCATSTranslator/Feedback/assets/2120526/e1800829-fad8-4d7a-9644-24c098c8eea0)

**Comment by remontoire-pac** [comment]
![image](https://github.com/NCATSTranslator/Feedback/assets/2120526/a194a088-f9d3-487a-aa94-7d9fc113f3ac)

Moreover, this example seems to be only the wrong direction (decreasing insulin is the wrong direction for treating any diabetes).

**Comment by remontoire-pac** [comment]
![image](https://github.com/NCATSTranslator/Feedback/assets/2120526/caa7ea5f-1e29-4335-bb5c-88e23c403a04)

**Comment by sandrine-m** [comment]
Queried the offending edges through ARAX: 
PK = [295eb375-b427-4121-a0d3-b6e20f97e48d](https://arax.ncats.io/?r=295eb375-b427-4121-a0d3-b6e20f97e48d)
we do find both "increase/decrease" statements. I think we should split this ticket in 2. One for the first comment (about grouping paths under results) and another ticket for the second comment "opposite to what I asked".  I'll go ahead and split the ticket.
