### ISSUE TITLE
"physical interacts" is not a correct interpretation of this evidence

### ISSUE THREAD

**Issue by remontoire-pac** [NCATSTranslator/Feedback#284]
![image](https://github.com/NCATSTranslator/Feedback/assets/2120526/193ff960-019a-487d-bbbb-f34bd0c7160e)
I don't think "physically interacts" correctly describes what is happening here.

**Comment by sierra-moxon** [comment]
@remontoire-pac - do you happen to remember the query you were testing to get this result?  
e.g. "what chemical upregulates x?" maybe?

**Comment by remontoire-pac** [comment]
for any of the tickets I just made, I am happy to clarify 1:1 1:several,
small group, big group, whichever ... my tickets are 269-284 (except 281)

All of my tickets referenced in that Slack were from

What drugs may treat …  “MODY”


[image: image.png]

**Comment by sandrine-m** [comment]
Queried the offending edge through ARAX with the following JSON
PK = [e689d336-5447-4aad-bd55-aa2d0ce6679c](https://arax.ncats.io/?r=e689d336-5447-4aad-bd55-aa2d0ce6679c):
{
   "edges": {
      "e00": {
         "subject":   "n00",
         "object":    "n01",
         "predicates": ["biolink:physically_interacts_with"]
      }
   },
   "nodes": {
      "n00": {
         "ids":        ["CHEMBL.COMPOUND:CHEMBL1561"]
      },
      "n01": {
         "ids":  ["CHEMBL.COMPOUND:CHEMBL1201538"]
      }
   }
}

Here are the agents returning the offending edge:
- ARAGORN
- RTX-KG2 (primary agent)
- Drugbank (primary source)

Interestingly, I cannot retrieve the paper cited here through ARAX.

**Comment by dkoslicki** [comment]
ARAX gets the "interacts" edge from Drugbank directly, so I don't know where that literature support is coming from

**Comment by sandrine-m** [comment]
@dnsmith124 could this be a UI issue?

**Comment by dnsmith124** [comment]
@sandrine-m what environment does that PK correspond to? I can't seem to recreate on test

**Comment by remontoire-pac** [comment]
@sandrine-m 

 - looking at my history, I see the following MODY search from during the Relay:
https://ui.test.transltr.io/results?l=Maturity-onset%20Diabetes%20Of%20The%20Young&i=&t=0&q=64df5558-131d-4514-876d-4d4ec75fde40

But, I don't see the exact result I was complaining about -- which was conflating "drug interaction" with "physical interaction"

**Comment by sandrine-m** [comment]
Thank you @remontoire-pac ! 
by using the entity search field for Miglitol I found the following response (in your history PK):
![image](https://github.com/NCATSTranslator/Feedback/assets/66342541/14f6bae6-c0a2-43b2-9d3a-25bb20554c6a)
![image](https://github.com/NCATSTranslator/Feedback/assets/66342541/2b6aff63-68ea-44b8-b492-2a81ac741144)

And found out the agents: ARAX, BTE, and ROBOKOP as provenance for the graph on that response. When I looked at it further on ARAX UI, I found out that the only physically_interacts_with edges were coming from RTX-KG2 that got it from SEMMEDDB:

![image](https://github.com/NCATSTranslator/Feedback/assets/66342541/d79341f8-a802-47cf-b13d-430270c8051a)
![image](https://github.com/NCATSTranslator/Feedback/assets/66342541/c9ee1fba-c7e7-46e0-b7f4-5a47bfd0d441)

**Comment by sandrine-m** [comment]
@dnsmith124 I figured looking at ARAX UI that my previous retests attempts were not working due to ARAX crashing and giving no answers. [Retested today](https://ui.test.transltr.io/results?l=Maturity-onset%20Diabetes%20Of%20The%20Young&i=MONDO:0018911&t=0&q=3294dd01-946c-4f98-b267-384e1c6e35c6) on UI test still leads to ARAX-KG2 crashing. I attempted a [retest on ARAX CI UI] (https://arax.ci.transltr.io/?r=ecf66596-649a-480f-9753-75fc6aad703e) with the corresponding json:
```
{
  "edges": {
    "e00": {
      "attribute_constraints": [],
      "object": "n01",
      "predicates": [
        "biolink:treated_by"
      ],
      "qualifier_constraints": [],
      "subject": "n00"
    }
  },
  "nodes": {
    "n00": {
      "constraints": [],
      "ids": [
        "MONDO:0018911"
      ],
      "is_set": false
    },
    "n01": {
      "categories": [
        "biolink:ChemicalEntity"
      ],
      "constraints": [],
      "is_set": false
    }
  }
}
```
ARAX gives 8.5MB of results :
![image](https://github.com/NCATSTranslator/Feedback/assets/66342541/3d4d2b51-b803-46b2-ab40-1773ba43fa84)
but the `biolink:physically_interacts_with` graph does not pop up in their support graphs.

So I think we can "close the issue" of physically interacts with.
