### ISSUE TITLE
Vehicle emissions treats brain death

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#285]
## Steps to reproduce:
Looks to be coming from unsecret agent; likely a SemMedDB problem

**Comment by sundareswarpullela** [comment]
Also shows **tobacco smoke pollution treats brain death** https://ui.test.transltr.io/results?l=Brain%20Death&t=0&q=ee459005-13f7-4f15-a45b-e46b9e5adbf3

**Comment by dkoslicki** [comment]
Belongs in #288 too

**Comment by colleenXu** [comment]
Note that:
* tobacco smoke pollution
* vehicle emissions

Shouldn't be valid drugs returned by "what drug treats disease X". However, this could be valid input for "what gene is regulated by chemical X"....

**Comment by gaurav** [comment]
In the [next version of NameRes (v1.3.1)](http://name-resolution-sri-dev.apps.renci.org/docs):
* "tobacco smoke pollution" will return IDs UMLS:C0040334 ("Tobacco Smoke Pollution", biolink:Phenomenon) and MESH:D014028 ("Tobacco Smoke Pollution", biolink:ComplexMolecularMixture), so not biolink:Drug.
* "vehicle emissions" will return IDs UMLS:C0004380 ("Vehicle Emissions", biolink:SmallMolecule), MESH:D001335 ("Vehicle Emissions", biolink:ComplexMolecularMixture) and UMLS:C4715636" ("Enforcement of vehicle emissions standards", biolink:PhenotypicFinding -- yes, this is wrong, and filed as https://github.com/TranslatorSRI/NodeNormalization/issues/206), so not biolink:Drug.

Does that meet all the criteria for this issue? If so, we might want to mark this as potentially fixed until NameRes v1.3.1 or later is released.

**Comment by sundareswarpullela** [comment]
Great! Can be closed.
