### ISSUE TITLE
META LIST: entities that are often wrong or not useful (but isn't embarassing or offensive)

### ISSUE THREAD

**Issue by colleenXu** [NCATSTranslator/Feedback#288]
known note: can we take resources that aren't giving curated / best-quality treatments for diseases....and give them a different predicate / qualifier-set and implement this IMMEDIATELY???

**Comment by colleenXu** [comment]
Do we want to remove these from selection in UI / showing up in results?

Often wrong:
* water (often a stand-in for hydrotherapy)

Not useful:
* water specimen
* hydrogen tritium oxide
* deuterium oxide
* water-d1
* hot water
* ice
* oil/water
* tap water
* tar-water


<img width="1585" alt="Screen Shot 2023-06-06 at 11 17 28 AM" src="https://github.com/NCATSTranslator/Feedback/assets/43731687/20d1ad1e-f8a8-4aef-8f73-b7c075adb8b2">

**Comment by jeffhhk** [comment]
Please use this spreadsheet: https://docs.google.com/spreadsheets/d/1A6HoztR5Qi0iNbKjH9zj1O2FOKLkHMgUcmODW-jE0OY/edit#gid=0

**Comment by saramsey** [comment]
Posted without comment.

<img width="1274" alt="Screen Shot 2023-06-06 at 8 47 15 AM" src="https://github.com/NCATSTranslator/Feedback/assets/5562107/31ad5e7f-2eed-4735-9d66-e45b84975bce">

**Comment by gloriachin** [comment]
Which drugs may treat Fanconi Anemia?
https://ui.test.transltr.io/results?l=Fanconi%20Anemia&t=0&q=2df0abaf-4481-45b6-81d1-dbcc4bb26494
<img width="855" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/2994757/9b6bd012-6305-4ec8-9d83-5aaa6aa0ea5f">
<img width="1020" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/2994757/9896241c-60bb-456c-98ad-6d1a1ee0e045">
<img width="1108" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/2994757/43b5e77f-08bd-4fc3-a486-5cd69c2aac2d">

**Comment by colleenXu** [comment]
@gloriachin make a separate issue for this!!! it's not really for statements!!!

**Comment by gaurav** [comment]
"Brain death" no longer appears in disease autocomplete because it's not in MONDO.

**Comment by sierra-moxon** [comment]
closing as complete; please reopen if need be.
