### ISSUE TITLE
Many explicit suicide terms in search box

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#289]
## Steps to reproduce:
Suicide related topics likely should be blacklisted

**Comment by dkoslicki** [comment]
Likely in #287

**Comment by sierra-moxon** [comment]
SEMMEDDB via BTE

**Comment by sierra-moxon** [comment]
If we limit autocomplete to MONDO terms and MONDO synonyms, does this issue go away?

**Comment by gaurav** [comment]
All the results for "suicide" I see on [the upcoming NameRes release](http://name-resolution-sri-dev.apps.renci.org/docs) have UMLS identifiers as their preferred identifier, so I think that yes, filtering to MONDO identifiers should eliminate this.

**Comment by gaurav** [comment]
"suicide" no longer matches anything after the MONDO filter.
