### ISSUE TITLE
Rho(d) immune globulin, human treats sadomasochism 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#292]
## Steps to reproduce:
Likely blacklist sadomasochism

**Comment by gaurav** [comment]
Tracking at https://github.com/TranslatorSRI/NameResolution/issues/63

**Comment by gaurav** [comment]
Added to blocklist (https://github.com/NCATSTranslator/Blocklists/blob/c899296eb31c9f5c580990d884c54a45972403d2/blocklist.yaml), closing.
