### ISSUE TITLE
These terms are potential embarrassing as diseases

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#293]
## Steps to reproduce:
Type "homosex" into search box.

## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20230606153426959920.jpeg)

**Comment by gaurav** [comment]
I was hoping that those "gender identity disorder" concepts were deprecated, but nope, they appear to be valid UMLS concepts: https://uts.nlm.nih.gov/uts/umls/concept/C0270310

**Comment by sierra-moxon** [comment]
what if we limit the autocomplete to only MONDO terms and their synonyms?  At least for September.

**Comment by dnsmith124** [comment]
@sierra-moxon this change has been implemented, I tested it on ci and can confirm that no terms return now when searching 'homosex' or 'homosexual'

https://ui.ci.transltr.io/

**Comment by sierra-moxon** [comment]
Hi @dnsmith124 - that's amazing! :). 

One thing I noticed is that we're not limiting the autocomplete to _only_ HP and MONDO terms and synonyms.  Maybe this strict limit is our best approach for September? 

e.g. ci autocomplete for 'fet' (first three letters of fetal alcohol syndrome) 
<img width="906" alt="Screen Shot 2023-06-09 at 12 23 38 PM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/4a4d8f97-7791-4acd-8d40-20b228633e67">

vs. Ontology Lookup Service (limited to MONDO and HP) 
<img width="723" alt="Screen Shot 2023-06-09 at 12 26 43 PM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/a4e06d9f-c8be-4e47-80ad-9156d318c2a0">

Maybe a standalone solr index with just those terms and synonyms for the 'treats' MVP autocomplete could be a way to go?  - if SRI provided this service would it be helpful?

**Comment by gaurav** [comment]
"Fetishism" (MONDO:0001504) would not be filtered out by the MONDO/HP filter, but "transvestism" (DOID:1233), "True compulsive fetishism" (UMLS:C0270505), "fetishism partialism" (UMLS:C0270526) and "Symptomatic fetishism" (UMLS:C0270506) would be.

**Comment by gaurav** [comment]
"Fetishism" (MONDO:0001504) has now been added to the Blocklist (https://github.com/NCATSTranslator/Blocklists/blob/c899296eb31c9f5c580990d884c54a45972403d2/blocklist.yaml), but I'll keep this open until we close https://github.com/NCATSTranslator/Blocklists/issues/1, which will allow us to block all child terms of "fetishism" as well.
