### ISSUE TITLE
Drugs treating sexual assault, or sexu*

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#294]
## Steps to reproduce:
Should blocklist anything that isn't a disease, or is not a disease treatable by a medication

**Comment by gaurav** [comment]
Tyler: Block anything that if the NIH stated could be treated by medication could be problematic.
Andy:
* We probably don't want to filter results, but note that nodes can show up in the middle of a result (this would require blocking at ARS or UI)

Management: who should take ownership of the blocklist (Red Team Committee?)
* Carrie: people were interested in testing at the Relay
* @capasfield to make an actual list and @gaurav to incorporate it into NameRes

**Comment by gaurav** [comment]
"Sexual and gender identity disorders" (MONDO:0000595) has now been added to the Blocklist (https://github.com/NCATSTranslator/Blocklists/blob/c899296eb31c9f5c580990d884c54a45972403d2/blocklist.yaml), but I'll keep this open until we close https://github.com/NCATSTranslator/Blocklists/issues/1, which will allow us to block all child terms of "Sexual and gender identity disorders" as well.

**Comment by gaurav** [comment]
Concept as well as subclasses are now blocked in https://ui.ci.transltr.io/, closing.
