### ISSUE TITLE
Potentially embarrassing to treat these as diseases

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#295]
## Steps to reproduce:
Type "gender" into the search box for What drugs may treat.

## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20230606153616461530.jpeg)

**Comment by dkoslicki** [comment]
#287

**Comment by gaurav** [comment]
I'm still working on figuring out exactly what combination of concepts we need to block to close this issue. Once I've figured that out, I'll add them to the Blocklist and close this issue.

**Comment by sierra-moxon** [comment]
retested and I can't find any issues on CI.  
close?
