### ISSUE TITLE
"death" autocompletes to "warfarin"

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#301]
## Steps to reproduce:
odd one

## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20230606154850602918.jpeg)

**Comment by dkoslicki** [comment]
#288

**Comment by sierra-moxon** [comment]
Note: with the fixes to CI to return only MONDO terms, we no longer see 'death' in the autocomplete (just plague), nor warfarin when typing death.

**Comment by cbizon** [comment]
This doesn't work for everything though:

![image](https://github.com/NCATSTranslator/Feedback/assets/10744350/f9711c19-0974-4ee8-bdf5-dd496ee216f7)

**Comment by gaurav** [comment]
This _looks_ like it's fixed on UI, probably because of filtering to MONDO. Okay to close?

<img width="1206" alt="Screenshot 2023-06-24 at 5 06 20 PM" src="https://github.com/NCATSTranslator/Feedback/assets/23979/c3b791af-2e54-42e7-b0eb-a3c00b42bb38">

**Comment by sierra-moxon** [comment]
@gaurav - definitely fixed for "what drugs may treat" MVP - Chris posted above that "death" still returns "Warfarin" in the gene upregulation/downregulation MVPs.  Any chance we can limit the MVPs that take gene symbols as input to gene identifiers only?  (e.g. check that the ID suggested by NameResolver has a prefix of "HGNC:" or "NCBIGene:" before returning it in the autocomplete picklist?  @dnsmith124

**Comment by gaurav** [comment]
Would it be possible to implement the same "matched on" string for genes and drugs as we see in diseases? I think "warfarin (matched on Arab rat death)" would make a lot more sense than the current string. This won't work in all cases (e.g. "Sinus" is a synonym of UMLS:C0723346, "Sinus brand of acetaminophen-pseudoephedrine"), but I think it will help.

**Comment by gaurav** [comment]
This would be bigger concern if "Death" was coming back as an autocomplete result, but if you search for Death and get back warfarin, that's fine (especically once we can see the synonym).

Warfarin should also link out to https://pubchem.ncbi.nlm.nih.gov/compound/54678486

**Comment by sierra-moxon** [comment]
ok from @gaurav's comments, I think we should close this ticket. :)
