### ISSUE TITLE
Clindamycin treats mental handicap (actually can cause mental symptoms)

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#302]
## Steps to reproduce:
What drugs may treat "mental handicap" (matched on "disability") returns Clindamycin hydrochloride, only support is an ARAX triple.
A quick literature search surfaces the opposite - clindamycin treatment can cause mental symptoms (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7278321/).

**Comment by gglusman** [comment]
(I reported this.)

**Comment by gaurav** [comment]
"Mental handicap" is a UMLS term, so it is being filtered out by the filter-to-MONDO rule currently on CI. I think we can close this.

**Comment by cbizon** [comment]
Closing based on @gaurav's comment
