### ISSUE TITLE
What chemicals upregulate SLC30A8 -- insufficient provenance

### ISSUE THREAD

**Issue by flannick** [NCATSTranslator/Feedback#303]
https://ui.test.transltr.io/results?l=SLC30A8&t=1&q=a7f93d49-550e-47f2-a698-fb02f05c01cc

The bottom results include a bunch of potentially interesting things, each of which has two supporting paths: a one-hop with provenance of "imProving agent" and a two-hop with provenance from LINCS. But the provenance just routes me to the github page for imProving and/or the LINCS home page. I'd like more information as to where imProving got it from (is this from LINCS even?) or which LINCS statistics supported to correlations.

**Comment by sierra-moxon** [comment]
@suihuang-ISB - can you point me to a better infores description or wiki page for use in the UI instead of the github URL?

**Comment by suihuang-ISB** [comment]
@flannick:  Yes, is it is from LINCS, and we have the associated LINCS stats in SPOKE. This is the info we have (see below), but I am not sure we have already implemented returning this and not sure if UI supports entry-specific URLs within a database other than PubMed.

Edge (SPOKE predicate type): OverExpressionGene-downreguates-Gene 
zscore: -4.87530
pvalue: 0.0010662485
sources: CMAP/LINCS overexpression (trt_oe)

I need t ask Karthik how this is mapped  to biolink/EPC and returned....

**Comment by brettasmi** [comment]
Is it possible to show provenance links beyond those configured in the infores catalog? If so, how are those exposed?

For some of imProving Agent's and SPOKE-KP's data, we do have additional link out information in attributes, but I'm not sure how to view those in the UI. However, in the specific case of LINCS data, I don't think we have that information.

**Comment by sstemann** [comment]
@sierra-moxon @Genomewide could you work with Brett?  its not clear why the additional information wouldn't be included in the primary/aggregator sources and i think that is what UI is pulling

**Comment by brettasmi** [comment]
For imProving Agent's provenance, we are working on updating our README content, moving it to the Translator wiki, and eventually to the "branded" pages that will live in the UI.

As for LINCS, I'm not sure what we can do to improve the provenance, and lincsproject.org is the correct URL. Maybe in the medium-long term we can write small blurbs for every source in the infores catalog and have them exposed in the UI?

**Comment by sierra-moxon** [comment]
improving agent now has a Translator Wiki page and is pointing there from their infores identifier in the catalog (released in biolink-model 3.5.0). https://github.com/NCATSTranslator/Translator-All/wiki/imProving-Agent. 

In terms of more provenance showing up in the form of additional URLs to more specific provenance; this definitely has come up before and currently is tabled for implementation until after September release.  

To me, the tasks that can be completed to address this ticket have been completed.  We can change the milestone here, keeping the ticket open for further work in September.

**Comment by brettasmi** [comment]
I have updated our wiki page to include descriptions of the inferred query logic for imProving Agent, so I agree with @sierra-moxon that this can be closed.

Thanks to @sierra-moxon for updating imProving's URL in the infores catalog.
