### ISSUE TITLE
Possibly embarrassing as diseases

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#304]
## Steps to reproduce:
Type "Polish" into search for disease

## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20230606155528450721.jpeg)

**Comment by gaurav** [comment]
No longer present in CI as it has been filtered out by MONDO.

**Comment by gaurav** [comment]
Confirmed no "polish" related terms after applying the MONDO|HP filter (http://name-resolution-sri-dev.apps.renci.org/lookup?string=polish&offset=0&limit=10&only_prefixes=MONDO%7CHP). Closing.
