### ISSUE TITLE
"Rape" in the dropdown (and do get some results when selecting some of the autocompletes)

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#306]
## Steps to reproduce:
Some are potentially offensive, some are not diseases

**Comment by dkoslicki** [comment]
#287

**Comment by gaurav** [comment]
No longer present in CI as filtered out by the MONDO filter.

**Comment by gaurav** [comment]
There are some terms related to sexual assault in MONDO|HP (http://name-resolution-sri-dev.apps.renci.org/lookup?string=Sexual%20Assault&offset=0&limit=10&only_prefixes=MONDO%7CHP) as well as across NameRes generally (http://name-resolution-sri-dev.apps.renci.org/lookup?string=Sexual%20Assault&offset=0&limit=10), so this will require a bit more work to identify the specific concepts we should add to the blocklist.

**Comment by gaurav** [comment]
No results for `rape` or `assault` in https://ui.ci.transltr.io/. Closing.
