### ISSUE TITLE
No results for Nausea disorder

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#308]
## Steps to reproduce:
Ran in CI - What drugs may treat "Nausea Disorder". Got 0 results.

**Comment by dnsmith124** [comment]
side note, 'Nausea Disorder' no longer returns now that we're filtering the autocomplete to only include MONDOs

**Comment by cbizon** [comment]
Are we going to allow HP as well?   There are lots of phenotypes that require treatment (like nausea)

**Comment by gaurav** [comment]
We've decided to revisit this after the other autocomplete issues are fixed (https://github.com/NCATSTranslator/Feedback/issues/327#issuecomment-1604543680).

**Comment by sierra-moxon** [comment]
closing as complete - lots of drugs returned for nausea query.
