### ISSUE TITLE
Incorrect wording ("1 Path that may upregulate Bdnf") returned when asking "Which chemical downregulates Bdnf?"

### ISSUE THREAD

**Issue by beasleyjonm** [NCATSTranslator/Feedback#309]
![image](https://github.com/NCATSTranslator/Feedback/assets/85600465/235b194f-843c-491e-ae7f-80381785deab)

Results state that "1 Path that may upregulate Bdnf" when asking "Which chemical upregulates Bdnf?"

Then, when the query prompt is switched to "Which chemical upregulates Bdnf?", the results switch to say "1 Path that may upregulate Bdnf"
![image](https://github.com/NCATSTranslator/Feedback/assets/85600465/f619b3e7-29a5-40c3-b74c-bef5dfffd6c1)

**Comment by beasleyjonm** [comment]
The real problem here is that the results remain the same, reflecting the original question, "Which chemicals may upregulate BDNF?"

**Comment by sierra-moxon** [comment]
@dnsmith124 - I think you might've been in our session this morning when @beasleyjonm found this one? :) ok if I assign it to the UI team and set in progress?  If I got that wrong, feel free to toss it back of course!!

**Comment by dnsmith124** [comment]
Yep, sounds good @sierra-moxon! This is a known issue that we're going to address.
