### ISSUE TITLE
Confusing Answers for What Treats Pregnancy

### ISSUE THREAD

**Issue by GitHubbit** [NCATSTranslator/Feedback#317]
https://ui.ci.transltr.io/results?l=Early Pregnancy&t=0&q=56ca021a-4629-461a-9b71-d1f866ff2efb
Results indicate that Mifepristone (an abortive drug) and ethanol/alcohol treats Early Pregnancy. 
Should find a way to state more clearly that Mifepristone induces termination of Early Pregnancy. 
Alcohol included in result due to papers discussing fetal alcohol syndrome. 
May be SEMMED DB related.

**Comment by sierra-moxon** [comment]
I would again think that if we limited autocomplete to MONDO term names and their synonyms for "what may treat" queries, we'd at least eliminate "Early Pregnancy" as a choice here.  

We'd still be able to search for drugs that may treat 'fetal alcohol syndrome' - note 'Ethanol' is still returned for that query.  
<img width="1439" alt="Screen Shot 2023-06-06 at 9 04 36 PM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/c8182842-7924-4c22-a37f-18569e29dced">

**Comment by sierra-moxon** [comment]
from TAQA:
alcohol is actually used to treat alcoholism 
are there patterns to the "doesn't make sense" (for opposite answers)?
There are still some KPs that are using a "treats" predicate for triples that should have "affects" predicates. 
perhaps from TMKP, perhaps from ROBOKOP

**Comment by sandrine-muller-research** [comment]
Pregnancy cannot be searched anymore (I verified today on PROD). Closing this issue, please reopen if need be.
