### ISSUE TITLE
feature addition : "this result is not exactly what you wanted but I thought it might be interesting"

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#318]
This issue originiates from issue #311 where the reasoning was ok but the result is not anwering the user intent: 
When asking What drug downregulates gene X? the user (at least our facet) is trying to find candidates for reducing the levels of expression of the target gene. 
When the result pattern is of the form 
chemical -- regulates -- gene -- has inscreased abundance caused by
The logic is correct but it is not quite what the users asks. However, those results could be important for the user to look at. Instead of filtering it at the ARA level (short term solution perhaps) one could think of a additional section below offering those kind of results.

**Comment by gprice1129** [comment]
@sandrine-m this requires discussion with a larger group than the UI. The UI team suggests getting this onto the architecture WG agenda if we want to move this feature forward.

This is not a priority for us this release cycle.

**Comment by sierra-moxon** [comment]
I believe this was fixed by changing the term "regulates" to "affects activity or abundance" in the UI.
