### ISSUE TITLE
If there's only one one-hop path, can the network view be minimized in the result?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#319]
MVP2 has a lot of one hops, seems like the default view for these should be with the network view minimized.

[![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/16d911ee-00a7-4b52-99da-6c5cfb5af3fb)](https://ui.test.transltr.io/results?l=Iron&t=3&q=1cb5dfa2-502b-45cf-a84e-f412bb4756ab)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/25fe1a8d-2f58-4f2f-ba8a-036628e5baa0)

**Comment by gprice1129** [comment]
This is done. Please verify @sstemann

**Comment by sierra-moxon** [comment]
I was able to verify! :) Thanks for this!! it's super nice and intuitive.  I'm going to go ahead and close; of course reopen if I made a mistake here.
