### ISSUE TITLE
autocomplete UI suggestions for "matched" text

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#320]
from TAQA, in reference to https://github.com/NCATSTranslator/Feedback/issues/198: 

Andrew: autocomplete Suggestion -- UI currently shows the pattern "X (matched on Y)". If X == Y, then don't show the "matched on" part... Gustavo: following up on Andrew’s, I’d suggest making the ‘matched on’ text gray, italics, smaller… anything to make the suggested term clearly stand out. David: +1

**Comment by gglusman** [comment]
Looks like this was implemented already?
