### ISSUE TITLE
Network View - Giant Box

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#323]
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/5350e13d-0255-470f-b325-ceb0eaca3f0a)

https://ui.test.transltr.io/results?l=Niemann-pick%20Disease&t=0&q=280c5d97-f8b1-4dcd-a809-a8136f3d3b64

Insulin degludec

**Comment by dnsmith124** [comment]
The truncation has prevented the overflow, and a tooltip window has also been added to provide the full name when the node is hovered over.

This was the best solution considering the massive variation in character length and the limitations of styling within the library that runs the graphs (cytoscape)
