### ISSUE TITLE
generate node counts for every KP and provide to UI

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#327]
from TAQA:
identifier | edge count

We think this might help solve the larger issues of "autocomplete" identified at the relay. 

Autocomplete
too many “red team” findings including “suicide, sex, early pregnancy, polish, combat fatigue”, etc.
type ahead suggestions are inconsistent and difficult for the user to understand
the list should grow longer or shorter when you type more characters, not both.
autocomplete choices imply to the user there are results for those choices, even when there are no results.  
Queries with 0 results (e.g. using one of the autocomplete terms that has no results) take the longest to return.
don’t include non-human species if we can’t return results for non-human species.

**Comment by sierra-moxon** [comment]
noting that BTE can not provide this information.

**Comment by sierra-moxon** [comment]
from TAQA:
what is the scale of missing information if BTE can not provide this information
from Andrew: we could base this on the precomputed sources, and we wouldn't lose that much from BTE in using this to filter - the exact numeric calculations are likely not that important. 
there are so many possible names that point to some UMLS id, that no one ingests information about and gives a list of results to the user that we can not get an answer for.  
it might be effective to limit the autocomplete to certain domains of names (e.g. MONDO or HP terms and synonyms for "treats" MVP) 
ranking in the drop-down isn't that big of a deal for September.  If we limit to MONDO/HP, then zero results might be less of a visible problem.  
Do we want to limit genes to human?  (seems restrictive) - diabetes searches still return a million different kinds of diabetes, of 
which we only have results for one form of diabetes.  
limiting them to a certain ontology has reduced the mismatches between gene symbols and disease acronyms.  
Andrew: there is an argument for providing zero-hit results.  
Chris: still going to be helpful to find the best result by number of hits.  
Sarah: if we have a set of resources to experiment with this, we should. 
Mark, Chris: its not clear why 0 results takes a long time to return - we can investigate with more testing.

**Comment by gaurav** [comment]
Cases:
1. Has no edges at all
2. Has an edge, but may not be responsive to the query

Tyler: note that the list of identifiers with data on them this will change over time.

Filtering to MONDOs should help with this -- we should know something about all the MONDO identifiers. Dan Korn has run every MONDO through ROBOKOP: "lots didn't have results, it was different for each ARA". (Dan's results will be discussed in the next Scoring meeting on Tuesday, June 27)

Not a high priority at the moment, but we can revisit once we expand autocomplete outside of MONDO.

**Comment by gaurav** [comment]
@sierra-moxon Have you seen any improvement to the speed of queries with no results? I feel like if we can get that down sufficiently, then we don't need to do more than explain to the user why they'll see no results for some queries. But if not, we might need to come up with something smarter (e.g. a popup warning that there might be no results if there haven't been any results in 120 seconds or something).
