### ISSUE TITLE
UI bug: creating hybrid queries

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#328]
1) select 'what drugs may treat'
2) enter 'Alzh' and choose 'Alzheimer Disease'
3) use the query selector to switch to 'what chemical upregulates'
4) click submit

Result: a mixed output showing chemicals that upregulate AD, or cause it, depending on where you look.
"1 Path that may upregulate Alzheimer Disease" vs. "[chemical name] causes Alzheimer Disease" in the path display.
The resulting chemicals are not the same as one gets from the 'what drugs may treat' query, suggesting that indeed the 'upregulates' query is sent with the CURIE for AD in place of a gene.

**Comment by gglusman** [comment]
Just for fun I tried also 'what gene is upregulated by' and learned from Semmeddb via ARAX that "Type 2 Diabetes Mellitus Has Increased Activity Or Abundance Caused By Alzheimer Disease".

**Comment by dnsmith124** [comment]
This is a great find @gglusman, the UI is supposed to wipe out the search bar whenever a new query type is selected, so this definitely isn't working as intended. I'll take a look.

**Comment by gglusman** [comment]
Beyond the UI aspect, is this exposing that downstream actors are not checking the class of the components of the query? Sounds like the query itself should have been rejected.

**Comment by sierra-moxon** [comment]
@gglusman - your last comment here is making me want to move this to "review status at TAQA"?  Is that ok?  Or do you think the change in the UI as @dnsmith124 suggests, would "fix" this issue by omission?

**Comment by dnsmith124** [comment]
I've resolved the UI portion of this ticket locally, waiting on a build now. 

I think it probably should be moved to 'review status at TAQA', it's worth investigating what @gglusman brought up.

**Comment by gglusman** [comment]
I think the 2nd issue is worth exploring indeed. Downstream actors should rely on the UI sending sanitized content.

**Comment by dnsmith124** [comment]
@sierra-moxon The UI portion of this ticket is resolved, who should we reassign this to in order to address @gglusman's request?

**Comment by sierra-moxon** [comment]
Thanks @dnsmith124!  - I'll put it in the Fall milestone and trust that @gglusman will help me bring it back up for more work as we go through the "Fall" tickets post September.

**Comment by gglusman** [comment]
@sierra-moxon Hey look we're post-September!

**Comment by gglusman** [comment]
This was solved a while ago with the new input system. Closing!
