### ISSUE TITLE
Combinatorial explosion in the number of answers returned to a query

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#33]
This issue is to formally report a known Translator issue, namely, a tendency for answer sets to explode combinatorially with certain types of queries.

For instance, during the October 2022 QotM, Translator team members found that moving from connections between _ATP1A3_ and chemical entities or diseases yields a reasonable number of results; however, when adding in intermediary genes and pathways, the answer sets explode and become unmanageable.

Example from comment posted by @colleenXu [here](https://github.com/NCATSTranslator/testing/issues/233):

"Not sure how to get from ATP1A3 -> related genes -> ChemicalEntity, Procedure, Treatment in a way that doesn't explode / become unmanageable
        
Pathways / BiologicalProcessOrActivity...caused explosions since they were linked to pathways that had lots of genes"

**Comment by sierra-moxon** [comment]
From TAQA:

- this is a huge issue, we probably need to break it down
- UI is working on fixes here, where you could eliminate a node and reduce the hairball.

from Sharat: four issues to be broken down into

- [ ] filter controls to the user. - UI group 
- [ ] merging records - already happening in different levels (ARS, agents, etc.).
- [ ] grouping records - travel up the ontology and give it to me above.
- [ ] scoring records - still have some way of bringing the bit to the top.  

big picture -> deep dive is important

from Chris B: perhaps another issue here is: this is a known query that has a lot of results - sorry.  Or, can we filter/sort our way out of this one? - is this doable?   Run this query, get a lot of answers back, know this - suggest to the user that they tighten this up.  Here are the common predicates associated with the answers you're getting back, can we try to help the user write a better query?  

from Sharat:  agree; this is the best we can do, here are ways to tighten it up.  
work on user workflows for two big queries.  
Andy is interested in more brainstorming on this; UI needs direction. 
In the end, there is one place where the quality of the results is the measurement (either UI/O&O or someplace we could get it).

**Comment by sharatisrani** [comment]
For the case of grouping records, O&O has a tracking issue at https://github.com/NCATSTranslator/Ordering-Organizing/issues/15, with a few additional comments.

**Comment by sharatisrani** [comment]
This is a major issue, but how likely is it to bite us for the September release?

**Comment by karafecho** [comment]
I think this is being addressed as described [here](https://github.com/NCATSTranslator/Feedback/issues/281) and recorded [here](https://github.com/NCATSTranslator/TranslatorArchitecture/pull/88).
