### ISSUE TITLE
suggestion for UI: disable 'enter' when typing query (and get rid of 'search' button)

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#332]
When one selects query, then starts typing, and presses enter, one gets "No term selected, please select a valid term."
This confusing outcome could be avoided by disabling the ability to 'submit' by pressing enter. One would then type, any enter presses would be ignored, the selection widget would appear, one would select and the form would be submitted automatically, without need to press 'search'.

**Comment by dnsmith124** [comment]
Completely agree with you @gglusman, this was actually how the search bar functioned in the past but the behavior was changed due to feedback from someone (I can't remember who). Going to push to have it reverted to match your suggestion.

**Comment by dnsmith124** [comment]
This issue has been resolved by our reimplementation of the query submission process. 

Closing.
