### ISSUE TITLE
Merged results, are showing paths that seem "duplicative" with different "diseases" for the MVP1 

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#335]
The QG for this query has MONDO:0020732 (https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0020732)

https://ui.test.transltr.io/results?l=Progeria&t=0&q=9a17d094-d303-44ba-8e21-2a4164dc19c8

Example: RNA, small interfering
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/b948dde6-4a72-4f9a-a5f7-88d1cb611ef8)

seems to be combined from BTE:
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/5f75d8a3-e966-4b0b-ac4f-30637373616a)

and Unsecret:
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/168c79da-f23a-4404-915a-c4607866fa92)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/f6040b54-e66c-48a0-b7cc-fc12481cedc5)

More examples:
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/1931f732-b320-4641-8163-db072e9fe4fd)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/1f2a9716-19f8-45a5-99ab-0da81ed580ed)

**Comment by andrewsu** [comment]
@sstemann Just to clarify, is the unexpected result here that you are seeing nodes for both "Progeria" and "Hutchinson-Gilford Progeria Syndrome" in the same answer?

**Comment by sstemann** [comment]
@andrewsu while it looks "duplicative" to me, Christine and Tyler say its okay.  I'll go ahead and close it.
