### ISSUE TITLE
generic report of generic thing treating another generic thing via a generic intermediate

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#336]
## Steps to reproduce:
'What drugs may treat inborn errors of metabolism'? Therapeutic agents, working via cytokines.

## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20230607164337371403.jpeg)

**Comment by gglusman** [comment]
Sorry, could not resist sharing this fun collection of generic stuff.

**Comment by sstemann** [comment]
@edeutsch @dkoslicki looks like this one is coming from ARAX

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/072559af-7a52-4f20-a9e9-79ca402375fe)

**Comment by edeutsch** [comment]
Thanks for reporting, we discussed strategies for eliminating such things at a meeting today and will if we can fix this soon. Adding @chunyuma

**Comment by sierra-moxon** [comment]
closing as complete; please reopen if necessary.
