### ISSUE TITLE
Synesthesia is a condition not a disease: put in the black list please

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#339]
## Steps to reproduce:
test ui, MVP1 for synesthesia

**Comment by sierra-moxon** [comment]
noting that "synesthesia" does not exist in either MONDO or HP.

**Comment by dnsmith124** [comment]
This has been resolved by filtering out all non-MONDO results for "What drugs may treat ____" per @Genomewide 's request. Confirmed on ci at https://ui.ci.transltr.io. 

Closing.
