### ISSUE TITLE
Is there a better link out for BTE?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#343]
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/ed5659b9-3885-4b73-9775-70f29478048d)

I'm not super sure where to look to understand the reasoning that BTE does when I land here:  http://biothings.io/explorer/

**Comment by sierra-moxon** [comment]
Noting that @andrewsu put in a change to the infores catalog this week for BTE.  https://github.com/biolink/biolink-model/pull/1337.  Assigning to me to make a release.

**Comment by andrewsu** [comment]
Sorry, my PR on Biolink Model was prompted by this issue, but it does not address this issue. I think we still need to figure out a new place (or repurpose an existing field) in the infores catalog to point to a description of the reasoning methodology, as you alluded to in https://github.com/NCATSTranslator/Feedback/issues/342#issuecomment-1594879308

**Comment by sierra-moxon** [comment]
from our DM call today: 
we decided that providers should update their wiki pages to reflect the methodology of edge generation according to this template:
[template](https://docs.google.com/document/d/1WMVwYK_u9vQ60F-aKfdCer27Y4Xm1X04/edit) examples: 
https://github.com/NCATSTranslator/Translator-All/wiki/Exposures-Provider-ICEES.

**Comment by andrewsu** [comment]
I took a crack at updating the BTE wiki page at https://github.com/NCATSTranslator/Translator-All/wiki/Exploring-Agent--(BioThings-Explorer).  However, I'm noting that the [ICEES example](https://github.com/NCATSTranslator/Translator-All/wiki/Exposures-Provider-ICEES) doesn't seem to follow the [linked template](https://docs.google.com/document/d/1WMVwYK_u9vQ60F-aKfdCer27Y4Xm1X04/edit) in @sierra-moxon's post above (and the template actually seems better suited to annotating individual knowledge sources as opposed to KPs or ARAs, IMO).

**Comment by sierra-moxon** [comment]
This has been updated in the infores catalog (as of last Friday);  we need a UI update to pull it into CI.

**Comment by dnsmith124** [comment]
@gprice1129 will update early next week.

**Comment by sierra-moxon** [comment]
added UI - display label to this ticket; the backend work was released in Biolink 3.5.4 yesterday, but we likely won't see the change in the UI until after code freeze.  :)

**Comment by Genomewide** [comment]
This is fixed in prod now. https://ui.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&q=20ef77f8-7aac-4d7b-9d8b-b3465e87e769

Closing

![Image](https://github.com/NCATSTranslator/Feedback/assets/55069176/3c22bba5-5125-472c-9daf-bd2d5a239844)
