### ISSUE TITLE
Add Description of Reasoning for the Unsecret Link Out

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#344]
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/7724378e-7de2-42df-9ea1-839dd10b1325)

https://github.com/NCATSTranslator/Translator-All/wiki/UnSecret-Agent

**Comment by sierra-moxon** [comment]
from our DM call today:
we decided that providers should update their wiki pages to reflect the methodology of edge generation according to this template:
[template](https://docs.google.com/document/d/1WMVwYK_u9vQ60F-aKfdCer27Y4Xm1X04/edit) examples:
https://github.com/NCATSTranslator/Translator-All/wiki/Exposures-Provider-ICEES.

**Comment by sierra-moxon** [comment]
https://github.com/NCATSTranslator/Translator-All/wiki/UnSecret-Agent looks updated.
