### ISSUE TITLE
integration of scores brings bad answers to the top

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#345]
Querying "what drugs may treat Postaxial Acrofacial Dysostosis (MIller Syndrome), the top answer given is Isofezolac with score 100.0. All the evidence behind this is a prediction from ARAX.
Consulted with @dkoslicki who indicated this is a very weak prediction with very low score, but since it's the only result from ARAX, it was 'rescaled' to 100.0 and presented as top answer.
I couldn't find any further support for this tentative connection.

**Comment by cbizon** [comment]
@dkoslicki is the new ara score merging going to handle this case better?

**Comment by andrewsu** [comment]
linking this [related comment](https://github.com/NCATSTranslator/Feedback/issues/191#issuecomment-1568927584) and [this reply](https://github.com/NCATSTranslator/Feedback/issues/191#issuecomment-1580975306) from @MarkDWilliams

**Comment by andrewsu** [comment]
Going to add another example to this issue (originally from https://github.com/NCATSTranslator/Feedback/issues/343).  In https://ui.test.transltr.io/results?l=Demyelinating%20Disease&t=0&q=bc5eb595-2aba-4e51-8dcd-5ba97bea05ce, the ranked results don't seem to agree with what I'd expect based on the underlying scores from ARAX and BTE...

**Therapeutic agent (substance)**
UI: rank 1 (score 100)
ARAX: 1 (0.9)
BTE: 181 (0.529)

**Rituximab**
UI: rank 34 (score 96.6)
ARAX: 6 (0.567)
BTE: 18 (0.823)

**Immunoglobulins, Intravenous**
UI: rank 75 (score 91.6)
ARAX: 2 (0.733)
BTE: 43 (0.712)

**Comment by sierra-moxon** [comment]
from TAQA:
Mark: low scores from ARAX, normalized to high scores in ARS.  The new scoring system (f-score) is going to fix this, this score will be deprecated. 
Matt: will knowledge_level be incorporated into score? (e.g. prediction vs. human-curation)
Andy: still in discussion at O&O. 
Paul: user looking for novelty vs. other - then they want a high score for a very novel result. 
Sui & Matt: fact answers (lookup answers) to the top - this isn't a ranking issue.  default ordering should be based on confidence, allowing user to change the "slider" of confidence if they want more novel answers.

**Comment by Rosinaweber** [comment]
Please hold off until July 14th to produce feedback on ordering because only then results will be sorted based on the f-score, which in turn will use aggregated confidences from multiple ARAs after drugs are merged.

**Comment by sierra-moxon** [comment]
Per feedback from @amberp2023 - this ticket can be closed.  @amberp2023 - would you mind giving 2-3 sentences here on how it was fixed?  (this might help other's in their testing :)).
