### ISSUE TITLE
SPOKE edges link to imProving Agent's GitHub repo

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#346]
This issue is to report that SPOKE edges point to imProving Agent's GitHub repo as source. Note that the README _may_ be sufficient, but that information needs to be displayed on a Translator wiki page or somewhere other than GitHub.

![image](https://github.com/NCATSTranslator/Feedback/assets/26254388/00b19237-667e-4b28-8709-ddc211e4c6d1)

**Comment by sierra-moxon** [comment]
from our DM call today:
we decided that providers should update their wiki pages to reflect the methodology of edge generation according to this template:
[template](https://docs.google.com/document/d/1WMVwYK_u9vQ60F-aKfdCer27Y4Xm1X04/edit) examples:
https://github.com/NCATSTranslator/Translator-All/wiki/Exposures-Provider-ICEES.

**Comment by sierra-moxon** [comment]
This has been updated in the infores catalog.  We need a change from UI team to see it in CI.

**Comment by gprice1129** [comment]
We decided to roll this in to a larger update that is coming soon.

**Comment by sierra-moxon** [comment]
closed as completed
