### ISSUE TITLE
chaining logic ignoring multiple possible causes for the same symptom

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#349]
Querying "what drugs may treat Postaxial Acrofacial Dysostosis (MIller Syndrome), the 3rd result is Ergocalciferol (vitamin D2) with 3 paths: a direct 'treats' path from BTE, and two chaining via the 'failure to thrive' and 'growth delay' symptoms of the disease.

The logic for the connection is extremely weak, since there can be very many causes to 'fail to thrive' and to delay growth. If D2 deficiency is the cause, supplementation may treat. In most other cases, this treatment would be irrelevant as it doesn't address the root cause - or even the mechanism.

https://ui.test.transltr.io/results?l=Postaxial%20Acrofacial%20Dysostosis&t=0&q=72fedb01-7ee2-4c7d-8a78-2cab471d4df8

**Comment by sierra-moxon** [comment]
@gglusman - before you navigate away from this query, can you put the URL in this ticket for your search?  That way we can directly go to the result and track it to the correct ARA.  Much appreciated :)

**Comment by gglusman** [comment]
...and of course I saw your reply right after closing it.
It was from BTE though.

**Comment by gglusman** [comment]
Reopening it from history... a sec.

**Comment by gglusman** [comment]
https://ui.test.transltr.io/results?l=Postaxial%20Acrofacial%20Dysostosis&t=0&q=72fedb01-7ee2-4c7d-8a78-2cab471d4df8

**Comment by andrewsu** [comment]
This case will be used as an example in a broader refactoring of BTE's scoring (issue linked above).  Thanks!

**Comment by andrewsu** [comment]
since I've put this example into https://github.com/biothings/biothings_explorer/issues/634, I'm going to close this issue
