### ISSUE TITLE
ROBOKOP sources incorrect in UI

### ISSUE THREAD

**Issue by cbizon** [NCATSTranslator/Feedback#350]
PK: 94344809-5bfa-41d2-a883-2194b010b622

In CI, I ran what treats Fabry disease.  ROBOKOP returns chloroquine.  There are 2 treats edges connecting chloroquine to Fabry.  

One is a direct edge that starts in TMPK, goes to robokopkg, then via automat.   
The other is an inferred edge going chloroquine similar to hydroxychloroquine to treats Fabry

In ARAX it looks like this:

![image](https://github.com/NCATSTranslator/Feedback/assets/10744350/b9a4ed9b-03ac-4b30-b52b-bcd70b9119e8)

And the treats edge has this provenance:
![image](https://github.com/NCATSTranslator/Feedback/assets/10744350/ec9ee9c3-d408-4705-bb96-55eb90b3e231)

a primary knowledge source of infores:textminingkp

The other treats edge is an inferred edge and has primary knowledge source of infores:aragorn reflecting that it is created by the rule miner.

In the Translator UI, these two edges are getting merged or overwritten, and the primary knowledge source of textminingkp is vanishing just showing aragorn as the primary knowledge source, implying that it found the listed publications.

![image](https://github.com/NCATSTranslator/Feedback/assets/10744350/d839cceb-e05c-4143-9449-2a22c2b1dafb)

**Comment by gprice1129** [comment]
@cbizon `infores:textminingkp` does not appear in the infores catalog. I think it might be `infores:automat-text-mining-provider`.

**Comment by mbrush** [comment]
@cbizon in the infores catalog the TMKP group defined separate infores identifiers for their targeted vs cooccurrence tools.  You are using the targeted tool here, which has the curie `infores:text-mining-provider-targeted`.  I assume this should be the primary source for the edge above.  Also, automat might want to change the infores of its wrapping of this resource to indicate it is the targeted version  - e.g. `infores:automat-text-mining-provider-targeted`.

**Comment by EvanDietzMorris** [comment]
I’ll get those fixed up. Note that robokop graph does contain edges from
tmkp so the automat-robokop infores can be a valid aggregator here.

**Comment by sierra-moxon** [comment]
reran this morning on CI, and now I see two items in the "sources" tab, Aragorn and Hetionet:

![Image](https://github.com/NCATSTranslator/Feedback/assets/4561292/e6ca4f11-55e0-4db4-a265-1d999368d8ed)

Rerunning on arax.ci.transltr.io as well: https://arax.ci.transltr.io/?r=0da3671f-a8a0-435c-b612-65229aa9e9e7.  

![Image](https://github.com/NCATSTranslator/Feedback/assets/4561292/f4ebd452-7d79-4908-a4dc-88da19a3c266)

**Comment by EvanDietzMorris** [comment]
I am still working on getting a new robokop kg up that would fix the textminingkp infores. We'd still need to get that moved up to CI/prod after that though.

**Comment by sierra-moxon** [comment]
Hi @EvanDietzMorris  - @sstemann showed me this morning that infores:text-mining-provider-cooccurrence  and infores:text-mining-provider-targeted are being returned from Aragorn results in ARAX CI environment 🎉 .  However, we still don't see those showing up as "sources" in the UI in CI.  Do you think this is "fixed" on your end and we can send over to the UI group for further investigation? (or should we wait until its in TEST/etc.)

**Comment by EvanDietzMorris** [comment]
Unfortunately it is taking longer than expected and we are still working on getting a new knowledge graph up with the proper infores for our textmining kp edges. So all tmkp results coming from our graphs still have the old "textminingkp" infores. Those would have infores:automat-robokop as the aggregator as well. I'm assuming Aragorn got the results with the infores' you mentioned from some other KP, so maybe there is an issue aside from ours.

**Comment by EvanDietzMorris** [comment]
@sierra-moxon all infores issues are fixed on the robokop side in dev and should be pushed to CI on Monday.

**Comment by EvanDietzMorris** [comment]
This appears to be fixed on test and ci, and should be fixed on prod with the deployments requested today.
