### ISSUE TITLE
answer too general, not useful


### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#358]
## Steps to reproduce:
What drugs may treat Alzheimer Disease? (CI)

**Comment by sandrine-m** [comment]
ARAX returns "Agonists -- treats -- Alzheimer Disease" (result no 2):
Paths show a few genes: could be good to know which antagonists instead of a general class of drugs. Ultimatively, result is wrong because it is not all antagonists which will treat AD.
