### ISSUE TITLE
MVP2 inverse edges should not be clustered together

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#359]
This issue is split from #283 . 
@remontoire-pac : "In this case we have a mixture of "increases" and "decreases" evidence. These should be separate paths.":
![image](https://github.com/NCATSTranslator/Feedback/assets/66342541/d1fc1200-03ad-4557-9fce-97eae629b835)

I think @remontoire-pac  comment (please correct me if I am wrong) is that on a query he made, he finds a result where you have both paths :
Miglitol -- increase expression of -- GCK
and
Miglitol -- decrease expression of -- GCK

However, for a Chemical biologist looking for understanding the mechanism by which Miglitol is acting on cellular phenotype X/pathway...etc, if is less likely that those 2 paths would be clustered together in a single mechanism because if GCK is the target, the action onto GCK will have diffent effects on dowstream pathways.

**Comment by sierra-moxon** [comment]
help @sandrine-m! :) I don't know who this should go to, or if it is something that folks would agree needs to be fixed for September.

**Comment by remontoire-pac** [comment]
I thought this was part of a more general discussion at the Relay about the
"algebra" of chains of connection (e.g., an inhibitor of an inhibitor is
the same "direction" as an activator). I think this is really important for
answer quality, but I do not have a sense where the best place to intercede
is (ARA, ARS, UI). I think the session was on Day 2

**Comment by sandrine-m** [comment]
@sierra-moxon I would have triage this to @cbizon as an architecture issue. I fully support @remontoire-pac's remarks.

**Comment by sierra-moxon** [comment]
@remontoire-pac @sandrine-m -

apologies for being pedantic - are the action items in this ticket (please correct me :)):
1. if a path shows both `increased` and `decreased` qualifiers, it should be split into two paths.
2. we need to update "rule-based" creative mode tools to add rules (TBD) that explicitly include "(e.g., an inhibitor of an inhibitor is the same "direction" as an activator)"

would either of you be able to post a PK to ARAX or the CI or TEST UI environment that shows a result like this?  And, do you have an opinion about if the above two action items must be done for September?

**Comment by sandrine-m** [comment]
The general rule may be that if you have multiple "affects" in different paths of the same result (same input and output/intermediary node) they should always be in the same direction. 

Examples of combined paths with opposite directions:
### on [test](https://ui.test.transltr.io/results?l=Alzheimer%20Disease&t=0&q=2a0fd314-3105-471e-8049-26e89cd6f800):
Agonists - ARAX:
<img width="968" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/294a36e4-eeb8-4820-bb93-8002d9e71a13">

Valproic Acid - ROBOKOP/BioThings Explorer:
<img width="935" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/fe415b4c-4ddb-4c9a-bdcb-68df89bd45a8">

### on [CI](https://ui.ci.transltr.io/results?l=Alzheimer%20Disease&i=MONDO%3A0015564&t=0&q=51efe187-d1cf-43f1-8499-50e6b30c7ad7):
Result 2 (Agonists - ARAX):
<img width="769" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/a3918594-248b-4b5f-b46e-f6bd65b71a9e">
Result 5 (Valproic Acid - ROBOKOP/BioThings Explorer):
<img width="580" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/6199804c-6116-45b8-9d68-8c68c6d1ba26">

**Comment by gglusman** [comment]
@sandrine-m I'm not sure I understand the benefit of such general rule, in cases like these where there is a 'genetic association', which is not inherently signed. Valproic acid increasing one gene and decreasing another, both of which are genetically associated with AD, doesn't seem like a problem.

(Separately, I'm not sure that 'agonists' is beneficial as an answer... too generic! But if it is, as above, an agonist increasing something associated with a phenotype, and the same agonist (or a different one) decreasing something else associated with the same phenotype... not an issue in my mind.)

**Comment by sandrine-m** [comment]
@gglusman I agree with you that this may not be the best examples, I took the first examples I could find. 
Here is the thought behind separating (at least from my understanding) : Given the number of genes in the valproic acid use case, I am not 100% positive valproic acid is targeting all those genes (very well could be I have not looked into this in detail). That means that the target(s) might be linked with those genes somehow. If the user is trying to sort by biological mechanism, it can be hypothesized that you may have 2 different targets : (1) one that increases expression/abundance of a set of genes, and (2) one that decreases expression/abundance of a set of genes. Through pathway enrichment analyses, one can learn about associated curated pathways and study them in detail.
There is also another interest IMO in splitting those is that we can further do operations between paths in workflows to compare, union...etc. the results.
(Looking a bit more in the Valproic acid use case, it looks to me that many of sources cited in that result in in stem cells/neurodevelopment which might be less interesting than other drugs/ it could be nice if the context is more explicit). 

I think we may need different grouping types: network based, input/output based, and mechanistic based on user preferences.

**Comment by cbizon** [comment]
I reran "What chemical downregulates GCK?" in CI.  b9aa3629-2c19-4b9b-9b44-7d287c01d1f6
and "what chemical upregulates GCK?" 294c6684-b11d-4bc9-8e3d-bffb72dad1a0

There were some timeouts, so it's hard to be certain, but only upregulates returned miglitol and that only contained on direction of edge (upregulates).  So it seems like the core issues is fixed (or perhaps masked by job failures).

I'm going to leave open until I can test in Test and get better throughput.

In terms of the other issues raised by @sandrine-m ... I think that these are interesting & might be good post-september updates to the UI?

**Comment by cbizon** [comment]
But the examples shown above other than the miglitol are not reasoning problems per-se because the genetic association is non-directional as noted by @gglusman

**Comment by Genomewide** [comment]
The current rule is to aggregate (not sure if that is the right word, but merge is too loaded) edges if the subject and object. We would not break that out into two paths.  Instead, we show the EPC tagged with each edge it supports. 

So, this is expected behavior for now pre-september.  If we want to discuss after that can be done.  I would snooze this one for now though.

**Comment by sstemann** [comment]
i'm not seeing the mix of predicate directions in the evidence in the example GCK and Miglitol https://ui.transltr.io/main/results?l=GCK%20(Human)&i=NCBIGene:2645&t=2&r=0&q=29eaa20d-f688-4691-b585-1256dd84bb9a

![image](https://github.com/user-attachments/assets/3a1ac0ac-b998-40f8-a5e0-91eb086f4092)

my understanding is there are tickets both in feedback and with BTE to respond with the query predicate vs "affects" so I do not think that should be part of this ticket.

when i re-run alzheimer https://ui.test.transltr.io/main/results?l=Alzheimer%20Disease&i=MONDO:0004975&t=0&r=0&q=01559819-7340-4d0a-bb15-b23b4ec2f823, i'm not seeing paths with Genetic Association (when i free text Search "genetic" or in the examples posted above so I feel like this ticket should be closed until a specific issue lumped in here surfaces again.  

![image](https://github.com/user-attachments/assets/328bc840-8ec1-4b43-820e-38eb3358b5f6)
![image](https://github.com/user-attachments/assets/f1c45660-7d60-4627-9b34-c72ebeda60c8)
