### ISSUE TITLE
duplicate node in graph views

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#361]
https://ui.test.transltr.io/results?l=Agoraphobia&t=0&q=2d8831d4-413b-408d-a6e5-4a40d3d46676

In all the graph views, "Cyclic AMP" appears twice, though both instances appear to link to the same path.

![Screenshot 2023-06-17 at 11 41 35](https://github.com/NCATSTranslator/Feedback/assets/3977332/c4b9607f-b9e9-4c3d-a2b4-39daa4f1c5f6)

**Comment by Genomewide** [comment]
Do these have different curies?

**Comment by Genomewide** [comment]
The one closer to the bottom does link back to a path either:

![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/a27e19ad-fc3d-46c3-a685-6f73dcce1e44)

**Comment by gglusman** [comment]
Indeed, just noticed that. Can't really say for sure if it did when I first encountered this last week.
Anything one can do with the 'ghost' path directly from the graph?

**Comment by dnsmith124** [comment]
I've certainly never seen this 'ghost' path issue before, I'm looking into it to figure out what may have caused it
