### ISSUE TITLE
what counts as a 'drug' (that may treat)

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#364]
https://ui.test.transltr.io/results?l=Mesothelioma&t=0&q=e1aeeb1f-f0cc-4637-ae68-bc74336573d3

What drugs may treat mesothelioma? The 7th result, with score 99.2 and ultimately coming from semmeddb, tells us that "Matrix Attachment Regions cause increased activity or abundance of Transgenes which cause Mesothelioma".

The mouseover popup shows that Matrix Attachment Regions (MARs) are a 'chemical entity' and links to https://id.nlm.nih.gov/mesh/D045170.html
Does it make sense to offer MARs as a 'drug' that 'may treat' the disease? They are segments of the genome that also perform a structural function.

Also - the 'transgenes' bit is perhaps too generic, and the statement that transgenes cause mesothelioma appears to be a misparsing of the literature.

**Comment by sierra-moxon** [comment]
@andrewsu - can you tell if this result "goes away" if we either limit PMID count or apply our d/r exclusion rules?

**Comment by andrewsu** [comment]
### pmid_count
`MAR - STIMULATES - Transgenes` is supported by 22 unique PMIDs: https://biothings.ncats.io/semmeddb/query?q=object.umls:C0282641%20AND%20subject.umls:C1257994%20AND%20predicate:STIMULATES

`Transgenes - CAUSES - Mesothelioma` is supported by 2 unique PMIDs: https://biothings.ncats.io/semmeddb/query?q=object.umls:C0025500%20AND%20subject.umls:C0282641%20AND%20predicate:CAUSES

**Conclusion**: a filter for `pmid_count > 2` would have filtered out the second edge in this support graph and removed MAR as a result

### d/r constraints

MAR has semantic type `bacs`
Transgenes has semantic type `gngm`
Mesothelioma has semantic type `neop`

All of the following are allowed according to the current [D/R curation spreadsheet](https://docs.google.com/spreadsheets/d/1c1gx0Jgm9rJUOXcQhBtZgvx50Cvz1-jh0DdGtg1zcd8/edit#gid=2099428392): `bacs - STIMULATES - *` `* - STIMULATES - gngm` `gngm - CAUSES - *` ` * - CAUSES - neop`

**Conclusion**: the D/R filters would not have affected MAR as a result for this query
