### ISSUE TITLE
consolidate SEMMEDDB d/r exclusion work into one consumable format

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#369]
Combine domain and range and category excluded spreadsheets into one consumable format.

Columns:
SEMMED SPO, category restriction annotation, d exclude annotation, r exclude annotation, resulting exclusion annotation, notes

If d/r conflict - go with the stronger exclusion number.

**Comment by sierra-moxon** [comment]
https://docs.google.com/spreadsheets/d/1c1gx0Jgm9rJUOXcQhBtZgvx50Cvz1-jh0DdGtg1zcd8/edit#gid=2099428392

**Comment by sierra-moxon** [comment]
output fields for new consolidated standard: https://docs.google.com/spreadsheets/d/1c1gx0Jgm9rJUOXcQhBtZgvx50Cvz1-jh0DdGtg1zcd8/edit#gid=2034260640

**Comment by andrewsu** [comment]
Based on discussion on a more recent Friday SemMedDB call and a [brief exchange on slack among consumers of this file](https://ncatstranslator.slack.com/archives/C05DPKD8QJY/p1688152813726889), the new proposed file format is [here](https://docs.google.com/spreadsheets/d/1c1gx0Jgm9rJUOXcQhBtZgvx50Cvz1-jh0DdGtg1zcd8/edit#gid=1690403935):


| SEMMEDDB Subject Code	| SEMMEDDB Subject T code	| SEMMEDDB Predicate	| SEMMEDDB Object Code	| SEMMEDDB Object T code| 
|  - |  - | - |  - |  - | 
| chem	| T103	| *	| *	| *| 
| *	| *	| *	| chem	| T103| 
| hlca	| TXXX	| COEXISTS_WITH	| *	| *| 
| *	| *	| AFFECTS	| humn	| TXXX| 
| aapp	| TXXX	| ADMINISTERED_TO	| famg	| TXXX|

**Comment by sierra-moxon** [comment]
@andrewsu - happy to fix as needed (only exclusion at the moment is the "Metaedge exclusion" lines, but will add). 

PR in biolink to add the new exclude list as YAML:
https://github.com/biolink/biolink-model/pull/1356

file example:
https://github.com/biolink/biolink-model/blob/990a7f25aaa49a3160b7a71b65c308c1745e64b4/semmed-exclude-list.yaml

TSV version for review: 
https://docs.google.com/spreadsheets/d/1c1gx0Jgm9rJUOXcQhBtZgvx50Cvz1-jh0DdGtg1zcd8/edit#gid=730479755

**Comment by ecwood** [comment]
That format looks good to me!

**Comment by sierra-moxon** [comment]
I think this ticket is out of Biolink hands now, and in the hands of implementors of the exclude list.

**Comment by ecwood** [comment]
We have implemented into `KG2.8.4pre` and are working as fast as possible to roll it out before the August 18 freeze.

**Comment by colleenXu** [comment]
[Done](https://github.com/biothings/biothings_explorer/issues/669#issuecomment-1668738570). 

I'll note that Service Provider is still doing some custom behavior ([collapsed section of this post](https://github.com/biothings/biothings_explorer/issues/669#issuecomment-1669117440)). So the d/r exclusions are not the only kind of SEMMEDDB processing that is done for our BioThings-SEMMEDDB-API-based KP...

**Comment by saramsey** [comment]
This has been rolled out to `kg2.test.transltr.io` and `kg2.ci.transltr.io`. On track to roll out to `kg2.transltr.io` by 8/22 or 8/23, depending on timeline of CAB approval.

**Comment by saramsey** [comment]
it was rolled out to kg2.transltr.io on 8/22 or so. Can we close it out?

**Comment by bill-baumgartner** [comment]
Closing this issue as it seems like it has been completed based on reading through the comments. Although it had a TMKP label, I don't think it involves TMKP, so I have removed that as well.
