### ISSUE TITLE
FDA Approved Filter

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#372]
I think these "levels" are actually Clinical Trial levels and not FDA Approval Levels.  I'm not sure if we need to discuss with @vdancik or maybe we can pull in someone from the FDA (Tyler Peryea) but my understanding is that FDA has marketing categories[ (NDA, ANDA, etc) ](https://www.fda.gov/industry/structured-product-labeling-resources/marketing-category).  

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/fdf8ee45-f3f3-47ea-be79-e72e507ba56b)

As an NIH site, we should not be calculating FDA approval based on anything other than FDA guidance.  There are some resources hosted by FDA:  https://www.accessdata.fda.gov/scripts/cder/ob/index.cfm or another view:  https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=browseByLetter.page&productLetter=D&ai=0

https://www.fda.gov/drugs/development-approval-process-drugs/drug-approvals-and-databases

**Comment by andrewsu** [comment]
I think one challenge we've always had working on the FDA sources directly is the difficulty in finding identifiers that bridge to other databases. So, for example, from the link you provided, we see `imatinib mesylate` has many ANDA IDs, and those appear to be the _only_ structured IDs in those records.

![image](https://github.com/NCATSTranslator/Feedback/assets/2635409/1f28f1ff-5118-4839-aacd-f38079a9f70e)

I'm not aware of other databases that incorporate mappings to ANDA, which is why we end up relying on mappings from ChEMBL and DrugCentral. (I wish those resources were more transparent about how they do their mappings!) Anyone else have better strategies here?

**Comment by sandrine-m** [comment]
FDA labels have changed lately (on CI):
<img width="174" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/31d72f9a-d501-4497-a227-7f76c9fabd86">
They appear to be better now (given what is available to us from sources already provided). I can look into it further if that is still necessary.

**Comment by sierra-moxon** [comment]
from TAQA:
this is still being worked on in the UI.  
phase 1,2,3 being separated is valuable

**Comment by Genomewide** [comment]
I found these as possible links to connect. Does this help?

RxNorm has links to FDA [MTHSPL](https://www.nlm.nih.gov/research/umls/rxnorm/sourcereleasedocs/mthspl.html)
https://www.nlm.nih.gov/research/umls/rxnorm/docs/techdoc.html

![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/77385bca-d027-4eb9-a42b-863fd2506917)


![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/41e9993e-c60d-4f9f-9a81-2169885da58c)

The RXCUI is searchable directly on the FDA API
https://www.nlm.nih.gov/research/umls/rxnorm/sourcereleasedocs/mthspl.html

![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/4fe80912-c31a-4b23-a131-01db37ccd357)


also UNII 
![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/c745f9ee-91e4-47b0-bb17-ff3bc0da83e7)

**Comment by sierra-moxon** [comment]
@Genomewide - not sure what to do with this ticket; is it for "Fall" milestone? :)

**Comment by sstemann** [comment]
@Genomewide the status report says this is done, but i'm not sure based on the discussion on this ticket if there is something else to do?

**Comment by Genomewide** [comment]
Yes, I will close this. The facets are tested and deployed. Closing this.
