### ISSUE TITLE
Reduce amount of results by drug class

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#375]
Issue created from feedback on slack channels O&O and UCWG by @Rosinaweber :
I have been looking into some example queries and my hypothesis is that users will not like the volume of results when so many of them are small variations. Our users are scientists that want to know what is established and what is not. Looking at 200 results where entire pages are covered by, for example, variations of steroids or triptans, would not make for a good user experience.
In the 'drugs that treat migraines' query, the first result reads like a category, namely, anticonvulsants but there on the second page there is Topiramate, which is an anticonvulsant. (also posting this to O&O)

**Comment by dkoslicki** [comment]
After the [Drug conflator](https://github.com/RTXteam/DrugConflator) is finished, everything that can be will be mapped to RxNorm, so this should be relatively straight forward to implement from a technical perspective. Then it just depends on who implements it where

**Comment by sierra-moxon** [comment]
@dkoslicki - can we assign this to you to keep us in the loop about the status of [Drug conflator](https://github.com/RTXteam/DrugConflator)?

**Comment by gaurav** [comment]
The drug conflator has now been deployed to dev instances (here are some [conflated identifiers on NodeNorm Dev](https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=UMLS%3AC0691824&curie=UMLS%3AC0981379&curie=UMLS%3AC0358131&curie=UMLS%3AC0792229&conflate=false&drug_chemical_conflate=true&description=false) versus [non-conflated identifiers](https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=UMLS%3AC0691824&curie=UMLS%3AC0981379&curie=UMLS%3AC0358131&curie=UMLS%3AC0792229&conflate=false&drug_chemical_conflate=false&description=false)), but we still need to fix a few more bugs before we can get these fixes into CI. We can retest this once that's done.

**Comment by pg427** [comment]
Just wanted to mention, the merged response from the ARS for a query " What drugs treat Migraine Disorder?" is having repeated results. 

Merged Response PK: 05809596-9252-4253-829b-4efbde9b527a
Environment: CI

Result 78 and 198 (Caffeine) are listed separately but correspond to the same chemical ID. Attached below is an image for reference.

![Result Repetition - Image 1](https://github.com/NCATSTranslator/Feedback/assets/58840680/efe07291-bccd-4578-8c64-f0ea3cbf13e3)
![Result Repetition - Image 2](https://github.com/NCATSTranslator/Feedback/assets/58840680/1fcd2434-421b-427a-b025-dd6733af3d5c)

**Comment by gaurav** [comment]
Some updates:
- Everything that can be mapped to RXCUIs should be mapped to RXCUIs now -- although bear in mind that we're only combining based on "active ingredient", so there are potentially other mappings we could pull in if that would be useful.
- I think we're doing a better job now on not returning general categories as a single result (i.e. returning both "anticonvulsants" and "Topiramate"). If not, we do have the answer blocklist, but if this is a widespread issue we could look at a more general solution.
- The facets in the UI should make it easier to include or exclude an entire class of chemical in the results.

What is the best way of retesting this? Is this something we could include in the Translator Test Harness?

**Comment by sstemann** [comment]
I propose this is actually part of the O&O WG work on ATC Classfication with the UI team.  

I'm not seeing Caffeine twice now, so I feel like that part of the ticket can be closed.  

https://ui.transltr.io/main/results?l=Migraine%20Disorder&i=MONDO:0005277&t=0&r=0&q=0fa38d96-d660-4bb3-952d-038ddd4eece8

https://ui.test.transltr.io/main/results?l=Migraine%20Disorder&i=MONDO:0005277&t=0&r=0&q=a40a9a95-c69d-4036-9127-166f9ae390ea

while I can't filter on anticonvulsant, i can filter on Central Nervous System, or other Chebi role.

![image](https://github.com/user-attachments/assets/76416c96-7670-46d2-b3c3-01e05cedde77)

**Comment by sstemann** [comment]
i'm closing this specific ticket.  i think #149 and the other tickets related to grouping/ATC are open
