### ISSUE TITLE
Fully semantically valid biolink 3.5.0 + TRAPI 1.4.0 from all actors

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#379]
Check each of these off when the validation is passing (for example, [this test shows an arax interface with red `x's` that show validation issues ](https://arax.test.transltr.io/?r=e4420d32-65c1-4b43-9cb9-ff55564978e9)) for your resource. 
- [ ] Expander
- [x] Exploring
- [ ] imProve
- [ ] Ranking
- [ ] Unsecret
- [ ] Clinical Data Svcs
- [ ] Connection Hypo
- [ ] Exposures (ICEES KG)
- [ ] Exposures (CAM)
- [ ] Genetics
- [x] MolePro
- [ ] Multiomics
- [x] Service
- [ ] RTX-KG2
- [ ] Text Mining / Service
- [ ] Text Mining Cooccurrence
- [ ] MediKanren graph
- [ ] SPOKE

**Comment by codewarrior2000** [comment]
What is implication of checking off for "Fully semantically valid biolink 3.5.0 + TRAPI 1.4.0 from all actors"?
Do we just check off if that given example has no red X for our actor?
Or is there a set of standard tests on ARAX that we should be running before we can check off?
Should we be continuously testing and then uncheck, if at a later time, validation doesn't pass?

**Comment by edeutsch** [comment]
I have updated the ARAX GUI to use version 3.6.5 of the TRAPI validator and Biolink 3.5.0. Therefore all displayed validation is against our target.

There is now also a distinction between critical errors (red X) and ordinary errors (orange !)
![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/85ce8bed-cc37-41ac-9634-8138c79eacfd)

Perhaps this is useful for reaching our goals.
https://arax.ci.transltr.io/?r=704b6fac-c47c-420e-b6e5-8be46ea9bf35

**Comment by colleenXu** [comment]
I think the Exploring / Service team tools (BTE / Service Provider TRAPI) have [almost reached this goal](https://github.com/biothings/biothings_explorer/issues/587#issuecomment-1645114233). 

The current (as-of late last Friday) orange errors + warnings are being addressed with changes to other tools:
* There are merged biolink-model PRs to address the orange errors and some warnings:
    * https://github.com/biolink/biolink-model/pull/1362
    * https://github.com/biolink/biolink-model/pull/1364
* There are [ongoing Slack discussions](https://ncatstranslator.slack.com/archives/C0156TX0VB2/p1689968072363309) on [one warning](https://ncatstranslator.slack.com/archives/C0156TX0VB2/p1689955201272839: ChemicalEntity and CHEMBL.COMPOUND KG Nodes). 

So...we may not show up as "passing validation" until these changes are fully deployed. I'm not sure of everything that's involved in this deployment (biolink-model release? -> reasoner-validator / biolink-model toolkit updates? -> ARAX UI update? and maybe BTE/Service Provider tools need to update which biolink-model version they advertise using?)

**Comment by sierra-moxon** [comment]
We will need a BMT release as well.  I’d like to see if there are more attributes that need to be added to the model (as people go through the validation warnings) before doing that.  For example, will a property for “semmed novelty score” need to be added?

**Comment by andrewsu** [comment]
>will a property for “semmed novelty score” need to be added?

I do not think this is necessary -- I think the plan is to do filtering at ETL/query time, rather than passing this info back to the user.

**Comment by colleenXu** [comment]
Going to check us off as "done", since we show up with a "green check" in [ARAX CI - which is using reasoner-validator 3.8.0 configured to validate against Biolink model 3.5.3](https://github.com/biothings/biothings_explorer/issues/587#issuecomment-1670688782) (but may have TRAPI validation warnings sometimes), based on two [quick](https://github.com/biothings/biothings_explorer/issues/587#issuecomment-1670127077) [checks](https://github.com/biothings/biothings_explorer/issues/587#issuecomment-1672313174).

Regarding Multiomics + Text-Mining KPs @gglusman @edgargaticaCU, careful testing of the TRAPI responses for your KP should allow to see if your edge-attributes / sources info (which may be different for different x-bte operations / data) passes TRAPI validation. If you feel confident that all your KPs pass, then you can check it off.

**Comment by codewarrior2000** [comment]
All righty!
On August 11, 2023 at 1145 EDT, MolePro is also now showing green status in the ARAX GUI (the latest validator version 3.8.0 configured to validate against Biolink model 3.5.3 )

**Comment by sstemann** [comment]
@sierra-moxon what say you on this? are we still working on it?

**Comment by sstemann** [comment]
agree with @codewarrior2000
