### ISSUE TITLE
In the results section of a search, the "Evidence" column header has what appears to be an "sort arrow" but clicking it does not change the result order

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#38]
## Steps to reproduce:
Searched for Fanconi Anemia in disease search

**Comment by sstemann** [comment]
@Genomewide this looks like it's working in ui.transltr.io/results?q=a9efb05f-0625-4f8f-b5dd-f3c82a986fa4 I think we should consider closing it

**Comment by sierra-moxon** [comment]
closing for now; please reopen if I got this wrong :)
