### ISSUE TITLE
Would be nice to more easily find my result. "Immunoglobulins" had a score of 16. But there were 784 entires. I had to click through a few pages at a time to find it in context. Note: I did not want it out of context, which I can get by filtering.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#383]
## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20230703203421411980.jpeg)

**Comment by Genomewide** [comment]
What would this feature look like? Instead of a filter, it would take you to the page it was on?

**Comment by gglusman** [comment]
I'm not sure what 'in context' means in, well, this context, as there is not really a relationship between results that are close to each other down the list.
That said, perhaps if when filtering the result indicated it's ranked 662, that might help retain that sense of 'context'.

**Comment by Genomewide** [comment]
I am pretty sure that is possible, but it could complicated if resorted for different preferences and the rank changed.
We can think about how to test this, but I agree with Gwen. I would like to be sure that I understand what the context means before acting on this.

**Comment by sstemann** [comment]
we never got the context of this report.  closing
