### ISSUE TITLE
Too generic : "Small molecule downregulates [gene x]"

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#384]
PK: [e27550bb-e389-4e92-a1b3-0b7e9273cba3](https://ui.test.transltr.io/results?l=DDX3Y&t=2&q=e27550bb-e389-4e92-a1b3-0b7e9273cba3)
UI test environment
MVP2/downregulates

Offensive edges (very top ones): 
"dna double stranded downregulates DDX3Y"
"Small molecule downregulates [gene x]"

<img width="946" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/dc251c92-4a3d-4582-aeef-35282f7dbd91">

Both are from BioThings Explorer

**Comment by sharatisrani** [comment]
This is part of the "category too generic" translator-wide issue.  Jason, if I am mistaken that you are handling that meta-issue, let us know.

**Comment by sierra-moxon** [comment]
closing as fixed.
