### ISSUE TITLE
filter by string : clear out multiple paths with same intermediary nodes

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#385]

**Comment by sandrine-m** [comment]
Sumitted by @sandrine-m 
When studying putative mechanisms to downregulate DDX3Y, I would like to:
 (1) group results by intermediary nodes and
 (2) filter by some of those.
<img width="323" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/b72941ee-e8ef-4426-adc1-142bfcb560a7">
In this example, I would like to be able to have fewer results :
- 1 involving DDX3X
- 1 implying EGR1...etc.
Ultimatively once I recognize all possible intermediary nodes, I'd like to filter out some based on a string filter.

**Comment by sandrine-m** [comment]
From 07/06/2023 DM call (focused on testing): grouping by intermediary node is a milestone post September

**Comment by sharatisrani** [comment]
I agree this would be a very useful feature, especially as we go forward towards the full drug discovery path (drug - gene - bioprocess - disease), and try to repurpose drugs. After our Fall 2022 SME discussions. UI had it in its list of possible filters/facets, not sure about the timing.

**Comment by Genomewide** [comment]
@sandrine-m  Would the text filter not work for this? Trying to understand. I am reviewing all facet tickets.

**Comment by sandrine-m** [comment]
@Genomewide not really in that case, if I remember well. DDX3X is often co-cited with DDX3Y for some reasons I am not interested in. My issues are:
-  I can search for DDX3X in the text search field but not exclude it
- DDX3X is often co-cited with DDX3Y which makes the search filed not very useful

**Comment by dnsmith124** [comment]
@sstemann the text filter search supports this, it just requires the user to click the exclude button instead of clicking the include button or pressing the enter key: 

![Screenshot 2024-08-08 at 10 39 57 AM](https://github.com/user-attachments/assets/01ef5ee9-01b6-4710-915d-911d013a8ed5)

This feature must not have been implemented yet back when this ticket was first created. 

Closing!
