### ISSUE TITLE
CAS != CAS

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#386]
https://ui.test.transltr.io/results?l=Childhood%20Apraxia%20Of%20Speech&t=0&q=5ef4556f-650d-4400-8263-6ab11b3f1615

I got intrigued by the assertion that antifungals (voriconazole, fluconazole) may treat Childhood Apraxia of Speech (CAS), but it seems to be a text-mining error caused by caspofungin also being shortened CAS:
![Screenshot 2023-07-05 at 10 47 27 AM](https://github.com/NCATSTranslator/Feedback/assets/3977332/b50dfceb-5652-4930-8dcd-ee610f8db9ad)

**Comment by andrewsu** [comment]
This appears to be from TMKP through robokop https://arax.ci.transltr.io/?r=8134162c-0eee-463f-892a-9f1cb3ecb6a2.  Assigning to @bill-baumgartner

**Comment by gglusman** [comment]
Same query, another result offers that Atorvastatin (and various other statins) treat CAS. Except here CAS means "Carotid Artery Stenting" in one paper, "Carotid Atherosclerotic Plaques" in another, "Coronary Artery Syndromes" in a third, "Carotid Artery Stenosis" in a fourth, and "Carotid Atherosclerosis" in the fifth.

**Comment by gglusman** [comment]
Same query, result = prednisolone, CAS here means "clinical activity score".

**Comment by sierra-moxon** [comment]
@bill-baumgartner - looks like we can close this as fixed now - do you concur? :)
