### ISSUE TITLE
find previous query automatically from history

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#387]
@MarkDWilliams @ShervinAbd92 Just an idea (not sure it will apply depending on caching requirements, and I do not think this is a priority at all): when selecting a MPVx with a given entity value, it could be nice if it could reload automatically a previous search we did (in case we forgot) or go get a relatively recent previous query made by another user to gain some time. I know the system is completely federated on some aspects (so may not be reproducible) but I know there have been efforts from SRI team that could leverage that feature and speed up performance.

**Comment by sandrine-m** [comment]
This idea came into mind while testing the ui tryong to reproduce results where PK was missing on huge diseases (Diabetes miletus, Alzheimer disease.... etc).
A fancier alternative would be to cache in function of search node degree/cardinality, run the query in parallel to improve previous run results.

**Comment by edeutsch** [comment]
You might find this ARAX GUI feature handy:
The 10 most recent queries to CI ARS:
https://arax.ci.transltr.io/?latest=10&from=ars.ci.transltr.io

The 10 most recent TEST queries to TEST ARS:
https://arax.ci.transltr.io/?latest=10&from=ars.test.transltr.io

Or you can access via the
![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/06f6fca5-8bae-463d-aa86-87e23052d782)
icon on any instance of ARAX (except production which is still ancient code)

**Comment by sandrine-m** [comment]
Yes! Thank you! I find really useful (as a user)! 
Would it be a good feature request for the general UI?

**Comment by edeutsch** [comment]
If you're asking me, I'm thinking that it is useful for our developers' GUI (ARAX GUI) but not so much for the general UI. but I don't feel strongly and maybe others disagree..

**Comment by sstemann** [comment]
@sandrine-m so in the UI, i go to search Castleman, and it says - you have already searched for this would you like to reload those results? based on my search history?

**Comment by sandrine-m** [comment]
Yes, thank you for coming back to fix. this issue can be closed! :)
