### ISSUE TITLE
filter to the type of underlying data

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#389]
This issue has been split from Type 2 diabetes drug results are unsatisfying #261.
@flannick : "_I would also like to be able to filter to the type of underlying data; e.g. "genetics" or "clinical" or "molecular". Ultimately everything in between the data and the result (the ontologies, the reasoning, the scoring) are less trustworthy than the data. We should surface the data more and also allow filtering or query tuning based on it_"

**Comment by dnsmith124** [comment]
@Genomewide et. al, is the type of data underlying a result something that is explicitly provided to the UI, or would we have to intuit that from the characteristics of a result?

**Comment by sharatisrani** [comment]
This is more a UI feature request than a scoring/ordering issue, and after talking to SMEs in Fall 2022, it was put in the list of future UI enhancements as "Node Type"

**Comment by Genomewide** [comment]
We are working on this in the facets.  V1 is the ability to select results with a category of node. Possibly, the ability to select edges or pattern in the future. The easy version is to have individual node categories or edges as facets.  Although the ne edges with qualifiers will complicate it.  This is a post September issue.

**Comment by gprice1129** [comment]
We need to break this ticket down into a concrete request. Right now it is too open ended, there is no definition for success.

**Comment by Genomewide** [comment]
Agree. If we don't get more feedback form @flannick in a week we can close this.

**Comment by gprice1129** [comment]
Closing. Re-open if you feel strongly this isn't complete.
