### ISSUE TITLE
Linkouts for chebi roles?

### ISSUE THREAD

**Issue by cbizon** [NCATSTranslator/Feedback#397]
![image](https://github.com/NCATSTranslator/Feedback/assets/10744350/3bccff62-455c-4d6b-9f5b-57d83b92d848)

These are very cool.  They all have CHEBI identifiers, so it would be nice to link out to them on the chebi site so that you could see the definitions.  I also wonder about ordering them?  Most to least common?

**Comment by sandrine-m** [comment]
Would the attribute server/BTE annotator be able to provide ChEBI identifiers links?

**Comment by sandrine-m** [comment]
@cbizon Do you have a pk available for this screenshot (for testing purposes)?

**Comment by newgene** [comment]
Service Provider already provides a CHEBI API, recently updated too, with all CHEBI terms. For example:

https://biothings.ncats.io/chebi/query?q=name:antioxidant&fields=name,def,subset,synonym

will help to find the matching CHEBI ID given a name term. You can do a POST with batch query if useful.

**Comment by sandrine-m** [comment]
Thank you @newgene ! 
If I am understanding correctly, your suggestion to build the link is :
(1) get ID list from parsing JSON from 
POST `https://biothings.ncats.io/chebi/query?q=name:` [ChEBI role] `&fields=name,def,subset;synonym`
(2) build links from:
`https://www.ebi.ac.uk/chebi/searchId.do?chebiId=` [UNPREFIXED ID]?
There may be a multiple mapping for the links (as I see on the antioxidant example), do you have recommendation of best ways to handle that? (shall we take all links or only some?, is the first ID the preferred one?, ...etc.).
TIA!

**Comment by newgene** [comment]
@sandrine-m by default, the `name` field is indexed a full-text field, so you cannot get the exact matches back, but usually the exact matches should rank higher. We can change how we index the data, so that you can do the exact match queries. However, in this use case, an easy poster-query filter should serve the purpose. 

The batch query via POST I mentioned can also be done easily via the `biothings_client` Python package:

```
# "pip install biothings_client" first
import biothings_client
chebi = biothings_client.get_client(url="https://biothings.ncats.io/chebi")
# sends a batch query for a list of names to the CHEBI API
res = chebi.querymany(["antioxidant", "antimicrobial agent"], scopes="name", fields="name")
# filter for those with the exact name matches
res_filtered = [x for x in res if x["query"].lower()==x["name"].lower()]
```

This should let you query any number of names at once. CHEBI id is returned as the `_id` field in the results, then you can build the links as you suggested.

**Comment by sandrine-m** [comment]
Thank you so much @newgene !

**Comment by Genomewide** [comment]
Is the request to have each name be a link? Not a pop up or something? I am pretty sure we can do this especially if there is a structured link base for each ID!

**Comment by sandrine-m** [comment]
@Genomewide yes, that was my understanding from @cbizon as a nice to have UI feature.

**Comment by sierra-moxon** [comment]
@dnsmith124 @Genomewide - is this a priority or shall we close it as "won't do"?

**Comment by dnsmith124** [comment]
This has actually already been implemented! Closing.
