### ISSUE TITLE
Results for Genistein show Iron "treats" as well as "Causes" Alzheimer's disease

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#4]

**Comment by nishad-instacart** [comment]
For those curious about the URL: this was reported while running a local version of the UI on my laptop. The localhost URL will not appear in actual use by real users.

**Comment by sstemann** [comment]
cannot replicate in Test.  currently 3 ARAs response with this result as a lookup in one direction [Test UI](https://arax.ncats.io/?r=5e2fb528-5360-4b8d-9cde-a4ab2f8932d1) i checked the individual ARAs via the ARAX GUI ([e2fb528-5360-4b8d-9cde-a4ab2f8932d1](https://arax.ncats.io/?r=5e2fb528-5360-4b8d-9cde-a4ab2f8932d1))

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/bef75232-723e-4c9a-a2d2-9bd682c076b5)
