### ISSUE TITLE
Autocomplete functionality on the home page limits autocomplete results without an indication that there are more matches with more typing. 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#40]
## Steps to reproduce:
Search term: Hereditary Chronic Pancreatitis

**Comment by sierra-moxon** [comment]
The link in this ticket points to a search box filled in with "X-linked Adrenoleukodystrophy" 
When I use the search autocomplete, the `-` in `X-linked` causes some inconsistent suggestion behavior.  

For example:
- **type `x` or `X`** - no autocomplete results

- **type `x-li` or `x-l` or `X-li` or `X-l`** - lots of autocomplete results:

<img width="646" alt="Screen Shot 2022-11-17 at 2 48 10 PM" src="https://user-images.githubusercontent.com/4561292/202576584-43ad6ae0-ac90-4583-ba6d-d12e897564ff.png">

- **type `x-lin` or `X-lin`** - only one autocomplete result: 
<img width="782" alt="Screen Shot 2022-11-17 at 2 46 02 PM" src="https://user-images.githubusercontent.com/4561292/202576280-a5e3360b-ea30-4cc8-b483-dfb7ca2dd6b8.png">



- **type `x linked`** - lots of results 
<img width="727" alt="Screen Shot 2022-11-17 at 2 45 20 PM" src="https://user-images.githubusercontent.com/4561292/202576165-cc6558d6-9c24-4e7a-9fb2-523d0322c633.png">

**Comment by sierra-moxon** [comment]
I also see unexpected results when I try `Hereditary Chronic Pancreatitis` in the autocomplete suggestions.
for example:

- type `Hereditary` or `Hereditary ` (note the space) or `Hereditary C` (note the space) - neither shows `Hereditary Chronic Pancreatitis` as a autocomplete suggestion.

to get back the disease of interest in the autocomplete, you have to type this at a minimum: `Hereditary Ch`

<img width="616" alt="Screen Shot 2022-11-17 at 2 50 54 PM" src="https://user-images.githubusercontent.com/4561292/202576951-54a2ee8e-adda-49bc-8748-3c6f54281e92.png">

**Comment by sierra-moxon** [comment]
This ticket was split into two actionable tickets:
- handing dashes in autocomplete input #42 
- more autocomplete results should be shown, or some indication that there are more results should be conveyed to the user without them continuing to type #43

closing for now as the work is in those tickets above.
