### ISSUE TITLE
Implement visual indicator for edges based on text-mined resources

### ISSUE THREAD

**Issue by dnsmith124** [NCATSTranslator/Feedback#400]
UI team intends to make edges based on text-mined resources visually distinct from other edges. This may take the form of dotted lines for text-mined edges and solid lines for others. 

Other questions to resolve:
- how to handle compressed edges that contain both types
- how to express to the user what the difference is between each type
- how to express which indicator corresponds to which type

**Comment by sierra-moxon** [comment]
@dnsmith124 - is this still on the radar for September, or is it for Fall? :)

**Comment by dnsmith124** [comment]
Right now it's looking like Fall.

**Comment by sierra-moxon** [comment]
closing as complete
