### ISSUE TITLE
all scores are 0 on CI

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#402]
## Steps to reproduce:
on CI
MVP1 on Hereditary sensory and autonomic neuropathy type 4

**Comment by sandrine-m** [comment]
Same happens on [T2D query](https://ui.ci.transltr.io/results?l=Type%202%20Diabetes%20Mellitus&i=MONDO:0005148&t=0&q=a40a11c7-4603-4fd9-a6f6-82ccffe167e5) as another example.

**Comment by sandrine-m** [comment]
submitted by @sandrine-m
