### ISSUE TITLE
tablet/desktop warning when used on PC with split screen

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#406]
## Steps to reproduce:
ON PC windows 11 machine
going to the UI side
splitting my screen
submitted by @sandrine-m

**Comment by sandrine-m** [comment]
<img width="472" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/3a0f9b50-423b-4e74-a349-516803411e29">
I suspect trigger based on size of window is creating this. It is a bit embarrassing that the website assumes I am on my phone while I just work on a split screen (which is by the way, way bigger than a tablet, even when splitted :) )

**Comment by sstemann** [comment]
@sandrine-m i get this a lot too when I'm using just my laptop screen but trying to split it in half.  i can zoom out on the browser and get this message to go away and show me the results but i agree @Genomewide @desiyopp we need some better language here.

**Comment by dnsmith124** [comment]
I've updated the language to the following in the meantime, thoughts @sstemann? (work is done, but again, waiting on a deployment)

```
Translator is intended to be used in a widescreen view due to the complex nature of our data and interactions.
If you're on a desktop or laptop, try increasing the size of your browser window.

If you're using a tablet, try rotating it into a landscape orientation.

If you're on mobile, please open the site on a device with a larger screen in order to experience all Translator has to offer. 
```
