### ISSUE TITLE
Normalize Durapatite node from SemMedDB API

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#407]
## Steps to reproduce:
MVP1 on Hereditary Sensory And Autonomic Neuropathy Type 4
UI test (persisting on CI)
submitted by @sandrine-m

**Comment by sandrine-m** [comment]
Results on Durapatite (persisting on CI):
<img width="943" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/842a308a-d063-4028-8764-dd0730019f4b">
Coming from BioThings explorer
On [ARAX UI](https://arax.ci.transltr.io/?r=cb5e2c9e-e1fc-4f4a-a572-19aeb8e54ebf), Durapatite class is `biolink:device` with UMLS CURIE. Aux graph as EPC (I absolutely love it!)
<img width="1145" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/1694750b-9aa2-40cd-97de-dd921cc2dff8">

### ARAX synonyms
[ARAX synonym look up](https://arax.ci.transltr.io/?term=durapatite) normalizes Durapatite node

### Name resolver
Name resolver does resolve IDs for durapatite:
```
{
  "HMDB:HMDB0303433": [
    "Durapatite",
    "Ossopan",
    "Osprovit",
    "Osteogen",
    "Alveograf",
    "Calcitite",
    "Periograf",
    "Interpore200",
    "Interpore500",
    "Interpore-500",
    "Interpore 500",
    "Interpore 200",
    "Interpore-200",
    "Hydroxyapatite",
    "Hydroxylapatite",
    "Calcium hydroxyapatite",
    "Hydroxyapatite, calcium",
    "Calcium hydroxide phosphate",
    "Ossein hydroxyapatite compound",
    "Ossein-hydroxyapatite compound",
    "Calcium hydroxide phosphoric acid",
    "Pentacalcium hydroxide triphosphoric acid"
  ],
  "PUBCHEM.COMPOUND:14781": [
    "Durapatite",
    "DURAPATITE",
    "Hydroxyapatite",
    "TRIBASIC CALCIUM PHOSPHATE",
    "Pentacalcium tris(phosphate) hydroxide"
  ],
  "UMLS:C0115137": [
    "Durapatite",
    "durapatite",
    "Durapatite (substance)",
    "Durapatite-containing product",
    "Product containing durapatite (medicinal product)",
    "Hydroxyapatite",
    "hydroxyapatite",
    "Hydroxylapatite",
    "hydroxylapatite",
    "HA - Hydroxyapatite",
    "calcium hydroxyapatite",
    "Calcium hydroxyapatite",
    "Calcium Hydroxyapatite",
    "Hydroxyapatite, Calcium",
    "Calcium Hydroxide Phosphate",
    "HA - Calcium hydroxyapatite",
    "Hydroxylapatite (Ca5(OH)(PO4)3)",
    "Hydroxyapatite-containing product"
  ],
  "UMLS:C3215152": [
    "durapatite Pill"
  ],
  "UMLS:C1178788": [
    "durapatite 830 MG"
  ],
  "UMLS:C1253679": [
    "durapatite Oral Tablet"
  ],
  "UMLS:C3215151": [
    "durapatite Oral Product",
    "Durapatite-containing product in oral dose form",
    "Product containing durapatite in oral dose form (medicinal product form)",
    "Hydroxyapatite-containing product in oral dose form"
  ],
  "UMLS:C5191159": [
    "Durapatite only product",
    "Product containing only durapatite (medicinal product)",
    "Hydroxyapatite only product"
  ],
  "UMLS:C0357210": [
    "durapatite 830 MG Oral Tablet",
    "Durapatite 830 mg oral tablet",
    "Product containing precisely durapatite 830 milligram/1 each conventional release oral tablet (clinical drug)",
    "Hydroxyapatite 830mg tablet",
    "hydroxyapatite 830 MG Oral Tablet",
    "Hydroxyapatite 830 mg oral tablet"
  ],
  "UMLS:C0543074": [
    "Durapatite 3.32 g oral granules sachet",
    "Product containing precisely durapatite 3.32 gram/1 sachet conventional release oral granules (clinical drug)",
    "Hydroxyapat 3.32g/sach grans",
    "Hydroxyapatite 3.32g/sachet granules",
    "Hydroxyapatite 3.32 g oral granules sachet"
  ]
}
```

**Comment by sandrine-m** [comment]
@sierra-moxon from the [tree vizualization](http://tree-viz-biolink.herokuapp.com/categories), `biolink:device` is a separate branch than the `biolink:ChemicalEntity`, although as I understood from the current definition of `biolink:device` this class is encompassing some examples like _fluoride_ that are also `biolink:ChemicalEntity`. Isn't it the same issue as the _water_ treats cerebral palsy issue? where in this example water is used as a device and not as a chemical? 

As a user the issue reported here comes from the _confusion_ of the ChEBI role facet to be descriptive of the role they have in the responses whereas in reality the ChEBI role facet are displaying the roles the ChemicalEntity _could_ have.

**Comment by sierra-moxon** [comment]
@sandrine-m - thank you!  this makes a lot of sense.  Yeah, it just seems like the SEMMED category is too broadly defined for us to use as a mapping (if the result of that mapping is the inference that water treats CP or Durapatite treats a disease).  At SEMMED, `STY:T122` is made up of chemicals and devices and even other stuff like "Flake" which I am not sure of the category. :) There is probably some work to do in the reasoning/inference here as well...

**Comment by sandrine-m** [comment]
Should we move this to Milestone:Fall ?

**Comment by sstemann** [comment]
@sierra-moxon @sandrine-m i'm not seeing Durapatite or Filter "Object Type = Devices" in this specific query on Test (Which is Fugu)

https://ui.test.transltr.io/main/results?l=Hereditary%20Sensory%20And%20Autonomic%20Neuropathy%20Type%204&i=MONDO:0009746&t=0&r=0&q=d920258f-42e3-48f3-9a3d-44e284b26b63

or CI (which is Fugu+)

https://ui.ci.transltr.io/main/results?l=Hereditary%20Sensory%20And%20Autonomic%20Neuropathy%20Type%204&i=MONDO:0009746&t=0&r=0&q=ec95811c-66b2-4dea-be51-216a8c106086

I do see it in Prod  (which is Eel)  https://ui.transltr.io/main/results?l=Hereditary%20Sensory%20And%20Autonomic%20Neuropathy%20Type%204&i=MONDO:0009746&t=0&r=0&q=28ba7721-8ae5-46d2-9ae0-124b972180a5 

the related Biolink ticket is still open.  i dont know if this is "resolved" or if that result is no longer returned or if its an environmental difference issue?

**Comment by sierra-moxon** [comment]
yep, this went into the latest release of Biolink, and I know Colleen picked it up for BTE.
