### ISSUE TITLE
apparent reversed predicates in top answer for Ehlers-danlos Syndrome, Dermatosparaxis Type

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#408]
The first result for [Ehlers-danlos Syndrome, Dermatosparaxis Type](https://ui.test.transltr.io/results?l=Ehlers-danlos%20Syndrome%2C%20Dermatosparaxis%20Type&t=0&q=4a24ced8-2097-4322-abdd-299e1699afcb), is Triamcinolone acetonide.

Two of the paths have apparently reversed predicates:
1) 'steroids causes Marchiafava-Bignami Disease'
2) 'glucocorticoids causes Marchiafava-Bignami Disease' (curiously together with 'treats' and 'predisposes').
I suspect they are somehow reversed since I find in the literature successful treatment of MBD with corticosteroids.
They seem to come from semmeddb.

![Screenshot 2023-07-07 at 12 21 59 PM](https://github.com/NCATSTranslator/Feedback/assets/3977332/9b6f9fd8-1d5a-442e-ad77-e537a6d75cb6)

**Comment by sandrine-m** [comment]
confirmed SEMMED DB issue:
<img width="881" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/58ddc792-efe6-436d-9bfe-ccc12a888ecb">

**Comment by andrewsu** [comment]
back to the semmeddb issue for a moment, noting that with `pmid_count: 2`, the example above would be filtered out with the solution to #100 .

**Comment by sandrine-m** [comment]
post DM call:
@gglusman's concern is in co-occurrence of antonyms predicates in the same result

**Comment by cbizon** [comment]
I think that this answer is coming from ARAX.  @dkoslicki I think I understand how these paths get made, but would it be reasonable to apply some output filtering for "unreasonable" paths?  i.e. e.g. if the reinforcement algorithm provides a path saying a-causes-b, it's not great support for a-treats-b.

**Comment by dkoslicki** [comment]
I like that idea @cbizon !

@chunyuma Let's discuss when we meet next about the feasibility of adding a-causes-b as negative examples for xDTD and identify who in our lab might implement this.

**Comment by sierra-moxon** [comment]
@dkoslicki - from your last comment, this seems like a post-September fix, is that right?

**Comment by dkoslicki** [comment]
Yes @sierra-moxon , Post-September

**Comment by mbrush** [comment]
Interesting issue at many levels. This is something that the 'support metapath catalog' idea discussed at the September Relay should help to address systematically across ARAs/Translator (for more see [comment in ticket here](https://github.com/NCATSTranslator/Feedback/issues/566#issuecomment-1753402545)).

It also highlights a potential issue with the UI that I'm not sure has been pointed out yet - which is that the window that shows provenance (pubs and sources) for edges that include >1 predicate doesn't seem to show the provenance of all of the different collapsed predicates.  Making a separate ticket for this [here](https://github.com/NCATSTranslator/Feedback/issues/578).

**Comment by sstemann** [comment]
i can't replicate this specific example in Test or Prod, so I'm closing this for now

Prod:  https://ui.transltr.io/main/results?l=Ehlers-danlos%20Syndrome,%20Dermatosparaxis%20Type&i=MONDO:0009161&t=0&r=0&q=d03af0f0-1aaa-4b70-ac45-1e536753672b

Test:  https://ui.test.transltr.io/main/results?l=Ehlers-danlos%20Syndrome,%20Dermatosparaxis%20Type&i=MONDO:0009161&t=0&r=0&q=5c1f9b96-54c2-4f2a-aedc-7feed65ac188
