### ISSUE TITLE
Confusing (wrong?) directions of chained results (MVP2)

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#409]
Tested on: https://ui.test.transltr.io/ 

Query: What gene is upregulated by Caffeine? 
https://ui.test.transltr.io/results?l=Caffeine&t=3&q=f38de412-ba86-4466-a0e9-5df486ccbae1

Problems with results:

1. Some results are inconsistent with the question, for example the attached screenshot showing the 6 paths for the result Acat2. Notice the last path, "Acat2" -> has **decreased** activity or abundance caused by -> "Melk" -> has **increased** activity or abundance caused by "Caffeine".
So if Caffeine causes an increase in Melk, which in turn causes a decrease in Acat2, then Acat2 is NOT upregulated by caffeine, which was the question. 
2. Also, one would think that Melk (and the other intermediates in the 6 paths in the screenshot) would also be listed individually as results, as they are directly affected by Caffeine. But none of them are. 
3. 
![Screen Shot 2023-07-07 at 2 30 18 PM](https://github.com/NCATSTranslator/Feedback/assets/1442197/6d2e3747-58c1-496c-952f-36cefb0a17b2)

**Comment by sharatisrani** [comment]
O&O issue #29 is similar, and it's assigned to the Feedback repo also.

**Comment by cbizon** [comment]
I think that in Test this was coming from improving.  I just tried in ci, and it doesn't seem anybody is returning ACAT2.  Will continue to monitor for the time being.

**Comment by suihuang-ISB** [comment]
This is the old probem of a "negative status" {**Knockdown** or **knockout** or **LOF mutation**} of a gene X leading to **down** regulation of its downstream target gene Y.  Thus X actually is a positive regulator (stimulates) expression of Y.
Without the information of the "node status" {...} for X , it looks like X inhibits Y.
The additional attribute of the status (which in SPOKE is part of the edge attribute/qualifier) , which affects the direction of the "net predicate"  is lost in biolink. This is being discussed in the data modeling.
