### ISSUE TITLE
time outs on small molecule to named thing - this is one of several general performance issues 

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#41]
for architecture meeting (see related detail in #23)

**Comment by andrewsu** [comment]
From https://arax.ncats.io/?r=385f6c86-9c1f-48ee-a859-ea9aae336f46, it looks like only aragorn timed out on this query

![image](https://user-images.githubusercontent.com/2635409/205363271-7444a767-cdd5-449d-a27f-05280cef8a9c.png)

**Comment by cbizon** [comment]
Yep.  But I think we have general concerns about performance that we'd like to address globally.
