### ISSUE TITLE
Disease cross references should link to the MONDO PURL rather than MonarchInitiative

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#411]
Some MONDO ids give errors when I try to access their disease pages at [monarchinitiative.org](http://monarchinitiative.org/), e.g.: https://monarchinitiative.org/disease/MONDO:0100489 via the autocomplete suggestion link-out.  

<img width="1152" alt="Screen Shot 2023-07-11 at 8 53 14 AM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/25bdbca6-67e1-4f40-9724-48a107c8a8b3">

The disease nodes themselves (in the paths section) use the correct PURL and do not need to be changed. 

Ontologies in the OBO foundry (including MONDO) have a system of persistent URLs (PURLs) that we should take advantage of instead.  MONDO curators control the location of the redirect of these pURLs.

MONDO pURLs should be constructed like this: 
http://purl.obolibrary.org/obo/MONDO_$1

And currently, these cross-references take the user to OLS 4: e.g. https://www.ebi.ac.uk/ols4/ontologies/mondo/classes?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0000001

OLS4 is updated on each release of MONDO.  

Note: this solution was proposed by the Monarch team :)

**Comment by sierra-moxon** [comment]
@dnsmith124 - that link above seems to be working for me now, I get to:

<img width="1127" alt="Screen Shot 2023-08-08 at 4 20 22 PM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/1cef5f5a-46d9-473a-888d-c003f7db1e68">

It could be that OLS4 was having a temporary issue?

**Comment by dnsmith124** [comment]
Must have been a temporary issue, it's working for me now as well @sierra-moxon! I'll be updating the link generation for these this week.

**Comment by sstemann** [comment]
@sierra-moxon we believe this is working now, can you confirm?

from the UI, Niemann Pick Disease went to https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0001982
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/8b8e6fa4-9dbe-47cc-bad5-37e8ce2463d9)

**Comment by Genomewide** [comment]
I think this is done and am closing.
