### ISSUE TITLE
Typo in download/PK pop-up window

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#412]
This issue is to report a typo in the pop-up window that appears after hitting the download button to grab a PK. Message should read: "... after which your question will **need to be** run again" OR "... after which **time** your question will **need to be** run again".

![image](https://github.com/NCATSTranslator/Feedback/assets/26254388/dc38705a-d063-4582-8618-c5444e14455f)

**Comment by sstemann** [comment]
deployed to prod 9/6
