### ISSUE TITLE
Missing pubmed IDs - maybe?

### ISSUE THREAD

**Issue by Genomewide** [NCATSTranslator/Feedback#414]
This was done on CI and realized too late - if fixed then close this without checking with me. 
Where PubMed IDs are normally shown the array just has this ["PMID:"]
If this indicates that there are zero publications provided then the UI is handling this as expected.  However, it looks like something is off?

https://ui.ci.transltr.io/results?l=Familial%20Pityriasis%20Rubra%20Pilaris&i=MONDO:0008251&t=0&q=d4025549-f5bf-470b-8c44-19be43866441

There are a few edges that have similar issue.

                        "infores:rtx-kg2:UniProtKB:P15428-biolink:gene_associated_with_condition-MONDO:0006590-infores:disgenet": {
                            "object": "MONDO:0006590",
                            "sources": [
                                {
                                    "resource_id": "infores:disgenet",
                                    "resource_role": "primary_knowledge_source",
                                    "source_record_urls": null,
                                    "upstream_resource_ids": null
                                },
                                {
                                    "resource_id": "infores:rtx-kg2",
                                    "resource_role": "aggregator_knowledge_source",
                                    "source_record_urls": null,
                                    "upstream_resource_ids": [
                                        "infores:disgenet"
                                    ]
                                },
                                {
                                    "resource_id": "infores:arax",
                                    "resource_role": "aggregator_knowledge_source",
                                    "source_record_urls": null,
                                    "upstream_resource_ids": [
                                        "infores:rtx-kg2"
                                    ]
                                }
                            ],
                            "subject": "NCBIGene:3248",
                            "predicate": "biolink:gene_associated_with_condition",
                            "attributes": [
                                {
                                    "value": "2023-07-03 18:04:04",
                                    "value_url": null,
                                    "attributes": null,
                                    "description": null,
                                    "value_type_id": null,
                                    "attribute_source": null,
                                    "attribute_type_id": "metatype:Datetime",
                                    "original_attribute_name": "defined_datetime"
                                },
                                {
                                    "value": true,
                                    "value_url": null,
                                    "attributes": null,
                                    "description": "This edge was extracted from RTX-KG2.8.0.1c by ARAXInfer.",
                                    "value_type_id": "metatype:Boolean",
                                    "attribute_source": "infores:arax",
                                    "attribute_type_id": "EDAM-DATA:1772",
                                    "original_attribute_name": null
                                },
                                {
                                    "value": [
                                        "NCBIGene:3248---biolink:gene_associated_with_condition---UMLS:C4551675---DisGeNET:",
                                        "NCBIGene:3248---biolink:gene_associated_with_condition---UMLS:C0022596---DisGeNET:"
                                    ],
                                    "value_url": null,
                                    "attributes": null,
                                    "description": "The IDs of the original RTX-KG2pre edge(s) corresponding to this edge prior to any synonymization or remapping.",
                                    "value_type_id": "metatype:String",
                                    "attribute_source": null,
                                    "attribute_type_id": "biolink:original_predicate",
                                    "original_attribute_name": null
                                },
                                {
                                    **"value": [
                                        "PMID:"
                                    ],**
                                    "value_url": null,
                                    "attributes": null,
                                    "description": null,
                                    "value_type_id": "biolink:Uriorcurie",
                                    "attribute_source": "infores:disgenet",
                                    "attribute_type_id": "biolink:publications",
                                    "original_attribute_name": null
                                }
                            ],
                            "qualifiers": null
                        },

**Comment by saramsey** [comment]
I think this is the Translator UI result in which the "missing PMID" is the issue, but I am not yet sure:

<img width="1371" alt="Screenshot 2023-07-18 at 10 51 50 AM" src="https://github.com/NCATSTranslator/Feedback/assets/5562107/9b9f201c-17d7-4e75-bd13-4d4c4880514d">

**Comment by saramsey** [comment]
Bug confirmed in RTX-KG2.8.0.1c.

**Comment by saramsey** [comment]
I'm going to close this issue but the RTX-KG2 issue 325 will remain open until we have deployed the fix into Translator CI.

**Comment by saramsey** [comment]
Thank you @Genomewide @sandrine-m and @sierra-moxon for bringing this issue to my attention.
