### ISSUE TITLE
UI: Make feedback box moveable

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#417]
## Original comment: 
When I am attempting to send feedback I can't move this feedback box around so I can see what I was looking at. This means I need to close the box, write down or copy the names of the drugs or whatever--then re-open to complete the feedback. Could this box be moveable so I can simply push it aside so I can see what I was looking at and copy from there? I believe this change would improve feedback quality. --Maureen

**Comment by dnsmith124** [comment]
Given the wide range of possible screen sizes and the difficulty of implementing this request as it's written, we've gone with a slightly different approach that resolves the problem. 

The Send Feedback modal now opens in a new tab when clicked, leaving the original tab open for review. 

Confirmed this feature is live on CI, closing.
