### ISSUE TITLE
Results Names - Too Wide in Result List

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#419]
Similiar to #356 but with the results page and chemicals so may not as similar as I think.  This is in Test on 7/13.

https://ui.test.transltr.io/results?l=Exotropia&i=MONDO:0001286&t=0&q=d56f9c65-450e-44b8-9c6e-0b329ad4e018

I dont see the difference in the names in lets call them rows 2-5, are they dupes?  i'm using a standard dell laptop screen and chrome set to 100%

<img width="933" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/1fb6b507-9493-4229-94e5-f0f30fdd3b9c">

in the initial expand in the network graph i can't see the full name
<img width="712" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/8b04a85b-d75d-4d4b-99cb-010d36f0b80e">

**Comment by dnsmith124** [comment]
Rows 2-5 appear to have the same names, but have different identifiers. If you open the path view and hover over the node in question, you can check the link in the tooltip there to confirm this. 

With regard to the graph view name overflowing the container, that issue has been resolved on dev and should be pushed to CI and test soon.

**Comment by sstemann** [comment]
i checked it out in CI
