### ISSUE TITLE
Results with Drug Dosage

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#420]
I was surprised to see results with dosage for MVP1.  I'm not sure if it's by design #70.

What drugs may treat exotropia?

https://ui.test.transltr.io/results?l=Exotropia&i=MONDO:0001286&t=0&q=d56f9c65-450e-44b8-9c6e-0b329ad4e018

Filter by Result Type "Drug"
<img width="935" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/f7ec60a8-8f0d-4eaa-aa8f-9c6cbe1ae71b">

I can't quite get the results load in the ARAX UI (https://arax.ci.transltr.io/?r=d56f9c65-450e-44b8-9c6e-0b329ad4e018), but the filter on the UI says its from ARAGORN
<img width="809" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/9ead39db-a395-48ee-a450-a4c6e346a740">

**Comment by sstemann** [comment]
@cbizon it's happening for this wagner disease also:  https://ui.test.transltr.io/results?l=Wagner%20Disease&i=MONDO:0007740&t=0&q=d42ef387-468d-40fc-a599-d89d7a1cccf7

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/17081646-11c3-46ca-b455-a0b43aae5c8c)

the results with the red line, is just to point out, that i think this are actually combinations of ingredients, not sure if thats what's intended

**Comment by sstemann** [comment]
this is still happening in UI Test for ARAGORN results:  https://ui.test.transltr.io/main/results?l=Wagner%20Disease&i=MONDO:0007740&t=0&r=0&q=ec4192f0-2eda-468d-ab87-81b67e5aa355

search for "charcoal" there are 18 results of different forms from ARAGORN - any chance this can be addressed in Lobster 1 backend for ARAGORN?

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/04d4861c-8a79-4b0b-9bad-f2c65f8f6f83)

**Comment by cbizon** [comment]
Couple of notes:
* The drug dosages are no longer there
* The charcoal answer is pretty bad, we're looking into why that is there and what we can do about it
* For the most part, I think that these are 18 different answers, because they are (mostly) charcoal + something else.  That said, there are a few here that I'd rather were merged together, but it's not going to reduce the total number by more than a few.   

Hopefully once we solve the charcoal problem this answer will get better.

**Comment by sstemann** [comment]
still an issue in Test - 3/28 https://ui.test.transltr.io/main/results?l=Wagner%20Disease&i=MONDO:0007740&t=0&r=0&q=630ae27e-4c39-454a-9580-f2a856bcc92c

**Comment by sstemann** [comment]
this looks OBE - ARAGORN does not return any results for Wagner Disease.  I ran it's parent vitreoretinal degeneration and charcoal/forms of charcoal did not return, closing this
