### ISSUE TITLE
UI results to query are complete but only six answers when Sierra showed many more

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#424]
During today's Data Modeling / UI testing call, I independently ran the same query that Sierra did ("What drugs may treat EDS, hypermobility type) and in the same test environment. The UI finished loading results very quickly (check box marked), but only six results were returned (all from ROBOKOP), whereas Sierra showed hundreds of results. The issue may be on my end, but I would like to confirm that.

![image](https://github.com/NCATSTranslator/Feedback/assets/26254388/c8f9d3ec-87e0-4a2a-84e2-ff7dfebb0cff)
 
![image](https://github.com/NCATSTranslator/Feedback/assets/26254388/b776839d-127e-4e59-b996-351891477e46)

**Comment by sstemann** [comment]
@karafecho i see this happen to me as well.  i find that sometimes if i hit the browser refresh more answers will load.  

do you have the full link that you provide here so we can take a look at the PK? you may be able to get to it from the Test UI > Search History (as long as you havent cleared your cache).  Appreciate the details, thanks!

**Comment by karafecho** [comment]
Thanks for the tip about the Search History feature. Here is the PK from Friday's test: a92b964f-aed4-499d-8ad5-590e0faa2aad. Note, however, that I am now seeing 504 results. I think this may be a UI bug, in that the UI appears to have incorrectly marked the query as complete after the first six results from ROBOKOP were returned, not the full answer set.

I also noticed that the query is time-stamped at 2:16 pm but I ran it on 12:16 pm. Minor issue, but probably should add the time zone to the search history results.

**Comment by sierra-moxon** [comment]
@dnsmith124 - have you ever had this happen to you?  Any ideas about where this ticket should go first?

**Comment by dnsmith124** [comment]
This can happen for a variety of reasons! It could be an ARA returning an erroneous response, or an issue with the UI's backend returning an error causing the polling for results to terminate early. 

Without a look at the browser console in an instance where this happens I can't be sure what exactly is causing it. Gus and myself are working on an overhaul of the UI's error handling to try to address it broadly.

**Comment by gprice1129** [comment]
Can we retest this on the latest UI?

**Comment by gprice1129** [comment]
After talking with @dnsmith124 I recommend we close this ticket. This is not something that can be "fixed", it is the reality of a system that has many components that may be down or up at different times. The UI can only display what is available in a certain time window, which may change at a different time. @sstemann @sierra-moxon @karafecho
