### ISSUE TITLE
group/filter by pattern of predicates

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#426]
This is linked to issue #408 
-  my concern is that the pattern/chain of predicates for subclass-->causes-->subclass are not treat edges to understand biological mechanism: it could be interesting to be able to group by chain of predicates

**Comment by sharatisrani** [comment]
Grouping-ordering are in the zone of UI for this release.  I am not able to edit the labels or assignees, please do so.

**Comment by sandrine-m** [comment]
After meeting at the DM call today; those type of data gap/reasoning issues need more work and will be fixed post September.

**Comment by sierra-moxon** [comment]
from TAQA:
- might not be all the way to the opposite of what I asked for; but this path doesn't support the answer seems like the bucket for this ticket - we need to fix at the source.  Label for this might be "transitive"
- it is worth discussing what we want to do via the UI - lots of answers (likely there will be some that people don't like), paths only get "made" in the UI - so if it is a path that is bad, clearly bad, then the UI might be able to suppress in a "stop gap" fashion?  Maybe we "rate" the paths (green, red, etc)
- we need to make sure we're not covering up the fundamental reasoning issues that we need to address.

**Comment by sierra-moxon** [comment]
This is a new bucket : poor paths/transitive path - we need to triage more into this bucket

**Comment by mbrush** [comment]
My comment in [the ticket here](https://github.com/NCATSTranslator/Feedback/issues/566#issuecomment-1753402545) is relevant to this issue.

**Comment by sierra-moxon** [comment]
I believe this is well on its way to be complete - we have support paths showing up in the UI and we other tickets to cover issues with this.  closing as complete - please reopen if I got this incorrect!
