### ISSUE TITLE
Many irrelevant (wrong) answers for "What treats lactose intolerance?" 

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#427]
Query: What drugs may treat lactose intolerance? 
https://ui.test.transltr.io/results?l=Lactose%20Intolerance&i=MONDO:0100345&t=0&q=d3e802da-c4c7-4816-9004-8b8c88c6b30d
https://ui.ci.transltr.io/results?l=Lactose%20Intolerance&i=MONDO:0100345&t=0&q=aa4289b5-66e0-4b6a-ad7a-350a47556b17

Lactose intolerance is due to insufficient levels of lactase being produced in the small intestine. As far as I know, and can tell from public sources, there is really only one treatment which is to supplement the missing lactase (in addition to dietary changes, i.e. avoid lactose). 

Total of 347 (!) results. In CI and test, the top result is lactase (good). Problems:
-  Ranked in the top 4 in both are alpha-lactose and beta-lactose. This is coming from DrugCentral (from Robokop and Improving).
- There are many irrelevant/incorrect results, including Tacrolimus (immunosuppresive drug), probucol (lipid-lowering drug), steroids, chemotherapies etc. Many of them come from paths with 2-3 intermediary genes, with the last one having a vague "associated with" link to lactose deficiency. Many seem to come from ARAX, but its not exclusive to ARAX.
![Screen Shot 2023-07-13 at 4 50 35 PM](https://github.com/NCATSTranslator/Feedback/assets/1442197/af510b81-2a69-4874-bff8-3cb5df5e7143)

**Comment by khanspers** [comment]
From ARAX interface, I see this:

For "lactose, anhydrous" from BTE, "primary_knowledge_source" is drugcentral:

![Screen Shot 2023-07-18 at 11 56 24 AM](https://github.com/NCATSTranslator/Feedback/assets/1442197/30716e1e-932f-4419-aac9-bfab5b84a985)

For beta-lactose, from Improving, "primary_knowledge_source" is drugcentral:

![Screen Shot 2023-07-18 at 11 58 38 AM](https://github.com/NCATSTranslator/Feedback/assets/1442197/1294ea66-2521-4e6f-b708-0645038a050a)

**Comment by sierra-moxon** [comment]
thank you, that's really helpful.

**Comment by suihuang-ISB** [comment]
@sierra-moxon 

On the point of using LACTOSE to treat LACTOSE INTOLERANCE:
'lactose' is indeed listed in DrugCentral under INDICATION  for lactose (or more precisely alpha-lactose)
https://drugcentral.org/drugcard/1535?q=lactose

My interpretation:
(1) **This is an error.**  Someone curating the data at DrugCentral mixed up lact_o_se with lact_a_se (which helps in lact**o**se Intolerance).
(2) There have been the idea floating around that SMALL amounts of of lactose may help: by inducing the expression of lactase again (since intolerance is due to shutting off the lactase gene in the adult) in the intestinal epithelium or microbiome...
https://www.sciencedaily.com/releases/2000/01/000127082535.htm
(Note that this is not he same as desensitization since Lactose Intolerance is not an allergy)

Thus, this is a simple case of error in the source database.

**Comment by sandrine-m** [comment]
For the first bullet point adding Rosina and Sharat as this could be used as a ground truth example.
For the second bullet point: After meeting at the DM call today; those type of data gap/reasoning issues need more work and will be fixed post September

**Comment by Rosinaweber** [comment]
The results are currently 1175. I'd like to use it as benchmark but I am unsure of what the correct results should be. I will bring this up in our next O&O meeting.

**Comment by sandrine-m** [comment]
@mbrush @sierra-moxon when we observe an error in the data ingested, usually we tell the source but we have no way to ensure that the change will be made. should we put in place a way to "correct" our ingested data adding a particular EPC so that ARA can make sure they use the correct info?

**Comment by sandrine-muller-research** [comment]
Retested today on [TEST](https://ui.test.transltr.io/main/results?l=Lactose%20Intolerance&i=MONDO:0100345&t=0&q=faf05624-2424-4152-8b68-badacbb03f43)
Beta- and Alpha-lactose still show up from improving, ARAX (from robokop), and BTE:
<img width="1166" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/4bc817ec-49f0-4931-8f28-b0c745052955">

<img width="1163" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/36490c8e-8c00-4fda-af68-46361a5f450f">

<img width="1172" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/257f565c-0fb2-422e-90ca-bc45e6d21ce3">

Adding this as a test asset for the acceptance tests.

**Comment by khanspers** [comment]
I ran this again today (in [test](https://ui.test.transltr.io/main/results?l=Lactose%20Intolerance&i=MONDO:0100345&t=0&r=0&q=c1de01af-bef5-4298-8529-a342504ed85a)), and there are still issues:

- The third result is Lactobiose, a synonym for lactose
- Water is returned as a result, and the inferred path includes several paths with a "Nameunknown" node. See below. The node type is "Molecular Activity". The knowledge source is PathWiz.

![Screen Shot 2024-05-13 at 5 07 37 PM](https://github.com/NCATSTranslator/Feedback/assets/1442197/28b6a13b-ea9e-4d04-a333-2d4d222738d3)

- The same paths include the statement "alpha-lactose treats lactose intolerance". This is the same problem as originally reported.

**Comment by gglusman** [comment]
Here's one of the culprit ids, via Aragorn:
![image](https://github.com/NCATSTranslator/Feedback/assets/3977332/c6a71dd3-a413-4036-af68-5c9f46ecac2e)
![image](https://github.com/NCATSTranslator/Feedback/assets/3977332/db441848-c135-44a4-a5db-26312448bd8a)

**Comment by suihuang-ISB** [comment]
(1) On "WATER" Checking the original source PathWiz had "H20" as part of the reaction involved in lactose breakdown into galactose and glucose, under disease 'pathway for lactose intolerance'. According to this logic, "galactose" should also appear as treatment, like water - can you check?

**Comment by khanspers** [comment]
To answer (1): "galactose" is not returned as a potential treatment.

**Comment by khanspers** [comment]
Retested in test today and Lactose is the second result listed:

https://ui.test.transltr.io/main/results?l=Lactose%20Intolerance&i=MONDO:0100345&t=0&r=0&q=027fec2a-2fba-4378-9092-abba65b6d96f

Of the two direct paths, the second one (Lactose - preventative for - lactose intolerance) is supported by papers describing the use of lactose in infants to prevent intolerance. Fine. 

The other is from Aragorn and has DrugCentral and RepoDB as sources:
![Screen Shot 2024-07-08 at 11 56 17 AM](https://github.com/NCATSTranslator/Feedback/assets/1442197/ba1db1b2-2f83-475e-ba0c-617be09b0794)

Didn't dig into these in detail, maybe they are referring to the same type of preventative use as the other result. Just thought I'd document it here.

**Comment by cbizon** [comment]
Well, that's certainly what drugcentral is showing: https://drugcentral.org/drugcard/1535

![image](https://github.com/NCATSTranslator/Feedback/assets/10744350/48b51df9-4796-4981-8143-f077589b290a)

But they don't really list a further source or more details that I can figure out

**Comment by andrewsu** [comment]
I would propose closing this issue. "Lactase" (which to my lay understanding is the "best" answer) does show up first. "Lactose" is tough to "fix" because it's so authoritatively declared by DrugCentral.  "Water" is the sixth answer with many (weak) support paths, so I think this falls to scoring optimization (which we all know we need to continue to do). So I think this ticket has served its purpose and can be closed. But will leave it to someone else to second this motion and close it.

(I will tag @bill-baumgartner because the evidence for the "water" answer includes some questionable triples from TMKP... But if that's useful, I think those can go to a more focused issue.)

**Comment by bill-baumgartner** [comment]
Thanks @andrewsu.  TMKP should now be excluding water. Just [retested on Test](https://ui.test.transltr.io/main/results?l=Lactose%20Intolerance&i=MONDO:0100345&t=0&r=0&q=645b8bef-8837-4ea7-9afe-4282238f724b), and water has dropped to the 3rd page of results, and the offending TMKP edges related to water do not appear as expected.

**Comment by sstemann** [comment]
i second Andrew's motion.  

1. pathwhiz nodes - still there in Prod and CI, related to #541 and #618 so i think we dont need to discuss here
2. water seems resolved with Fugu which is on test

**Comment by sierra-moxon** [comment]
from TAQA:
- this is a two-pronged issue, one issue about water, that has been fixed, one about lactose treating lactose intolerance. 
- since its a edge from a source, we can't fix as a one off.
