### ISSUE TITLE
more matches need to be returned into the autocomplete

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#43]
see issue #40 for some examples.  
it takes typing `Hereditary Ch` to get the disease to show up in the autocomplete pick list (however, it is true that searching for 'hereditary' is kind of like starting a search with 'the' :)).  But maybe some indication of "more results" or organizing autocomplete alphabetically, or some other fancy solution would be nice for (naive) users of the system

**Comment by dnsmith124** [comment]
This is a great suggestion Sierra! I'm adding an overhaul of the autocomplete functionality to my to do list, and will be incorporating these suggestions.
