### ISSUE TITLE
I would have expected to see a path containing the BRAF pathway here. Why don't we see that? BRAF is a known target of this drug, so any tumor or other disease mechanism driven by BRAF defects would be interesting to test.  -Maureen 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#430]

**Comment by sstemann** [comment]
I'm seeing BRAF in the paths in the Test Environment https://ui.test.transltr.io/results?l=Papillary%20Craniopharyngioma&i=MONDO:0002788&t=0&q=e2bbf37b-9dda-4f43-87d9-dafd3b7767f4

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/23b95aa9-84dc-40f5-982a-90d97e3cdcc8)
