### ISSUE TITLE
Vaccines treat multiple sclerosis

### ISSUE THREAD

**Issue by andrewsu** [NCATSTranslator/Feedback#431]
Separated out from https://github.com/NCATSTranslator/Feedback/issues/214

In "What treats multiple sclerosis" (https://ui.test.transltr.io/results?q=61466522-c32d-4310-a830-fea687642ef7, https://arax.ci.transltr.io/?r=61466522-c32d-4310-a830-fea687642ef7), there are several results for various vaccines 

![image](https://github.com/NCATSTranslator/Feedback/assets/2635409/2d2fd8da-55d1-43fc-b1f9-ab2caa2f7a8c)

Results are coming from BTE (referencing semmeddb) and from improving agent (referencing chembl).

**Comment by sandrine-muller-research** [comment]
I agree with @andrewsu's issue here and logged _some_ in the testing asset sheet but not all: I found papers supporting the assertion:
**For Vaccines, dna:**
_DNA vaccines have recently emerged as a therapeutic agent for treating autoimmune diseases, such as multiple sclerosis._ https://pubmed.ncbi.nlm.nih.gov/29894515/
_Several disease-modifying agents have been approved for the treatment of MS_ https://pubmed.ncbi.nlm.nih.gov/19649992/
