### ISSUE TITLE
"Search History" feature

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#434]
This issue is to report a minor improvement in the "Search History" feature. Specifically, I pulled up a query that I ran on Friday (PK = a92b964f-aed4-499d-8ad5-590e0faa2aad). I noticed that the query is time-stamped at 2:16 pm but I ran it on 12:16 pm ET. I assume this is a time zone issue, in which case that information should probably be captured as part of the search history.

**Comment by sstemann** [comment]
can i piggyback on this? i'd really like the PK to show in the search history this is a testing helper only

**Comment by sstemann** [comment]
for my queries today the timestamp in the search history is for my current time zone
<img width="726" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/648a342f-af5b-4cc2-b346-2a16f85ff6e6">

@karafecho is it working for you?

**Comment by dnsmith124** [comment]
The timestamp should correspond to the timezone set on the user's device, it's not being overridden by the UI in any way that I can tell.

@sstemann with regard to having the PK available for testing purposes, would logging the pk and query string to the browser console be acceptable for your purposes?

**Comment by gprice1129** [comment]
@sstemann please open a new ticket. Piggybacking on tickets makes the process more difficult.
