### ISSUE TITLE
Display when using MVP2 - include Species in results and search history

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#436]
After I select a gene from the list(with the species specified), the results and search history don't indicate which species i selected making it hard to remember/reference

<img width="750" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/20fde5bf-fd9d-4fe5-aabd-57b632cce7e4">

MOUSE - https://ui.test.transltr.io/results?l=Col6a1&i=NCBIGene:12833&t=1&q=2b2f388c-2df7-48c9-9c0e-fbe6898846c4
<img width="946" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/02569fe2-9fcb-4e28-9112-fe3ce7df6ff5">

HUMAN - https://ui.test.transltr.io/results?l=COL6A1&i=NCBIGene:1291&t=1&q=893a4ee5-893d-44ac-b9c4-0f46d573a12d
<img width="937" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/f47ce6cc-df4b-4974-843a-55f039505e39">

**Comment by sierra-moxon** [comment]
@dnsmith124 - is this something you are working towards pre-September, or should we adjust the milestone to "Fall" ? :)

**Comment by sstemann** [comment]
deployed to prod 9/6

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/f5dc143f-37b6-4403-a56e-deceb96cdd45)
