### ISSUE TITLE
primary knowledge source of treats edge from ChEMBL missing

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#437]
## Steps to reproduce:
MVP1 on MONDO:0007827
result for 3-pyridinecarboximidoyl chloride, n-[(2r)-2-hydroxy-3-(1-piperidinyl)propoxy]-, 1-oxide

## Screenshots:
submitted by @sandrine-m

**Comment by sandrine-m** [comment]
The edge (from imProving) shows ChEMBL with no primary knowledge source:
![image](https://github.com/NCATSTranslator/Feedback/assets/66342541/e4aec0b1-88d5-44e2-80c4-c010b774ab90)
MolePro edge is not present in UI but present in results:
![image](https://github.com/NCATSTranslator/Feedback/assets/66342541/201d9062-4f52-42ca-a69e-58f49b40b2bf)
Improving agent does not report the NCT IDs from Clinical trials:
![image](https://github.com/NCATSTranslator/Feedback/assets/66342541/c9ad8411-b6fc-44ed-99cf-6ad118603932)

What could be done to fix:
(1) improving agent provide source of info
(2) UI use MolePro edge as source of info

**Comment by sandrine-m** [comment]
@suihuang-ISB and @Genomewide Please advise of the best course of action and feel free to reassign to anyone you think can help. Thank you!

**Comment by brettasmi** [comment]
@sandrine-m , it looks like imProving is reporting `infores:chembl` as the `primary_knowledge_source` in the ARAX and the UI.

For us, that's correct to the definition per the [SRP spec](https://docs.google.com/document/d/177sOmjTueIK4XKJ0GjxsARg909CaU71tReIehAp5DDo/edit): 
> The most upstream source of the knowledge expressed in an Association that a knowledge provider can identify.

imProving gets this edge from SPOKE KP, which ingests ChEMBL directly. However, SPOKE KP only grabs the "max phase" property for a given indication, not the specific NCT ids (though this is in the works).

**Comment by sandrine-m** [comment]
Thank you so much @brettasmi ! that is clearer now! closing the issue.
