### ISSUE TITLE
duplicate results for Natalizumab 

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#438]
what drugs may treat Inclusion body myositis ([ci](https://ui.ci.transltr.io/results?l=Inclusion%20Body%20Myositis&i=MONDO:0007827&t=0&q=39d68464-4792-4ead-b505-cfd1bbaa9c5e), [test](https://ui.test.transltr.io/results?l=Inclusion%20Body%20Myositis&i=MONDO:0007827&t=0&q=f409140a-52c1-426b-a85a-2705707bdd98))

arax: https://arax.ncats.io/?r=39d68464-4792-4ead-b505-cfd1bbaa9c5e

<img width="1018" alt="Screen Shot 2023-07-20 at 11 56 08 AM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/ba2167b4-1bc3-44a9-99ee-600758239c3a">

**Comment by gglusman** [comment]
Re-testing [on ci 8/18](https://ui.ci.transltr.io/results?l=Inclusion%20Body%20Myositis&i=MONDO:0007827&t=0&q=4b3ea4bc-2822-498f-8173-dbf1b3eb23dd)

The problem persists:
![image](https://github.com/NCATSTranslator/Feedback/assets/3977332/7efedde4-ac82-472d-9c34-5d8bce53538a)
Curiously the 2nd result lost all publications and much of its score, lost the one non-direct path it had (via autoimmune disease), gained two new paths (via gait disturbance, Gne myopathy), and switched from a [MeSH id](http://id.nlm.nih.gov/mesh/D000069442) to a [UNII id](http://identifiers.org/unii/3JB47N2Q2P).

**Comment by gaurav** [comment]
Good news: the latest NodeNorm Dev [combines these identifiers](https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=UNII%3A3JB47N2Q2P&curie=CHEMBL.COMPOUND%3ACHEMBL1201607&conflate=true&drug_chemical_conflate=false&description=false) (i.e. ChEMBL.COMPOUND:CHEMBL1201607 and UNII:3JB47N2Q2P) into a single clique with type biolink:ChemicalEntity, with primary identifier UNII:3JB47N2Q2P. I can close this issue once we push this to ITRB CI and we've tested this on UI.
