### ISSUE TITLE
filter for results with only single edges "treats"

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#443]
## Steps to reproduce:
MVP1 on Maturity-onset Diabetes Of The Young
submitted by @sandrine-m

**Comment by sandrine-m** [comment]
When looking at the first page of results it seems that a few issues appear:
- results indicated as complete (checkmark on top) but needed to refresh to see all results. In case that helps here are observations before refreshing:
(1) only ROBOKOP provides answers
(2) single treat edges were not filtered

**Comment by sandrine-m** [comment]
Feel free to close right away if unuseful

**Comment by sstemann** [comment]
related to #543

**Comment by dnsmith124** [comment]
I'm going to close this as a duplicate of #543, as that ticket is more clear with regard to the action item.
