### ISSUE TITLE
Gene autocomplete fails when complete symbol of the gene is typed in (e.g. no autocomplete suggestions for `BRCA1`)

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#446]
Testing on CI as part of the TAQA:

BRCA1 – but BRCA works!
Same with MUC5B
(MUC5 works, MUC5B doesn’t… ? strange.) 
MUC5B autosuggests (Rat) only but MUC5 shows MUC5B (Human) also 
PCSK9

**Comment by sierra-moxon** [comment]
@gaurav - I retested on CI today; still seems to be an issue.  Do you think this is a post-September issue?

**Comment by gaurav** [comment]
I have a theory about why this is happening: I think `BRCA1` matches >40 non-human genes before we get to human genes, so they all get filtered out of the results by the UI, but both `BRCA` and `BRCA-1` are matching 2x human and 1x rat result, which are not filtered out. I'm hoping that the CURIE suffix sorting we added yesterday will close this ticket and help with similar problems until September 🤞🏾

**Comment by sierra-moxon** [comment]
from TAQA:
Andy: it works on NameResolver directly, just waiting on deployment to CI.  Sorting by ID is an awesome idea, and it does exactly what we want.  Bovine comes up high, but we can filter this out, now Komodo dragon is not the gene set that comes up first. thanks @gaurav !!

**Comment by gglusman** [comment]
I just re-tested all the examples mentioned above, and all work fine now.
