### ISSUE TITLE
cannot search type 2 diabetes

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#447]
## Steps to reproduce:
MVP1 on type 2 diabetes
on ui.ci.translator.io
look at autocomplete
submitted by @sandrine-m

**Comment by sstemann** [comment]
i looked at UI CI today

if you type "type 2 diabetes":
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/47ee0ca1-f8fd-46b8-a8cf-ad7c0b236acd)

if you type "type 2 diabetes " (with a SPACE after diabetes):
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/a601e40e-5926-469c-8cbc-0728afcfda40)

seems problematic

**Comment by dnsmith124** [comment]
@gaurav @Genomewide please see above

**Comment by gaurav** [comment]
It's very strange that both "type 2 diabetes " and "diabetes type 2" work well -- only "type 2 diabetes" fails! I'm tracking this at https://github.com/TranslatorSRI/NameResolution/issues/96.

**Comment by sierra-moxon** [comment]
this works now; closing as complete.
