### ISSUE TITLE
Robokop Infores lists ARAGORN as Primary KS?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#450]
It looks like Robokop's Infores is listing ARAGORN as primary KS, you can see in the the Translator UI as well as in the ARAX UI.  I'm not sure if this is intentional.  The UI may not be using the latest catalog, I'm not really sure where the problem is:

1. Test environment > MVP1 > Attention deficit disorder, inattentive type
2. Entity search for Acids
3.  Notice several ARAs are listed: Robkop, BTE, Unsecret

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/7db6b59f-409a-46a5-8780-de6491be954b)

4. Click the top path for treats, one source, ARAGORN, but that's not listed as an ARA on the right 

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/8cd614ad-f089-4774-9430-2eb103ed7309)

5. Go to ARAX UI, and ARAGORN is N/A
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/057f6185-91ed-44d2-9181-913af4f1ecd8)

6. View Robokop Results - I'm not sure if it's trying to say that ARAGORN predicted this edge and Robokop found it? 

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/bbc1779f-44c4-47f7-b699-5e7e8ecd1375)

7.  I'm not sure which infores should be used (and this may be a seperate issue for the UI to update once the infores yaml is frozen)
 
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/e0a6893e-c4ed-44bc-abd2-96171f421957)

On automat-robokop but it's listed as KG not just plain
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/3d7c2fd6-0a2a-4848-9c53-90a7e1de467a)

**Comment by cbizon** [comment]
This is really a robokop problem with it returning the wrong infores.   I'll make a fix in dev today.

**Comment by cbizon** [comment]
OK, the fix is in dev and will work its way up the chain.

**Comment by sstemann** [comment]
looks fixed.
