### ISSUE TITLE
Inferred Edge without Support Auxiliary Graphs 

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#451]
1.  UI Test > MVP1 > Cowden Disease:  https://ui.test.transltr.io/results?l=Cowden%20Disease&i=MONDO:0016063&t=0&q=ab056621-569e-4a29-83c3-509e81abada4
2. Entity Search AKT1, narrow to Improving Agent (2)
3. Expand Noscapine, click Treats on the top path

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/654fa6d4-d9e1-441e-a863-274fd7baf711)

4. Go to ARAX UI  > Improving Agent > Noscapine https://arax.ncats.io/?r=ab056621-569e-4a29-83c3-509e81abada4
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/3947597f-8477-428b-8932-5c79dc051078)

Says the edge is inferred but i dont see any support graphs on the result or edge level.  Is this valid?

**Comment by edeutsch** [comment]
The id can be any string, and the fact that it is "inferred_195" does seem to hint to human readers that it comes from some inference code, but the id itself is not officially indicative of anything. This result from imProving has no auxiliary_graphs, and the metadata of many edges appears incomplete. The ARAX GUI is showing what is in the TRAPI:
```
    "auxiliary_graphs": {},
...
        "inferred_195": {
          "object": "MONDO:0016063",
          "predicate": "biolink:treats",
          "sources": [
            {
              "resource_id": "infores:improving-agent",
              "resource_role": "primary_knowledge_source",
              "upstream_resource_ids": []
            },
            {
              "resource_id": "",
              "resource_role": "primary_knowledge_source",
              "source_record_urls": null,
              "upstream_resource_ids": null
            }
          ],
          "subject": "PUBCHEM.COMPOUND:275196"
        },
```

I agree that the metadata needs to be much better in this TRAPI document from imProving.

Note that the validator points out the resource_id is empty, which is semantically invalid:
```
Errors:
* Knowledge Graph Edge Sources Retrieval Source Resource Id:
=> Empty 'resource_id' property in Edge
	$ global
		# PUBCHEM.COMPOUND:44555670--biolink:treats->MONDO:0016063
```

Is that what you wanted me to provide?

**Comment by suihuang-ISB** [comment]
also assigned to @Brett Smith....  for explaining the formulate the inference in TRAPI.

@sstemann:  The larger problem lies in the very mode of "inference". There are fundamentally, two types of inference to arrive at a hypothesis in medicine, deduction and empirical: 
(1) **Mechanistic reasoning** (deduction), which in the Translator can be represented as an multi-hop path in the large KG.
(2) **Direct empirical observation**, agnostic of mechanistic basis. In imRPOVING this is achieved by learning node weights that reflect relationships between concepts (nodes) based on **empirical** data, such as EHR and multi-omics studies  (not established knowledge). 

Thus, in the case of (2) we do NOT have an auxiliary graph.   A mechanistic aux. graph exists only in type (1) inference.
There is, I guess, no good way yet to indicate an empirical-finding-based inference (2) - but these are much more reliable in medicine than mechanism based (1).  IN the case of (2) the link under 'source' should actually point to the imPROVING **Wiki** that explains how empirical evidence is used, and the data sources but in the UI it still (not in all but in most cases) points to the Github page which is not helpful for the end-user/  as discussed.

**Comment by brettasmi** [comment]
I feel like we've discussed this previously, but I'm not sure where.

Our understanding was that updating our [wiki page](https://github.com/NCATSTranslator/Translator-All/wiki/imProving-Agent) to describe our inference process for MVP1 would be sufficient. If the user clicks the improving agent link out from the UI, they should be taken to the wiki page. We don't have support graphs for this type of inference.

Thank you @edeutsch for finding that missing resource ID; that's definitely a bug. The primary knowledge source in the first element of the sources array correctly identifies improving agent as the primary knowledge source.

**Comment by sierra-moxon** [comment]
@brettasmi - from your comment, it seems like the missing resource ID will be fixed before the September release, is that right? :) And, because y'all have been working on the infores wiki pages, the other part of this ticket is already fixed! :)   Is this all correct?
