### ISSUE TITLE
Increase/Decrease Relationship with the same publication for Evidence

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#452]
UI Test - MVP1 - Cowden Disease https://ui.test.transltr.io/results?l=Cowden%20Disease&i=MONDO:0016063&t=0&q=ab056621-569e-4a29-83c3-509e81abada4

Entity search KLLN
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/716e3db5-8aa4-427e-817d-cece375f3ee9)

Click the "Causes Increased Activity + 1 more" between Doxorubicin and KLLN

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/0c7d25f7-31b5-4eff-8f75-7d7c02390ccd)

The same publication is used twice for the both increase and decrease evidence.  Source says both are from TMKP

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/ac3a269a-00f5-4087-8413-dbcff14a1711)

**Comment by gglusman** [comment]
Looking at the paper, 'doxorubicin increases KLLN expression' is the correct reading (though more mechanistically, doxorubicin causes DNA damage, which leads to increased KLLN expression).
I'm guessing the text mining got confused by statements in the paper describing how they used siRNAs to silence KLLN _after doxorubicin treatment_. Out of context, there is some language ambiguity in the use of the word 'after'...

**Comment by sstemann** [comment]
cannot replicate
