### ISSUE TITLE
Same Pub Appears Twice for one Edge

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#453]
I can't tell why - maybe because one is a PubMed ID and other is a PMCID but its to the same ultimately - I also don't know where this should be addressed, so tagging UI, ARA (Unsecret) and KP (TMKP)

1. UI Test > MVP1 > Cowden Syndrome 1
https://ui.test.transltr.io/results?l=Cowden%20Syndrome%201&i=MONDO:0008021&t=0&q=68db57f6-ff84-44b1-af2c-af8d922d3568

2. Entity Search Everolimus, click on the Everolimus Affects PTEN edge, note the publications look duplicative

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/2874843f-6a68-4a1f-9360-d96c5caa0362)

3. View the Unsecret result in ARAX GUI:  https://arax.ncats.io/?r=68db57f6-ff84-44b1-af2c-af8d922d3568

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/a7c9c596-a810-4c28-9b10-b5c387cfd5e4)

**Comment by dnsmith124** [comment]
You are correct @sstemann, the UI is not counting this as a duplicate because the underlying IDs are different. (PMID:30160042 and PMC6198234)

**Comment by saramsey** [comment]
I believe PMC manuscript identifiers and PubMed abstract identifiers are numerically inequivalent even for the same publication, and refer to different texts in a sense (PubMed records contain just the abstract and associated metadata; PubMed Central, or PMC, contains the complete manuscript, figures, and often the supplementary material).

**Comment by gglusman** [comment]
@saramsey All true, but it is probably not a good idea to count them as separate lines of evidence. :)

**Comment by edeutsch** [comment]
Note that providing the PMID and PMCID for the same publication is not permitted in TRAPI. See item #4 here: https://github.com/NCATSTranslator/ReasonerAPI/blob/master/ImplementationGuidance/Specifications/supporting_publications_specification.md

**Comment by kaiwenho** [comment]
> I believe we have addressed the issue of multiple identifiers being returned for the same document in our current release, however since Unsecret uses a cached version of the TMKP data, I'm wondering if they are using an older version where the bug persists.

Thank you for the update! Unsecret will import the new version of TMKP data soon.

**Comment by bill-baumgartner** [comment]
Just to followup - we are checking to see if we might still be providing multiple document identifiers for the same document under some conditions. I will update when I have more information.

**Comment by saramsey** [comment]
All fair points above.

Sure, if a KP provides a triple that is extracted by text-mining of an article _abstract_, it should probably provide the PMID and not the PMCID, insofar as the PMID makes it more clear that the information came from the abstract. On the other hand, suppose KP X extracts a triple from a PubMed abstract and KP Y extracts a triple from the full text of the corresponding article, why shouldn't KP Y provide the PMCID?  I'm not sure why we would want to prohibit that.

Admittedly, the above scenario may be a corner case.

**Comment by saramsey** [comment]
> Note that providing the PMID and PMCID for the same publication is not permitted in TRAPI. See rule 4 here: https://github.com/NCATSTranslator/ReasonerAPI/blob/master/ImplementationGuidance/Specifications/supporting_publications_specification.md

Good to know!

**Comment by sstemann** [comment]
looks resolved
