### ISSUE TITLE
Node Norm - UNII has the UMLS, UMLS only has UMLS, doesn't seem to be getting normalized

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#456]
In UI CI or UI Test, run 

1.  MVP1 > Bethlem Myopathy https://ui.test.transltr.io/results?l=Bethlem%20Myopathy&i=MONDO:0008029&t=0&q=b034384d-ae21-4cbf-935c-85be54474b5a
2. Entity search for , notice its there twice, both from BTE
<img width="937" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/ae13aefc-db72-4ef5-a476-3f8f75f56eb5">

3. view the BTE results in ARAX GUI https://arax.ncats.io/?r=b034384d-ae21-4cbf-935c-85be54474b5a

4. result # 1 and 9
 
<img width="887" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/a1dae1aa-e3b3-4d39-b0cc-754080644d4e">

5.  result # 1 is UMLS:C0006050 
 
<img width="847" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/7da8a668-5a55-4ea1-96d3-d95db3aa50af">

{
  "UMLS:C0006050": {
    "id": {
      "identifier": "UMLS:C0006050",
      "label": "botulinum toxin type A"
    },
    "equivalent_identifiers": [
      {
        "identifier": "UMLS:C0006050",
        "label": "botulinum toxin type A"
      },
      {
        "identifier": "UMLS:C0591427",
        "label": "Dysport"
      },
      {
        "identifier": "UMLS:C2719424",
        "label": "abobotulinumtoxinA"
      },
      {
        "identifier": "UMLS:C2719767",
        "label": "onabotulinumtoxinA"
      },
      {
        "identifier": "UMLS:C2744602",
        "label": "Xeomin"
      },
      {
        "identifier": "UMLS:C2930113",
        "label": "incobotulinumtoxinA"
      },
      {
        "identifier": "UMLS:C4083128",
        "label": "Onaclostox"
      },
      {
        "identifier": "UMLS:C4721552",
        "label": "EvabotulinumtoxinA"
      },
      {
        "identifier": "UMLS:C4745461",
        "label": "prabotulinumtoxin A"
      }
    ],
    "type": [
      "biolink:Protein",
      "biolink:Polypeptide",
      "biolink:BiologicalEntity",
      "biolink:NamedThing",
      "biolink:Entity",
      "biolink:GeneProductMixin",
      "biolink:ChemicalEntityOrGeneOrGeneProduct",
      "biolink:ChemicalEntityOrProteinOrPolypeptide",
      "biolink:ThingWithTaxon",
      "biolink:GeneOrGeneProduct",
      "biolink:MacromolecularMachineMixin"
    ]
  }
}

6.  result # 9 is UNII:E211KPY694
<img width="875" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/768dd3f5-e0da-4d6e-97ad-2b976fd65a10">

{
  "UNII:E211KPY694": {
    "id": {
      "identifier": "UNII:E211KPY694",
      "label": "BOTULINUM TOXIN TYPE A"
    },
    "equivalent_identifiers": [
      {
        "identifier": "UNII:E211KPY694",
        "label": "BOTULINUM TOXIN TYPE A"
      },
      {
        "identifier": "MESH:C542870",
        "label": "[OBSOLETE] onabotulinumtoxinA"
      },
      {
        "identifier": "MESH:D019274",
        "label": "Botulinum Toxins, Type A"
      },
      **{
        "identifier": "UMLS:C0006050",
        "label": "botulinum toxin type A"
      },**
      {
        "identifier": "CHEMBL.COMPOUND:CHEMBL2108035",
        "label": "INCOBOTULINUMTOXINA"
      },
      {
        "identifier": "CHEMBL.COMPOUND:CHEMBL4297862",
        "label": "BOTULINUM TOXIN TYPE A"
      },
      {
        "identifier": "CHEBI:3160",
        "label": "Botulinum toxin type A"
      },
      {
        "identifier": "DrugCentral:5368",
        "label": "botulinum toxin type A"
      },
      {
        "identifier": "KEGG.COMPOUND:C07946",
        "label": "Botulinum toxin type A"
      }
    ],
    "type": [
      "biolink:ChemicalEntity",
      "biolink:NamedThing",
      "biolink:Entity",
      "biolink:PhysicalEssence",
      "biolink:ChemicalOrDrugOrTreatment",
      "biolink:ChemicalEntityOrGeneOrGeneProduct",
      "biolink:ChemicalEntityOrProteinOrPolypeptide",
      "biolink:PhysicalEssenceOrOccurrent"
    ]
  }
}

I dont know if this is node norm or BTE so tagging both to take a look and Mark since merging will be ARS responsibility shortly.

**Comment by andrewsu** [comment]
I think this is a duplicate of #395 and #167

**Comment by sstemann** [comment]
closing this in favor of the other two tickets
