### ISSUE TITLE
If I can search by disease, I also want to search by symptom or phenotype!

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#457]

**Comment by sierra-moxon** [comment]
Per: Anthony Hickey (SME) user testing.  If we find a set of chemicals for a disease (that might treat it), we also want to query the phenotypes associated with this disease to find treatments that might make a certain symptom better for the patient (and also lead to research around _why_ this drug or _how_ this drug is affecting the disease) would be wonderful.

**Comment by gglusman** [comment]
On random checking, some but not all seem to be there already.
