### ISSUE TITLE
UI suggestions: paginator on top, collapse-all button

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#459]
1) Right now there's a paginator at the end of each page of results. Would be nice to have a paginator at the top as well, to avoid lots of scrolling up and down.
2) A button to collapse all expanded results would come handy.

**Comment by dnsmith124** [comment]
These are great suggestions @gglusman, thank you! I'll look into how/when we can implement these.

**Comment by gprice1129** [comment]
@gglusman the UI team has decided not to implement a collapse-all button as it seems like a very tester oriented feature. We do think that including either a paginator on top or one that follows the user's view is a good idea.

**Comment by sstemann** [comment]
pagination is done.  collapse-all can be brought up again when requested.
