### ISSUE TITLE
More evidence types, kinds, and metadata would be extremely valuable on edges.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#46]

**Comment by sierra-moxon** [comment]
(Captured from issue title before edits):
Relationships appear to have little to no metadata. Eg. a "treats" edge, when clicked on, shows nothing about where this edge came from. 

Some other "treats" edges appear to come from the literature but are missing basic information (like year, the snippet, etc.)

- [ ] add evidence metadata other than publications to "Evidence" display (starting with infores data potentially)
- [ ] for evidence on edges that do contain publications, consistent metadata about the year of publication, the abstract, etc, would be helpful.

**Comment by Genomewide** [comment]
We are currently developing a template that would cover what we are looking for.  
https://docs.google.com/document/d/1WMVwYK_u9vQ60F-aKfdCer27Y4Xm1X04/edit

Matt is doing some work on the categorization of EPC.  However, the more descriptive text is what we would like to link to if possible. 

We are also considering just having the link to the source of the data.  However, it is currently not clear how to decern this for every edge.

**Comment by sierra-moxon** [comment]
From TAQA:
- link from infores type -> group is available
- still need resources to declare their "primary knowledge source" vs. "original knowledge source"
- please see Andy's presentation of EPC attributes
  - Need folks to update to use one "primary knowledge source" 
  - Need folks to comply with the latest representation 
  - "have evidence" - needs EPC standardization
  - UI can focus on the InformationResource attributes for now while we wait for EPC harmonization. 
  - end of the day - if I see PKS = spoke, then tell UI what to do with it.  infores is linked to the attributes that are available. 
  - we need structured edge attributes.

**Comment by sierra-moxon** [comment]
Best would be:
for each infores and association type, we want a list of available EPC attributes that you can reliably show.

**Comment by gprice1129** [comment]
Can we close this?

**Comment by sierra-moxon** [comment]
closing.
