### ISSUE TITLE
Translator should not provide brand names as results. 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#461]
## Steps to reproduce:
Query for "What drug may treat" multiple sclerosis

**Comment by sierra-moxon** [comment]
Avonex is listed as an answer. This is important for trustworthiness, and for normalizing anwers to reduce noise in the answer sets. Per NIH styleguide, medications should be listed with their generic names. RxNorm can map to Avonex to ingredient (in this case, interferon beta-1a)

**Comment by sierra-moxon** [comment]
@jh111 - is post-September the right time to address this? :)

**Comment by jh111** [comment]
I think post-September is fine, but those presenting Translator may want to be aware of it, and either avoid using examples that feature brand names or notes it's something that will be fixed.

**Comment by gglusman** [comment]
Another example:
[What drugs may treat EDS, vascular type](https://ui.test.transltr.io/main/results?l=Ehlers-danlos%20Syndrome,%20Vascular%20Type&i=MONDO:0017314&t=0&q=ea31c185-6f5d-46dd-9aa5-4601bf4d09f4), 2nd result is 'Omniscan', brand name of [gadodiamide](https://en.wikipedia.org/wiki/Gadodiamide).

**Comment by dnsmith124** [comment]
Where does responsibility for addressing this lie exactly? Considering the ruling for this comes from the NIH style guide I would think we'd want to address this as far upstream as possible, though I'm willing to be overruled!

**Comment by sierra-moxon** [comment]
@vdancik @sandrine-m - as our resident chemical experts - do you know which KPs could be providing chemicals via brand names?  And do you have any sources that map brand names to generic forms that we could use in name resolver?

**Comment by jh111** [comment]
RxNorm will map brand names to ingredient(s) and/or specific ingredient(s)

**Comment by andrewsu** [comment]
tagging @gaurav 

This result comes from BTE, but I believe this is a nodenorm issue. BTE uses node labels from the nodenorm service (and I believe even if we didn't, ARS would also overwrite ARA-provided labels with ones from node norm).  In the case of `PUBCHEM.COMPOUND:24847884`, nodenorm's official label is "Omniscan":

https://nodenorm.transltr.io/1.3/get_normalized_nodes?curie=PUBCHEM.COMPOUND:24847884

The Avonex example also comes from BTE, but that one is a little different.  Semmeddb finds an `Avonex - treats - MS` edge from semmeddb, and semmeddb of course uses UMLS identifiers.  UMLS has an Avonex identifier [C0594372](https://uts.nlm.nih.gov/uts/umls/concept/C0594372) that is separate and distinct from other related identifiers, e.g., [C0254119](https://uts.nlm.nih.gov/uts/umls/concept/C0254119) for `interferon beta-1a`.  So this is probably also a nodenorm issue, but more of a clustering issue.

**Comment by gaurav** [comment]
We do a better job of this now (for example, [PUBCHEM.COMPOUND:24847884 is now labeled "gadodiamide"](https://nodenorm.transltr.io/get_normalized_nodes?curie=PUBCHEM.COMPOUND:24847884). I'm not sure if there's a good way to test this at scale -- I can export a massive list of preferred labels without too much work, but it'll be a very long list. Any ideas?

For interferon beta-1a, we should be combining both into UNII:XRO4566Q4R "interferon beta-1a", but [we don't](https://nodenormalization-sri.renci.org/1.5/get_normalized_nodes?curie=UMLS%3AC0594372&curie=UMLS%3AC0254119&curie=UNII%3AXRO4566Q4R&conflate=true&drug_chemical_conflate=true&description=false). I'll look into how to fix this in Hammerhead.

**Comment by sandrine-muller-research** [comment]
@gaurav I can help you with testing things (fail test for brand names?). Perhaps this could be a good topic for the testing meeting @maximusunc ?

**Comment by sstemann** [comment]
in the Hammerhead release on Test Multiple Sclerosis

https://ui.test.transltr.io/results?l=Multiple%20Sclerosis&i=MONDO:0005301&t=0&r=0&q=4f9e38a4-e3ef-46d6-b04a-bad322b5526e

No Avonex, Interferon does return

Ehlers-Danlos syndrome, vascular type
https://ui.test.transltr.io/results?l=Ehlers-danlos%20Syndrome,%20Vascular%20Type&i=MONDO:0017314&t=0&r=0&q=a9e005b3-70eb-4de5-8e17-411da4725337

No Omniscan, Gadodiamide does return.

Closing for now.
