### ISSUE TITLE
Results not supported by reference; drug/compound returned is wrong and doesn't match with publication

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#463]
Query: What drug may treat Rabies?
https://ui.transltr.io/results?l=Rabies&i=MONDO:0019173&t=0&q=f6a8e64c-c40e-4151-aadf-978a6d40c936

Results include (number 2 and 3) Methionine and Cefaclor, both pointing to the same [article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4243955/):

![Screen Shot 2023-08-08 at 4 06 07 PM](https://github.com/NCATSTranslator/Feedback/assets/1442197/5e429f99-7b07-4973-96ac-b33c0143b485)

Neither Methionine nor Cefaclor are mentioned in the text of the paper. The paper is about Met-ccl5, which seems to be methionylated Ccl5 (found in one of the references). Not sure how Met-Ccl5 gets translated into Methionine/Cefaclor, but it is not correct.

Here's the source in the UI:

![Screen Shot 2023-08-08 at 3 59 38 PM](https://github.com/NCATSTranslator/Feedback/assets/1442197/fd0815f9-fbb3-481c-86b8-2c0d95501580)

Also, Met-Ccl5 is not returned as a result, even though it might have been expected based on the paper linked above.

**Comment by gglusman** [comment]
Noting that Met is a standard abbreviation for Methionine and CCL (without the 5) is a valid abbreviation for Cefaclor.
Still, obviously in error!

**Comment by sstemann** [comment]
i cant replicate this on Test or Prod, I'm going to close it.  

https://ui.transltr.io/results?l=Rabies&i=MONDO:0019173&t=0&r=0&q=c95ff9e9-5fc1-4170-a050-ab989fbc1239

https://ui.test.transltr.io/results?l=Rabies&i=MONDO:0019173&t=0&r=0&q=ad2efedc-f0fe-4c2d-a705-0eb11188fe00
