### ISSUE TITLE
Add a check-box or button for "always hide graph view" 

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#467]
While the graph view might be very useful for some purposes, I find that it make sit harder to view the results. The "Hide graph view" button is great, but I have to redo it for every result I want to review. It would be nice to have a button or check-box at the top somewhere to set "Hide graph view" as the default state.

**Comment by sierra-moxon** [comment]
+1

**Comment by dnsmith124** [comment]
This is coming as part of the user accounts implementation and is completed but waiting to be deployed. 

We currently have a set of user preferences that include an option to display graphs "Always", "Sometimes" (meaning when the # of paths > 1, this is the behavior now), and "Never". So you will be able to do this by September!

**Comment by sstemann** [comment]
deployed to prod 9/6
