### ISSUE TITLE
a drug name is "RNA sequence"

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#47]
## Steps to reproduce:
What drugs may treat Focal segmental glomerulosclerosis?

**Comment by sandrine-m** [comment]
<img width="974" alt="image" src="https://user-images.githubusercontent.com/66342541/204110927-305bc89b-84ba-47e1-844e-8466dfb85554.png">

**Comment by sandrine-m** [comment]
Improvement: "synthetic drugs may treat FSGS" Not very intelligent answer (arrives in the top 60)
<img width="968" alt="image" src="https://user-images.githubusercontent.com/66342541/204111093-cf1f2d64-5991-4528-9d69-d26c3237ccd4.png">

**Comment by sandrine-m** [comment]
For O&O: for this question, I would have liked to be able to rank the answers by the "evidence" = number of paths found for each meta edge.

**Comment by sierra-moxon** [comment]
splitting this issue into three: 
- [ ] RNA sequence is not a drug
- [ ] Synthetic drugs is not a very good result for the question "what drugs may treat disease"
- [ ] Ordering by number of evidences is important.

**Comment by sierra-moxon** [comment]
closing this parent ticket in favor of the two tickets I split here, which may have different fixes.  Please reopen if I got this wrong @sandrine-m  :)
