### ISSUE TITLE
CFTR is a gene and should be found. There are FDA approved drugs/chemicals that regulate it (eg Ivacaftor) 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#472]
## Steps to reproduce:
selected gene/chemical and entered CFTR in search (cystic fibrosis gene) --was not found

**Comment by sandrine-m** [comment]
<img width="1274" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/1ed6b55b-eb98-4b47-a535-34e9e30c3a31">
[NameRes in RENCI dev ](https://name-resolution-sri-dev.apps.renci.org/lookup?string=CFTR&offset=0&limit=10) does find the gene.

**Comment by gaurav** [comment]
This is because https://ui.ci.transltr.io/ is still using the [previous version of NameRes](https://name-lookup-dev.apps.renci.org/docs) without sorting by CURIE suffix. Once they update to the latest version of NameRes, this should work and then we can close this issue.

**Comment by gaurav** [comment]
Now working on UI Prod! Closing.

![Screenshot 2023-10-19 at 5 26 18 PM](https://github.com/NCATSTranslator/Feedback/assets/23979/0bc2b38f-25c8-4c4d-95a4-adb8730a112a)
