### ISSUE TITLE
Liberal usage of treats in TMKP

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#473]
this issue is a split ticket from #468 

@gglusman was testing Upon re-re-testing what drugs may treat [Familial Pityriasis Rubra Pilaris](https://monarchinitiative.org/disease/MONDO:0008251) ([on ci](https://ui.ci.transltr.io/results?l=Familial%20Pityriasis%20Rubra%20Pilaris&i=MONDO:0008251&t=0&q=19f03de9-d166-413a-9495-8e438869caa1)), and comparing to [the previous test](https://ui.ci.transltr.io/results?l=Familial%20Pityriasis%20Rubra%20Pilaris&i=MONDO:0008251&t=0&q=1fe9cae2-1531-44c9-9053-6fdb52b500e3)

She encountered the following statement:
The 'retinol (aka vitamin A) treats PRP' triple cites as provenance [just one paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5440448/) about acne. The actual relevant content in the paper:
In 1953, [Sidney Q. Cohlan (1953)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5440448/#bb0015) observed that high doses of vitamin A had teratogenic effects on pregnant rats. G. L. Peck was initially researching vitamin A for the treatment of Darier’s disease, ichthyosis, and pityriasis rubra pilaris and discovered its therapeutic effects on acne vulgaris. [Peck et al. (1979)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5440448/#bb0095) also counseled on contraception, [...]

Her following assessment is that : a 1979 paper mentions in passing that someone was initially researching using X for the treatment of Y, and this is interpreted to mean that X treats Y. This is not necessarily a semmed filtering issue. Of note, this is significantly weaker evidence of X actually treating Y than if there is a clinical trial testing the effectiveness of X in the treatment of Y... and we were told we cannot derive 'X treats Y' from the presence of such a clinical trial.

**Comment by andrewsu** [comment]
could be an argument to do some benchmark testing to see if a pmid_count threshold would help TMPK as well, following the analysis of semmeddb in https://github.com/NCATSTranslator/Feedback/issues/100.

**Comment by sandrine-m** [comment]
agree. That is why at first I mistriaged it in EPIC:SEMMED...  I'll watch out for other examples. What would we need to do so? any timeframe for such activities? Was an overlap before/after pmid_count correction done between SEMMED and TMKP (i.e. could we use cleaner SEMMED to inform TMKP edges? 
Please let me know how you would like such examples to be triaged (= if more examples to come, should we create a METALIST of TMKP issues to test the pmid_count parameter? )

**Comment by sandrine-muller-research** [comment]
Retested today on [TEST](https://ui.test.transltr.io/main/results?l=Familial%20Pityriasis%20Rubra%20Pilaris&i=MONDO:0008251&t=0&q=c009d2b0-116e-4fe8-a5f8-630e541faa22)

**Comment by sstemann** [comment]
retested on Hammerhead in Prod, and looks like OBE, I dont get this pub in the Vitamin A results which are now supported only by two hop support graphs

https://ui.test.transltr.io/results?l=Familial%20Pityriasis%20Rubra%20Pilaris&i=MONDO:0008251&t=0&r=0&q=4b0eea45-9cc1-4a4b-bee6-42298673d3be
