### ISSUE TITLE
add provenance on edges is input of and has input

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#474]
This issue is a split ticket from issue #468 

@gglusman is testing what drugs may treat [Familial Pityriasis Rubra Pilaris](https://monarchinitiative.org/disease/MONDO:0008251) ([on ci](https://ui.ci.transltr.io/results?l=Familial%20Pityriasis%20Rubra%20Pilaris&i=MONDO:0008251&t=0&q=19f03de9-d166-413a-9495-8e438869caa1)), she found `is_input_of` and `has_input` edges with no associated evidence (Retinal, 9-cis- result).
<img width="743" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/23e8e24f-7156-414b-80b9-6910fdd6bbb5">

**Comment by sandrine-m** [comment]
On ARAX UI, it looks like these edges are in ARAGORN aux graph for Retinal, 9-cis- and reports the following sources:
<img width="1144" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/307b9911-3eae-4e1f-9910-8ebf216342ab">

**Comment by Genomewide** [comment]
@gprice1129 @dnsmith124 I don't see anything weird in the JSON from this result.  See edge json below. It has a primary knowledge source = infores:sri-ontology. Not sure why the EPC does not show the link to that as sources.  

`                        "9538f3aa9b91": {
                            "object": "PUBCHEM.COMPOUND:1070",
                            "sources": [
                                {
                                    "resource_id": "infores:sri-ontology",
                                    "resource_role": "primary_knowledge_source"
                                },
                                {
                                    "resource_id": "infores:automat-ubergraph",
                                    "resource_role": "aggregator_knowledge_source",
                                    "upstream_resource_ids": [
                                        "infores:sri-ontology"
                                    ]
                                },
                                {
                                    "resource_id": "infores:aragorn",
                                    "resource_role": "aggregator_knowledge_source",
                                    "upstream_resource_ids": [
                                        "infores:automat-ubergraph"
                                    ]
                                },
                                {
                                    "resource_id": "infores:ara-aragorn",
                                    "resource_role": "aggregator_knowledge_source",
                                    "source_record_urls": null,
                                    "upstream_resource_ids": null
                                }
                            ],
                            "subject": "GO:0005503",
                            "predicate": "biolink:has_input",
                            "attributes": [
                                {
                                    "value": 1,
                                    "value_type_id": "EDAM:data_1669",
                                    "attribute_type_id": "biolink:has_numeric_value",
                                    "original_attribute_name": "weight"
                                }
                            ]
                        },`

**Comment by gprice1129** [comment]
This has to do with us having an old infores catalog. This fix will be part of a larger update that is coming.

**Comment by sstemann** [comment]
seems to be working:
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/af6e9967-cb94-46ae-8875-3e8931b1d42b)
