### ISSUE TITLE
Small typo in Help Topics

### ISSUE THREAD

**Issue by codewarrior2000** [NCATSTranslator/Feedback#475]
This is just a comment on a "parallel syntax" in the [Evidence page](https://ui.transltr.io/evidence) of Help Topics (https://ui.transltr.io/evidence).  Removing one word, "the", will correct the parallelism between two intended syntactic equivalent clauses in the following statement.

_"A smaller P value means a higher chance of an incorrect null hypothesis or **the** presumption that differences between data sets are insubstantial._"

As a grammatical test, if the two clauses in the statement were parsed into separate statements, they would be:
1. A smaller P value means a higher chance of an incorrect null hypothesis.
2. A smaller P value means **the** presumption that differences between data sets are insubstantial.

The risk is that the reader would perceive two opposite definitions of "smaller P value".

However, if the word "the" was removed, the two parsed clauses would be:
1. A smaller P value means a higher chance of an incorrect null hypothesis.
2. A smaller P value means a higher chance of an incorrect presumption that differences between data sets are insubstantial.

**Comment by gglusman** [comment]
How about:
"A smaller P value means a higher chance of an incorrect null hypothesis, which is the presumption that differences between data sets are insubstantial."

**Comment by codewarrior2000** [comment]
I like it! 
What about using the nonrestrictive clause in the past tense?
"A smaller P value means a higher chance of an incorrect null hypothesis, which was the presumption that differences between data sets are insubstantial."

**Comment by gglusman** [comment]
That sounds a bit more confusing to me. In the present tense it's meant to serve as a definition.

**Comment by sstemann** [comment]
OBE this page is gone
