### ISSUE TITLE
snail preparation ... of the wrong snails

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#478]
https://ui.ci.transltr.io/demo/results?l=Aggressive%20Systemic%20Mastocytosis&i=MONDO:0020333&t=0&q=c0e8f2ed-8e10-4711-bd5f-fed713672e02

<img width="829" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/3977332/735b06a3-d7c7-4bf8-a830-69d898fad6c4">
The three papers supporting the "Snail Preparation Causes Decreased Activity Or Abundance Of Pcna" edge talk about snail-family transcription factors, not about snails.
The 'snail preparation' node links out to the very uninformative http://linkedlifedata.com/resource/umls/id/C3535672<br/><br/>
@gprice1129 edited this to a modern link structure

**Comment by sierra-moxon** [comment]
"Wash them carefully and blanch in boiling salted water for 5 minutes. Take each snail out of its shell and remove the black part of the tail. Wash the snails again in plenty of water, then boil them for 2 hours in a well-seasoned court-bouillon with white wine."  -- no.

@gglusman @gaurav - another item for the block list?  Just for my understanding, is "adding to the blocklist" something that can be done right up to release, or does it need to be done ahead so things can rebuild before it takes effect?

**Comment by gaurav** [comment]
> @gaurav - another item for the block list? Just for my understanding, is "adding to the blocklist" something that can be done right up to release, or does it need to be done ahead so things can rebuild before it takes effect?

We don't currently have a blocklist for answers/results, only for autocomplete. The autocomplete blocklist _should_ be very easy to change at any time (restarting a NameRes deployment will cause it to redownload the latest block list and delete those concepts), but I think autocomplete should be frozen whenever the UI is frozen so that nothing changes unexpectedly thereafter.

**Comment by bill-baumgartner** [comment]
Thanks. I caught this one during some recent error analysis as well. It will be excluded from future releases of TMKP data. I will close this issue when the change makes it into our data release.

**Comment by gglusman** [comment]
Still observed in results. https://ui.test.transltr.io/main/results?l=Aggressive+Systemic+Mastocytosis&i=MONDO%3A0020333&t=0&r=886b1372&q=246f5c17-fd36-4980-92fe-e8cf105e53fc

**Comment by bill-baumgartner** [comment]
There is a new version of our KG deployed to CI that addresses this issue. There is an older version of our KG still being used (cached) by Unsecret Agent in CI, however, so the result is still observed. We are working with Unsecret Agent to resolve this.

**Comment by gaurav** [comment]
Do we still want to add this to the Results Blocklist?

**Comment by gaurav** [comment]
I've just confirmed that searching for "snail" returns some odd results in Autocomplete, but nothing offensive or that needs to be blocked, I think:

<img width="1170" alt="Screenshot 2024-02-23 at 1 56 54 AM" src="https://github.com/NCATSTranslator/Feedback/assets/23979/d48d8aa3-dfd3-41c4-9f93-85cce4fcb912">

* Schneckenbecken Dysplasia (matched on Chondrodysplasia With Snail-like Pelvis)
* Microtia, Second Degree (matched on Snail Ear)
* Schistosomiasis (matched on Snail Fever)

<img width="1165" alt="Screenshot 2024-02-23 at 1 57 57 AM" src="https://github.com/NCATSTranslator/Feedback/assets/23979/2431bc8b-16bd-44c9-aaeb-7d052769ab16">

* Snail Venom
* Snail/hdac-in-1

**Comment by sierra-moxon** [comment]
@gaurav - I think we can close this as complete based on your comment and no other disagreements :D - please reopen if necessary, of course.
