### ISSUE TITLE
Tobacco smoke "may treat" Huntingtons Disease

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#48]
https://arax.ncats.io/?r=a9283f17-127b-41ce-abb1-65ee32de3fa8

In ARAX, I see "genetic association" as expected. 
<img width="870" alt="Screen Shot 2022-11-30 at 4 45 59 PM" src="https://user-images.githubusercontent.com/4561292/204938775-507e5196-4bbf-4374-ac06-49942fd71ffa.png">

However, beyond `Tic Association` it might be good to understand how the "increases response to" predicate is being used in creative mode.  

@cbizon - if I look at the associated metadata in Biolink for "increases response to" in biolink, this use in Robokop is not technically an error or violation of the model.  But if I read the definition of the predicate, its tricky to insert a chemical for the domain and a gene for the range.  For this triple, are we trying to say "tobacco smoke exacerbates the effects (increases the response to) of _mutations_ in GSTP1? 

<img width="658" alt="Screen Shot 2022-11-30 at 4 49 41 PM" src="https://user-images.githubusercontent.com/4561292/204939374-efd1967a-6d35-424e-af63-45f4d9945527.png">

**Comment by sierra-moxon** [comment]
From TAQA: 
- question is, should we group chemicals/treatments into groups?  (let's put it in front of the users?)
- we do need to tag/group

The "orange book" is published by the DEA
GSRS tags substances with it in the NCATS GSRS instance

Another tag for grouping, discussed during Wednesday's TCDC call, is by whether or not there is RWE for the use of a drug, e.g., Adderall (mixed amphetamine).

**Comment by sierra-moxon** [comment]
Is there a particular KP that will volunteer to extract and load these additional "tags"?  

@vdancik are "orange book" tags something that is relevant for MolePro?  

@karafecho - from the TCDC, are there any groups that can provide the RWE piece here?  What attributes would we return from the TCDC that could be used to clarify "tobacco smoke may treat Huntington's Disease" to a user?

**Comment by karafecho** [comment]
I'm not sure any of the clinical KPs have data on tobacco use (or vaping, etc). I know that we (Exposures Provider) intentionally do not attempt to capture that data field because (1) it is very sparse and (2) even if someone is asked, they tend to lie. :-)

**Comment by gglusman** [comment]
We actually do have such data. Indeed responses can be not fully reliable, but then some metabolomics data can show a different picture. ;)

**Comment by sierra-moxon** [comment]
This is being handled by Architecture committee; do not need to review in TAQA.

**Comment by cbizon** [comment]
I think that this should be handled by putting the relevant information into Chunlei's Annotation Server.

**Comment by sierra-moxon** [comment]
06/22/23 - retesting 
I can no longer find tobacco smoke treats Huntington Disease.   closing as complete! :)
