### ISSUE TITLE
Vehicle Emissions as a Treatment

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#480]
Requesting that Vehicle Emissions be on the block list for result for MVP1.  

Unsecret returns it in CI and Test

CI:  https://ui.ci.transltr.io/results?l=Castleman%20Disease&i=MONDO:0015564&t=0&q=23017da1-cd67-4f5a-9323-8d16848a52ea

CI ARAX GUI:  https://arax.ncats.io/?r=23017da1-cd67-4f5a-9323-8d16848a52ea

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/0f9f4ad7-58ef-4f12-a181-9143c751299c)

Test:  https://ui.test.transltr.io/results?l=Castleman%20Disease&i=MONDO:0015564&t=0&q=1f0281fd-36e1-4b52-8f1a-1408f342f2dc

Test ARAX GUI:  https://arax.ncats.io/?r=1f0281fd-36e1-4b52-8f1a-1408f342f2dc

**Comment by sstemann** [comment]
@sierra-moxon i dont really know where the block list lives, or how it works for results, do you?

**Comment by gglusman** [comment]
We were trying to figure that out in #471

**Comment by sandrine-m** [comment]
Putting the label _category too generic_ as I think this labels deals with the blocklist action point but it is in real an _opposite of for I asked for_ : vehicule emissions can cause diseases but not treat.

**Comment by sandrine-muller-research** [comment]
retested today on [PROD](https://ui.transltr.io/main/results?l=Castleman%20Disease&i=MONDO:0015564&t=0&q=578ee27e-e4d8-45df-bf71-76cde364049d) (reproduced):
<img width="1250" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/9b069c95-e837-46a0-a545-2064b0ac77a5">

**Comment by kaiwenho** [comment]
"Vehicle Emissions" has been eliminated from all results returned by mediKanren. If this feedback is solely about not returning Vehicle Emissions as a treatment, it is safe to close it now. 
On TEST today: https://ui.test.transltr.io/main/results?l=Castleman+Disease&i=MONDO%3A0015564&t=0&r=90645ef8&q=3f4e27b2-ae6c-4b5d-8388-4fca90dce651
