### ISSUE TITLE
Can substances be both FDA Approved and Not FDA Approved?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#482]
UI CI > MVP2 > What chemical upregulates BRCA1 (human) 

https://ui.ci.transltr.io/results?l=BRCA1&i=NCBIGene:672&t=1&q=5817478c-c887-47b6-9f41-0c0c6f236e22

Click FDA Approved - Nicotinic Acid at the top
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/99a6c03b-eee6-4709-b4a6-aeb35a087b1b)

Unselect FDA Approved, Click Not FDA Approved - Nicotinic Acid at the top
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/9e7b7192-dc14-40d8-8b7d-b026f0dbb930)

**Comment by sstemann** [comment]
not sure if this is happening at the UI or Annotator?

**Comment by Genomewide** [comment]
Yes. They are 'schrodinger's compounds' that have not been observed yet.  
But seriously, this is going to change soon. FDA and answer type will be combined into 'drug' 'in clinical trial (level n)' and 'other'. 

Also, Gus is aware of the issue of not adding up. So, I think it will all get changed together. I just tagged him here.

**Comment by sstemann** [comment]
looks resolved!
