### ISSUE TITLE
Known drugs not found (and other issues) for What treats Hookworm Infectious Disease

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#483]
**Query 1:** What drugs may treat Hookworm Infectious Disease? (MONDO:0005799)

CI: https://ui.ci.transltr.io/results?l=Hookworm%20Infectious%20Disease&i=MONDO:0005799&t=0&q=95b9cf5c-f99a-43bc-9ecb-168ad0681677
Results: None

Test: https://ui.test.transltr.io/results?l=Hookworm%20Infectious%20Disease&i=MONDO:0005799&t=0&q=4e75ab7f-f5de-4d0f-b137-8f7d1b0a7130
Results: 500. Known treatments [albendazole](https://en.wikipedia.org/wiki/Albendazole) and [mebendazole](https://en.wikipedia.org/wiki/Mebendazole) are NOT found.

UI: https://ui.transltr.io/results?l=Hookworm%20Infectious%20Disease&i=MONDO:0005799&t=0&q=3c676b42-ddd5-4838-8061-363c9902941f
Results: 500
Problems:
- Searching for albendazole or mebendazole gives multiple results, but none of them are direct "x-treats-y" interactions but rather 2-hop results for something else, see below for example.

![Screen Shot 2023-08-15 at 11 03 54 AM](https://github.com/NCATSTranslator/Feedback/assets/1442197/de833e5f-ec01-41bc-85c9-d387e47fc2d1)

- Many of the top-scoring results are for the more general term "infectious disease", for example:

![Screen Shot 2023-08-15 at 11 37 06 AM](https://github.com/NCATSTranslator/Feedback/assets/1442197/3520b666-fb0d-4a11-88ea-7107e3647ba3)

**Query 2:** What drugs may treat Ancylostomiasis? (MONDO:0005645)

When typing in "hookworm disease" the autocomplete shows "Ancylostomiasis (matched on Hookworm infectious disease)" so I decided to try that instead. (Ancylostomiasis is disease from a subset of hookworms, [Ancylostoma](https://en.wikipedia.org/wiki/Ancylostoma))

CI: https://ui.ci.transltr.io/results?l=Ancylostomiasis&i=MONDO:0005645&t=0&q=a814bf56-0d3e-431a-bf4f-3b2e2d4e7d18
Results: 519. 
- Albendazole is found, but with a not-great score of ~85, after things like Air, Date allergenic extract etc
- Mebendazole is found with a very low score of 25

Test: https://ui.test.transltr.io/results?l=Ancylostomiasis&i=MONDO:0005645&t=0&q=0fe7a2ea-bc4d-49ef-9f75-0727b6fe6b8b
Results: 512
- Albendazole is the top result!
- Mebendazole also found

UI: https://ui.transltr.io/results?l=Ancylostomiasis&i=MONDO:0005645&t=0&q=7e80ae67-46c2-4f87-ab46-0cdaa899fb89
Results: 8
- Mebendazole and Albendazole both found.

**Comment by khanspers** [comment]
Ran the query 1 (What drugs may treat Hookworm Infectious Disease?) on ui.transltr.io and got 4 answers: Mebendazole, Pyranthel, Thiabendazole and Dichlorophen. The first 3 are correct but the last one, Dichlorophen, is a veterinary drug not used in people. Still missing from results:  Albendazole (one of the two main treatments for hookworm)

**Comment by sierra-moxon** [comment]
from TAQA: using the "test asset" label to mark that this ticket has been converted into a series of P/F tests in the information radiator.

**Comment by sierra-moxon** [comment]
from TAQA: 
we need to identify the test asset id that this is formalized in and then see which ARAs need to do work and assign out. 
(sierra will track down)

**Comment by khanspers** [comment]
Latest test in test gives the same 4 results: https://ui.test.transltr.io/main/results?l=Hookworm%20Infectious%20Disease&i=MONDO:0005799&t=0&r=0&q=fabee1a2-2569-4f4c-bf44-6792dec7c336

Still no Albendazole.

**Comment by khanspers** [comment]
Tested on test again today and Albendazole is now returned as an answer for MONDO:0005799 (Hookworm Infectious Disease).

**Comment by sstemann** [comment]
we're getting both answers in Test.  while [Albendazole ](https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6c48fd89-cb40-477c-8a78-15cbe0df6faa)is lower, per DailyMed its indicated for pork and dog tapeworm, whereas [Mebendazole ](https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fa778759-2b9a-4446-ba06-d3c486019e79)is indicated for hookworm.

![image](https://github.com/user-attachments/assets/61fa9da8-cf50-4a01-8103-1a6525f8ea82)

https://ui.test.transltr.io/main/results?l=Hookworm%20Infectious%20Disease&i=MONDO:0005799&t=0&r=0&q=070cea6c-fb4b-40a9-923a-0fdfa666670e
