### ISSUE TITLE
"Synthetic drugs" as an answer should be pushed lower in the return, or not returned in a search for FSGS

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#49]
Originally documented by Sandrine in [an issue](https://github.com/NCATSTranslator/Feedback/issues/47) that was split:
Improvement: "synthetic drugs may treat FSGS" Not very intelligent answer (arrives in the top 60)
<img width="968" alt="image" src="https://user-images.githubusercontent.com/66342541/204111093-cf1f2d64-5991-4528-9d69-d26c3237ccd4.png">

**Comment by karafecho** [comment]
Related issue: 

What drugs may treat fentanyl overdose? First answer is naloxone (yay!); second answer is antidote (not very helpful).

**Comment by sharatisrani** [comment]
To be covered by @flannick TAQA breakout on Jul 13.

**Comment by sierra-moxon** [comment]
closing as a result of "fentanyl overdose" no longer being searchable in TEST.
