### ISSUE TITLE
filter pesticdes and poisons from ChEBI roles in responses

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#490]
## Steps to reproduce:
MVP1 on Premature menopause
select Poison ChEBI role

**Comment by sandrine-m** [comment]
Hexadrin in a highly toxic pesticide, I suggest it get removed from the responses:
<img width="182" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/d700dfe0-34b9-4b8f-aeef-1d049b254a4a">

**Comment by sandrine-muller-research** [comment]
[Retested today](https://ui.ci.transltr.io/main/results?l=Premature%20Menopause&i=MONDO:0001119&t=0&q=58c40fd1-2c87-44be-9730-ab1e24b61985):
Poison does not appear in the ChEBI roles anymore but pesticides do: 
<img width="1255" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/b129c689-8b7a-422f-8f6b-498f05d51c35">

**Comment by sandrine-muller-research** [comment]
As noted by @gglusman in #601 it can happen that some pesticides are also used for therapeutics (the ergocalciferol case) so a block list is not a solution.
