### ISSUE TITLE
Results returned from ARA, and the score is 0, so seguno is 0

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#493]
Steps to Reproduce:

1. Test UI > Run MVP1 for Aortic Valve Stenosis
https://ui.test.transltr.io/results?l=Aortic%20Valve%20Stenosis&i=MONDO:0042981&t=0&q=84b2a619-0536-4a64-81b0-874102ac92bd

2.   Go to Andy's Google Colab which takes an original PK, finds the merged PK, and flattens the results at the result level:  https://colab.research.google.com/drive/1p2MKFxvPouMI59_p5b59asIQ1x1FgpUK?usp=sharing

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/a339b01c-b5d1-4dfb-83cb-9916b5b633b4)

4.  View the file attached here 
[aortic valve stenosis_84b2a619-0536-4a64-81b0-874102ac92bd_2023_8_24_21_34.xlsx](https://github.com/NCATSTranslator/Feedback/files/12433566/aortic.valve.stenosis_84b2a619-0536-4a64-81b0-874102ac92bd_2023_8_24_21_34.xlsx)

AVS Original PK:  84b2a619-0536-4a64-81b0-874102ac92bd
AVS MERGED PK:  61e54aed-57c4-45bb-9af8-1ac90fc262be
AVS MERGED JSON is here:  https://drive.google.com/file/d/1rq-WGOTEERfdUQk6z5k4OXea_08lE_Sw/view?usp=drive_link

5. Filter Column G "component_confidence" to 0  
6. Column V will inform you which ARA returned the result

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/1fe9176a-07db-42b4-92e2-9eea961483a6)

7. (View merged results PK 61e54aed-57c4-45bb-9af8-1ac90fc262be in the ARAX GUI:  https://arax.ncats.io/beta/?r=61e54aed-57c4-45bb-9af8-1ac90fc262be (it does take awhile to load)

8. Go to result 2-Allylthio-6-amino-3-benzyl-quinazolin-4(3H)-one

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/fae19b51-1576-4814-98ab-7586a497f276)

Also happens on MVP2
https://ui.test.transltr.io/results?l=GALT&i=NCBIGene:2592&t=1&q=05877abb-92d7-49ff-bc4d-413c57d2155b

[GALT_05877abb-92d7-49ff-bc4d-413c57d2155b_2023_8_24_21_56.xlsx](https://github.com/NCATSTranslator/Feedback/files/12433712/GALT_05877abb-92d7-49ff-bc4d-413c57d2155b_2023_8_24_21_56.xlsx)

GALT Original PK:  05877abb-92d7-49ff-bc4d-413c57d2155b
GALT MERGED PK:  37b7db35-9db3-4fe5-92bb-454353b40a56
GALT MERGED JSON:  https://drive.google.com/file/d/1rq-WGOTEERfdUQk6z5k4OXea_08lE_Sw/view?usp=drive_link

**Comment by sstemann** [comment]
@brettasmi @suihuang-ISB on one of the calls today, Tyler Beck mentioned that any results with Seguno = 0 will be blocked from the UI, typically, the Seguno has been 0 when the ARA Component of the Seguno is 0.  this is happening when the result is returned but no ARA gives it a score > 0.  Through investigation, it seems Improve is the primary source of this situation.

**Comment by brettasmi** [comment]
To the extent possible, we plan to fix this for MVP1 by early next week. This won't require any code changes, rather we will just be adding some more scoring data in the backend.

We are working on the equivalent fix for MVP2, though that will require some assistance from ITRB. Still, it should be much better by launch.

**Comment by cbizon** [comment]
So just to make sure I understand - Improving is the only ARA returning score=0, and the problem arises when it has unique answers.   

Is that right @sstemann ?

**Comment by suihuang-ISB** [comment]
I am not sure if this is the same problem that we have been working on for a while (no score if no clinical evidence) and for which we had found a solution (get a score from purely graph topology based embedding without learning from clinical data).
If that is the case, then this should be purely an implementation issue, and I believe @brettasmi and @karthiksoman have been working on it.

**Comment by brettasmi** [comment]
I have deployed some changes to CI that should alleviate this issue for MVP1 queries where we were failing to score completely, returning lots of 0 scores. If improving answers an MVP1 query it _should_ be scored, but maybe we'll find some edge cases.

We're working on MVP2 queries where the gene is defined (which chemical affect gene X), hopefully that will be implemented soon. The other MVP2 query (which genes are affected by chemical X) is a little more complicated because the huge number of chemicals out there.

@sstemann , @cbizon , should scores NEVER be zero? I thought there was a requirement to score from 0 - 1, which we interpreted as a closed interval (inclusive of 0 and 1). Is that not the case?

**Comment by cbizon** [comment]
Yeah that's a good question.  I think from the architecture / guidelines side, a 0 is in the allowed range.   I does sort of raise the question though of what a 0 score means.  I would interpret it as - this is an answer in which we have 0 confidence.  So while it's in the allowed range, I'd start to question whether we really want it or not.

**Comment by Mathelab** [comment]
Agreed that this needs to be defined clearly.  From what I gather, 0 can also mean 'no score returned', but this all depends on the level (e.g., ARA vs. ARS...). Adding this to O&O group to define clearly.

**Comment by sstemann** [comment]
closing many efforts to address scores are happening in O&O
