### ISSUE TITLE
Proposed benchmarks

### ISSUE THREAD

**Issue by IritR** [NCATSTranslator/Feedback#494]
This is a thread for proposing benchmarks in response to [Data Modeling 8/24/2023](https://docs.google.com/document/d/1Vcpp6ehoq_Ba4NmdRkpSGnWfACfDo4owYqC10hQlE2I/edit)

I will add more as I go along, and anyone is invited to contribute.
-----------

Here are several FDA-approved drugs for treating Gaucher Disease type1: Eliglustat, Imiglucerase, Taliglucerase alfa, Velaglucerase-alfa, Miglustat. They should all score very high.

Approved for Niemann-Pick type C: miglustat

Approved for Familial hypercholesterolemia homozygous (LDLR): Rosuvastatin Lomitapide Mipomersen Evolocumab

Approved for Familial hypercholesterolemia heterozygous (LDLR): Rosuvastatin Evolocumab

Approved for Familial defective apolipoprotein B (APOB): Rosuvastatin Evolocumab

**Comment by andrewsu** [comment]
On the subject of benchmark examples, just want to note that we have several benchmarks related to diseases and treatments that have been systematically harvested in the [Benchmarks repo](https://github.com/TranslatorSRI/Benchmarks). Of particular note are the following:
* [DrugCentral](https://github.com/TranslatorSRI/Benchmarks/blob/main/config/DrugCentral_creative/data_full.tsv): 8675 indications harvested from [DrugCentral](https://drugcentral.org/), mostly for common diseases
* [OOPD](https://github.com/TranslatorSRI/Benchmarks/blob/main/config/OOPD/data_full.tsv): 3915 indications harvested from the [Orphan Drug Designations and Approvals database](https://www.accessdata.fda.gov/scripts/opdlisting/oopd/) created by FDA's Office of Orphan Products Development, mostly for rare diseases
* [GTRx](https://github.com/TranslatorSRI/Benchmarks/blob/main/config/GTRx/data_full.tsv): 695 indications from https://gtrx.radygenomiclab.com/ and [this publication](https://pubmed.ncbi.nlm.nih.gov/35882841/) focused on rare genetic diseases
* [IRDiRC](https://github.com/TranslatorSRI/Benchmarks/blob/main/config/IRDiRC/data.tsv): 120 indications from Table 1 of [this publication](https://ojrd.biomedcentral.com/articles/10.1186/s13023-021-01923-0) focused on rare diseases

Spot checking the examples above against these sources (though note that some of the "not found" examples may be found under alternate names):

* Gaucher Disease type1
   * Eliglustat: found in OOPD
   * Imiglucerase: found in IRDiRC
   * **Taliglucerase alfa: not found**
   * **Velaglucerase-alfa: not found**
   * Miglustat: found in OOPD and IRDiRC

* Niemann-Pick type C
   * miglustat: found in OOPD and GTRx

* Familial hypercholesterolemia homozygous (LDLR)
   *  Rosuvastatin: found in DrugCentral, IRDiRC
   * Lomitapide: found in DrugCentral, IRDiRC
   * **Mipomersen: not found**
   * Evolocumab: found in IRDiRC

* Familial hypercholesterolemia heterozygous (LDLR)
   *  Rosuvastatin: found in DrugCentral
   * **Evolocumab: not found**

* Familial defective apolipoprotein B (APOB)
   * **Rosuvastatin: not found**
   * **Evolocumab: not found**

**Comment by sandrine-muller-research** [comment]
Thank you @IritR ! I have added these to the test assets sheet.

**Comment by cbizon** [comment]
Current benchmarking work is happening in the repo linked above.
