### ISSUE TITLE
soot causes OSA not treats

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#496]
## Steps to reproduce:
1) MVP1 on obstructive sleep apnea
2) search for soot

**Comment by sandrine-m** [comment]
Soot -- treats -- OSA
very interesting result though (as it looks like the genes involved in this response could be a cause of the disease). I am a bit surprised it is ranked so high.

**Comment by sandrine-m** [comment]
Perhaps a way to distinguish the causes from treats would be by comparing the level of evidence on the 2 opposite queries for the same nodes: which paths are the most likely to occur ?

**Comment by sstemann** [comment]
OBE soot is no longer returned
