### ISSUE TITLE
partial_agonism missing from biolink spec

### ISSUE THREAD

**Issue by sandrine-m** [NCATSTranslator/Feedback#499]
This issue stems from #495 pointed out by @edeutsch .
MolePro team retested using the [CI endpoint ](https://ars.ci.transltr.io/ars/api/submit)(directly hitting ARS CI with the above shared message): the validator does not lead to any errors now [see results on ARAX UI](https://arax.ncats.io/?r=cc1f7ba3-878c-443d-b483-702ebf694bd4)
Still returns: 
```
Errors:`
* Knowledge Graph Edge Qualifiers Qualifier Value:
=> Qualifier_type_id for edge has unresolved qualifier_value
	$ infores:dgidb -> infores:molepro
		# partial_agonism:
		- edge_id | qualifier_type_id: 
			PUBCHEM.COMPOUND:5358[biolink:ChemicalEntity]--biolink:affects->NCBIGene:3351[biolink:Gene] | biolink:causal_mechanism_qualifier
```
It seems that `biolink:partial_agonism` is missing from the [biolink model](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml). @sierra-moxon could you please help with that?
For any changes during the code freeze, options were highlighted with @RichardBruskiewich on #498 .

**Comment by RichardBruskiewich** [comment]
@sandrine-m, you have correctly surmised that fixing this is a Biolink Model revision. No change needed in the reasoner-validator implementation.

**Comment by sstemann** [comment]
closed by related ticket
