### ISSUE TITLE
Would be great to have an "export to CSV" option. That would allow me to quickly search in some external program (for example, to find that my positive control appears on page 37 out of 140).

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#5]

**Comment by sstemann** [comment]
Feature is not yet assigned to a release on the UI roadmap but is planned. 

Current workaround is to go to the Dev Tools > Console > New Results, copy/paste this JSON to another editor for viewing.  Keep in mind, it is not TRAPI JSON.

![image](https://user-images.githubusercontent.com/38321826/223856117-9f3b7fc2-4333-4a60-84e2-18ec15e45d31.png)

**Comment by sstemann** [comment]
UI team targeting the June Relay release

**Comment by gprice1129** [comment]
This is done. Closing.
