### ISSUE TITLE
Disclaimer statement does not sufficiently stand out

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#501]
This issue is to report that the disclaimer statement on the UI does not sufficiently stand out to users. Specifically, the font seems to small and perhaps would benefit from a bit more contrast (i.e., different color font? running banner?). This opinion was expressed by several people, including Christine, Tony Hickey (external SME), me, others.

**Comment by gprice1129** [comment]
Can this be closed now @karafecho ?

**Comment by karafecho** [comment]
Yes, thank you, closing ticket now ...
