### ISSUE TITLE
SME received application server issue

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#502]
When testing the CI instance of the UI, one of our external SMEs, Tony Hickey, received an application server error when he attempted to explore the UI. He was working in Safari, and Gwênlyn could not reproduce the error, but I'm reporting it here, just in case it appears again.

**Comment by sandrine-m** [comment]
"Assigning" this ticket to @Genomewide so that he can keep an eye on it. It case it happens again, it could be nice perhaps to have a screenshot to help with the error type.

**Comment by sstemann** [comment]
CI is intented to be less stable

**Comment by karafecho** [comment]
Yes, but the weird part was that no one else on the call had any issues with the CI instance of the UI. We initially thought it was a browser issue, but that turned out to not be the case.
