### ISSUE TITLE
Account - Show Account Login Username

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#509]
some folks have multiple ways to pass through UNA, i think it would be helpful to show which username in the Preferences and in the little icon

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/6e48389e-1904-44c1-a1ea-c7127ec435a4)

**Comment by sstemann** [comment]
is this something that can be added to Lobster1?

**Comment by dnsmith124** [comment]
@sstemann this is currently in design right now, we plan on implementing it next release!

**Comment by sstemann** [comment]
working in test!  thank you!
