### ISSUE TITLE
FAQ > Logging In - Not sure this is the right Heading for the text in this sess

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#510]
Alot of the text is actually not specific to logging in or even features you have access to after logging in

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/3488a3ae-6696-4cc6-9c07-9483c7e69e1b)

**Comment by dnsmith124** [comment]
I'm poised to make whatever changes are deemed appropriate with regard to renaming this section, splitting up the content, etc. 

@Genomewide thoughts on adjustments for this section?

**Comment by Genomewide** [comment]
I created that section as a reminder and could not get screenshots bc of the UNA delays.  I should have removed the header before sending to David.  I am putting that text together now.

**Comment by dnsmith124** [comment]
The help page has been overhauled to make the entire set of topics more informative and detailed. Confirmed the changes are live on test. 

Closing!
