### ISSUE TITLE
During User Login Prompt the User to Accept the Disclaimer

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#511]
The disclaimer text:  This system is for research purposes and is not meant to be used by clinical service providers in the course of treating patients. 

Should be displayed at login and the user should have to acknowledge it before logging in.

**Comment by Genomewide** [comment]
Do you think it needs to be every time they log in?

**Comment by dnsmith124** [comment]
Per discussion on 11/29/23, the disclaimer will be updated to function as follows: 
- On first visit to the site the user will be prompted to accept the disclaimer
- On first login the user will be prompted to accept the disclaimer
- Once per year after that the a user logging in will be prompted to accept the disclaimer.

**Comment by Genomewide** [comment]
This is on our list. So, I am closing it.

**Comment by dnsmith124** [comment]
The above behavior has been implemented and is now live on CI!
