### ISSUE TITLE
Chemical Categories and ChEBI Role Classifications Missing - CI, Test and Prod

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#513]
On 9/5, Sierra Moxon posted a screenshot that showed results with filters for Chemical Categories and ChEBI Role Classification as well as pill labels for ChEBI Role Classifications.  I'm not seeing those in CI, Test or Prod.  MVP1 or MVP2 (MVP2 is the same query that Sierra sent)

09/05

![Sierra SOX1](https://github.com/NCATSTranslator/Feedback/assets/38321826/d1fb85ab-73be-4eff-9524-36c25290dc47)

MVP1
![Cowden Test](https://github.com/NCATSTranslator/Feedback/assets/38321826/8fe8ab29-3766-4d9e-8464-387efe8a464d)
![Cowden CI](https://github.com/NCATSTranslator/Feedback/assets/38321826/d165ee5c-f6ce-4574-b90d-e8aad3e59ae3)
![Cowden Prod](https://github.com/NCATSTranslator/Feedback/assets/38321826/86ea5cba-a005-47b4-9a49-ef68799ea3a3)

MVP2

![Sox1 CI](https://github.com/NCATSTranslator/Feedback/assets/38321826/e02a5bc1-c8dc-4636-bcc3-2b74a5398cbd)
<img width="950" alt="Sox1 Test Complete" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/3f0fa945-3a7e-4eca-a05e-6c533cf7bae9">
<img width="943" alt="Sox1 Prod" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/cbc95d17-f2c7-499d-bdbc-d5810599d351">

**Comment by dnsmith124** [comment]
I'm looking into this this morning, it appears we may not be recieving the data from the annotation server that we should.

**Comment by dnsmith124** [comment]
Coordinated with Gus on this. Here is what is going on with the CHEBI roles:
- CI: The service was down, it appears to have been brought back up again. 
- Test: The service appeared to be completely gone. Chunlei restored it, so it is back up again. 
- Prod: There was an error in our configuration which has been resolved locally. Will be resolved upon our next deployment to prod. 

So to summarize: CHEBI roles in CI and Test are fixed, prod will be fixed on next deploy

Will close once it is resolved on prod.
