### ISSUE TITLE
More Prominent Disclaimer Banner

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#514]
In addition to #511 it was also discussed that in general, the disclaimer banner isn't prominent enough.

**Comment by dnsmith124** [comment]
@desiyopp will be performing user testing on several different potential designs to improve the prominence of the disclaimer banner, adding her onto this ticket to keep track of that. 

In the meantime I have increased the font size, height of the banner, and changed the color to something that stands out much more compared to the original purple. 

Before: 
![Screen Shot 2023-09-07 at 10 07 35 AM](https://github.com/NCATSTranslator/Feedback/assets/54226761/d6f29498-a189-496b-bb95-f180c4baf321)

After:
![Screen Shot 2023-09-07 at 10 09 23 AM](https://github.com/NCATSTranslator/Feedback/assets/54226761/8c2c540f-0db8-4e6f-9424-97d450033c77)

This change is now live on CI, will close this ticket once it reaches Test.

**Comment by dnsmith124** [comment]
Confirmed new banner is live on test. 

Closing!
