### ISSUE TITLE
Result for diabetes includes target disease 'progressive encephalomyelitis with rigidity and myoclonus'

### ISSUE THREAD

**Issue by Genomewide** [NCATSTranslator/Feedback#518]
https://ui.ci.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&q=946a46c9-25fc-4127-9c7c-37663c191558

Glyburide result for diabetes includes target disease 'progressive encephalomyelitis with rigidity and myoclonus' (Stiff person syndrome)

This does not appear to be a subclass.

I tried the subclass_of subclss_of and didn't see it. Kaiwen mentioned it could be connected that way.
https://arax.ncats.io/?r=50d79d56-f4fe-4aaf-88d2-f027d38190ee

This just seems off on the connection between the two diseases and it is the top of the results.

**Comment by kaiwenho** [comment]
Thank you for pointing it out! The subclass relationship is from one of the KGs (Robokop)  mediKanren utilizes and here is the data line 

{"subject":"MONDO:0018581","predicate":"biolink:subclass_of","object":"MONDO:0005015","biolink:primary_knowledge_source":"infores:ontological-hierarchy"}

where MONDO:0018581 is [progressive encephalomyelitis with rigidity and myoclonus](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0018581) , and MONDO:0005015 is [diabetes mellitus](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0005015) . 

If this information is not correct, Unsecret will remove it in the next release.

**Comment by cbizon** [comment]
@EvanDietzMorris is this still the case in newer builds?

**Comment by EvanDietzMorris** [comment]
No, looks like that edge has been removed from Ubergraph (and subsequently Robokop) since early this year.

**Comment by kaiwenho** [comment]
Thank you for the information! Unsecret will deploy the latest version of Robokop for the next release.

**Comment by sstemann** [comment]
i'm fairly certain this is resolved
