### ISSUE TITLE
Text Filter - When it matches a node and text the node should be filtered to the top

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#520]
Steps to reproduce:

1. Test UI > MVP2 >FRAS1: 
https://ui.test.transltr.io/main/results?l=FRAS1 (Human)&i=NCBIGene:80144&t=1&q=4841c127-c54a-4808-bb8e-c581fbd2862e
2. Notice Valproic Acid is a result
<img width="875" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/ce20fd80-4582-4a17-bdb6-4ee39ded5558">

3. Reverse sort the results by score (so lowest scores are the first page)
<img width="950" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/da7ad205-e187-4baf-a6f6-0b0552a82ea0">

4. in the Text filter enter "valproic"
5. Not valproic acid is not filtered at the top
<img width="937" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/72e9924f-c962-48aa-bc3c-bd10dc4a3ce2">

**Comment by gglusman** [comment]
The paths being displayed do include valproic acid in them (consistent with the filter), and are the lowest scoring (consistent with the sorting). Isn't this exactly as it should be have?

**Comment by gprice1129** [comment]
The UI team agrees with @gglusman. Filtering and scoring should be independent features.
