### ISSUE TITLE
Is SPOKE still a thing?

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/Feedback#523]
I notice in all the recent queries from ARS in TEST and CI, Spoke no longer shows up. Has Spoke been retired?

https://arax.ci.transltr.io/?latest=10&from=ars.test.transltr.io
![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/c31234b1-ae06-49c9-96c1-429e36d84d23)

https://arax.ci.transltr.io/?latest=10&from=ars.ci.transltr.io
![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/c6795252-d4e6-4928-a42a-33f8d0d9b0fa)

**Comment by brettasmi** [comment]
No, SPOKE hasn't been retired. It is a KP ([SmartAPI](https://smart-api.info/ui/7f70cdfaeb801501da08dacc294e8b9f)), and  it looks like only ARAs are in your images.  Maybe this just has to do with the ARS registrations prior to launch?  @MarkDWilliams ?

**Comment by edeutsch** [comment]
ah okay, my mistake, only ARAs should be in the above lists.
