### ISSUE TITLE
Is ARA robokop still running?

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/Feedback#524]
It seems like whenever I look at recent ARS results, robokop always returns a 404 error. Why is that? Is that okay?

https://arax.ci.transltr.io/?latest=10&from=ars.test.transltr.io
![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/2a24a39c-bbd4-44ea-a101-2bc9471a73b1)

https://arax.ci.transltr.io/?latest=10&from=ars.ci.transltr.io
![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/ffe7c82c-cd60-4d2f-9ba6-b246b72bea2c)

**Comment by edeutsch** [comment]
ah, found this: https://github.com/NCATSTranslator/Relay/issues/473

**Comment by sandrine-m** [comment]
Should we close this issue?

**Comment by edeutsch** [comment]
Does not seem fixed to me

**Comment by uhbrar** [comment]
I don't think it's fixed yet, no. I believe the ARS is still contacting Robokop. However, Robokop has been delisted from smartapi.

**Comment by edeutsch** [comment]
okay, thanks. There seems to be a pretty substantial disconnect between ARS and SmartAPI. What do we want ARS to be doing? I think this may be a topic for the Architecture Cttee? @cbizon ?
See also https://github.com/NCATSTranslator/Relay/issues/501#issuecomment-1712171379

**Comment by sierra-moxon** [comment]
@newgene - just wanted to get your feedback on the next steps here to hopefully resolve the disconnect between ARS and SmartAPI that @edeutsch notes?  Do we need this to go to a particular team or is it a discussion-level ticket?

**Comment by edeutsch** [comment]
I suspect this is an issue for the ARS team @MarkDWilliams @ShervinAbd92 . Or perhaps better a topic for Architecture call on how we all agree that the ARS should be operating. Based on observing what happens, I suspect that ARS has a hard-coded set of endpoints that it hits, and it is not based on SmartAPI. and that hard-coded list hasn't been updated in a long time. But I am uncertain.

ah, looking again this morning, it seems that Robokop has now been removed:
https://arax.ci.transltr.io/?latest=10&from=ars.ci.transltr.io

The issue that ARS still hits a subset of KPs remains:
https://arax.ci.transltr.io/?r=46c9678f-52fe-4c72-ad97-265852ed262e
Do we want ARS to be doing that? Should ARS:
- Continue to hit a subset of KPs
- Hit only ARAs and not KPs
- Hit all KPs based on SmartAPI instead of a hard-coded subset?
This seems like a policy issue that should be discussed at Architecture.

**Comment by cbizon** [comment]
@MarkDWilliams can you comment here please on these issues?

**Comment by MarkDWilliams** [comment]
Happy to reassess what the ARS hits.  As to the URLs, there _shouldn't be_ any hardcoded URLs that we hit that aren't based on SmartAPI.  However, there is a hard coded fallback that can come into play if for some reason, there was a failure to pull the current information from SmartAPI for some reason, but barring that, all the URLs should be pulled from SmartAPI at boot time.

**Comment by cbizon** [comment]
So the lag between ROBOKOP being de-listed on SmartAPI and ARS is just because ARS didn't refresh?

**Comment by MarkDWilliams** [comment]
Ah no, that would be a case where likely the ARS wasn't able to find the registration and falling back to the URL we have in the backup config file.  This behavior could be changed to have the ARS just skip anything it can't get a SmartAPI pull for if folks think that would be preferable.

**Comment by sierra-moxon** [comment]
fixable this month on the ARS side. 
from tAQA: just kill it.

**Comment by ShervinAbd92** [comment]
robokop agent has been removed from ARS side.
