### ISSUE TITLE
Paths seem to disappear

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#526]
Steps to replicate: 

1. Access UI Test > Login > Run a query: https://ui.test.transltr.io/main/results?l=Gliofibroma&i=MONDO:0003170&t=0&q=f3d79f53-aa4c-4a7c-87c4-c751c35cb428
2. Expand a result (i went for one with more than one path)
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/e362c7f1-3105-44cd-8723-54a3970c1ef6)

3. Click show more - paths disappear
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/03b3785d-a4eb-4be6-b666-1dc19c851a83)

**Comment by sandrine-m** [comment]
Retested today and confirmed solved on [CI](https://ui.ci.transltr.io/main/results?l=Gliofibroma&i=MONDO:0003170&t=0&q=57a87469-a4d9-4beb-947e-cf04d6ba9150):
<img width="1052" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/66342541/4ac920f1-72ee-4444-9be7-470adba856f8">
Closing this issue, @sstemann @dnsmith124 feel free to reopen
