### ISSUE TITLE
Indicate when there are more ChEBI roles on a result

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#527]
Steps to recreate:

1. CI UI > Login > Castleman Disease 
2. Find prednisone
3. There are 5 ChEBI role labels on it
 
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/25a39dc3-ef22-449c-b48f-3a2cbfba5cf2)

4. Expand and there are 18 ChEBI roles - seems like it would be useful to indicate somehow.  
5. This also goes in reverse, if a substance has many roles, and you filter on one that is not in the top row, then you dont see the role in the filtered results list.

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/a9c5774b-7920-4529-86bd-a3e9a1b9cbd7)

**Comment by dnsmith124** [comment]
Added indication of additional chebi role terms on results:
<img width="1375" alt="Screen Shot 2023-10-11 at 1 45 00 PM" src="https://github.com/NCATSTranslator/Feedback/assets/54226761/6a9547a6-2f8f-4f34-be0d-a4a241cfc6bb">

confirmed live in CI, closing.
