### ISSUE TITLE
Publications Count but no Publications Tab

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#531]
Minor but - the Result display of Show All Evidence says Publications (2) and Sources (1) but the EPC Modal shows Clinical Trials (2) and Sources (1).  I'm not sure if users would care but should CTs be shown on the Show All Evidence? 

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/46bbd81f-4779-4a74-a486-523d4e9beae8)

Steps to reproduce:
1. UI Test > Login 
2. Drug > Disease Aortic Valve Stenosis https://ui.test.transltr.io/main/results?l=Aortic%20Valve%20Stenosis&i=MONDO:0042981&t=0&q=df12b9f8-ee27-4d1a-95d5-cb9fe8fef6f9
3. Click View All Evidence
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/5e677145-7ebb-42d3-8196-88d65b010295)

Probably not as obvious when there are both Pubs and CTs in the Pubs count
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/7dee90d4-aaf6-4084-9c56-89d229423ee2)

**Comment by dnsmith124** [comment]
The counts under View All Evidence have been adjusted to display counts for Publications, Clinical Trials, and Sources. Given the amount of vertical space available I decided to not include Misc. links in the counts, as there are relatively few of them. If there's strong feelings against this decision we can reopen this ticket and I can add them. 

Confirmed in CI, closing.
