### ISSUE TITLE
Help - Workspace and Filters

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#532]
1.  I'd really love one of these Help Topics to be called Workspace.  I feel like step 8 in "Review and Identify Favorite Results" is a bit buried and then "Focused Analysis of the Top Results" doesnt really tell me much. 

3. Seems like there should be a topic on Filters

**Comment by gprice1129** [comment]
@sstemann is the solution above good?

**Comment by sstemann** [comment]
yep sounds good!

**Comment by sstemann** [comment]
when will the help be updated?
<img width="551" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/3415d19c-421d-4bec-bd59-fcfaf0605720">

**Comment by Genomewide** [comment]
This sprint.

**Comment by sstemann** [comment]
is this considered the final?
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/ab8e1c53-e325-4783-b8c4-0d735322ac89)

there's also a lot here;  https://ui.transltr.io/demo/review-and-identify that seems like could be broken out

**Comment by Genomewide** [comment]
I agree. I will update our internal tracking ticket.

**Comment by sstemann** [comment]
with all the changes to facets this i think there are updates here

**Comment by sierra-moxon** [comment]
from TAQA:  this is a duplicate of another ticket, @dnsmith124 - seems correctly labeled but will reconcile.

**Comment by sstemann** [comment]
@dnsmith124 i dont see any changes in CI or Test, should the label be updated?

**Comment by dnsmith124** [comment]
The 2 action items from this ticket have been deployed to prod:
1. Workspace help topic added
2. Content added for facets to the Review and Identify Favorite Results page [here](https://ui.transltr.io/review-and-identify)

An upcoming interactive tutorial will also further address this issue, but for now I think we can consider this matter resolved.
