### ISSUE TITLE
Workspace Requests

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#533]
1. Workspace, but labelled Saved Results - seems like it should be labelled Workspace
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/37b7c562-df29-49e9-a9c8-ffbf236af4b8)

2. Enable the ability to collapse queries
3. Add a note that these are in alphabetical order on the query input
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/e9a6fd70-10c8-453f-822a-fb136b0b7206)

**Comment by gprice1129** [comment]
@sstemann can you please break this into multiple tickets and then close this ticket.

**Comment by dnsmith124** [comment]
Completed item 1 ("Saved Results" now reads "Workspace"), working on the other two

**Comment by dnsmith124** [comment]
Queries in the workspace can now be collapsed & expanded, confirmed live in CI!
