### ISSUE TITLE
Search History - Missing some searches

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#535]
I ran a couple of queries around the same time on the same day on the Test UI environment.  

I bookmarked/notes some results and those queries/results show in the Workspace but I'm not seeing these same searches in my Search History.  

<img width="943" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/33e6c173-b8e4-43ca-93b1-ee2be8d1e738">

**Comment by dnsmith124** [comment]
This is probably a silly question, but just to confirm @sstemann, you ran both of these queries manually correct? I've run half a dozen queries in test and made bookmarks and notes with results from each and have not been able to recreate the issue.

**Comment by gprice1129** [comment]
@sstemann can you please try to recreate on Prod and give very precise steps to reproduce?

**Comment by sstemann** [comment]
cannot replicate
