### ISSUE TITLE
Consider Hiding the Submit Another Query button from Demo Side

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#536]
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/f4c54917-9932-40ff-9e48-881ca0a1294d)

it opens a new demo homepage window, doesn't let you submit another query or give guidance on what to do:

**Comment by dnsmith124** [comment]
Just implemented a change that hides this button for non-logged in users, confirmed live on CI.

closing!
