### ISSUE TITLE
UI Example Queries - Addison Disease

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#538]
The MONDO used by the UI for the example Addison Disease is obsolete and you can't actually run this Disease/MONDO in the UI:

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/62e1c5cb-020e-4bff-bf15-90e04814d9eb)

Please use the updated MONDO or pick another example.  The Example Addison Disease uses MONDO:0009410

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/c4b19547-4d56-4265-b755-1ce19c0e751c)

https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0009410

**Comment by dnsmith124** [comment]
All of the example queries are sent from the UI backend, the frontend just displays them. @gprice1129 could you look into getting this updated?

**Comment by Genomewide** [comment]
change it to 'chronic primary adrenal insufficiency' MONDO:0015129
this is what replaced it https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0015129?lang=en

**Comment by dnsmith124** [comment]
I believe Gus has updated this example and re-run it. Once we are out of code freeze we can request a deployment to test and then to prod to update it.

**Comment by gprice1129** [comment]
@sstemann @dnsmith124 is right. We have a pending change that will address this issue but it did not make it in before the code freeze.

**Comment by sstemann** [comment]
its in CI.  i think we should close for now.
