### ISSUE TITLE
UI Example Queries - Type 1 Diabetes Mellitus

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#539]
I think the cache query should be updated

The example version has 298 results/1 ARA

https://ui.transltr.io/demo/results?l=Type%201%20Diabetes%20Mellitus&i=MONDO:0005147&t=0&q=a514fec0-b841-48d8-b997-0693378e5f30

A new run has 892 results/4 ARAs 

https://ui.transltr.io/main/results?l=Type%201%20Diabetes%20Mellitus&i=MONDO:0005147&t=0&q=3afe6ce5-d7be-4dd0-915f-4af2023269d9

**Comment by dnsmith124** [comment]
@gprice1129 is among the one's we've rerun recently?

**Comment by sstemann** [comment]
cached versions look reasonable.
