### ISSUE TITLE
Starter Ticket for: Sort and Filter Options for # of Paths, # of Hops, Predicates in Paths

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#543]
We'd like to have the ability in the UI to both Sort and Filter for

- number of paths on a result
- number of hops in a path on a result
- predicate types in the path

The filter may be more of a max/min than set number

Not sure how sort would work since these aren't distinct columns in the result list

**Comment by Genomewide** [comment]
One possible design would be to have it as part of the dropdown planned for prioritizing novelty or clinical evidence scores. However, that would mean you could not sort for 'most paths' and novelty. 
Maybe a filter for this would be best. Something similar to the evidence count filter. It could even be options for 1, 2-5, 5-20, >20 for path count. 
Hops should be filter for 1,2,3. @desiyopp

**Comment by sandrine-m** [comment]
+1 on this topic, as a user I would love to **group** by predicates pattern (i.e. the type of predicates used in the result, the number of hops, the order in which they are used, the `biolink:class` of the intermediary nodes to be able to see emerge possible mechanistics paths as putative hypotheses

**Comment by gprice1129** [comment]
@sstemann please break this into multiple tickets and then close.

**Comment by sstemann** [comment]
is this something @kingsj208 can do on behalf of the UI team to track?

**Comment by kingsj208** [comment]
Closing this ticket, broken into separate tickets
