### ISSUE TITLE
AEOLUS as source of incorrect 'treats' assertions

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#546]
[What drugs may treat EDS, vascular type](https://ui.test.transltr.io/main/results?l=Ehlers-danlos%20Syndrome,%20Vascular%20Type&i=MONDO:0017314&t=0&q=ea31c185-6f5d-46dd-9aa5-4601bf4d09f4), 2nd result is 'Omniscan', brand name for gadolinium, a contrast agent.

Omniscan is shown as 'treating' a whole slew of phenotypes of EDS. The source for all these assertions is AEOLUS, which lists side effects. Similar to #123 for clinical trials, I guess this contrast agent is being misrepresented or misinterpreted as a treatment.

**Comment by andrewsu** [comment]
Thanks @gglusman, I agree that we need to change how BTE ingests AEOLUS data from mychem.info.  I created a full ticket here https://github.com/biothings/biothings_explorer/issues/727.  

In the short term (and "short term" can be defined many ways), I think we have three options:
* **Do nothing.**  We are in code freeze, so let's not change anything
* **Eyeball an appropriate "count" threshold for AEOLUS indications.** This would be similar to how we handled the `pmid_count` threshold for semmeddb.
* **Remove AEOLUS indication edges my mychem.info completely.** Given that we also get drug indications from curated resources ChEMBL and DrugCentral through BTE, I'm guessing this won't have a significant negative impact on completeness of indications.

Searching in our Feedback issues, I don't see AEOLUS frequently mentioned among bad results. That might suggest a conservative approach of doing nothing for now.  But if testers have noticed this more commonly and just haven't created issues, please speak up -- that would definitely favor doing something about this now.

**Comment by sandrine-muller-research** [comment]
The query gives 3 answers that are contrast agents:
- Omniscan
- Gadobutrol
- Gadopentetate dimeglumine
They all come from AEOLUS. I will add them as a test asset and add a label for block list (the contrast agents could be put as a block list for treats).

**Comment by cbizon** [comment]
This is being tracked in BTE and the treats refactor may affect it as well, so closing for now.
