### ISSUE TITLE
One of the examples to try out is addison's disease. however, when we view the evidence, the label for it is marked as "obsolete" which is very strange to see!

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#548]
## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20230920131720366559.jpeg)

**Comment by dnsmith124** [comment]
This is an issue that the UI is aware of and has addressed, but we're waiting on the code freeze to be lifted in order to deploy.

**Comment by dnsmith124** [comment]
Confirmed resolved in prod. Closing!
