### ISSUE TITLE
Minor type on MVP2 query. The text "View this smallmolecule on PubChem" should have a space between "small" and "molecule".

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#549]
## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20230920141458522073.jpeg)

**Comment by dnsmith124** [comment]
I've pushed a fix to the UI's develop branch for this issue, I'll circle back once it's deployed.

**Comment by dnsmith124** [comment]
The fix for this has been deployed to CI. Closing.
