### ISSUE TITLE
Add HPO to the choices for MVP1 "What drugs may treat"

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#554]
We'll need to develop a query block list for HPO phenotypes

**Comment by gaurav** [comment]
Thanks! I'm tracking this on NameRes at https://github.com/TranslatorSRI/NameResolution/issues/93.

I think the best way to do this might be to check the previous blocklist terms we identified in https://github.com/TranslatorSRI/NameResolution/issues/63 against NameRes, but filtering to MONDO and HPO (i.e. query for https://name-lookup.ci.transltr.io/lookup?string=Suicide&offset=0&limit=10&only_prefixes=MONDO%7CHP and decide if we want to block the resulting term, HP:0031589 "Suicidal ideation").

**Comment by gprice1129** [comment]
@gaurav is this a UI, NameRes or both issue?

**Comment by Genomewide** [comment]
For us,I think it is just adding the curie prefix to the possible ones that are returned. So, MONDO and HPO can be returned.  
@gaurav We can 'OR' curry prefixes right? 

After that, there will need to be testers trying to break it.  

I also think we can help by showing something similar how the Monarch site does by indicating wether a term is a 'disease' or 'phenotype'

**Comment by dnsmith124** [comment]
@Genomewide @sstemann do we want to enable HPO immediately, or wait for the blocklist to be implemented?

**Comment by sstemann** [comment]
@Genomewide @dnsmith124 i would like to defer HPO being deployed to production until the blocklist is identified and implemented.  I think the draft plan for the UI is:
- Add back the ability of the autocomplete to return HPO curries.
- Enlist testers (yet unidentified) to do some searches looking for terms to be blocked or possibly confusing terms when displayed with diseases from MONDO.  
- Individual terms deemed inappropriate may be blocked using the block list. 
- Terms that appear duplicative or confusing for other reasons will need specific consideration for how to deal with them.  
- The Monarch initiative has both and simply indicates in the same row of an answer whether it is a phenotype or a disease. We currently plan to adopt this as well.

**Comment by dnsmith124** [comment]
@sstemann HPO terms have been added to the autocomplete for Drug/Disease queries and I can confirm they're showing up on CI! We can begin testing for the blocklist now. 

I still need to add some additional design elements that make whether you're selecting a disease or a phenotype clear to the user, I'm working on that now, but I didn't want that to hold back testing.

**Comment by dnsmith124** [comment]
I've added an icon and textual indication of what biolink type an autocomplete term is to the autocomplete window. The change is live on CI, so I believe the UI's work on this ticket is complete.

**Comment by gaurav** [comment]
I've gone through the list of red team terms we found two Relays ago and tested them against HPO in https://github.com/NCATSTranslator/Blocklists/milestone/1. I plan to review them in TAQA tomorrow, get Link Brokers to okay the final list, and then implement it in NameRes Dev.

**Comment by sierra-moxon** [comment]
Per discussion offline, we want to implement HP in the autocomplete in the next release and also finalize the blocklist.

**Comment by sstemann** [comment]
in prod as of 2/27
