### ISSUE TITLE
Retain PKs that are bookmarked by UI

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#556]

**Comment by Genomewide** [comment]
This should be happening. They should be in the workspace and in your history.  Please provide more details.

**Comment by gprice1129** [comment]
@Genomewide I believe @sstemann is talked about how the ARS will remove PKs after 30 days

**Comment by sstemann** [comment]
yes, so the plan is for the ARS to remove PKs from its database after 30 days unless the PK has been sent to the retain endpoint.  I had assumed (Which might be wrong) that if a user bookmarked (via bookmark or edit) a result, that this PK should be saved beyond the 30 day expiration.  This might not be true.  

If it is true, then the ARS has a retain endpoint that PKs with bookmarked results should be sent to so that the PKs won't expire and users will be able to access bookmarks forever.

**Comment by andrewsu** [comment]
Just want to note that AWS [S3 Glacier Instant Retrieval](https://aws.amazon.com/s3/storage-classes/glacier/instant-retrieval/) is [$4/TB/month](https://aws.amazon.com/s3/pricing/?nc=sn&loc=4), and the [Intelligent Tiering](https://aws.amazon.com/s3/storage-classes/intelligent-tiering/) system automatically moves data between storage classes depending on usage patterns.  Just noting in case this option hadn't been considered before...

![image](https://github.com/NCATSTranslator/Feedback/assets/2635409/830b331c-5323-4fcf-827c-940610ab28fd)

**Comment by edeutsch** [comment]
yeah, I'm thinking that deleting pks after 30 days is going to cause substantial pain for extremely little cost savings compared with a 1 or 2 year retention policy.

**Comment by gprice1129** [comment]
We very unfortunately did not have time to implement this before the freeze. It will be high on our development priorities after the unfreeze. We will also try to perform some retroactive saving of PKs for current users.

**Comment by Genomewide** [comment]
@sstemann this is an NCATS decision point on the timing of how long to save by default.  30 days is pretty arbitrary (@MarkDWilliams I could be making this up, but I think it is what you said) on one hand, but we have no data to suggest otherwise.  Either way, the UI needs the ability to save things for long periods (indefinitely?) or we should save them ourselves on on a UI server? 

@gprice1129 I think this is true... As long as we have the 'forever' button we are good.  If people think the default should be longer, then that should be a separate ticket and beyond the purview of the UI. Happy to be told I am wrong here, but I don't think so.

**Comment by saramsey** [comment]
While I understand the desire to control costs, I have concerns that this change would make it significantly harder to reproduce issues that are logged in the NCATSTranslator/Feedback issue tracker.  Couldn't we just compress JSON responses and keep them for a year? Could this be revisted in the Architecture committee?

**Comment by Genomewide** [comment]
Architecture was mentioned so how do we get it on the calendar? @capasfield

**Comment by sstemann** [comment]
@MarkDWilliams @capasfield this should be discussed on Architecture this week 2/19/2024 if possible

**Comment by sstemann** [comment]
in prod as of 2/27
