### ISSUE TITLE
Several SmartAPI registrations degraded

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/Feedback#557]
I noticed that some test queries on ARAX are not performing well in dev, and I notice that the state in SmartAPI has degraded.

https://arax.ci.transltr.io/?smartapi=1

Many services don't have a development service anymore:
![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/e075b3a1-1181-4ff8-9566-440fc7fbbb02)

and also there seems to be a new service identifying itself as infores:molepro, and since we organize KPs by their infores key, we are no longer querying MolePro at all:

![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/33a3cadb-54c1-44ed-8d55-d1298f93b993)

Can anyone help here?

Should it be legal to have two different services identifying at the same infores key?
I think we are assuming that they would be unique.

**Comment by vdancik** [comment]
@edeutsch - I was not aware of restriction that we can have only one service per infores - I will put a bandage on the registration and use a different infores until we clarify a policy.

**Comment by edeutsch** [comment]
@vdancik thanks, I don't know that there is a formal restriction, I suspect it was an critical assumption in our implementation. 

@capasfield, maybe we can add this as a request for decision for the next Architecture meeting  ?

**Comment by maximusunc** [comment]
The Automats should be fixed now!

**Comment by edeutsch** [comment]
@maximusunc thanks!

@capasfield this is issue is really two issues and is half fixed, I'm going to close this, and I opened a specific issue for the remaining one to be discussed at Architecture here: https://github.com/NCATSTranslator/TranslatorArchitecture/issues/93
