### ISSUE TITLE
This is pretty good! Just trying some queries, and the immediate thing I noticed was whether there is a way to download or export the results. That would be very useful not only discovery purpose but also for validation of findings from experiments or some other approaches.

Will explore more but looks quite promising from what I have tested so far!

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#558]

**Comment by sierra-moxon** [comment]
Noting that if we provide downloads, we need to provide Translator-version, build-date, etc. as metadata to those downloads  (and consider keeping archives of downloadable data), so that users downloading data can reproduce their findings from one UI release to the next.

**Comment by dnsmith124** [comment]
@sierra-moxon could you create a ticket that sets out to detail exactly what this metadata needs to be?

**Comment by sierra-moxon** [comment]
related: https://github.com/NCATSTranslator/Feedback/issues/556 (but not part of this request, this is a ticket about retention of PKs for more than 30 days)

**Comment by sierra-moxon** [comment]
I added some details to https://github.com/NCATSTranslator/Feedback/issues/555 @dnsmith124 and tagged some more folks with better experience than mine.

**Comment by dnsmith124** [comment]
@sierra-moxon does that mean we can close this ticket and track this issue in #555?

**Comment by sandrine-muller-research** [comment]
closing, please reopen if you think needs be
