### ISSUE TITLE
Under 'methylphenidate' as suggested treatment for Ehlers-Danlos Syndrome (EDS), it links a paper for treatment of excessive daytime sleepiness (also denoted 'EDS') using stimulants. I suspect this was not meant to be linked to EDS/Ehlers Danlos.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#562]

**Comment by gglusman** [comment]
Adding that in the same search, the result 'metformin treats EDS' is claimed to be supported by https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5526451/ but this paper doesn't seem to mention EDS at all.

**Comment by sstemann** [comment]
OBE, cannot replicate in Hammerhead
https://ui.test.transltr.io/results?l=Ehlers-danlos%20Syndrome&i=MONDO:0020066&t=0&r=0&q=adca89a0-6873-481c-8242-91c6c73fd1a3
