### ISSUE TITLE
RTX-KG2 is a KP, not an ARA

### ISSUE THREAD

**Issue by dkoslicki** [NCATSTranslator/Feedback#569]
RTX-KG2 is the knowledge graph that serves as one of the KP's behind ARAX. The UI has RTX-KG2 as a knowledge graph: 
![520E024A-4225-41B3-8600-0130A6ADA314](https://github.com/NCATSTranslator/Feedback/assets/6362936/54870a0a-5560-4324-b394-169be6f35db3)

**Comment by Genomewide** [comment]
@gprice1129 Can you comment on this? It looks like there are multiple kinds of 'resource_id" fields. Looks like each result has that key at the top level One is inside the "analysis" array and one outside of it.  I bet we are using the one inside the analysis to display the source ARA.   I am not sure what happens to the one outside of the analysis when the results are merged? Is it maintained? I believe that we have to keep the analysis separate. 


                    {
                        "id": null,
                        "score": null,
                        "essence": "Risperidone",
                        "analyses": [
                            {
                                "score": 0.9717772692601068,
                                "attributes": null,
                                "resource_id": "infores:rtx-kg2",
                                "edge_bindings": {
                                    "t_edge": [
                                        {
                                            "id": "infores:rtx-kg2:PUBCHEM.COMPOUND:5073--biolink:treats--None--None--None--MONDO:0005260--infores:semmeddb",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:automat-biolink:PUBCHEM.COMPOUND:5073--biolink:treats--None--None--None--MONDO:0005258--infores:sri-reference-kg",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:service-provider-trapi:PUBCHEM.COMPOUND:5073--biolink:treats--None--None--None--MONDO:0005260--infores:semmeddb",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:automat-drug-central:PUBCHEM.COMPOUND:5073--biolink:treats--None--None--None--MONDO:0005258--infores:drugcentral",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:service-provider-trapi:PUBCHEM.COMPOUND:5073--biolink:treats--None--None--None--MONDO:0005260--infores:aeolus",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:rtx-kg2:PUBCHEM.COMPOUND:5073--biolink:treats--None--None--None--MONDO:0005258--infores:repodb",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:molepro:PUBCHEM.COMPOUND:5073--biolink:treats--None--None--None--MONDO:0005258--infores:sider",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:molepro:PUBCHEM.COMPOUND:5073--biolink:treats--None--None--None--MONDO:0005258--infores:ctd",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:service-provider-trapi:PUBCHEM.COMPOUND:5073--biolink:treats--None--None--None--MONDO:0005260--infores:text-mining-provider-targeted",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:molepro:PUBCHEM.COMPOUND:5073--biolink:treats--None--None--None--MONDO:0005258--infores:drugcentral",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:rtx-kg2:PUBCHEM.COMPOUND:5073--biolink:treats--None--None--None--MONDO:0005258--infores:semmeddb",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:molepro:PUBCHEM.COMPOUND:5073--biolink:treats--None--None--None--MONDO:0005258--infores:chembl",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:rtx-kg2:PUBCHEM.COMPOUND:5073--biolink:treats--None--None--None--MONDO:0005258--infores:chembl",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:spoke:PUBCHEM.COMPOUND:5073--biolink:treats--None--None--None--MONDO:0005260--infores:chembl",
                                            "attributes": null
                                        },
                                        {
                                            "id": "infores:rtx-kg2:PUBCHEM.COMPOUND:5073--biolink:treats--None--None--None--MONDO:0005258--infores:drugcentral",
                                            "attributes": null
                                        }
                                    ]
                                },
                                "scoring_method": null,
                                "support_graphs": [
                                    "aux_graph_N1_269;N1_314",
                                    "aux_graph_infores:automat-biolink:MONDO:0005258--biolink:subclass_of--None--None--None--MONDO:0005260--infores:automat-biolink;infores:automat-drug-central:MONDO:0005258--biolink:subclass_of--None--None--None--MONDO:0005260--infores:automat-drug-central;infores:molepro:MONDO:0005258--biolink:subclass_of--None--None--None--MONDO:0005260--infores:molepro;infores:rtx-kg2:MONDO:0005258--biolink:subclass_of--None--None--None--MONDO:0005260--infores:rtx-kg2_option_group-subclass:on--on"
                                ]
                            }
                        ],
                        "row_data": [
                            0.972,
                            "Risperidone",
                            "['biolink:Drug', 'biolink:SmallMolecule']"
                        ],
                        "confidence": null,
                        "score_name": null,
                        "description": "No description available",
                        "resource_id": "ARAX",
                        "result_group": null,
                        "node_bindings": {
                            "on": [
                                {
                                    "id": "MONDO:0005258",
                                    "query_id": null,
                                    "attributes": null
                                },
                                {
                                    "id": "MONDO:0005260",
                                    "query_id": null,
                                    "attributes": null
                                }
                            ],
                            "sn": [
                                {
                                    "id": "PUBCHEM.COMPOUND:5073",
                                    "query_id": null,
                                    "attributes": null
                                }
                            ]
                        },
                        "score_direction": null,
                        "essence_category": "['biolink:Drug', 'biolink:SmallMolecule']",
                        "normalized_score": 100.0,
                        "result_group_similarity_score": null
                    },

**Comment by edeutsch** [comment]
My recollection is that this bug:

```
                    "analyses": [
                        {
                            "score": 0.9717772692601068,
                            "attributes": null,
                            "resource_id": "infores:rtx-kg2",
```

was identified and fixed after the code freeze, but not deployed to TEST or PROD because of the code freeze. Now that the freeze is thawing, a fix for this was deployed to TEST yesterday and will be deployed to PROD next week Wednesday or so.

**Comment by gprice1129** [comment]
The UI currently constructs this facet based on the resource_id. The definition is as follows:
```
        resource_id:
          $ref: '#/components/schemas/CURIE'
          description: The id of the resource generating this Analysis
```

Can we get clarification on what entries are valid for this attribute? Its possible we may have to change the way we construct the facet.

**Comment by edeutsch** [comment]
Hmm, this is definitely weird. When I perform queries locally, the resource_id seems correct ("infores:arax"). But I see that in the result that you provide it is incorrect ("infores:rtx-kg2").

I am baffled. I will need to puzzle further on this one.

**Comment by edeutsch** [comment]
okay, we think we've *really* fixed this this time. Pushed out to dev and CI, but not TEST and PROD.

**Comment by Genomewide** [comment]
This should fix itself in the UI as it bubbles up.

**Comment by sstemann** [comment]
@edeutsch I see it in the CI UI now 

is this something that should be pushed to Test so it can be included in next week's ARAX push to prod?  

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/1d48195c-21cf-4b07-9cb3-2202824cfde7)

**Comment by edeutsch** [comment]
yes! It was prepped for TEST this afternoon. I don't think it's been deployed yet, but probably will be Friday.

**Comment by MarkDWilliams** [comment]
Yes, I believe the request to push these changes to Test has been made and will go through today

**Comment by sstemann** [comment]
@edeutsch i'm not sure what to do with this or if it's a problem related to this issue?

I noticed in Test, that he UI was showing 14 results for [ARAX](https://ui.test.transltr.io/main/results?l=Stickler%20Syndrome&i=MONDO:0019354&t=0&q=740fb674-e601-4a25-8cb0-bd87ee6d239b), and the [ARAX GUI](https://arax.ncats.io/beta/?r=740fb674-e601-4a25-8cb0-bd87ee6d239b) shows 15 PK: 740fb674-e601-4a25-8cb0-bd87ee6d239b.  I did a compare of the UI to the ARAX GUI and it looks like the UI is not tagging Losartan as an ARAX result.  When I look at in the ARAX GUI, the infores does not look like ARAX, so i think the UI is doing what it is supposed to. 

Maybe it is intentional, but I wanted to doublecheck

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/f8a98ef4-db0c-4e3a-9be6-c30205453983)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/302e8423-8554-4301-87ff-9d592ca5b5be)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/9c1a4310-6137-4aa7-8131-05e8ffcae17a)

**Comment by edeutsch** [comment]
Hi @sstemann I am not seeing the problem. If I go to: https://arax.ci.transltr.io/?r=172980
and look up Losartan, I see two edges:
![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/b4d476df-aae0-4a6b-bfe1-3cf85f86ec70)

For the first edge, the sources ends with infores:arax
![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/0407b7a0-cca0-4f96-85c1-b78bdcc5a70a)

For the second edge, the sources also ends with infores:arax
![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/b5e38450-00b1-4394-b025-c392e8cd667a)

It seems to me that everything is in order with ARAX for this result?

One thing I notice is that the upstream_resource_ids is big and bold, while the resource_id is not in the ARAX display. I'll see if we can fix that, but that's just a matter of what's displayed more prominently.

**Comment by Genomewide** [comment]
It sounds like there is a disconnect between our count and what is in ARAX UI.  @sstemann can you you share the UI link? They are less easy to recreate these days.  I can but want to be sure I am not introducing a variable. 

I also think this is a separate issue and may need a separate ticket.

**Comment by sstemann** [comment]
@Genomewide seems like we should start a new ticket.

**Comment by sstemann** [comment]
actually, we'll leave this specific one open, should be in prod tomorrow, might as well make sure we check it tomorrow.

**Comment by Genomewide** [comment]
ok thanks!
