### ISSUE TITLE
SME request: when a node is returned, provide basic information about it including: name, synonyms, cross references, and potentially Gene Ontology annotations

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#57]
The QotM surfaced SME desire for richer node annotation. Specifically, a request was made for richer annotation of gene nodes, e.g., “what is this gene?” and “what biological process(es) is this gene involved with? The user desired the ability to hover over a node and see human-readable information.

Another SME put forward a perhaps related suggestion related to gene lists. Specifically, this user question what a user would do with a list of genes, even if scored and ranked, Can Translator provide additional information to assist users with interpretation of the results?

**Comment by sierra-moxon** [comment]
From TAQA:
- node attributes aren't consistent across results, UI can't do this yet. 
- maybe could be handled with link outs to underlying databases? 
  - e.g. this node is from DrugBank, make a link to DrugBank, and then it's done.

**Comment by sierra-moxon** [comment]
closing after split into two new tickets: #91 and #92
