### ISSUE TITLE
Disease normalization fail results in two identical looking target disease nodes. 

### ISSUE THREAD

**Issue by Genomewide** [NCATSTranslator/Feedback#571]
Both examples have the mono curie.  pharm prep has a umls curie also and the other has DOID.  The two are from unsecret and ARAX.  

url: https://ui.transltr.io/main/results?l=Alzheimer%20Disease&i=MONDO:0004975&t=0&q=4f464de7-2968-4553-83f5-0c0df6a2f0eb

![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/18294787-495d-4e64-8d52-8d8501343bb4)

![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/1bd9b72d-c3d7-439c-9305-8961e024edbf)

**Comment by gaurav** [comment]
Those identifiers should be getting conflated together as per NodeNorm Prod: https://nodenorm.transltr.io/1.3/get_normalized_nodes?curie=MONDO%3A0004975&curie=DOID%3A10652&curie=UMLS%3AC0002395&conflate=true&drug_chemical_conflate=false&description=false

**Comment by Genomewide** [comment]
Ok thanks! Assuming node norm is up @MarkDWilliams @gprice1129 where does the normalization happen now? Thoughts on why it would do this?

**Comment by gprice1129** [comment]
I believe the normalization still happens at the ARS level @MarkDWilliams?

**Comment by sstemann** [comment]
i'm not able to replicate for Alzheimer's Alzheimer 

https://ui.test.transltr.io/main/results?l=Alzheimer%20Disease&i=MONDO:0004975&t=0&r=0&q=8f5abbac-0dc3-4617-ba36-ccd4c0f4000c

<img width="668" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/828b0156-f8d6-41b4-a459-0a1d7b48f18c">
