### ISSUE TITLE
Organic group (and many others) too generic

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#572]
## Steps to reproduce:
What drugs may treat:Aceruloplasminemia
on PROD
submitted by @sandrine-muller-research

**Comment by sandrine-muller-research** [comment]
this result comes from ARAGORN:
![image](https://github.com/NCATSTranslator/Feedback/assets/22616936/1f21bd61-11d4-47d8-873f-d4f19a90233b)
Here is the ChEBI definition of anb organic group:
![image](https://github.com/NCATSTranslator/Feedback/assets/22616936/bbc12274-30de-48f0-938c-fc7ab09a2b17)

**Comment by sandrine-muller-research** [comment]
Organic Chemicals MESH:D009930 is also appearing and too generic

**Comment by sandrine-muller-research** [comment]
molecular entity ( `CHEBI:23367` )  is also appearing and too generic

**Comment by sandrine-muller-research** [comment]
molecule (`CHEBI:25367`) is also appearing and too generic

**Comment by sandrine-muller-research** [comment]
oxygen molecular entity (`CHEBI:25806`) is also appearing and is too generic

**Comment by sandrine-muller-research** [comment]
Other examples of too generic:

1. polyatomic entity: CHEBI:36357
2. carbon group molecular entity : CHEBI:33582
3. inorganic chemicals: MESH:D007287
4. heteroorganic entity: CHEBI:33285
5. main group molecular entity: CHEBI:33579
6. heteroatomic molecular entity: CHEBI:37577
7. cyclic compound : CHEBI:33595
8. heterocyclic compounds: MESH:D006571
9. CHEBI:24836 - inorganic oxide
10. CHEBI:24431 - chemical entity

**Comment by gprice1129** [comment]
Thank you for this @sandrine-muller-research! The UI team will discuss.

**Comment by gprice1129** [comment]
Oops, I misunderstood the issue... Nevermind, I don't think it is a UI issue.

**Comment by sandrine-muller-research** [comment]
no problem at all! ;) I'm almost like the Charlie Chaplin in the Modern Times after a day of testing :D

**Comment by cbizon** [comment]
We are implementing a genericity filter in ARAGORN ATM.   Also these terms have been added to the ARS blocklist.

**Comment by cbizon** [comment]
Aragorn issue: https://github.com/ranking-agent/aragorn/issues/225

**Comment by sierra-moxon** [comment]
closing as complete per the aragorn ticket being closed
