### ISSUE TITLE
wrong path to disease

### ISSUE THREAD

**Issue by sandrine-muller-research** [NCATSTranslator/Feedback#573]
This is a splitted ticket from #506 .

PATH : ... affects... contributes_to is leading to cause of the disease in that particular example (case of iron)

**Comment by sstemann** [comment]
It looks like many of the ARAs are doing this via the TMKP edge.  I'm not super clear what is distinct here from #506 so I may be misssing the point

![image](https://github.com/user-attachments/assets/b79c54ff-3fae-43eb-828a-29505f8010b8)

https://ui.test.transltr.io/main/results?l=Aceruloplasminemia&i=MONDO:0011426&t=0&r=0&q=5435b997-a309-4aef-b7b1-db5e743111cd

**Comment by sstemann** [comment]
asking @sandrine-muller-research to clarify the issue here and how its distinct from #506

**Comment by sandrine-muller-research** [comment]
Hi @sstemann 
Looking at ticket 506, it looks like the offending edges were coming from TMKP and unsecret. There was 2 different issues :
- one "data error" issue from TMKP (see [here](https://tmui.text-mining-kp.org/evidence/09e177f5568fb6f5b09c1a3f31fe1d90e4da509ba24e413009d34f401b5408f2)) as an example
- one reasoning issue from unsecret : 
![image](https://github.com/user-attachments/assets/e9667e48-e520-4263-8147-4fe33d9b9414)

The previous ticket got split for each type of issue.

I retested [today](https://ui.test.transltr.io/main/results?l=Aceruloplasminemia&i=MONDO:0011426&t=0&r=0&q=af9f66c3-09d0-4379-92ef-43e6ba4dbba3). 
Iron ion is still returning from ARAGORN with the same offending edge present in the reasoning of 3 metagraphs :
<img width="803" alt="image" src="https://github.com/user-attachments/assets/eda91948-03a0-465c-a726-7aa77539f835">
The offending edge is a "treat or applied to treat" from TMKP:
<img width="863" alt="image" src="https://github.com/user-attachments/assets/9e85646d-03d2-4657-ba85-0935ab8b59bf">
Here is an example:
https://tmui.text-mining-kp.org/evidence/a74db459b9d18d99fda07b38a121ed1b274989fff6f08f5e0324238442ded2c6

The iron result does not show up anymore for unsecret (I have checked that unsercret did complete with no error).

closing this ticket as the unsecret resoning issue is not present anymore.
