### ISSUE TITLE
ARAX ignores a node in a query where subject and object is fixed

### ISSUE THREAD

**Issue by sandrine-muller-research** [NCATSTranslator/Feedback#574]
I made the [following query](https://arax.ci.transltr.io/?r=982dcbe5-3e9f-40f5-a090-47283ba2639c) through ARAX UI (CI environment):
```
{
  "edges": {
    "t_edge": {
      "attribute_constraints": [],
      "knowledge_type": "inferred",
      "object": "on",
      "predicates": [
        "biolink:treats"
      ],
      "qualifier_constraints": [],
      "subject": "sn"
    }
  },
  "nodes": {
    "on": {
      "categories": [
        "biolink:Disease"
      ],
      "constraints": [],
      "ids": [
        "MONDO:0019600"
      ],
      "is_set": false
    },
    "sn": {
      "categories": [
        "biolink:SmallMolecule"
      ],
      "constraints": [],
      "ids": [
        "PUBCHEM.COMPOUND:23931"
      ],
      "is_set": false
    }
  }
}
```
I am getting plenty of other compounds but not the one I asked. If there would have been no results, I would have expected 0 as an answer.

**Comment by saramsey** [comment]
I thought PloverDB doesn't allow a one-hop query with both subject and object node fixed by `id`. Is that correct, @amykglen ?  Perhaps I mis-remembered.

**Comment by saramsey** [comment]
Can confirm, `kg2cploverdb.ci.transltr.io` (queried directly) returns no results for the above query.

**Comment by edeutsch** [comment]
I'm thinking that PloverDB is fine with that, but this is an inferred query, so it is going to xDTD. I am thinking that xDTD queries were not designed to be initiated with a fixed drug. It was perhaps designed assumed that drugs is unconstrained (i.e. Which drugs treat X).

**Comment by saramsey** [comment]
We've opend [ARAX issue 2160](https://github.com/RTXteam/RTX/issues/2160) on this

**Comment by dkoslicki** [comment]
We've determined that this is indeed an ARAX issue: we have a plan in place to fix this month. The planned behavior is when both nodes are pinned, if these are in the top 50 precomputed xDTD results (creative mode), these and the associated `lookup` will be returned. If the pinned drug is not in the top 50 precomputed creative results, only the `lookup` will be returned.

Side note: arbitrary (drug, disease) pinned pair xDTD queries are out of scope, but [this repo](https://github.com/chunyuma/KGML-xDTD) allows you to run this yourself if you really want them

**Comment by sandrine-muller-research** [comment]
thank you @dkoslicki for the feedback! I put the issue to no longer needs review. Please keep us posted if you'd like us to make some testing whenever. Thank you!

**Comment by edeutsch** [comment]
This is now working in ARAX CI. Although there are no results for the original query in this post. It does work fine in cases where an answer is expected:
https://arax.ci.transltr.io/?r=173216
Okay to close?

**Comment by sandrine-muller-research** [comment]
I reran the first query as a retest on [ARAX CI](https://arax.ci.transltr.io/?r=f43938aa-125e-49be-9b68-5ad151045f7b) and I still get plenty of compounds back.

**Comment by edeutsch** [comment]
The results you link to were not run on CI:
https://ars.ci.transltr.io/ars/api/messages/f43938aa-125e-49be-9b68-5ad151045f7b

They were run on prod:
https://ars-prod.transltr.io/ars/api/messages/f43938aa-125e-49be-9b68-5ad151045f7b

The code changes to support your use case have only make it as far as CI so far, so you will need to query through CI so see the change.

**Comment by dkoslicki** [comment]
Confirmed in CI that this has been fixed. See https://github.com/RTXteam/RTX/issues/2160
