### ISSUE TITLE
Pesticides proposed as treatment

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#575]
## Steps to reproduce:
MVP1 on autism spectrum disorderselect pesticides from ChEBI roles

**Comment by sandrine-muller-research** [comment]
Should we remove the ChEBI role pesticides from the facet for the _treats_ query?

**Comment by sierra-moxon** [comment]
retested adn no longer see pesticide role for treatments of ASD - fixed!
