### ISSUE TITLE
opposite of what I asked for: Valproic acid treats autism

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#577]
## Steps to reproduce:
MVP1 on autism
search for Valproic acid

**Comment by sandrine-muller-research** [comment]
From unsecret :
Valproic acid is in the top results and is used in rodents (prenatal stage) to induce autistic behavior (https://pubmed.ncbi.nlm.nih.gov/28472621/,https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4511955/)

**Comment by sandrine-muller-research** [comment]
It could be very nice if we could have access to the aux graphs, some results are REALLY interesting!

**Comment by sstemann** [comment]
i'm not seeing opposites in the support graphs so i think we can close this example, re-open if needed

https://ui.test.transltr.io/main/results?l=Autism&i=MONDO:0005260&t=0&r=0&q=a8b74d1e-e0bc-4ff2-85c7-9934a2c40ed6

![image](https://github.com/user-attachments/assets/91b11e0f-d1aa-404c-9610-9e38f9a89ad4)
