### ISSUE TITLE
Ambiguous provenance of edges that include >1 predicate

### ISSUE THREAD

**Issue by mbrush** [NCATSTranslator/Feedback#578]
A potential issue with the UI that I'm not sure has been pointed out yet is that the window that shows provenance (pubs and sources) for edges that include >1 predicate doesn't seem to show the provenance of all of the different collapsed predicates. 

e.g. the circled 'causes' edge below actually holds three predicates (`causes`, `predisposes`, and `treats`) - and clicking this edge opens a single provenance window that shows the combined Pubs and Sources for any of these three predicates mixed together.  

However, the predicate used in the 'RELATIONSHIP' column for every row in the Pubs or Sources tables is `causes` (there are no rows for `predisposes` or `treats`) . . . I assume that in the Sources table below, there should be (at least) one row for each of these predicate`. 

![image](https://github.com/NCATSTranslator/Feedback/assets/5184212/1305ac6f-54a9-4346-8599-f341a003a32e)

Noted also that if you page through all pubs, every row has `causes` as the predicate - nothing for `predisposes` or `treats`:

![image](https://github.com/NCATSTranslator/Feedback/assets/5184212/23adcd68-95b4-4f43-9758-3df233c7f7d5)

Link: https://ui.test.transltr.io/main/results?l=Ehlers-danlos%20Syndrome,%20Dermatosparaxis%20Type&i=MONDO%3A0006497&t=0&q=4a24ced8-2097-4322-abdd-299e1699afcb

**Comment by gprice1129** [comment]
@mbrush please check out the new evidence modal on Test. For your convenience: https://ui.test.transltr.io/demo/results?l=Breast%20Cancer&i=MONDO:0007254&t=0&q=a6d28087-f193-441c-ade3-26b04fdd0dd1

**Comment by gprice1129** [comment]
@mbrush can you retest this on the current UI and see if the problem is addressed?

**Comment by mbrush** [comment]
Yes, it is addressed by the new EPC modals where the two predicates are split out and I can click on each one separately to see the specific supporting pubs and sources for each.  I no longer see a column in the new tables that reports the edge itself - but I can tell which edge the pubs and source  metadata is shown for because: (a) it is highlighted in a different color in the path above it, and (b) and this edge is reported in the 'Showing Evidence For' at the top left of the window: 

![image](https://github.com/NCATSTranslator/Feedback/assets/5184212/82cc33a9-f9dc-404f-adce-a36d54a2f815)


I think this is very nice.  Thanks!

**Comment by mbrush** [comment]
New evidence modals address the issue, as described above.
