### ISSUE TITLE
Result Graph Missing Predicate

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#579]
In Test UI:

1. Login > Run MVP1 - Diabetes Mellitus:  https://ui.test.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&q=ac6c81ff-33f7-48c5-b217-463e337ca871

2.  Notice no results from ARAGORN
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/54158869-9855-4055-a6cf-942597a38db4)

3. Go to ARAX GUI > Notice 109 Results: https://arax.ncats.io/beta/?r=ac6c81ff-33f7-48c5-b217-463e337ca871

4. Expand a few and notice in the result graph there are no predicates
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/3685f26e-7594-4915-acdd-9262a242dbfa)

In Prod, ARAGORN has 0 results for Diabetes Mellitus
https://ui.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&q=7ae1fbfa-63af-48c0-a3cd-e21f9995cf54
https://arax.ncats.io/beta/?r=7ae1fbfa-63af-48c0-a3cd-e21f9995cf54

**Comment by maximusunc** [comment]
This has been fixed on Test and I'm currently rerunning on Prod as well, but it looks like the Prod UI is not working currently? (https://ui.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&q=Internal%20Server%20Error)

https://ui.test.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&q=26091f3a-2aff-4d43-92d1-2cdb1168d5eb

https://arax.ncats.io/?r=26091f3a-2aff-4d43-92d1-2cdb1168d5eb

**Comment by sstemann** [comment]
@maximusunc today in Prod, for Diabetes Mellitus - ARAGORN has unscored results, which I think is coming from ARAGORN since the results are unscored when viewed in the ARA GUI as well

https://ui.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&q=2f7ccdcb-f926-4464-b9a3-9ee3d981b40b

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/e87b9ed4-86a0-4b59-a600-4553fc01c44f)

https://arax.ncats.io/beta/?r=2f7ccdcb-f926-4464-b9a3-9ee3d981b40b

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/17697a04-18a9-4bbc-8e7e-770791f23395)

it looks strange still in Test as of 10/13
- No treats edges
- The path predicates don't seem to align with the "analysis support graphs" that I can view in ARAX GUI, I can't view the support graph on the "treats" edge in the ARAX GUI so maybe the UI is using something I can't see in the ARAX GUI

https://ui.test.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&q=8e3f5517-2579-47df-8d54-56017fffd0c5

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/01b45191-8e46-4f1a-8675-cd4579b75d42)

https://arax.ncats.io/beta/?r=8e3f5517-2579-47df-8d54-56017fffd0c5

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/5641ab8c-e2f9-4175-a8bc-b82ff4393d35)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/350fa26f-f490-4381-8752-7cb08035f19e)

**Comment by sstemann** [comment]
@uhbrar is it intentional that ARAGORN doesn't respond to Diabetes Mellitus MONDO:0005015

https://ui.test.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&r=0&q=44aa2330-0847-49e2-a8d0-84e2e4685a09

As of 2/15

**Comment by sstemann** [comment]
Looks resolved in Test
