### ISSUE TITLE
WikiPathways and BioPlanet

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#58]
The QotM surfaced a desire for Translator to draw from [WikiPathways](https://www.wikipathways.org/index.php/WikiPathways) and [BioPlanet](https://ncats.nih.gov/pubs/features/bioplanet). These are considered ‘trusted’ by toxicologists, but are not Translator knowledge sources. Note that BioPlanet is an NCATS resource.

**Comment by andrewsu** [comment]
Both WikiPathways and BioPlanet are available in Translator through BTE.  For example, this query retrieves pathways associated with NCBIGene:1017 (CDK2):

```
{
    "message": {
      "query_graph": {
        "nodes": {
          "n0": {
            "ids": ["NCBIGene:1017"]
          },
          "n1": {
            "categories": ["biolink:Pathway"]
          }
        },
        "edges": {
          "e01": {
            "subject": "n0",
            "object": "n1"
          }
        }
      }
    }
  }
```

Example results: https://arax.ncats.io/?r=3571f4ec-6214-4d4d-83bc-0f383f415e71 (Wikipathways is imported through CPDB)

![image](https://user-images.githubusercontent.com/2635409/207918690-3de5f4aa-d7d5-4c3f-8543-97320ead89ff.png)

See BTE results 92-160 to see them in the ARAX UI.

![image](https://user-images.githubusercontent.com/2635409/207919734-bebdf8fb-e911-4905-b9a2-ae5bc5f959c6.png)

This does point out that we should do more to get human-readable names there. We will investigate a little and create a new ticket that links to this one...

**Comment by sierra-moxon** [comment]
@andrewsu @karafecho - since we already have this data available to Translator, does it makes sense to close this ticket (will still be available to reference in your new ticket @andrewsu)?  I'll close, but please reopen if I got this wrong. :)

**Comment by marcdubybroad** [comment]
@karafecho we also have wikipathways data with genetics associations to disease edges (p-values). I did notice that our curie format for them differ from BTE, so I'll fix that.
We downloaded are gene sets from https://www.gsea-msigdb.org/gsea/msigdb/ (the C2 and C5) library; I don't remember seeing the bioplanet datasets there. I'm more than happy to incorporate those in our computational workflow if someone points me to the where I can download the data.

**Comment by karafecho** [comment]
@andrewsu : Perhaps you can point Marc to the correct URL for accessing the BioPlanet data?

**Comment by karafecho** [comment]
Reopening, as issue is active.

**Comment by sierra-moxon** [comment]
for @sierra-moxon - please add 'wikipathways' as an `id_prefix` for the correct class, with the correct prefix to Biolink.

**Comment by andrewsu** [comment]
> @andrewsu : Perhaps you can point Marc to the correct URL for accessing the BioPlanet data?

Looks like the bioplanet website is down at the moment... https://tripod.nih.gov/bioplanet/

**Comment by sstemann** [comment]
> > @andrewsu : Perhaps you can point Marc to the correct URL for accessing the BioPlanet data?
> 
> Looks like the bioplanet website is down at the moment... https://tripod.nih.gov/bioplanet/

looks like its back up

**Comment by andrewsu** [comment]
I think @marcdubybroad and team should import BioPlanet into their system if they like, but I'd suggest that for the purposes of Translator, the objective of providing BioPlanet and Wikipathways data as KPs has already been achieved and this issue should be closed.  My two cents!
