### ISSUE TITLE
Duplicate Publications in the Sources - Looks Isolated to Unsecret/TMKP

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#583]
in Test, MVP1 > Glioblastoma
https://ui.test.transltr.io/main/results?l=Glioblastoma&i=MONDO:0018177&t=0&q=0fbfbeed-1362-4690-88f4-67f45c62aee8

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/d1000068-d9b1-4959-8101-3b0d2c194a8f)

In ARAX GUI
https://arax.ncats.io/beta/?r=0fbfbeed-1362-4690-88f4-67f45c62aee8
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/e6290f23-572e-4dbe-b23d-b6f9085ed5cd)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/28f5f2f9-e4de-451e-b41b-7abf80988a7f)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/10fef771-b79f-4b6c-b72f-bf379e2bbf09)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/600a366f-b1b8-48f7-9dfb-a817cf5ade2e)

**Comment by webyrd** [comment]
@kaiwenho took a look at the duplicate publications, which apparently comes from the original edge from the Text Mining Provider KG.  We will check if that duplicate still exists in the new version of the KG we are going to import.  We will also run a 'remove-duplicates' step when building our new mediKanren-compatible KG.

**Comment by kaiwenho** [comment]
This duplicate list of publications is eliminated in the new version of the Text Mining Provider KG. The edge/answer `Selinexor treats Glioblastoma` does not contain duplicate publication in UI TEST now: https://ui.test.transltr.io/main/results?l=Glioblastoma&i=MONDO%3A0018177&t=0&r=4fcd5534&q=813a60b6-c9a9-44f5-a1e5-bc5b82266bb9. 
<img width="1515" alt="Screenshot 2024-01-02 at 9 48 59 AM" src="https://github.com/NCATSTranslator/Feedback/assets/67288473/632878f5-9de9-4070-b255-bbb1750b4990">
