### ISSUE TITLE
Should Disease (MONDO:0000001) be Blocked from Querying against?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#587]
In Prod UI
UI:  https://ui.transltr.io/main/results?l=Disease&i=MONDO:0000001&t=0&q=ec62b8c8-6e52-4d64-8b81-d07f01d33753
PK in ARAX GUI:  https://arax.ncats.io/beta/?r=ec62b8c8-6e52-4d64-8b81-d07f01d33753

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/766f5633-251b-41b2-8a99-d85ca266096d)

**Comment by gaurav** [comment]
I'm happy to add MONDO:0000001 to the NameRes Blocklist. Do we need additional NCATS sign-off on this or is this ticket sufficient? I can make the change itself in the Blocklist (tracking at https://github.com/NCATSTranslator/Blocklists/issues/9).

Are there other high-level MONDO and HP concepts we should consider blocking in autocomplete? For example, MONDO:0000001 has two direct children: [MONDO:0700096 "human disease"](http://purl.obolibrary.org/obo/MONDO_0700096) and [MONDO:0005583 "non-human animal disease"](http://purl.obolibrary.org/obo/MONDO_0005583).

**Comment by brettasmi** [comment]
If we agree to block this, I would advocate that it be blocked at the ARS level such that a blocklist doesn't need to be implemented and maintained by all of the teams individually.

As for the name resolver, I would advocate leaving as much in there as possible to make the tool as useful (complete) as possible beyond its association with the frontend.

**Comment by gaurav** [comment]
The reason to block this in NameRes/Autocomplete would be to prevent people who querying "[drug] treats Disease", which is probably not a very useful query. If it would be useful, we could potentially also set up a RENCI-only NameRes instance that doesn't have a blocklist.

**Comment by gaurav** [comment]
This has been added to the autocomplete blocklist, but ui.test.transltr.io currently uses name-lookup.transltr.io (NameRes Prod) and not NameRes Test, so it doesn't have the latest blocklist loaded.

@dnsmith124 Could you please change https://ui.test.transltr.io/main to use name-lookup.test.transltr.io? If that's not doable, please let me know how I can fix NameRes to make that work!

**Comment by dnsmith124** [comment]
@gprice1129 The change for the FE to set the NR endpoint based on the config is in TEST, can you merge the BE portion of that change?

**Comment by gaurav** [comment]
@dnsmith124 Just wanted to note that https://ui.test.transltr.io/main is still using name-lookup.transltr.io instead of name-lookup.test.transltr.io :)

**Comment by dnsmith124** [comment]
@gaurav we'll be requesting a deployment to test today or tomorrow to address that!

**Comment by gaurav** [comment]
Ah, gotcha, I thought you said that that had already happened -- my bad!

**Comment by dnsmith124** [comment]
@gaurav the UI has deployed this change to test! So the UI on test calls name-lookup.test

**Comment by gaurav** [comment]
Thank you so much @dnsmith124!

Now that that's updated, MONDO:0000001 is no longer returned. Closing this issue.

![Screenshot 2024-01-26 at 1 38 29 PM](https://github.com/NCATSTranslator/Feedback/assets/23979/14f95e95-2696-4779-9f40-f0884b95f5f5)
