### ISSUE TITLE
Pregnenolone succinate - Can't find evidence it's Indicated for Disease

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#588]
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/5c8f4fbb-fa64-427b-ade1-343581d967bf)

the link out says:  https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL2105373/

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/bc7c2d7f-4b96-4a88-a670-a26ebd773016)

https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=Pregnenolone+succinate

https://ui.test.transltr.io/main/results?l=Autism&i=MONDO:0005260&t=0&q=9c1a9505-b5c7-4f1c-981e-a2a48358a803

tagging @newgene and @brettasmi - I'm not sure if this is coming from Improving or from the annotator.

**Comment by gglusman** [comment]
See https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4194260/

**Comment by gglusman** [comment]
It seems to be getting it via Chembl from Clinical Trials: https://clinicaltrials.gov/search?id=%22NCT01881737%22OR%22NCT02627508%22
The paper I linked is the one reporting the results of the completed trial.

**Comment by sstemann** [comment]
thanks for the paper, i'm still hoping to understand where the indicated for disease tag is coming from.  It's been raised by our FDA and pharma alumni.

**Comment by newgene** [comment]
I know annotator does provide this `max_phase` info from Chembl, will need UI team to confirm if annotator is the source for rendering this table column.

**Comment by sstemann** [comment]
@gprice1129 it looks like, the Chembl max_phase in this example is "2" "clinical candidate drug".  i don't think that's the same as indicated for.  can you confirm?

**Comment by gprice1129** [comment]
We get the "indicated for" tag directly from the annotator by way of the chembl.indications attribute. @newgene @sstemann

**Comment by brettasmi** [comment]
imProving returns the max_phase attribute for indication edges from CHEMBL.

**Comment by newgene** [comment]
@sstemann the indications data from the annotator for this particular drug is returned as this:

https://biothings.ncats.io/annotator/CHEMBL.COMPOUND:CHEMBL2105373?fields=chembl

**Comment by cbizon** [comment]
The attribute should only be applied in the UI if the annotation is in chembl indications AND the Phase = 4.  Per @vdancik at Jan Relay

**Comment by sstemann** [comment]
@gprice1129 it looks like the max_phase_for_ind https://biothings.ncats.io/annotator/CHEMBL.COMPOUND:CHEMBL2105373?fields=chembl is 4.  Can you please update the UI to apply indicated for as Vlado recommended at the relay?

https://ui.test.transltr.io/main/results?l=Autism&i=MONDO:0005260&t=0&r=0&q=5236e220-4e90-46f2-a1fb-85d0c2aa14f1

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/77bc3602-f7bb-4f32-aa19-3cd7ea310a4b)

**Comment by gprice1129** [comment]
@sstemann this is an issue we are planning to fix this cycle.

**Comment by sstemann** [comment]
@gprice1129 I believe this is still an issue, in Test 

https://ui.test.transltr.io/main/results?l=Autism&i=MONDO:0005260&t=0&r=0&q=67bd84e7-57bf-448e-b6bf-9afa1315c72a

<img width="886" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/242d611a-6ef0-4fd9-9771-167c4affaba1">

https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL708/

<img width="779" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/5583f098-6c8a-4153-83b6-fb71cd3bc814">

https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8f78b278-a0b3-47ce-bbad-5dad7012896a

there are 38 drugs in the Drugs Indicated for Autism filter and i just don't think that's correct

**Comment by gglusman** [comment]
Checked our upcoming KPs:

_FDA approvals:_ indeed none of the 38 labels for oxytocin indicate it for ASD.
_Clinical Trials:_ there is [a clinical trial at phase 4](https://clinicaltrials.gov/study/NCT02940574) for Syntocinon (Oxytocin) for Autism Spectrum Disorders.
