### ISSUE TITLE
Support for pathfinding queries

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#589]
This issue is to suggest a new Translator feature, namely, support for pathfinding queries. The desire for this capability has been expressed in numerous forums, including the QotM (see https://github.com/NCATSTranslator/testing/issues/230). I did not see a formal ticket within this repo that is related to pathfinding queries, so I am creating one.

**Comment by sierra-moxon** [comment]
This is now actively being worked on; @gprice1129 is this still a ticket that helps you prioritize work or since this is already prioritized and being worked on, shall we close?  (please do as you see fit).

**Comment by gprice1129** [comment]
@sierra-moxon it doesn't help up prioritize. We will start closing feature level tickets that we have prioritized internally.
