### ISSUE TITLE
which KPs/ARAs can provide relationships between propofol, soybean oil, and β-sitosterol?

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#59]
iDISK. Note that an iDISK API was created by Service Provider team and is registered in SmartAPI here: https://smart-api.info/registry?q=32f36164fabed5d3abe6c2fd899c9418. While it is tagged as a Translator service, it was not invoked, e.g., to find relationships between propofol, soybean oil, and β-sitosterol.

**Comment by andrewsu** [comment]
I can confirm that BTE is successfully calling the Service Provider iDisk API through the TRAPI query and example ARS PK below.  But it's not clear to me that iDisk should be queried "to find relationships between propofol, soybean oil, and β-sitosterol".  iDisk is primarily used to track relationships between dietary supplements and diseases (with some drug interactions as well). I'm forgetting some of the details of that particular QotM, but I seem to recall the need for relations between foods (like soybean oil) and the chemicals that are found therein (like β-sitosterol). Those relations should come from resources like FooDB and FoodData.  Service Provider also created APIs for those (https://biothings.ncats.io/foodb and https://biothings.ncats.io/fooddata), but those are pending SmartAPI registration for inclusion in BTE.  (That is certainly on our to-do list, but we do not have an explicit issue to track it...)

----

ARAX UI link: https://arax.ncats.io/?r=fbae7299-8872-4fa1-8dab-8a9fb128c309
Query:
```
{
    "message": {
      "query_graph": {
        "nodes": {
          "n0": {
            "ids": ["UMLS:C0242383"]
          },
          "n1": {
            "categories": ["biolink:ChemicalEntity"]
          }
        },
        "edges": {
          "e01": {
            "subject": "n0",
            "object": "n1"
          }
        }
      }
    }
  }
```

**Comment by sierra-moxon** [comment]
From @karafecho - In addition, the QotM identified [FooDB](https://foodb.ca/) <-> [FoodOn](https://foodon.org/) mappings, [FoodData Central](https://fdc.nal.usda.gov/) as sources of nutrient data and food-derived chemicals. It was noted that the SPOKE team manually created mappings from FoodDB <> FoodOn, which they offered to send to SRI. In addition, there are existing tickets in the biothings repo for both FoodDB and FoodDataCentral: https://github.com/biothings/pending.api/issues/65 and https://github.com/biothings/pending.api/issues/66. Creating ticket here to promote broader discussion and prioritization.

**Comment by sierra-moxon** [comment]
related tickets are closed; closing this one.
