### ISSUE TITLE
spoke: meta_knowledge_graph/ endpoint in dev returns expired certificate error 

### ISSUE THREAD

**Issue by isbluis** [NCATSTranslator/Feedback#595]
ARAX has not been able to expand to **spoke** in _development_ for the past week or so, since the published endpoint (https://spokekp.healthdatascience.cloud/api/v1.4/meta_knowledge_graph) does not return a valid meta_knowledge_graph:

![image](https://github.com/NCATSTranslator/Feedback/assets/37852256/e787e624-434f-4aff-a009-688ccbf3de1b)

_Production_, _testing_, and _staging_ seem to be in good working order.

**Comment by isbluis** [comment]
Just a quick follow up on this.  ARAX has not been able to expand to **spoke** in _development_ since mid-October.  Same issue with expired certificate.

**Comment by suihuang-ISB** [comment]
Brett - can you address this issue? Thx

**Comment by isbluis** [comment]
This seems resolved. Closing.
