### ISSUE TITLE
return the number of agents who responded in UI

### ISSUE THREAD

**Issue by sandrine-muller-research** [NCATSTranslator/Feedback#596]
Perhaps a tester UI feature request only (although it could be claimed that it could help users understand why results may change over time). 
some issues are closed because the tester could not reproduce but sometime, we figure out that it was because only a few agents responded (many others returned a 598). Knowing that some agents where not available when the query was "complete" could actually be very helpful.

**Comment by Genomewide** [comment]
We actually have this on our radar now. And are looking at letting users know when they may want to run again later.

**Comment by sierra-moxon** [comment]
@Genomewide - is this still something the UI is thinking of handling or is it already handled?  I am not sure how to test or otherwise resolve this one. :)

**Comment by dnsmith124** [comment]
@sierra-moxon I'm not entirely sure, it seems to me that the UI already handles this in a sense. Currently we have a facet for Reasoning Agent, which communicates to the user which ARAs have returned on a given query, though this can change on subsequent loads of the same link if an ARA errors out initially but returns results later.

The ARAs that have returned are also logged to the browser console, so we're technically showing it in two places. 

I'm of the mind that this can be closed as completed, but I'm willing to be overruled

**Comment by sstemann** [comment]
agree with @dnsmith124
