### ISSUE TITLE
The link to the Mesh ID corresponding to "Plant extracts" is broken

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#598]
## Steps to reproduce:
search for plant extracts (result #50)
click on the [node link](https://id.nlm.nih.gov/mesh/D010936)
submitted by @sandrine-muller-research

**Comment by sandrine-muller-research** [comment]
Same for [Plant preparations ](https://id.nlm.nih.gov/mesh/D028321)

**Comment by sandrine-muller-research** [comment]
link works today closing
