### ISSUE TITLE
broken link for Ergocalciferol related publication

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#599]
## Steps to reproduce:
text filter for Ergocalciferol

**Comment by sandrine-muller-research** [comment]
Broken link for [Ergocalciferol related publication](https://www.ncbi.nlm.nih.gov/pmc/PMC7527498)
<img width="997" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/56a95c3c-97e5-408e-991a-7bb28f04ba38">

**Comment by sandrine-muller-research** [comment]
lnik works today, closing
