### ISSUE TITLE
Busulfan cause POF (induce in animal model of the disease) not treats

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#608]
## Steps to reproduce:
MVP1 on Premature menopause
search for Busulfan

**Comment by sandrine-muller-research** [comment]
Busulfan is shown with high score but the paper supporting the edge is actually stating that busulfan induce POF in animal models hence cause the disease.
"busulfan-induced mouse ovarian damage"

**Comment by sierra-moxon** [comment]
can not reproduce; closing as complete.
