### ISSUE TITLE
FoodDB, FoodON, FoodDataCentral

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#61]
The QotM identified [FooDB](https://foodb.ca/) <-> [FoodOn](https://foodon.org/) mappings, [FoodData Central](https://fdc.nal.usda.gov/) as sources of nutrient data and food-derived chemicals. It was noted that the SPOKE team manually created mappings from FoodDB <> FoodOn, which they offered to send to SRI. In addition, there are existing tickets in the biothings repo for both FoodDB and FoodDataCentral: https://github.com/biothings/pending.api/issues/65 and https://github.com/biothings/pending.api/issues/66. Creating ticket here to promote broader discussion and prioritization.

**Comment by sierra-moxon** [comment]
duplicate/more grouping issue for #59, copied content there for ease of review in TAQA (we can split it out into a ticket for bringing in each of these specific databases after we figure out which KP will be in charge of that).
