### ISSUE TITLE
acetaminophen treated by obstructive sleep apnea (openAPI predict)

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#610]
## Steps to reproduce:
MVP1 on Obtructive sleep apnea
search for acetaminophen

**Comment by sandrine-muller-research** [comment]
I think the predicate should be reversed for this result:
<img width="881" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/a9b637de-a5c6-47cb-9ccc-84417afd1689">

**Comment by cbizon** [comment]
This appears to be an openpredict issue

**Comment by andrewsu** [comment]
No longer appears to be an issue in the current system: https://ui.transltr.io/main/results?l=Obstructive+Sleep+Apnea+Syndrome&i=MONDO%3A0007147&t=0&r=69ba184a&q=a3a387b0-6d9a-4ec1-940d-de0157d56915

![image](https://github.com/NCATSTranslator/Feedback/assets/2635409/b4870c4a-6d1c-4d8b-8195-6a5433328dc2)
![image](https://github.com/NCATSTranslator/Feedback/assets/2635409/307bd103-c742-4fe3-8afb-a60fd2b63858)
![image](https://github.com/NCATSTranslator/Feedback/assets/2635409/e9007f90-cdd0-4100-8ee0-f126263c8987)
