### ISSUE TITLE
Influenza vaccine nodes not normalized

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#612]
## Steps to reproduce:
MVP1 on Multiple scerosis
search influenza
submitted by @sandrine-muller-research

**Comment by sandrine-muller-research** [comment]
<img width="988" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/9e647619-96d3-43dd-b4c3-60d11f17ce7a">
**identifiers:**
http://identifiers.org/chembl.compound/CHEMBL2109042
http://id.nlm.nih.gov/mesh/D007252
**NameRes:**
[NameRes DEV](https://name-resolution-sri-dev.apps.renci.org/lookup?string=INFLUENZA%20VIRUS%20VACCINE&offset=0&limit=10) seems to put those 2 in the same clique

It should be fixed soon when the released is pushed to test but I would liek confirmation from @gaurav that this was not fixed even before (hence could be a display issue). 
Thank you!

**Comment by gaurav** [comment]
This is [still split incorrectly](https://nodenorm.test.transltr.io/1.4/get_normalized_nodes?curie=CHEMBL.COMPOUND%3ACHEMBL2109042&curie=MESH%3AD007252&conflate=true&drug_chemical_conflate=false&description=false). Tracking on Babel at https://github.com/TranslatorSRI/Babel/issues/234

**Comment by sstemann** [comment]
![image](https://github.com/user-attachments/assets/1dbaa237-ec99-4fbb-80c0-fc872654d968)
