### ISSUE TITLE
Complement system proteins from MESH:D003165 not correctly normalized

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#615]
## Steps to reproduce:
MVP1 on MODY
submitted by @sandrine-muller-research

**Comment by sandrine-muller-research** [comment]
MESH:D003165 is shown as a chemical entity and should be a biological entity:
<img width="713" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/a3f2478b-19d0-4f20-b267-7d09880aae41">
Node norm:
Hitting NodeNorm is not found:
```
{
  "MESH:D0031653": null
}
```

**Comment by cbizon** [comment]
FWIW, I think that there's an extra 3 on the identifier in the comment above.  NN does know about the term, but it also does call it a chemical.

**Comment by sandrine-muller-research** [comment]
Oh right! there's a typo in the ID... Here is the returned json from NodeNorm with correct ID:
```
{
  "MESH:D003165": {
    "id": {
      "identifier": "MESH:D003165",
      "label": "Complement System Proteins"
    },
    "equivalent_identifiers": [
      {
        "identifier": "MESH:D003165",
        "label": "Complement System Proteins"
      },
      {
        "identifier": "UMLS:C0009498",
        "label": "Complement System Proteins"
      }
    ],
    "type": [
      "biolink:ChemicalEntity",
      "biolink:NamedThing",
      "biolink:Entity",
      "biolink:PhysicalEssence",
      "biolink:ChemicalOrDrugOrTreatment",
      "biolink:ChemicalEntityOrGeneOrGeneProduct",
      "biolink:ChemicalEntityOrProteinOrPolypeptide",
      "biolink:PhysicalEssenceOrOccurrent"
    ]
  }
}
```

**Comment by gaurav** [comment]
Tracking at Babel at https://github.com/TranslatorSRI/Babel/issues/233

**Comment by sierra-moxon** [comment]
I retested this morning and no longer see "Complement system proteins" as a result in the MODY type 2 query.  Please reopen if this is a different MODY or otherwise still a problem as I did my best to test it and follow the related links and can't see the issue any longer. :)
