### ISSUE TITLE
Autocomplete: cannot search for DDX3Y gene anymore

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#616]
## Steps to reproduce:
MVP2 What chemical may downregulate DDX3Y?

**Comment by sandrine-muller-research** [comment]
In the past I could search for this gene (see issue https://github.com/NCATSTranslator/Feedback/issues/384)

**Comment by gaurav** [comment]
DDX3Y has reappeared, closing.

<img width="1315" alt="Screenshot 2024-01-23 at 2 25 32 PM" src="https://github.com/NCATSTranslator/Feedback/assets/23979/59d639ab-d318-4583-8b26-ad7ab2834e39">
