### ISSUE TITLE
Exclude filter

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#619]
## Steps to reproduce:
MVP1 on HIV-associated nephropathy

**Comment by sandrine-muller-research** [comment]
I would like to **exclude** paths that contain ABCB1 gene. I am not able to do that currently.

**Comment by gprice1129** [comment]
This is a great suggestion. Thanks!

**Comment by sierra-moxon** [comment]
@gprice1129 - do you still want this as an issue?  Is it likely to be prioritized in the next year?  Or is it a future request that we can close and reopen as need be.

**Comment by gprice1129** [comment]
@sierra-moxon I will bring this up with the team and will get back to you.

**Comment by dnsmith124** [comment]
Exclusion has been implemented on all filters, closing.
