### ISSUE TITLE
Which KP can bring in data from DDInter database to help Translator return more drug-drug interaction data?

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#62]
The QotM identified [DDInter database](http://ddinter.scbdd.com/) as a potential source of data on drug-drug interactions, e.g., a relationship between CBD and valproic acid: http://ddinter.scbdd.com/ddinter/interact/1002248/.

**Comment by sierra-moxon** [comment]
from #66 - we want data that can show the content of CBD oil.

**Comment by andrewsu** [comment]
A few notes on DDInter:
* Service Provider created an API, available at https://biothings.ncats.io/ddinter
* Incorporation into BTE is pending review/merging of the SmartAPI annotation, tracked in https://github.com/biothings/pending.api/issues/68
* The list of downloadable files at http://ddinter.scbdd.com/download/ appears to be incomplete. For example, the interaction noted by @karafecho above (http://ddinter.scbdd.com/ddinter/interact/1002248/) is not found in any of the linked files, but it is found in the _unlinked_ http://ddinter.scbdd.com/static/media/download/ddinter_downloads_code_N.csv file
* I'd previously emailed the authors on the [contact page](http://ddinter.scbdd.com/contact/) twice about an identifier mapping issue and got no response.

**Comment by sierra-moxon** [comment]
related BTE ticket is closed; closing this.
