### ISSUE TITLE
Missing data from Aragorn

### ISSUE THREAD

**Issue by Genomewide** [NCATSTranslator/Feedback#620]
I was getting sample data and running it through the script to get back spreadsheets.  So, if fails if anything is different or missing. Out of 10 searches Aragorn returned results for 4 and two of them gave me an error. 

For the first one, I could not find it via search in the UI after chasing up to the node for Chalcogens.  It was not exhaustive search though.  It does appear to be a nested inferred edge (I think).  

https://ui.transltr.io/main/results?l=Codeine&i=PUBCHEM.COMPOUND:5284371&t=3&q=da11f5a0-eb84-4784-a67b-f43dc5c5a41f
support graph ID referenced but not in the knowledge graph edges

                        "35c5bc0ccab7": {
                            "object": "NCBIGene:8648",
                            "sources": [
                                {
                                    "resource_id": "infores:service-provider-trapi",
                                    "resource_role": "primary_knowledge_source"
                                },
                                {
                                    "resource_id": "infores:aragorn",
                                    "resource_role": "aggregator_knowledge_source",
                                    "upstream_resource_ids": [
                                        "infores:service-provider-trapi"
                                    ]
                                }
                            ],
                            "subject": "PUBCHEM.COMPOUND:5284371",
                            "predicate": "biolink:affects",
                            "attributes": [
                                {
                                    "value": [
                                        "support0-PUBCHEM.COMPOUND:5284371-affects-NCBIGene:8648-via_subclass"
                                    ],
                                    "attribute_type_id": "biolink:support_graphs"
                                },
                                {
                                    "value": 1,
                                    "value_type_id": "EDAM:data_1669",
                                    "attribute_type_id": "biolink:has_numeric_value",
                                    "original_attribute_name": "weight"
                                }
                            ]
                        },

https://ui.transltr.io/main/results?l=Bethlem%20Myopathy&i=MONDO:0008029&t=0&q=cd108944-3281-4aea-adf5-90200503bbdb
Node referenced and not in nodes:
PUBCHEM.COMPOUND:1103

                        "ca63d5667cf0": {
                            "object": "PUBCHEM.COMPOUND:1102",
                            "sources": [
                                {
                                    "resource_id": "infores:umls",
                                    "resource_role": "primary_knowledge_source"
                                },
                                {
                                    "resource_id": "infores:service-provider-trapi",
                                    "resource_role": "aggregator_knowledge_source"
                                },
                                {
                                    "resource_id": "infores:aragorn",
                                    "resource_role": "aggregator_knowledge_source",
                                    "upstream_resource_ids": [
                                        "infores:service-provider-trapi"
                                    ]
                                }
                            ],
                            "subject": "PUBCHEM.COMPOUND:1103",
                            "predicate": "biolink:subclass_of",
                            "attributes": [
                                {
                                    "value": 1,
                                    "value_type_id": "EDAM:data_1669",
                                    "attribute_type_id": "biolink:has_numeric_value",
                                    "original_attribute_name": "weight"
                                }
                            ]
                        },

**Comment by cbizon** [comment]
I have a suspicion that this could be a strider issue... what do you think @uhbrar ?

**Comment by sierra-moxon** [comment]
https://github.com/ranking-agent/strider/pull/443 reports this is fixed. 
closing
