### ISSUE TITLE
Why is BTE the primary source of phenotype_of Edges?

### ISSUE THREAD

**Issue by mbrush** [NCATSTranslator/Feedback#628]
https://ui.test.transltr.io/main/results?l=Cerebral%20Palsy&i=MONDO:0006497&t=0&q=52bea588-5893-48b2-8561-16309ab0a1ed

![image](https://github.com/NCATSTranslator/Feedback/assets/5184212/14dd6695-4c8f-41d8-9650-65e99e0588d5)

BTE shows as the primary source of phenotype_of edges in the support paths for many results, e.g. the `Hypotonia -phenotype_of--> Cerebral Palsy` edge in the example above.  I suspect the actual primary source is likely HPO Annotations, but the ARAX UI does not actually report any source provenance for the phenotype edges - so I cannot say for sure:
![image](https://github.com/NCATSTranslator/Feedback/assets/5184212/e257a29c-a5bf-4fe8-be65-1f5c698669b1)

I suspect that this may be a case where **HPOA reports that Hypotonia  is a phenotype of some subclass of Cerebral Palsy** - and **BTE makes the trivial inference that it is also a phenotype of the more general Cerebral Palsy parent** - and thus gives itself credit as the primary source for this edge.  This is known to happen - but the way things are currently displayed in the UI it is confusing, because we cannot see that this inference happened (which would require a 'nested' support graph for the trivially inferred phenotype_of edge).

-----

A **problem with this explanation**, however, is that, I note in this example that **subclass_of edges are shown in other paths where it seems this type of trivial inference is performed**, and the subclass of edge is explicitly shown in the support path, e.g.:

![image](https://github.com/NCATSTranslator/Feedback/assets/5184212/95294631-bfdb-4037-bbae-137fc03bd263)

This, of course, makes me doubt the above explanation of the BTE-attributed phenotype-edges.

Hoping @colleenXu or @andrewsu  can help make sense of what is happening here.

**Comment by gprice1129** [comment]
Hi @mbrush we are currently working to redesign the path display to make in clear which paths support which edges. Right now it is very difficult to trace this in the UI.

**Comment by sierra-moxon** [comment]
closing as complete.
