### ISSUE TITLE
CPT and CMS are proprietary: can NCATS reach out to AMA as was done with SNOMED to grant Translator access?

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#63]
The QotM highlighted the fact that procedures are not well represented in Translator. CPT and CMS data are proprietary. OHDSI has approval to use CPT, but not CMS. UMLS also is proprietary, but Translator’s use of data is acceptable to SNOMED (NCATS has letter of waiver). A GitHub ticket was posted, and the CPT prefix was added to bioregistry (see https://github.com/TranslatorSRI/NodeNormalization/issues/124 and PR https://github.com/biolink/biolink-model/pull/993). However, this effort is on hold due to licensing concerns. A decision was made for NCATS to discuss the issue internally to determine if it makes sense to reach out to the AMA, as was done with SNOMED. Creating a ticket here to circle back to previous discussions.

**Comment by sierra-moxon** [comment]
@sstemann - I saw that you were assigned to the DrugBank ticket, is it ok if I assign this to you as well?  I think it basically talks about NCATS possibly reaching out the AMA about licensing CPT?

**Comment by sierra-moxon** [comment]
@cartmanbeck - is this something NCATs could do, or should we look for alternatives?

**Comment by cartmanbeck** [comment]
I think it's possible that we could do so, but it's not really a priority right now. I'd recommend this becoming an "after September" topic.

**Comment by sierra-moxon** [comment]
closing as "won't do" - please reopen if need be.
