### ISSUE TITLE
Evidence for Prednisone treats Gout query is duplicative

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#630]
https://ui.transltr.io/main/results?l=Gout&i=MONDO:0005393&t=0&q=1ae897c3-72cd-4ea5-96b2-d40ef7bc379b

In the evidence display, this pub: https://pubmed.ncbi.nlm.nih.gov/36345820/ shows up many times in at least the first three pages of results. 

<img width="1128" alt="Screen Shot 2023-11-13 at 8 29 41 AM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/288097f6-9875-4a16-90cd-7fcb6bef0b0a">
<img width="1123" alt="Screen Shot 2023-11-13 at 8 29 23 AM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/6dd1531a-f87b-44bc-9415-6c08d8098b9d">
<img width="1154" alt="Screen Shot 2023-11-13 at 8 28 56 AM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/cb326617-9bec-45ab-9853-51c6fff87313">

**Comment by gprice1129** [comment]
@sierra-moxon please see the new evidence modal in Test. It is no longer possible to "view all evidence". You can now only view evidence in the context of a path.

There is also a known issue which rarely causes duplicates because we get the same publication with different IDs (PMC vs. PMID).
