### ISSUE TITLE
unclear from sources and publications how CYP2C9 associated with gout

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#631]
https://ui.transltr.io/main/results?l=Gout&i=MONDO:0005393&t=0&q=1ae897c3-72cd-4ea5-96b2-d40ef7bc379b

Looking at the paths for Sulfaphenazole.  
<img width="1086" alt="Screen Shot 2023-11-13 at 8 57 56 AM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/a0b665d3-b2e2-4b83-9a7f-2dd47794cc8c">

None of the first 5 publications have any mention of the gene nor of gout.
<img width="1151" alt="Screen Shot 2023-11-13 at 8 58 21 AM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/71d885d5-2293-406d-8262-134b5f26fa6f">

a quick google of "Cyp2c9 Associated With Gout" gives me this pub: https://pubmed.ncbi.nlm.nih.gov/30742400/ which is quite helpful in determining that Cyp2c9 breaks down a treatment for gout, Lesinurad, into inactive metabolites and those with Cyp2c9 variants often are at risk for non-gout related affects. 

second google result: https://bmcmedicine.biomedcentral.com/articles/10.1186/s12916-017-0878-5 talks about several other genes associated with gout, but again Cyp2c9 is described as a metabolizer of the treatments.  

As a user of the system I could not find evidence for the assertions made in this result even with an additional 15 mins of research outside of translator.  15 mins isn't a lot of time, but it is significant.

**Comment by gprice1129** [comment]
Hi @sierra-moxon is this a UI issue?

**Comment by sierra-moxon** [comment]
I think the new evidence widget helps fix this problem.   I checked the first pub that says Sulfaphenazole affects Cyp2c9 and I was able to find the connection right away.  And the first pub returned is different than shown in these screen shots. I'm closing as completed! :)
