### ISSUE TITLE
Searched on gene POGZ and only had results from one source

vsutton@bcm.edu

Thanks!

Reid Sutton

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#637]

**Comment by sierra-moxon** [comment]
@dnsmith124 @Genomewide @gprice1129 - I can not reproduce this one; is it possible it was a case where new results were still loading, or did you notice any downtime this afternoon?

**Comment by sstemann** [comment]
when i click on the link, there's only one Reasoning Agent - Improving Agent - and two sources Improving Agent and LINCS for the 299 results

<img width="935" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/1214233d-3ca3-44e8-828d-f57586a83f49">

<img width="683" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/58ae090a-007e-4bab-bc78-2d622a7404c9">

**Comment by dnsmith124** [comment]
Opening this query in ARAX shows 300 results from improving, 0 results from all other providers: 

https://arax.ncats.io/?r=01096467-84d8-4346-a7b6-d80eaf92c947

**Comment by gprice1129** [comment]
@sierra-moxon @sstemann shouldn't we close this? Not sure what the action item is supposed to be.
