### ISSUE TITLE
Ethanol causes, does not treat, alcoholic hepatitis

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#638]
What may treat alcoholic hepatitis?

https://ui.transltr.io/main/results?l=Alcoholic%20Hepatitis&i=MONDO:0001505&t=0&q=461d8e85-cc77-40b1-b2b3-8be21053e1d5

Results include Ethanol (score 4.97), with multiple paths, including a direct path with 8 publications listed as evidence. Sources are BTE, Sem Med Db and Text Mining Targeted Association API. 

Related issue: [Promiscuous compounds](https://github.com/NCATSTranslator/Feedback/issues/617) (Ethanol is one of the promiscuous compound listed).

**Comment by khanspers** [comment]
Ethanol also comes up as a result for **What drugs may treat Alcohol Dependence**: 
https://ui.transltr.io/main/results?l=Contact%20Dermatitis&i=MONDO:0005480&t=0&q=ec7728fd-0ecd-47ab-a368-b16df12c77d6

**Comment by khanspers** [comment]
Re-tested on **test**:

Ethanol is there, but with a slightly lower score (4.75, on the 4th page of results). This time there is only one _treats_ path, from Text Mining provider, with 8 publications.

https://ui.test.transltr.io/main/results?l=Alcoholic%20Hepatitis&i=MONDO:0001505&t=0&r=5b81e344&q=ca0579fa-146c-4de0-8e9d-f870e223b9be

**Comment by sierra-moxon** [comment]
from TAQA: retested on TEST today and do not see ethanol in the results.
