### ISSUE TITLE
openpredict returning invalid TRAPI

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/Feedback#640]
Seen in recent query: https://arax.ci.transltr.io/?r=663047cb-3be8-4d5b-accf-9e269b16528b

openpredict returns TRAPI that fails validation:
![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/e2eceeb5-5d32-4428-a61c-b6b73adead64)

```
Critical:
* Trapi:
=> Schema validation error
	$ global
		# v1.4.2:
		- component | json_path | reason: 
			Result | $.analyses[0].score | '0.37232527298936924' is not valid under any of the given schemas
			Result | $.analyses[0].score | '0.3523232735105733' is not valid under any of the given schemas
			Result | $.analyses[0].score | '0.3452443056654675' is not valid under any of the given schemas
			Result | $.analyses[0].score | '0.29251829801939117' is not valid under any of the given schemas
...
```

**Comment by sierra-moxon** [comment]
from TAQA: @CaseyTa - is this possibly something that you are already aware of? :)

**Comment by CaseyTa** [comment]
@vemonet Looks like score is being written as str. I can see this behavior currently in all environments (dev and all ITRB).

**Comment by vemonet** [comment]
Thanks for the notification, I made sure that we are formatting the score as `float()` in python. But it is automatically converted to a string back in the response

I think I remember it was returned as number in the past, and we did not made any change to it  since then, so a bit 
mysterious

**Comment by CaseyTa** [comment]
Working correctly in CI.
