### ISSUE TITLE
Water is a drug?!

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#641]
## Steps to reproduce:
What drugs may treat:Alcoholic Hepatitis?
select : Drug, and all phases

**Comment by sandrine-muller-research** [comment]
<img width="1255" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/137a6d6e-140f-47af-9009-d0fc2dbd740a">
BTE returns Water classified drug, that does not look right to me? or, what is the real definition of Drug there?
Thanks

**Comment by sandrine-muller-research** [comment]
I found also atoms such as nitrogen and hydrogen as "drugs".
The website specifies : "Drug is a substance intended for use in the diagnosis, cure, mitigation, treatment, or the prevention of a disease."

**Comment by sandrine-muller-research** [comment]
also found amino acids

**Comment by gglusman** [comment]
[2024/1/11 test of 'what chemicals may upregulate NGLY1'](https://ui.test.transltr.io/main/results?l=NGLY1+%28Human%29&i=NCBIGene%3A55768&t=1&r=53ab4490&q=85359158-4838-483c-a204-ba536d2388ba): water is a result, and it's retained when selecting 'drug':
<img width="1494" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/3977332/1ae84916-2b31-4510-9b54-966a38cd58cc">

**Comment by sierra-moxon** [comment]
from TAQA: retested today on TEST and do not find water; closing
