### ISSUE TITLE
genetics-data-provider: meta_knowledge_graph/ endpoint in dev returns 502 error

### ISSUE THREAD

**Issue by isbluis** [NCATSTranslator/Feedback#645]
ARAX has not been able to expand to **Genetics KP** in _development_ for the past week or so, since the published endpoint (https://translator.broadinstitute.org/genetics_provider/trapi/v1.4/meta_knowledge_graph) does not return a valid meta_knowledge_graph:

![image](https://github.com/NCATSTranslator/Feedback/assets/37852256/891f0f79-5b28-4339-bfc0-0f483efa9edc)

**Comment by isbluis** [comment]
Just a quick follow up on this issue, pre-code freeze. ARAX has not been able to expand **Genetics KP** in _development_ since mid-November. Still get same 502 error.

**Comment by sierra-moxon** [comment]
@marcdubybroad - is this your KP? :) if not, pleas feel free to reassign to me for investigation.

**Comment by isbluis** [comment]
This seems resolved.  Closing.
