### ISSUE TITLE
can we search for any disease?

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#648]
## Steps to reproduce:
remove search for disease

**Comment by sandrine-muller-research** [comment]
<img width="1221" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/22616936/07ac64ef-1689-45bc-a9f7-05a29d6095c8">

**Comment by sandrine-muller-research** [comment]
already exists in #587
