### ISSUE TITLE
Add license / usage restriction disclaimer on UI landing page

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#651]
Per discussion with @Genomewide, @cartmanbeck, @sierra-moxon, and @tursynay, we have agreed to include a disclaimer statement on the UI landing page related to licensing and usage restrictions. Currently, this information is included within a field on the wiki page for each Translator resource. We will remove that field from the wiki pages for all resources _except_ those in which licensing and usage restrictions are critical to include, namely, DrugBank and the clinical KPs.

Suggested wording:

"The Translator System is comprised of numerous distinct components, including an interface, data, ontologies, software, and algorithms. It is therefore not possible to provide everything under a unified license. However, every effort is made to ensure that all components are openly available and free of usage restrictions."

**Comment by dnsmith124** [comment]
@karafecho is this verbiage finalized? I'm happy to add this to the current disclaimer page asap, just want to make sure we've got the final wording before doing so.

**Comment by sstemann** [comment]
@dnsmith124 @karafecho @Genomewide @cartmanbeck 

After talking with Christine and Tyler, we'd like the language to read:  Translator components are made publicly available from the sources listed [insert wiki homepage]. Please respect their individual licenses regarding proper use and redistribution.

We also agreed it does not need to be in the disclaimer banner, we'd like to keep the disclaimer banner focused on the intended usage of the results.    I'm not super clear with the Wiki InfoRes landing page so I didnt provide the specific link.

**Comment by Genomewide** [comment]
Thanks! Adding @dnsmith124 @gprice1129 for implementation.

**Comment by dnsmith124** [comment]
I've added the approved verbiage to the UI's disclaimer, it now reads the following: 
![Screen Shot 2023-12-05 at 2 21 33 PM](https://github.com/NCATSTranslator/Feedback/assets/54226761/e0a6a5fb-078e-47c7-9225-cf64bc6c5978)

This has been deployed to CI, @karafecho are we good to close?

**Comment by karafecho** [comment]
@sstemann : Is the above okay? You mentioned that Link Brokers didn't want to include the disclaimer in the banner, but the text is separated and not very wordy, so perhaps it's acceptable?

**Comment by dnsmith124** [comment]
Just to clarify, the above is not the banner, it's the disclaimer that appears when a user first accesses the site or first logs in

**Comment by karafecho** [comment]
Oh, thanks for the clarification. Unless Sarah objects, then I'd say the verbiage is fine.

**Comment by gprice1129** [comment]
Closing. Re-open if you feel strongly that this issue has not been resolved.
