### ISSUE TITLE
Trapi not returning forward and reverse predicates

### ISSUE THREAD

**Issue by Genomewide** [NCATSTranslator/Feedback#652]
@cbizon @dkoslicki - Was not sure who to share this with, but it looks like there is a wide change to what I thought the rules were and wanted to check in with the two of you. 

I understood previously that a query for any predicate would be returned for both directions. So, if I query with 'Affects' then it would also return 'Affected_by.'  Doing some work to investigate what is returned when getting all nodes one hop from a target node, I tried both directions by swapping the subject and object of a query and I get very different counts of what is returned.  I have not looked at the over lap, but the counts suggest that it currently a poor assumption that you get back both directions for a single query. Below are some examples.  

Some of them differ by 100s.  

Link 1a: https://arax.ncats.io/?r=36d95514-e302-44a7-92be-7f64a9472cf9
Query:
```json
{
  "edges": {
    "e0": {
      "attribute_constraints": [],
      "object": "n1",
      "predicates": [
        "biolink:affects"
      ],
      "qualifier_constraints": [],
      "subject": "n0"
    }
  },
  "nodes": {
    "n0": {
      "categories": [
        "biolink:Gene"
      ],
      "constraints": [],
      "ids": [
        "NCBIGene:8878"
      ],
      "is_set": false
    },
    "n1": {
      "constraints": [],
      "is_set": false
    }
  }
}
```

Results:
![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/7b8360e5-2301-48b5-b9f4-663f45369d74)
  

Link 1b: https://arax.ncats.io/?r=e1878639-741f-4281-a870-41429d9d9617
Query:
```json
{
  "edges": {
    "e0": {
      "attribute_constraints": [],
      "object": "n0",
      "predicates": [
        "biolink:affects"
      ],
      "qualifier_constraints": [],
      "subject": "n1"
    }
  },
  "nodes": {
    "n0": {
      "categories": [
        "biolink:Gene"
      ],
      "constraints": [],
      "ids": [
        "NCBIGene:8878"
      ],
      "is_set": false
    },
    "n1": {
      "constraints": [],
      "is_set": false
    }
  }
}
```

Results:
![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/6b36ab6b-467b-4855-8513-cf76a3e1927d)

Other examples:
2a: https://arax.ncats.io/?r=d08f1bac-794d-4ef8-bbbd-222e3d9c43c0
![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/19b237d4-2e3e-44e3-ae85-a32a29ee21b5)

2b: https://arax.ncats.io/?r=669c7210-a231-4459-8038-7b92e0a9f0af
![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/4a57bcdd-3756-455f-9c82-42dd9bd0d4e7)

3a: https://arax.ncats.io/?r=9ad34654-3c83-4164-8df4-aa73181d50ad
![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/72df7df3-7dbf-4d03-b6a8-c7512cdfa563)

3b: https://arax.ncats.io/?r=b00af29d-5b70-45bd-acb0-8d9cd00615d5
![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/69bf4339-c01b-47fb-a838-7ec437cbcedd)

4a: https://arax.ncats.io/?r=b340c22c-f158-4463-a052-ed7444d73ddd
![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/33601bad-cd03-4f57-857a-ad5665892a79)

4b: https://arax.ncats.io/?r=34cadb3a-ca89-46e6-b841-080497f34fb7
![image](https://github.com/NCATSTranslator/Feedback/assets/55069176/0c0eb216-6e40-415e-aee4-dbcc4768bc3e)

**Comment by cbizon** [comment]
One more potentially relevant point - when results are being returned, say for the affects query.  It would be semantically correct to return either A-[affects]->B or B-[affected by]->A, but in this case TRAPI components are supposed to return only the canonical direction, as defined in the biolink model.

**Comment by Genomewide** [comment]
Ok. I think this was my issue.  I misunderstood. Thanks for the clarification.  This last point is what I was confusing.

From: cbizon ***@***.***>
Date: Friday, December 1, 2023 at 8:23 AM
To: NCATSTranslator/Feedback ***@***.***>
Cc: Andy Crouse ***@***.***>, Author ***@***.***>
Subject: Re: [NCATSTranslator/Feedback] Trapi not returning forward and reverse predicates (Issue #652)

One more potentially relevant point - when results are being returned, say for the affects query. It would be semantically correct to return either A-[affects]->B or B-[affected by]->A, but in this case TRAPI components are supposed to return only the canonical direction, as defined in the biolink model.
