### ISSUE TITLE
Curated Publications

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#654]
Seeing Curated in the UI, for me, was interpreted as "Curated" for/by Translator.  It's hard to understand how or where it was curated.

https://ui.ci.transltr.io/main/results?l=Marfan%20Syndrome&i=MONDO:0007947&t=0&q=1a27a88f-2b0b-455a-b34a-eafe6a0cbbee

- What drugs may treat Marfan Syndrome
- 2nd path: Cyclophosphamide - Ehmt2 - Flna - **Associated With** Marfan
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/00924ed2-2c03-4e19-a62c-7f0a62c8c09c)

- Are these pubs Curated by "Diseases"?
- The wiki says its automatic text mining, manually curated literature, cancer mutation data, and genome-wide association studies
- I did end up finding Marfan-FLNA under Text Mining, Z-Score

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/ec6fc60e-277a-46d0-b2f2-eea01b83759e)

**Comment by Genomewide** [comment]
We have had a request to add this information and will track it with this ticket.  
The current plan is to put the source in the column with the term currated.

**Comment by gprice1129** [comment]
@sstemann does the current Evidence Modal address this issue?

**Comment by sstemann** [comment]
i think so, thanks!
