### ISSUE TITLE
Semmed as the only Knowledge Source

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#655]
Can you have a result from Semmed without a pub?

What may treat a common cold in CI https://ui.ci.transltr.io/main/results?l=Common%20Cold&i=MONDO:0005709&t=0&q=51d223a5-3af5-4c3b-a8d6-4fc11f4bef78

Result: Medicament
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/cdbb43a9-944f-404e-adfd-0ee883a8b667)

Result Graph EPC
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/fb62c87a-b34e-4b5c-a626-103d21b89ed3)

Analysis Graph Info
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/082d3954-69f4-4fd9-86dc-84c9e5e78396)

**Comment by gglusman** [comment]
Also, something as generic as 'medicament' should be on the block list.

**Comment by edeutsch** [comment]
It looks like this edge comes from biothings, so we don't have control over the lack of publication.
but I can check why medicament is not in our block list and perhaps add it.

**Comment by sstemann** [comment]
@andrewsu just checking if you have thoughts why the edge listed as Semmed without any publications? is that expected?

**Comment by andrewsu** [comment]
This is not expected -- a bug that was introduced in CI.  Ticket added here: https://github.com/biothings/biothings_explorer/issues/766

**Comment by colleenXu** [comment]
This should be addressed in BTE dev/CI since 12/15 https://github.com/biothings/biothings_explorer/issues/766#issuecomment-1858703041

**Comment by sstemann** [comment]
can't replicate so must be fixed.  Thank you!
