### ISSUE TITLE
Miscellaneous Links from MolePro - Pubs as Strings

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#656]
CI > What drugs may treat common cold > aspirin > top level path > treats > Miscellaneous

https://ui.ci.transltr.io/main/results?l=Common%20Cold&i=MONDO:0005709&t=0&q=51d223a5-3af5-4c3b-a8d6-4fc11f4bef78

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/18d58772-f7c9-495d-b30f-5be93bb63fa8)

Links are going to here:
https://ui.ci.transltr.io/main/785e913e-1780-4fd4-8428-d83c26fe810c
https://ui.ci.transltr.io/main/b4a9f50f-9eda-4d8f-91be-4053ee6ce0ec
https://ui.ci.transltr.io/main/4ca79a79-b977-40e5-87d6-fd7d7a1240a9
https://ui.ci.transltr.io/main/1118dc27-0a9e-4a48-b86c-1338bf28fecc
https://ui.ci.transltr.io/main/4e13511b-fbb5-2523-e054-00144ff88e88

I don't know if this is a UI or ARAX issue there are many links via the ARAX Viewer and I can't figure it out.

**Comment by edeutsch** [comment]
If this is meant for me, I don't quite understand the issue. I think I was able to find my way to the same page:
![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/8a856d35-c461-4ee0-ac86-5cbdf4874aef)

But I don't see link outs the ARAX viewer. The second batch seems to go to the Translator UI.

So I don't know exactly what the issue is here.

**Comment by dnsmith124** [comment]
I loaded this pk into ARAX then navigated to the Asprin result provided by ara-arax and found the following:

On the 5th treats edge from the bottom yyou can see the above alphanumeric codes (they look like pks to me), provided under the attribute "biolink:publications":
![Screen Shot 2023-12-05 at 10 16 24 AM](https://github.com/NCATSTranslator/Feedback/assets/54226761/40798526-1dd3-4529-aa34-6eb435abb4c4)

So it doesn't appear to be a UI bug in this case. @sstemann @edeutsch do either of you know what these codes are supposed to represent?

**Comment by edeutsch** [comment]
Ah, I see it now, thanks. This edge is coming from MolePro and ARAX is just including it as-is.

So I think @vdancik is the one that needs to be tagged here.
@vdancik see this result:
https://arax.ci.transltr.io/?r=179144
Search for Aspirin
5th from the bottom treats edge

MolePro appears to encoding DailyMed UUIDs as publication identifiers, which is leading to a confusing display in the Translator UI. I don't think UUIDs are suitable publication identifiers.

![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/1f86b376-8181-4b74-8905-a4fc0c723587)

**Comment by sstemann** [comment]
> If this is meant for me, I don't quite understand the issue. I think I was able to find my way to the same page: ![image](https://private-user-images.githubusercontent.com/12707718/287873567-8a856d35-c461-4ee0-ac86-5cbdf4874aef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MDA3MTMsIm5iZiI6MTcwMTgwMDQxMywicGF0aCI6Ii8xMjcwNzcxOC8yODc4NzM1NjctOGE4NTZkMzUtYzQ2MS00ZWUwLWFjODYtNWNiZGY0ODc0YWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE4MjAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNDljNDZiYTdkNTg1OGZhZjE5ZDUwOTAzMGM1YmQ1OWZjMmViZDhkYTU1YmE3M2IxZGYxY2RmMWEzMjEwMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E8xkUOCKh583ENdtxtY7AOciSQOMHG0Vk2KhW5VYnpw)
> 
> But I don't see link outs the ARAX viewer. The second batch seems to go to the Translator UI.
> 
> So I don't know exactly what the issue is here.

I'm sorry about this @edeutsch , I think i had too many trains of thought at the same time.  I do appreciate you looking into it.

**Comment by vdancik** [comment]
@sstemann , indeed it's an issue with MolePro, references with URLs should not be repeated as strings.

**Comment by sstemann** [comment]
@gprice1129 @dnsmith124 it looks fixed in the UI but I'm still seeing UUIDs in the publication string from MolePro so is this ready for closing or is MolePro working on a fix still for the JSON? @vdancik 

https://ui.test.transltr.io/main/results?l=Common%20Cold&i=MONDO:0005709&t=0&r=0&q=13feaf81-b638-41b9-bde7-49edb7e8f3fd

https://arax.ncats.io/beta/?r=13feaf81-b638-41b9-bde7-49edb7e8f3fd
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/f4fe4964-9ec3-4a05-8649-71ac8c5e9de4)

**Comment by gprice1129** [comment]
References with URLs should not be repeated as strings, which is still the case here, so this is still an open issue for MolePro.

**Comment by sstemann** [comment]
this looks resolved
