### ISSUE TITLE
Edges with Only ARA as the Evidence - listed as "Knowledge Source"

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#657]
I guess this is the inferred edge.  and the ARA is listed as the Primary Source in the JSON.  It might just be listing them under Knowledge Sources, where often we find Chembl or Diseases should be reconsidered?
Steps to recreate:

1. UI Prod > Log > What drugs may treat Fanconi Anemia
2. Result Tretinoin
3. First path (the one hop)
4. Click Treats

Unsecret
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/c3abc381-d4fb-46f1-a628-f61cf7c87ff5)

ARAX - Triamcinolone Diacetate (last path after expanding)
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/8a3691fb-bbf8-4c24-80e5-f56a9ac94942)

**Comment by gprice1129** [comment]
@sstemann this is working as intended. This is the reason we need a path display redesign: to show the user very clearly what paths support this edge.

**Comment by sstemann** [comment]
I get that it matches the model.  I'm wondering if users understand why we are showing a direct path with one "KS" (reasoner).

**Comment by dnsmith124** [comment]
I think you're right @sstemann, I believe Gus' point was to say that we're currently working on the path display redesign to address this issue. So we should be able to close this ticket, since we're tracking this problem and currently working to address it.

**Comment by colleenXu** [comment]
Was this happening in prod (text of original post), test (screenshots of original post), or ci? 

Our team earlier noticed an issue in CI https://github.com/biothings/biothings_explorer/issues/770 but it seems to have resolved w/o any ARS action ([Translator Slack link](https://ncatstranslator.slack.com/archives/C013Q5TVC87/p1704818100671529))

**Comment by gprice1129** [comment]
@sstemann does the version in the Test UI make this clearer? If so can we close this issue?

**Comment by sstemann** [comment]
this looks better!  thank you!
