### ISSUE TITLE
UMLS Metathesaurus in Download but Not UI

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#658]
Steps to recreate:

1. Log into Test UI
2. Run What drugs may treat for Fanconi Anemia: https://ui.test.transltr.io/main/results?l=Fanconi%20Anemia&i=MONDO:0019391&t=0&q=f541f71f-db3a-4cb8-a765-e7ccd0016c61
3. For result Sargramostim , click Download
4. Open CSV in Excel 
5. Notice this in column J
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/c52f381e-26e6-4fe4-b87d-02f8c82335c5)

6. In the corresponding path in the UI, Sagramostim > Granulocyte-Macrophage Colony-Stimulating Factor > TNF, I dont see those other KS's 

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/4565b556-383e-4b0a-a94e-1904e7d64c26)

I guess Semmed is on the Affects edge, but i dont see umls-metathesaurus.  I see umls-metathesaurus in info-res so asking UI to investigate.

**Comment by dnsmith124** [comment]
Retested today after our recent deployment to TEST, this issue has been resolved. Knowledge sources returning on that edge now read: 
![Screen Shot 2024-01-23 at 1 16 11 PM](https://github.com/NCATSTranslator/Feedback/assets/54226761/d7bb5043-7955-4408-892d-420a22268636)

Closing.
