### ISSUE TITLE
What drugs may treat depression (depressive disorder)

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#660]
**Query:** What drugs may treat depression (depressive disorder [MONDO_0002050](http://purl.obolibrary.org/obo/MONDO_0002050))
**UI:** https://ui.transltr.io/main/results?l=Depressive%20Disorder&i=MONDO:0002050&t=0&q=33b4732e-8549-43d5-b53f-f9a0072f29b8
**CI:** https://ui.ci.transltr.io/main/results?l=Depressive%20Disorder&i=MONDO:0002050&t=0&q=78b8dd7d-6ddd-4d31-99a9-7d725eb3b7ad

Many known treatments are returned with high scores (Lorazepam, Sertraline, SSRIs, Bupropion etc), but some weird answers also have high scores:

- On CI, the third result listed (score 5.0) is for Lipopolysaccharides (LPS). The only mentions of LPS and depression that I can find are for animal models of depression where LPS is used to _**induce**_ depression. A direct treats path is coming from Unsecret agent (no publications). 

The other path is through IL-1b (see below). For the first part, LPS is associated with IL-1b, there are a lot of publications, most of them are related to inflammation/immune function/lung function/infection. The second part does include some papers relevant to depression.
![Screen Shot 2023-12-18 at 11 14 22 AM](https://github.com/NCATSTranslator/Feedback/assets/1442197/3c6bee91-fa2c-4321-b226-8e8813a8428e)

- On both UI and CI, Novobiocin (an antibiotic) is returned with a score of 4.98, coming from Improving agent.

**Comment by khanspers** [comment]
Tested on **test** today, and LPS is there with the same paths

https://ui.test.transltr.io/main/results?l=Depressive%20Disorder&i=MONDO:0002050&t=0&r=561f1f4e&q=4b13f903-f59d-4055-a91d-f439d0c26873

**Comment by khanspers** [comment]
Just tried this today and not seeing Lipopolysaccharides in results on test: https://ui.test.transltr.io/main/results?l=Depressive%20Disorder&i=MONDO:0002050&t=0&r=0&q=71a825d2-b5a3-4aef-8c19-7e244f26250b.
So maybe it should be closed.

**Comment by gaurav** [comment]
Glad to hear the result is no longer showing up! Even if it did show up, the updated UI design should make it clearer that this is inferred. Closing.
