### ISSUE TITLE
I suggest that you load all the results before providing them to users. It is not obvious that the results are not complete when the page first loads. A loading bar could help clarify that the algorithm is still running, so users do not refresh the page. 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#662]

**Comment by gglusman** [comment]
One component of a solution could be to display something like 'Sneak peek at preliminary results...' instead of 'Results', while they are incomplete.

**Comment by codewarrior2000** [comment]
I recall that at some point in 2023, the notion of a progress bar was dismissed as the visual cue to the user of more incoming results. If not a progress bar, then something to show that not all ARAs have reported in with results yet.

**Comment by dnsmith124** [comment]
We've gotten this bit of feedback before and made changes to address it, like adding the floating progress window to the bottom right of the viewport, but that change appears to have not been enough. 

As a team we're currently investigating ways to improve the clarity of this for users.

**Comment by dnsmith124** [comment]
A loading bar has been added to the results page to make the current status of results more obvious to the user. 

Closing
