### ISSUE TITLE
What drugs may treat Autism fails in the Test and CI UI

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#668]
Test UI

https://ui.test.transltr.io/main/results?l=Autism&i=MONDO:0005260&t=0&r=0&q=f1036b1d-fd6a-46da-97b3-56ffb991bf05

https://arax.ncats.io/?r=f1036b1d-fd6a-46da-97b3-56ffb991bf05

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/967ccfcd-8cac-446d-abf1-3807287958b8)

Seems like all of the ARAs but ARAGORN responded
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/89bdf7fe-4de9-4de2-8906-11a1d4d62fc1)

CI UI

https://ui.ci.transltr.io/main/results?l=Autism&i=MONDO:0005260&t=0&r=0&q=decae620-720a-437d-972a-1d9b762598da

https://arax.ncats.io/?r=decae620-720a-437d-972a-1d9b762598da

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/6afa296c-3d83-4ed4-a008-bcbe65305a15)

seems like several ARAs responded in CI
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/484362db-1d3f-4b85-8752-14556ab88fea)

**Comment by gprice1129** [comment]
This is due to an unexpected `null` value appearing in the results for one of the responses (ara-aragorn). @MarkDWilliams is it expected that from now on `null` can appear as the value under `fields.data`?

**Comment by gprice1129** [comment]
I added a fix on the UI side to account for this case. It is now working in CI. Going to close.

**Comment by sstemann** [comment]
do you think we can get this to test?  unfortunately i keep hitting this issue in Test

https://ui.test.transltr.io/main/results?l=Desanto-shinawi%20Syndrome&i=MONDO:0018760&t=0&r=0&q=3601756a-a128-43e2-817b-9602212b6214

https://ui.test.transltr.io/main/results?l=Stickler%20Syndrome&i=MONDO:0019354&t=0&r=0&q=ad241236-2a1e-46cd-95e0-f531c82b44a3

**Comment by gprice1129** [comment]
@sstemann this should have been included in the most recent deployment. Clicking on the links you provided works fine for me.
