### ISSUE TITLE
Can MolePro answer the question: what is the molecular structure, binding and activity (molecular target of) SRI-37330?

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#67]
The QotM identified a data/attribute gap related to chemical structure, binding, and activity. It was noted that Molecular Provider exposes data that may be leveraged to support use cases such as identifying the molecular target of SRI-37330. Creating a ticket here to promote a broader discussion and prioritization.

**Comment by sierra-moxon** [comment]
@sandrine-m @vdancik

**Comment by sandrine-m** [comment]
Hi @karafecho,
What data/attribute gap did you identify with SRI-37330? Do you expect to see information that you did not get back from Translator/MolePro? 
I could not do an ARAX query with this compound. MolePro has knowledge about the compound but no gene related to it. Are you referring to a service like a creative mode looking for targets of chemically similar compounds?

**Comment by karafecho** [comment]
Hi @sandrine-m . This issue originated during a QotM call. The QotM SME was looking for anything related to SRI-37330, as very little is known about this compound. As such, anything MolePro can provide would be welcome. Thanks!

**Comment by sandrine-m** [comment]
Hi @karafecho !
Here is [what](https://translator.broadinstitute.org/molecular_data_provider/compound/by_name/SRI-37330) what MolePro knows about the compound but has no connections to other entities. 
The compound is known from MolePro through our chemical entity synonym mapping (see issue #23 ).

**Comment by sandrine-m** [comment]
MolePro and others are aware of this type of issue (compound is fairly new/did not get a "standard" naming). The issue has been discussed at the last chemical info WG and we discussed a way to accomodate a broader range of chemical names. The current solution will involve a broader list of synonyms in case the compound cannot be searched (like MolePro service is providing). However, the user should be aware that the synonym list will not ensure a good quality mapping although providing more coverage of the chemical space. 
To note that for now when a compound name is not "standard" yet (like in this example), usually no association will be found (even from text mining KPs) as those names have not been mapped into publications. 
We are thinking of a more curated and larger version of the chemical synonyms but this is a longer term goal.

**Comment by sierra-moxon** [comment]
@sandrine-m - is this closeable?  It sounds like you have a partial solution in place at MolePro to add additional synonyms?

**Comment by sandrine-m** [comment]
@sierra-moxon yes, that is correct MolePro has additional chemical synonyms that you can get access to using MolePro API. I was unsure that the question was about the result itself or the process to obtain it. 
I usually let the person who open the ticket to close it if they consider it solved. :) @karafecho would you consider this ticket solved?

**Comment by karafecho** [comment]
I would consider this issue partially resolved, as noted above, although it would be nice to confirm with the SME that the partial fix is acceptable, at least as a starting point. I'm guessing that would be a bit out of scope for this testing effort, however, so I'll close the ticket.
