### ISSUE TITLE
Evidence Modal - Predicate Boxes - auto-adjust width?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#671]
Is there a way for the predicate boxes to be wider when there are less hops in the modal?

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/604fd7de-2c6b-47a5-be30-5a59c462f1d0)

This is from UI TEST what chemical upregulates FZD4

https://ui.test.transltr.io/main/results?l=FZD4+%28Human%29&i=NCBIGene%3A8322&t=1&r=b324ea62&q=e003888a-7551-4d1f-9211-75656fffb6e2

**Comment by gaurav** [comment]
Not a showstopper, deferred to next release.

On UI action list for next release.

**Comment by dnsmith124** [comment]
This feature has been added and deployed to the test environment. Closing!
