### ISSUE TITLE
Text Filter Search - Sometimes misses text in edge, is it related to multiple edges?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#672]
In UI Test run the query "What drugs may treat Exudative Vitreoretinopathy 1"

https://ui.test.transltr.io/main/results?l=Exudative+Vitreoretinopathy+1&i=MONDO%3A0007589&t=0&r=172478e5&q=c4da4789-3291-4d8e-9292-c9ed66646bc3

Notice that Cefaclor > the second path has two predicates Causes Increased... and Causes Decreased...

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/036e128b-9397-4640-88aa-c2bb48e501a3)

Text Filter search for Causes. Cefaclor still shows up
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/5bd948c3-d1b5-47b2-ba8d-731fb5b0ee36)

Text Filter search for Activity. Cefaclor still shows up
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/906eb129-2615-4702-b538-4da6b5730e0a)

Text Filter search for Decreased - which is part of the second predicate in the previous screens and no Cefaclor
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/5b0a0b1e-8867-47e6-97c8-b4f614ddfedc)

Noticed that the Text Filter search for Decreased did return an edge with the predicate I was looking for when it was the only edge?

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/e1185a2c-051c-4fbb-b357-5a1ce809a87c)

**Comment by gaurav** [comment]
Not a showstopper, deferred to next release.

**Comment by sstemann** [comment]
this is really minor.  no need to resolve.
