### ISSUE TITLE
Main Group Molecular Entity as a Treatment

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#675]
I'm not sure if this goes on that ARS Block List or to the ARA (in this instance ARAGORN) to investigate but putting both

Steps
1. UI Test > What drugs may treat Myopathy, Lactic Acidosis, And Sideroblastic Anemia
2. https://ui.test.transltr.io/main/results?l=Myopathy%2C+Lactic+Acidosis%2C+And+Sideroblastic+Anemia&i=MONDO%3A0000863&t=0&r=169f7ff2&q=7b6c8f93-cede-40f4-a2a9-08df03603d46

ARAX GUI:  https://arax.ncats.io/beta/?r=7b6c8f93-cede-40f4-a2a9-08df03603d46

3.  Filter UI Results for ChEBI Role Classification "metabolite"
4. FIrst page has things like "metal atom" "polyatomic entity" "main group molecular entity"
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/759492fd-d505-4848-9c16-8b5b8991dfe6)

The paths are listing  "has input" "water" .

These seem very "generic" and seem to come primarily from ARAGORN

**Comment by sierra-moxon** [comment]
from TAQA: Chris and Abrar have a plan for pulling out overly generic nodes (intermediate node), but won't be released until next release.  

For now, @MarkDWilliams - can you block this in the ARS?

**Comment by sstemann** [comment]
looks resolved in test.
