### ISSUE TITLE
What drugs may treat Klinefelter Syndrome - top results includes Benzo(a)pyrene

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#677]
**Query:** What drugs may treat Klinefelter Syndrome? ([MONDO_0006823](http://purl.obolibrary.org/obo/MONDO_0006823))
**Results:** https://ui.transltr.io/main/results?l=Klinefelter%20Syndrome&i=MONDO:0006823&t=0&r=0b10660a&q=fbb2bb98-94ad-407e-90ec-9d48512e3b65

The second result returned is **[Benzo[a]pyrene](https://en.wikipedia.org/wiki/Benzo(a)pyrene)**, a polycyclic aromatic hydrocarbon that is a carcinogen as well as toxic to many organ systems etc. 

The paths look like this:
![Screen Shot 2024-01-05 at 4 48 19 PM](https://github.com/NCATSTranslator/Feedback/assets/1442197/cfc04e62-f027-4f2d-b5cf-8c51399846a3)

_Treats_ edge is coming from UnSecret Agent with no knowledge source / evidence.
The other paths are technically correct given the evidence, but maybe Benzo[a]pyrene should be on a block list? (Do we have such a list for compounds?) It doesn't look so good to have this obviously incorrect result as the second result.

**Comment by khanspers** [comment]
Update: the same query on **test** does NOT include Benzo(a)pyrene as a result, so maybe this ticket can be closed.

https://ui.test.transltr.io/main/results?l=Klinefelter%20Syndrome&i=MONDO:0006823&t=0&r=426f052c&q=6231f720-794b-45c6-b818-9c7b56420622

**Comment by sierra-moxon** [comment]
tested again at TAQA - can not reproduce on TEST with a new query, closing (noting "water" treats it, we're looking into that in another ticket).

**Comment by sharatisrani** [comment]
Benzo(a)pyene DOES need to belong on blocked list.  It is reported as a carcinogen, even ChatGPT catches that.

**Comment by sierra-moxon** [comment]
@khanspers - thanks for this ticket!! I moved the carcinogen issue to the block list repo here: https://github.com/NCATSTranslator/Blocklists/issues/22 if you want to follow.
