### ISSUE TITLE
not all results displayed

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#679]
Re-testing [what drugs may treat pityriasis rubra pilaris](https://ui.test.transltr.io/main/results?l=Pityriasis%20Rubra%20Pilaris&i=MONDO:0100017&t=0&r=ee8ef27c&q=cfcdc63b-f49f-4ebd-bda1-c2510bd353f1), the initial search returns just 26 results, all from ARAGORN. End state indicates 'results complete', with no indication there's need to reload for more (nor a way to do it).

Loaded the pk via ARAX interface and saw there was a lot more to be had, from other ARAs... so went back to Translator UI and reloaded the page. This resulted in 960 results being displayed, combining 5 ARAs.

**Comment by gprice1129** [comment]
This is due to a bad assumption on my part about the statuses provided by the ARS. Will provide a fix ASAP.

**Comment by gprice1129** [comment]
Upon further investigation we believe the root cause may be on the ARS side. The UI will provide a fix that should reduce the probability of this happening, but we cannot completely eliminate it. @MarkDWilliams is currently investigating.

**Comment by dnsmith124** [comment]
@MarkDWilliams any update here?

**Comment by sstemann** [comment]
@MarkDWilliams @dnsmith124 are we good with this?  i think we are

**Comment by sstemann** [comment]
completed
