### ISSUE TITLE
Can Ubergraph import the MRO ontology?

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#68]
The QotM identified a data gap related to HLA serotype-specific genes. MRO ontology was identified as a potential source to support HLA serotype-specific genes: https://droid.ontodev.com/MRO; https://github.com/IEDB/MRO. MeSH and UMLS were also identified as potential sources of HLA serotype-specific genes, e.g., https://uts.nlm.nih.gov/uts/umls/concept/C0009780.

**Comment by sierra-moxon** [comment]
Hi @gaurav @balhoff  - is it possible for Ubergraph to import (or maybe it does already), the MRO ontology?

**Comment by balhoff** [comment]
I think it should be fine. I created an issue: https://github.com/INCATools/ubergraph/issues/111

**Comment by sierra-moxon** [comment]
@balhoff already incorporated this into ubergraph! :). closing as completed!
