### ISSUE TITLE
how to figure out text mining riddles?

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#684]
It frequently happens that a paper is given as support for an assertion, but it's hard to find entities in the paper since they use aliases / alternate names. What's the best way to figure this out? Here I show an example using the Translator UI (which users are expected to use) and then the ARAX UI (which presumably users won't be digging into).

[2024/1/11 test of drugs that may upregulate NGLY1](https://ui.test.transltr.io/main/results?l=NGLY1+%28Human%29&i=NCBIGene%3A55768&t=1&r=6b271808&q=85359158-4838-483c-a204-ba536d2388ba), the top result being S-adenosylmethionine, claimed to cause increased activity or abundance of MYT1L gene and 7 proteins, which in turn are claimed to upregulate NGLY1.

Digging into the support for 'MYT1L upregulates NGLY1'.
<img width="1210" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/3977332/54cd06e7-7fb7-4696-a214-b19e79644c10">
Looking into the paper, I recognize Png1 as an alias of NGLY1, but I can't find MYT1L (by any other name) in there.

The assertion comes via BTE, ultimately from TMKP.
<img width="1189" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/3977332/cd5d68ca-bfa1-428e-877b-22196d22c8ed">
This seems to indicate that MYT1L is mentioned in the sentence "Png1 preferentially deglycosylates misfolded proteins in vitro ([Hirsch et al., 2004b](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2063551/#bib14); [Joshi et al., 2005](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2063551/#bib16)) and in cell extracts upon the overexpression of Png1 or glycoproteins ([Hirsch et al., 2003](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2063551/#bib12))." I just don't see how. Is there any way to tell?

**Comment by khanspers** [comment]
Another similar riddle in https://github.com/NCATSTranslator/Feedback/issues/686 where the referenced paper does not mention the relevant node.

**Comment by sierra-moxon** [comment]
Hi @bill-baumgartner - is there some meta data here that we should be looking for to justify the TMKP answer?  :) thanks in advance.

**Comment by bill-baumgartner** [comment]
In this specific case, Png1 is associated with the Protein Ontology records for both [NGLY1](https://www.ebi.ac.uk/ols4/ontologies/pr/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPR_000011196) and [MYT1L](https://www.ebi.ac.uk/ols4/ontologies/pr/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPR_000010893), and both are subsequently used to form an assertion -- clearly a disambiguation error on the part of TMKP.

In regards to the question about solving these kinds of riddles, yes, there is metadata to help the user understand which parts of the text were tagged as the subject and object, however the UI does not yet make use of this data. You can see it in the screenshot above. The `biolink:subject_location_in_text` and `biolink:object_location_in_text` attributes store character offsets into the sentence that supports the assertion. These offsets could be used to highlight the different parts of the sentence that are part of the assertion. If you use the ARAX interface, you can click on the `value_url` field for a given assertion, and it will open a browser that [shows the sentence with highlighted entities](https://tmui.text-mining-kp.org/evidence/862bb13bf75e3d7590138411d280fce2ad547b00ab85222b3bc355d289680c6d).

**Comment by gglusman** [comment]
@bill-baumgartner That interface showing the details on the evidence is awesome. Thanks!!
