### ISSUE TITLE
no response after a long wait

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#688]
2024/1/21 [What chemicals may upregulate ERS1 (Human)](https://ui.test.transltr.io/main/results?l=ESR1%20(Human)&i=NCBIGene:2099&t=1&r=0&q=44db0dc9-a379-47e8-9fc1-cd00f14dd7f1) ... still spinning after 25 minutes.
Reloading the page doesn't yield any change (still spinning).

**Comment by sierra-moxon** [comment]
I had the same issue with MVP1 query, went back to the page after a couple of hours, and noticed I had been logged out.

**Comment by gglusman** [comment]
Interesting! I had checked later yesterday and it was still spinning. I checked again now and got results... Every single time, it showed me as logged in, so I don't know how to interpret.

**Comment by sierra-moxon** [comment]
@gprice1129 - impossible ticket to debug I'm sure.  Since this is the second instance of long waits that we've experienced during testing, I thought I'd at least tag you on it.  I went through slack to find uptime robot channels to see if I could see any downtime of components that might cause this -- I couldn't.

**Comment by sierra-moxon** [comment]
from TAQA:
timeouts on UI backend/frontend and ARS level. 
if none of those got triggered, then there was probably an error that the front end got, but broke the timeouts.  
results are likely complete, but spinner icon is still going.

**Comment by gprice1129** [comment]
@sierra-moxon @gglusman occasionally the UI can experience a seemingly random unspecified Network Error that we do not handle very well right now. In has been on our radar for a while and I'm guessing this is what caused the issue.

**Comment by sstemann** [comment]
its more sloth than cheetah but incremental results loaded fairly quickly.  the final results was about 8 minutes out.

i will say this these 50+ path resutls seems overwhelming

https://ui.test.transltr.io/main/results?l=ESR1%20(Human)&i=NCBIGene:2099&t=1&r=0&q=c13fe32a-c97f-4e18-bece-02b6bb28ae0b

<img width="843" alt="image" src="https://github.com/user-attachments/assets/bdde162c-8580-4f67-8df7-f04fd4c36ddb">

but probably unrelated to this actual ticket, which i'm going to close.
