### ISSUE TITLE
predicates not precise [drug causes gene?]

### ISSUE THREAD

**Issue by gloriachin** [NCATSTranslator/Feedback#689]
We have observed a predicate "causes" between a compound and a gene, which is not understandable. 
Example KG came back are as below:

'PUBCHEM.COMPOUND:4763_NCBIGene:675': {'predicate': ['biolink:causes',
   'biolink:affects'],
  'subject': 'PUBCHEM.COMPOUND:4763',
  'object': 'NCBIGene:675',
  'primary_knowledge_source': ['infores:ctd', 'infores:ctd'],
  'aggregator_knowledge_source': ['infores:automat-cam-kp',
   'infores:automat-cam-kp'],
  'evidence': ['PUBCHEM.COMPOUND:4763_biolink:causes_NCBIGene:675_infores:automat-cam-kp_infores:automat-cam-kp',
   'PUBCHEM.COMPOUND:4763_biolink:affects_NCBIGene:675_infores:ctd_infores:automat-cam-kp']},

Another example is: 
![image](https://github.com/NCATSTranslator/Feedback/assets/2994757/54a20849-6c61-4097-b8bd-885832902b4e)

This result came from the following API. 
https://automat.ci.transltr.io/cam-kp/1.4/query

Can @YaphetKG look into it as you are listed as the owner of automat cam-kp in the smart API system. We can consider remove  "biolink:causes" between the compound and the gene?

Thank you!

**Comment by balhoff** [comment]
@gloriachin we had a mistaken relation mapping from RO to Biolink, which I have corrected. We output 'affects' for this relation, but inadvertently also a 'causes' via an inverse property. It should be cleaned up in our next release.
