### ISSUE TITLE
Which KP can bring in variant->disease relations?

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#69]
The QotM identified genetic variants as a data/attribute gap. Specifically, Translator has many sources of knowledge on genes, but few (if any) on variants. For example, Translator knowledge sources cannot identify nuances such as “loss of function” or “gain in function”. It was noted that MolePro and TextMiner may be able to provide this information. Creating a ticket her to promote broader discussion and prioritization.

**Comment by sierra-moxon** [comment]
@bill-baumgartner and I worked on a change in the qualifier model to help TMKP support 'loss of function' and 'gain of function' qualifiers for their data. 

A broader discussion of genes/variants should be added to the data modeling agenda/TODO list as we know that other teams might want to help design this part of the model (Sergio Baranzini's team, etc).

**Comment by marcdubybroad** [comment]
The genetics KP has a data source which calculates gene/disease p-value genetic associations based on LoF variants in the genes. We were planning on annotating those edges with qualifiers, but need to touch base with @sierra-moxon on the correct way to do that.

**Comment by sierra-moxon** [comment]
from discussions with various teams and a bit of a deep dive into variant data and modeling it in Biolink, we do not think variant->disease is a priority for Translator (at the moment), however, Monarch (@kschaper) is planning on ingesting allele/variant to disease data from model organisms and some modeling effort will happen in Biolink as a result.
