### ISSUE TITLE
missing linkouts from predicates

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#690]
I realize some of this may be temporary with the new (and fun and cool) versions of the UI display of results.

When asking for chemicals that may upregulate CARD14 [(test, 2024/01/19)](https://ui.test.transltr.io/main/results?l=CARD14%20(Human)&i=NCBIGene:79092&t=1&r=0&q=4af917d7-06f2-406a-9212-a626e4202e79), I see paths like this:
![image](https://github.com/NCATSTranslator/Feedback/assets/3977332/fb665f6b-95e8-479a-bb7a-173caba10520)
This makes me wonder what it means for a chemical to 'cause' a gene. (edited to add: see #689)

A similar search via [UI instance (2024/01/26)](https://ui.transltr.io/main/results?l=CARD14+%28Human%29&i=NCBIGene%3A79092&t=1&r=fbbaa8be&q=2d2da308-30a7-4935-a17b-94c20afe17d7) shows:
![image](https://github.com/NCATSTranslator/Feedback/assets/3977332/e8eb0f7a-9ab2-4d03-bc2c-72448f0d2f2a)
...so I'm guessing that the current test version is inadvertently truncating the predicate to just 'causes'.

That said, **neither version allows me to get more info on what the predicate actually means**. Clicking on the predicate opens the evidence modal, which doesn't explain predicate semantics.
Suggestion: Perhaps a linkout to biolink model might help, or including the definition in the mouseover text.

**Comment by gaurav** [comment]
The first part of that (compound --(causes)--> gene) is definitely coming from CAM-KP, and is probably the same bug as https://github.com/NCATSTranslator/Feedback/issues/689.

**Comment by gprice1129** [comment]
@gglusman a linkout is a good idea in some cases. Qualifiers makes this a much more difficult problem in terms of user clarity. For example, the predicate "causes decreased activity or abundance of" is generated by the UI by interpreting the predicate and qualifiers associated with the edge. We could link out to all the definitions of predicates and qualifiers and hope the user "gets it" but it may end up confusing them even more.

We are definitely open to suggestions or ideas here. It is something we are thinking about and trying to find a good solution to.

**Comment by gprice1129** [comment]
@gglusman I looked into this issue and it appears that sometimes ARAs send us an edge with the predicate `causes` and no directional qualifiers. In those cases we just show what we have. I'm going to add @cbizon and @uhbrar to look at the predicate issues.

**Comment by cbizon** [comment]
I think that @gprice1129 and @gaurav are both right: the primary KS is CTD, but the aggregator is CAM-KP which is making these into funky causes edges (Soon to be corrected)

**Comment by gprice1129** [comment]
The UI team is planning to provide predicate linkouts for the Lobster release.

**Comment by sierra-moxon** [comment]
implemented a linkout - closing as complete! :)
