### ISSUE TITLE
Evidence Modal Missing RepoDB Edge

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#694]
UI Test > MVP1 > Migraine Disorder:

https://ui.test.transltr.io/main/results?l=Migraine%20Disorder&i=MONDO:0005277&t=0&r=0&q=4d935f1d-6f19-4536-aac2-3c45d38ee3e5

1. View Sumatriptan > Second Path (first ribbon) Evidence > Knowledge Sources
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/13dbce05-a25d-45c1-bf63-2c3bc57af901)

2. In the ARAX GUI > ARAX > Sumatriptan there is an edge for RepoDB
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/04e4d778-d6d5-458c-ba79-c23fb7f2d5de)

3. It's not in the Evidence Modal, it does have an entry in GitHub, not sure why it didnt make it to the UI https://github.com/NCATSTranslator/Translator-All/wiki/repoDB

**Comment by dnsmith124** [comment]
@gprice1129 I don't see that primary knowledge source in the response from the BE, can you look into this?

**Comment by gprice1129** [comment]
@sstemann I see https://github.com/NCATSTranslator/Translator-All/wiki/repoDB in the list under `Drug Repositioning Database` in the screenshot you provided. I also missed it the first time I looked but it seems that everything is good.

**Comment by sstemann** [comment]
confirmed in Prod
