### ISSUE TITLE
Node Norm Label for Thiamine

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#695]
In UI Test, I ran MVP1 for [Myopathy, Lactic Acidosis, And Sideroblastic Anemia](https://ui.test.transltr.io/main/results?l=Myopathy,%20Lactic%20Acidosis,%20And%20Sideroblastic%20Anemia&i=MONDO:0000863&t=0&r=0&q=15b85852-f5f5-4fac-8561-802519c105d9)

Filtered on Chebi Role > Metabolite - and noticed this substance:3-(4-amino-2-methyl-pyrimidin-5-ylmethyl)-5-(2-hydroxy-ethyl)-4-methyl-thiazol-3-ium

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/e2dc3152-0c93-418d-a899-562ac27b7988)

Click on the Node of the substance and you end up here:  https://pubchem.ncbi.nlm.nih.gov/compound/1130
- which looks like it should be called Thiamine

I plugged PUBCHEM.COMPOUND:1130 into [Node Norm](https://nodenormalization-sri.renci.org/docs#/default/get_normalized_node_handler_get_normalized_nodes_get) - maybe I have an out of date node norm bookmarked - and it got the crazy label for Pubchem which I dont think is what Pubchem is using, the other identifier labels use some form of Thiamine

I dont know where this decision is made - so tagging UI Front End, ARS and Node Norm.

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/6c6713f7-18bd-4b32-bc91-bac5c028d7d7)

Adding a second example:  [MVP2, what may upregulate Mapk8ip3](https://ui.test.transltr.io/main/results?l=MAPK8IP3%20(Human)&i=NCBIGene:23162&t=1&r=0&q=267c40e1-4540-4662-af1d-7d7c850aa206)

Result S-adenosylmethionine - links to PubChem [Ademetionine](https://pubchem.ncbi.nlm.nih.gov/compound/34755).  
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/208591ad-b954-4639-87e3-34341201ed47)

Node Norm PubChem label is S-adenosylmethionine, other identifiers in node norm are using ADEMETIONINE

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/c88fbc82-ad33-4365-bcc7-3ca2ca04bd89)

**Comment by dnsmith124** [comment]
3-(4-Amino-2-methyl... is the label returned to the UI FE for that result, @gprice1129 do we call node norm now that we aren't doing merging, or is that the label we receive from the ARS?

**Comment by gprice1129** [comment]
The ARS does node normalization before its merging step so it should not matter which version of merging is being used.

**Comment by andrewsu** [comment]
I think the root of this one is a difference between PROD and TEST node norm:

* PROD: https://nodenorm.transltr.io/1.3/get_normalized_nodes?curie=PUBCHEM.COMPOUND:1130 --> "Thiamine"
* TEST: https://nodenorm.test.transltr.io/1.3/get_normalized_nodes?curie=PUBCHEM.COMPOUND:1130 --> "3-(4-Amino-2-methyl-pyrimidin-5-ylmethyl)-5-(2-hydroxy-ethyl)-4-methyl-thiazol-3-ium"

**Comment by dnsmith124** [comment]
Great find @andrewsu, @gaurav see the above comment.

**Comment by gaurav** [comment]
NodeNorm now returns "thiamine" as the label for CHEBI:18385 (previously PUBCHEM.COMPOUND:1130) and "ademetionine" as the label for CHEBI:15414 (previously PUBCHEM.COMPOUND:34755). This is true on:
* [NodeNorm Dev](https://nodenormalization-sri.renci.org/get_normalized_nodes?curie=PUBCHEM.COMPOUND%3A1130&curie=PUBCHEM.COMPOUND%3A34755&conflate=true&drug_chemical_conflate=false&description=false)
* [NodeNorm CI](https://nodenorm.ci.transltr.io/get_normalized_nodes?curie=PUBCHEM.COMPOUND%3A1130&curie=PUBCHEM.COMPOUND%3A34755&conflate=true&drug_chemical_conflate=false&description=false)
* [NodeNorm Test](https://nodenorm.test.transltr.io/get_normalized_nodes?curie=PUBCHEM.COMPOUND%3A1130&curie=PUBCHEM.COMPOUND%3A34755&conflate=true&drug_chemical_conflate=false&description=false)
* [NodeNorm Prod](https://nodenorm.transltr.io/get_normalized_nodes?curie=PUBCHEM.COMPOUND%3A1130&curie=PUBCHEM.COMPOUND%3A34755&conflate=true&drug_chemical_conflate=false&description=false)

I think that closes this ticket.
