### ISSUE TITLE
User Preferences - Number of Paths to Show and Collapse/Expand Request

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#697]
In UI Test - I have number of paths to show set to 5 (used to be all, I updated > Saved > closed my browsers/cleared my cache), logged back in, verified my preferences are set as below:

https://ui.test.transltr.io/main/results?l=Myopathy,%20Lactic%20Acidosis,%20And%20Sideroblastic%20Anemia&i=MONDO:0000863&t=0&r=0&q=15b85852-f5f5-4fac-8561-802519c105d9 > Oxygen > 27 paths

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/990f93e3-d352-4a3c-bca5-005d98e7eeda)

But all paths are always expanded, this is particularly problematic when there are multiple sets of inferred paths

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/3a71da5c-b5fc-4dc5-b19b-3f05d6ceac3e)
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/66121876-7d37-4468-a6e4-9cbdd422124d)

I would also like to request the ability to expand collapse on an inferred path when there are multiple inferred paths in the result.

**Comment by sstemann** [comment]
@dnsmith124 the preferred number of paths still doesn't seem to affect my display.  I have my preferences set to 5, and i'm seeing at like 8 at once

**Comment by sstemann** [comment]
do you know if this is targeted up an upcoming release? it looks like sometimes we have 50+ support paths and its just overwhelming

<img width="843" alt="image" src="https://github.com/user-attachments/assets/49eb6a31-d433-4935-9bfd-d1cbc9758ea9">

https://ui.test.transltr.io/main/results?l=ESR1%20(Human)&i=NCBIGene:2099&t=1&r=0&q=c13fe32a-c97f-4e18-bece-02b6bb28ae0b

**Comment by dnsmith124** [comment]
@sstemann absolutely, this is something I will be resolving as part of the facelift we're currently working on.

**Comment by dnsmith124** [comment]
This user preference is actually being removed in the part 2 of the UI facelift, will provide an update here when it's been changed.

**Comment by sstemann** [comment]
Looks like the # of paths user preference was removed altogether

![image](https://github.com/user-attachments/assets/41395e02-2636-4d22-8316-fd2b42d7121e)

there are now pages of paths
![image](https://github.com/user-attachments/assets/0ad62847-dbd2-43e2-8660-300c1fd14068)

**Comment by dnsmith124** [comment]
@sstemann that's correct, the new path pagination feature adds pages at each level of paths, and any support paths present within support paths start collapsed for better readability.  

We can look into adding the # of paths preference back in the future (I think ideally with one for top level and one for support paths, since their use cases are a bit different), but for now I think we're good to close, as the path pagination is now in TEST.
