### ISSUE TITLE
Can't select HER2 from UI (CI, Test, prod) 

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#698]
HER2 [NCBIGene:855338](https://www.ncbi.nlm.nih.gov/gene/855338) (human) isn't in the selection box for MVP2

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/3007e4cb-3d83-439e-af0c-ccccebe0ff92)

Seems like it should be?
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/819a1975-c715-4de9-a286-daad845d8817)

**Comment by gprice1129** [comment]
One possibility is that mygene.info does not have information regarding the species for this gene. I tried to get the data on NCBIGene:855338 on mygene.info specifically for humans and it returned nothing. Can you please verify @newgene?

**Comment by andrewsu** [comment]
[NCBIGene:855338](https://www.ncbi.nlm.nih.gov/gene/855338) corresponds to a yeast gene.  If you're talking about the breast cancer tumor marker, then you're probably looking for ERBB2 [NCBIGene:2064](https://www.ncbi.nlm.nih.gov/gene/2064)...

**Comment by gprice1129** [comment]
The name resolver does find NCBIGene:2064 when searching for 'HER2' but it comes back with a rank of 676, a label of 'ERBB2' and does include 'HER2' in its list of synonyms. Currently we limit the response size to the first 100 entries which is why it does not show up.

**Comment by gprice1129** [comment]
@sstemann the gene you are actually looking for does show up in the autocomplete but under a label you don't expect (thank you @andrewsu for pointing this out to me!)

**Comment by sstemann** [comment]
thank you both!
