### ISSUE TITLE
Provide dose and concentration information if available when a drug is suggested as a treatment

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#70]
Several SMEs requested that dose and concentration information are returned in query results.

**Comment by sandrine-m** [comment]
MolePro is currently looking into this

**Comment by karafecho** [comment]
@sandrine-m : FWIW, I think the request for dose and concentration information is a bit out of scope for Translator, at least for now. I reported it here only because more than one SME requested that information. However, I would consider this a very low priority in the near term.

**Comment by gglusman** [comment]
Agreed. Would be nice to link out to such information if easy, but definitely not something Translator has to provide...

**Comment by sandrine-m** [comment]
agreed too. My idea is that dosage is in DrugBank and upon licensing agreements we might be able to make the ingest available if available.

**Comment by sierra-moxon** [comment]
@karafecho @sandrine-m - correct to set the milestone for this to "D: Fall - 2023"?

**Comment by karafecho** [comment]
I would definitely mark this issue as Fall 2023. It requires discussion. I personally do not think this is within scope of Translator, at least not within the foreseeable future. Plus, this feels at odds with the goals of the Drug Synonymizer.

**Comment by sierra-moxon** [comment]
closing for now as out of scope.
