### ISSUE TITLE
More than 10 ties in top decile - ARA resolutions issue?

### ISSUE THREAD

**Issue by sharatisrani** [NCATSTranslator/Feedback#701]
See pks:
add93fee-ee4e-4f41-8e24-83a8f8bbc65d (Lots of #16 in 979 results)
5bf126ed-ec36-499f-92f7-d454818a404a (Lots of #52 out of 667 results)

In both cases, it appears that ARAGORN and/or BTE are returning those tied results but not creating resolution (and btw the other ARAs are not returning those or any results).

**Comment by cbizon** [comment]
From the ARAGORN side, this is maybe an epiphenomenon of some poor answers that we are currently engaged in cleaning up. (see the linked issue above)
