### ISSUE TITLE
Improving, Unsecret did not return any MVP1 results

### ISSUE THREAD

**Issue by sharatisrani** [NCATSTranslator/Feedback#702]
In my series of tests yesterday, Improving was erroring out.  Unsecret was returning no results.

See, for instance, MVP1 pks
ba71677a-1e25-42b6-ab54-d548944afebf
28cd4748-ff37-4b39-9f1e-b76698171e02
74d45286-f834-4ee7-a74f-3b8bb6e9dce7
add93fee-ee4e-4f41-8e24-83a8f8bbc65d

MVP2 pk (here Unsecret was returning results, but not Improving - granted these are gene related Q's):
ae7061cd-a67d-45a6-a32e-812727c6f5ae

**Comment by sstemann** [comment]
it looks like the query JSON is close but not quite MVP1 and I believe many tools respond to the specific MVP1 structure - so the nodes should be disease/MONDO and chemicalentity.

using other node types - may be supported by some ARAs but is not required for support for inferred.  The inferred tag is in the qgraph is not generalized as of yet.

**Comment by brettasmi** [comment]
For imProving, @sstemann  is correct. When looking at the responses via ARAX, our response message is as follows:

`'Unsupported qnode object for "inferred" predicate "biolink:treats"'`

When the MVP queries were originally proposed, they were called "template queries," so we implemented the specified template that Sarah described.

---

WRT the MVP2 pk  ` ae7061cd-a67d-45a6-a32e-812727c6f5ae`, I see 300 results from imProving via ARAX:  

![Screenshot 2024-02-01 at 10 10 28](https://github.com/NCATSTranslator/Feedback/assets/8398927/3ba5dd4d-10b9-4981-acdd-241670f5997d)

Maybe you encountered a temporary issue with ARS retrieving the results?

**Comment by sierra-moxon** [comment]
@sharatisrani  - can we close this issue?
