### ISSUE TITLE
ARAX not returning MVP2 results

### ISSUE THREAD

**Issue by sharatisrani** [NCATSTranslator/Feedback#703]
In all my MVP2 tests yesterday, ARAX returned no results.  See for instance 

5bf126ed-ec36-499f-92f7-d454818a404a
ae7061cd-a67d-45a6-a32e-812727c6f5ae
c502d4e9-f671-47ed-9b6a-dd8813b5654b

**Comment by sharatisrani** [comment]
pls hold off on this till we can check how ARAX as an infores is checked by the scoring code.

**Comment by sierra-moxon** [comment]
from TAQA:
we think we can close this as completed - of course, please reopen if need be. 
thanks!
