### ISSUE TITLE
UMLS Metathesaurus (curated) and Semmed DB (textmined) - Return same Pubs, for same Edge

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#705]
In the Test UI > MVP1 > common cold

https://ui.test.transltr.io/main/results?l=Common%20Cold&i=MONDO:0005709&t=0&r=0&q=a49c78af-b108-490e-b48f-f7aa7a5e568c

Take a look at Desloratadine > inferred paths with one hop that has both text mined and curated icons

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/7e911226-6d69-4104-8073-11b6de01734f)

Notice that the Pubs all say Curated - UMLS Metathesaurus
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/3aba9eae-3f3b-49fa-b7f5-3a94c6d216f2)

But the KS for this hop has UMLS Metathesaurus and Semmeddb - which implies some pubs should be from Semmed Db - or what is the text mined icon doing there?

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/4e46efc1-0501-4e68-a84a-e68b8597c68d)

In the source - ARAX GUI > ARAX > Desloratadine > SG edge > Support Graph > Allergic Rhinitis > Common Cold > has two subclass_of edges

one edge has 6 pubs from UMLS, the other has the same 6 pubs from SemmedDB

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/37acd370-e006-4713-9f4a-eb1eb947c25e)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/7830b999-59ab-4f4a-9e91-4d1ffc6f0904)

Are the pubs both curated and text mined?

**Comment by dnsmith124** [comment]
The evidence modal removes any duplicate publication ids provided to it by the selected edge. It appears that since these 6 pubs are identical for both edges the duplicates are removed and the curated ones are processed first, so they remained. 

What is the ideal behavior here exactly? Should the duplicates be shown since the knowledge levels are different, or should we try to fit both of the sources into the sources column?

**Comment by sstemann** [comment]
i'd like to here how they should be tagged from a KL prespective?  @mbrush 

i'm not sure what should happen, the triple looks duplicative with duplicative publication evidence, i dont know what value it is by showing it twice, and as a user it makes me question Translator if two exact same triples have the same evidence but we're saying its derived two different ways.  Is Translator weighing the same pieces of evidence twice?

**Comment by sstemann** [comment]
i cant replicate this so yay!
