### ISSUE TITLE
Which KP(s) can provide "time course", "before or after a procedure" ?

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#71]
Several SMEs have requested that spatiotemporal information ( e.g., time course, acute vs chronic, before or after a procedure). The clinical KPs have or are developing approaches for capturing some of this information, and an approach for modeling space and time has been developed through the use of qualifiers, but space and time have not really been implemented in Translator.

**Comment by sierra-moxon** [comment]
@karafecho - can any of the clinical KPs provide this information?

**Comment by karafecho** [comment]
Theoretically, yes, but this is not a priority for Phase II. Closing after first adding the "long-term parking lot" label.
