### ISSUE TITLE
Biolink version in Info Radiator

### ISSUE THREAD

**Issue by sharatisrani** [NCATSTranslator/Feedback#711]
Are I.R. templates to standardize on Biolink 4.1.0?  "Treats" and "Ameliorates" are [not supported there](https://tree-viz-biolink.herokuapp.com/predicates), and we don't want to run all the tests with this gap.

**Comment by sierra-moxon** [comment]
Thanks for taking a look, @sharatisrani -  In Bioloink 4.1.0, "treats" is now a mixin predicate and mixins don't show up in that visualization, however, [this visualization](https://biolink.github.io/biolink-model/treats_dag.html) (zoom in helps, click on the nodes to see all the details about a specific predicate including the mixin predicates like treats and ameliorates condition) will show you a subset of the predicate hierarchy focused on the "treats" refactor. (the full hierarchy of non-mixin predicates [is here](https://biolink.github.io/biolink-model/predicates.html) -- note the tab link at the top of the page to "Treats With Mixins" which will take you back to the "treats" visualization linked above).

With regards to timing of being able to test this new hierarchy, I believe KPs are going to implement Biolink 4.1.0 in the February 2024 release, and ARAs will start implementing it in the March 2024 release.

At the moment, the tests are running on Biolink 3.x which does have the "treats" predicate as well, but with a much more broad meaning than the refactored, 4.1.0 version of biolink.

**Comment by sharatisrani** [comment]
Thanks for the timetable.
