### ISSUE TITLE
KL Source Link vs Pub Link

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#712]
I found myself clicking on TMKP repeatedly instead of the Publication Title and being frustrated I was taken to the TMKP wiki instead of the pub.  Since these are both hyperlinks, should they look the same?

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/a1493010-2312-4b38-87d2-8f64e46268bc)

**Comment by dnsmith124** [comment]
I definitely think underlining the title would be appropriate in this case to make it more obvious that the title is also a link. The challenge is that these three items serve different purposes, but there's some overlap in those purposes. The TMKP link is context for content in that cell along with a link and the title _is_ the content of a cell and also a link. So making them identical makes their importance less parsable at a glance, but I think unifying them as links with an underline makes sense and better matches the styling for links elsewhere on the site.

**Comment by sstemann** [comment]
<img width="727" alt="image" src="https://github.com/user-attachments/assets/95570f3d-4601-4e30-b455-7a57474d543b">
