### ISSUE TITLE
Some (MVP2?) Queries not in my search history

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#717]
I ran this query on the left 2/5 at 11:42 AM and today 2/5 3:05 PM its not in my search history.

https://ui.test.transltr.io/main/results?l=BRAF%20(Human)&i=NCBIGene:673&t=2&r=0&q=bf47b371-acf2-4cc0-9354-2cdf349b9a0d

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/b5c9ecc6-d658-4a05-9134-4518057f3348)

Other queries are in my search history as proof i have not cleared my cache.

**Comment by dnsmith124** [comment]
Attempting to recreate this on test.

**Comment by sierra-moxon** [comment]
@dnsmith124 - is this re-creatable on TEST?

**Comment by dnsmith124** [comment]
@sierra-moxon I tried this in CI, TEST, and PROD and have been unable to recreate the issue.

**Comment by sierra-moxon** [comment]
closing for now; will reopen if we see it again, thanks! :)
