### ISSUE TITLE
full gene name not being matched, when partial name works

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#719]
What chemicals may upregulate [glyoxalase]? (on test, but got the same result with the non-test version)
![image](https://github.com/NCATSTranslator/Feedback/assets/3977332/51c54aea-9a6f-452f-b909-13b8844380e9)
![image](https://github.com/NCATSTranslator/Feedback/assets/3977332/db2e2d85-c18c-4578-8c49-d81e492c479e)
![image](https://github.com/NCATSTranslator/Feedback/assets/3977332/f3773d68-1be9-4f9a-8f86-ff5d97515b9d)
...clicking on the linkout from GLO1:
![image](https://github.com/NCATSTranslator/Feedback/assets/3977332/e90020b3-690e-4596-9b38-d3bf74f1a11f)

**Comment by sierra-moxon** [comment]
Hi @gaurav, @dnsmith124 - looks like we have another "too many results" issue with autocomplete for gene names, maybe?  Or maybe we aren't indexing some part of the name that the user expects to find the gene?  Not sure.  Any chance you could shed some light on the underlying cause here?

**Comment by dnsmith124** [comment]
@sierra-moxon after looking into this the issue appears to be that the name resolver is not returning any genes of a valid species (Human, Mouse, Rat or Zebrafish) among the first 100 results for the search term "glyoxalase". 

Since the UI filters out any results that don't apply to one of these taxonomies, no results are shown in the autocomplete.

**Comment by sierra-moxon** [comment]
@dnsmith124 @Genomewide - this query in name resolver, returns the human gene, GLO1 second in the result list:
```https://name-resolution-sri.renci.org/lookup?string=glyoxalase&autocomplete=true&offset=0&limit=10&biolink_type=biolink%3AGene
```

- without the type filter set to `biolink:Gene`, `glyoxalase` in many different protein names swamps the top 100.
- without the type filter set to `biolink:Gene`, `glyoxal` returns a lot of GO terms, `glyoxa` returns HP terms.  

I think this is an issue we should prioritize fixing because it seems like it would confuse users and hopefully it can be fixed with a filter on the name resolver call.  What are the downsides to filtering on `biolink:Gene` in this MVP?

**Comment by dnsmith124** [comment]
@sierra-moxon the UI already limits by biolink:Gene in its call to the name resolver. When we call out to mygene for the taxonomy ID in order to determine the species for each gene, none of the instances of GLO1 return with a taxonomy ID matching the one for human (9606).

**Comment by newgene** [comment]
@dnsmith124 can you provide the actual call (or the call template if not easy to obtain the actual call URL) passed to mygene.info API, so that we can have a look on our side?

**Comment by Genomewide** [comment]
@sierra-moxon I don't understand this comment:
`In Biolink, we constrain the "regulate" predicate to genetically evolved mechanisms of regulation. I know this is tangential to this ticket, but the idea that we are advertising chemical-upregulate-gene answer triples/paths gives me pause. `
Can you explain?

**Comment by dnsmith124** [comment]
@newgene we make a POST request to the following: `https://mygene.info/v3/gene`. Here's the payload: 

`{
    "ids": [
        "984676",
        "1024857",
        "2682118",
        "3878628",
        "4566100",
        "4567403",
        "5073200",
        "5847644",
        "7199032",
        "7199111",
        "8243662",
        "8509129",
        "10028299",
        "10030868",
        "10032521",
        "11638342",
        "11848085",
        "13451013",
        "17279534",
        "18757478",
        "19261219",
        "19460586",
        "20347230",
        "23223116",
        "24106847",
        "24407529",
        "24416516",
        "25011173",
        "25012500",
        "28841408",
        "28862219",
        "28872925",
        "29846562",
        "31019383",
        "34559093",
        "34562650",
        "34562655",
        "36285119",
        "36285120",
        "39590819",
        "39607790",
        "41984265",
        "43161958",
        "48013433",
        "48014315",
        "51135935",
        "55978370",
        "55982002",
        "57107883",
        "100710103",
        "101073381",
        "101172148",
        "101475986",
        "102205874",
        "102233240",
        "102296931",
        "102367254",
        "102688221",
        "103022823",
        "103136013",
        "103379235",
        "103462198",
        "104919745",
        "104951454",
        "105909451",
        "106524265",
        "106904090",
        "106962072",
        "107099139",
        "107396758",
        "108241588",
        "108263425",
        "109513924",
        "109937030",
        "110000649",
        "110959634",
        "111563336",
        "111834103",
        "112161068",
        "112302242",
        "112308816",
        "113026340",
        "113122398",
        "113174024",
        "113541949",
        "113575544",
        "113655241",
        "114143724",
        "114648383",
        "114784708",
        "115028563",
        "115357097",
        "115417031",
        "115558870",
        "115775417",
        "116057042",
        "116325578",
        "116384092",
        "116694196",
        "116719131"
    ],
    "fields": [
        "symbol",
        "taxid"
    ]
}`

**Comment by newgene** [comment]
@dnsmith124 human gene GLO1 has the NCBI Gene ID `2739`:

https://mygene.info/v3/query?q=symbol:GLO1&species=human

I don't see it in the `"ids"` list above passed to mygene.

When searching `glyoxalase` from mygene, the human gene does return as the top hit:

https://mygene.info/v3/query?q=glyoxalase&species=human

**Comment by dnsmith124** [comment]
@newgene thank you for looking into this! 

@sierra-moxon based on Chunlei's efforts I think we can safely say that the name resolver does not return the human GLO1 gene in the first 100 results for the search term `glyoxalase `

**Comment by sierra-moxon** [comment]
talked to @gaurav - it looks like a NameRes with the option to restrict taxon is coming very soon.  This would allow us to restrict the return to Human, Mouse, Rat, and Zebrafish and weed out the overwhelming number of results from other species that swamp the first 100 results.

**Comment by sierra-moxon** [comment]
@Genomewide - https://biolink.github.io/biolink-model/regulates/ 
_"Description: A more specific form of affects, that implies the effect results from a biologically evolved control mechanism. Gene-affects-gene relationships will (almost) always involve regulation. Exogenous/environmental chemical-affects-gene relationships are not cases of regulation in this definition. Instead these would be captured using the 'affects' predicate, or possibly one of the 'interacts with' predicates depending on the nature of the interaction.
"_

Is this a mismatch in semantics between how biolink defines "regulates" and how we ask users to enter their queries in MVP2,3.  e.g. we're asking "What chemicals may upregulate xyz"?

**Comment by Genomewide** [comment]
@sierra-moxon I think you are right.  It does look like there is a mismatch here.  The drug exogenous chemical part especially.

**Comment by mikebada** [comment]
@sierra-moxon Agreed, for a chemical X regulating a gene/gene product Y, I believe the pattern should be:
subject: X
predicate: affects
object: Y
object_aspect_qualifier: activity or abundance

**Comment by gaurav** [comment]
> talked to @gaurav - it looks like a NameRes with the option to restrict taxon is coming very soon. This would allow us to restrict the return to Human, Mouse, Rat, and Zebrafish and weed out the overwhelming number of results from other species that swamp the first 100 results.

This is now deployed in CI, Test and Prod -- but even without that, Gwenlyn's originally reported issue has now been fixed in CI and Test (I assume this is because of something @dnsmith124 has done!). I'm going to close this, but I can't evaluate if @sierra-moxon, @Genomewide and @mikebada's issues have been addressed -- if not, could you please open another ticket to discuss that? Also please reopen this ticket if there's something I've missed.
