### ISSUE TITLE
Round result scores to 2, not 3 in current CoLab code (and Appraiser?)

### ISSUE THREAD

**Issue by sharatisrani** [NCATSTranslator/Feedback#722]
From CoLab code:

      for key in row.keys():
          if key.endswith('_score'):
              # row[key] = round(row[key], 3)
              # ALLOW FOR N/A TO BE THERE BUT ROUND IF NUMBER
              if isinstance(row[key], (int, float)):
                  row[key] = round(row[key], 3)

**Comment by maximusunc** [comment]
Hey Sharat, can you provide a little more detail please? I'm not sure I understand what you want in this ticket.

**Comment by sstemann** [comment]
@maximusunc Mark is working on this.  nothing needed from you for now.

**Comment by MarkDWilliams** [comment]
To clarify, I don't think that Appraiser would have any bearing on the rounding issue.  At the source, neither ARS nor Appraiser does any rounding (or if they do, it's out to 5+ decimal places).  Rounding in the way of meaningful truncation, really only happens in the colab and the UI.  I have changed the one in the colab from 3 to 2.  On a related note @sharatisrani do you have permissions to make changes on the colab yourself?  If not, I'm happy to add you, and these types of changes I'm fine with you putting through yourself.  I don't imagine other users would have an issue with having the rounding match the UI

**Comment by sstemann** [comment]
i think this is completed
