### ISSUE TITLE
ARAX Edge Support Graph Not Displayed in the UI

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#726]
I don't know where this issue is happening at but here are the steps:

1. In Test UI > What drugs may treat > multiple sclerosis:  https://arax.ncats.io/beta/?r=157f5fc2-1748-459f-b381-724d0c353ab9
2. View result for Teriflunomide - three "lookup paths"
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/53326675-fe56-423b-ac48-7d5f0658f644)

3. View this same result in the ARAX GUI: https://arax.ncats.io/beta/?r=157f5fc2-1748-459f-b381-724d0c353ab9

4. One treats edge is [sg] which has an edge support graph - this graph has a predicate "predisposes" which i think might be updated to "predisposes_to_condition" in Biolink Model - so maybe this is an obsolete issue? #330 
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/df245b19-3cd3-4ddf-9b0c-d084a5087dc1)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/ffd5c43f-270e-4a34-91bf-5a032294478c)

**Comment by gprice1129** [comment]
@sstemann @MarkDWilliams I looked into this and it seems to be a result of the ARS merging because the aux graph `aux_graph_420_creative_DTD_option_group_0` cannot be found in the `auxiliary_graphs` field. Looking at the subgraph it seems there are several very general nodes which may be blocked. According to the ARS logic this would remove the entire aux graph.

**Comment by MarkDWilliams** [comment]
Yes, the current behavior is to remove the whole support graph if it contains blocked nodes to avoid sending possibly disjointed graphs after removing specific nodes.  However, I can change this behavior to selectively remove nodes and edges and leave the rest of the graph.

**Comment by gprice1129** [comment]
@MarkDWilliams we should coordinate to run a test for the behavior you described. Please reach out when you have some time.

**Comment by sstemann** [comment]
i can't retest this while #911 is happening
