### ISSUE TITLE
Ethanol treats Alcohol Abuse 

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#728]
are the "award-winning" badges on the paths that make up this 2-hop misleading when the resulting inference of "treats" is "ethanol treats alcohol abuse"? 

<img width="1217" alt="Screen Shot 2024-02-15 at 4 49 37 PM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/a40c06ac-6039-40dd-9cdf-81a335777896">

<img width="1579" alt="Screen Shot 2024-02-15 at 4 46 43 PM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/0486b624-2b59-429a-9ab2-835677c80670">

https://ui.test.transltr.io/main/results?l=Alcohol%20Abuse&i=MONDO:0002046&t=0&r=0&q=8d283c81-7da9-400c-8cf1-12954c1b16ab

**Comment by gprice1129** [comment]
@sierra-moxon possibly? All it means is that the edge is from a curated source.

From a human's perspective this relationship definitely seems dubious but it isn't obvious how to determine that programmatically. This definitely seems like a reasoning issue to me.

**Comment by sstemann** [comment]
sorry i was looking at alcohol hepatitist in CI dd654d1c-5ba4-4995-9c84-329d6f066108 and thought it was the same issue
