### ISSUE TITLE
Same term for HPO and MONDO

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#729]
In TEST UI type in Neutrop and notice there are two entries - one for disease and one for phenotype

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/733b8360-67fc-4224-88ef-dd50f6aa28d9)

**Comment by gaurav** [comment]
HP:0001875 "Neutropenia" is now normalized to MONDO:0001475 "neutropenia" in CI, Test and Prod, so it only appears once in autocomplete. Closing.
