### ISSUE TITLE
Which KP provides information relating ChemicalEntities to BiologicalProcess?

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#73]
The QotM identified a data gap related to ChemicalEntity – BiologicalProcess relationships. For example, a SME requested this information to identify mechanistic explanations for the observation that cannabidiol is generally safe except in patients taking valproic acid.

**Comment by sierra-moxon** [comment]
@sandrine-m @vdancik - is this something MolePro already provides?  Is it possible that the data sources that provide this general kind of information are missing information for cannabidiol?

**Comment by sierra-moxon** [comment]
From TAQA:
Vlado:
we have some chemical->pathway (not the entire biological process)

**Comment by capasfield** [comment]
Vlado says YES. Vlado and Sandrine to update and then off to Kara.

**Comment by sierra-moxon** [comment]
Hi @karafecho  - can this be closed?  :)

**Comment by karafecho** [comment]
@sandrine-m : Perhaps you can post an example query?

**Comment by vdancik** [comment]
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n2": {
                    "ids":["PUBCHEM.COMPOUND:10032468"]
                },
                "n3": {
                    "categories": [
                        "biolink:BiologicalProcess"
                    ]
                }
            },
            "edges": {
                "e03": {
                    "subject": "n2",
                    "object": "n3",
                    "predicates": [
                        "biolink:related_to"
                    ]
                }
            }
        }
    }
}
```

**Comment by karafecho** [comment]
Thank you, Vlado. This issue can now be closed.
