### ISSUE TITLE
"Date Allergenic Extract" comes up based on sentences like "that have been reported to date are" and "only a few DPAGT1 inhibitor molecules have been identified to date"

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#732]
## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20240302173857659069.jpeg)

**Comment by sstemann** [comment]
based on the screenshots this looks like one for @bill-baumgartner

**Comment by sstemann** [comment]
resolved!
