### ISSUE TITLE
Support Graph includes a rare disease as being treated by 390+ Drugs

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#733]
If you run What may downregulate GNAS (human) in Test you should get these results:  https://ui.test.transltr.io/main/results?l=GNAS%20(Human)&i=NCBIGene:2778&t=2&r=0&q=ba0ffb85-71af-47c0-a4d5-c965cbbe9061

If you filter the above results by Node Type = Disease, there are 397 results with a disease in its inferred path

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/3628b923-3cb0-4738-a4bf-246cfbaeea20)

When you expand these results with the Disease Node - they appear to all be result [Result] _treats_ **Mccune-albright Syndrome** _caused by_ GNAS

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/dc62070f-2461-4be3-b06b-0f75d0773d5e)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/370dd4e9-cb7b-4801-a9cb-155c3ad85a45)

Maybe all of these results treat symptoms of MAS and so this is useful information.  So looking for feedback.  These seem to come from OpenPredict via ARAGORN

**Comment by CaseyTa** [comment]
OpenPredict was previously returning all drugs regardless of prediction score, so many drugs were being returned with low scores. We've changed OpenPredict's default behavior to only return results with score > 0.5, which yields 3 results for MAS. These changes are deployed in CI and should be in Test soon.

**Comment by CaseyTa** [comment]
Retested this in Test and no longer seeing the above behavior. 

https://ui.test.transltr.io/main/results?l=GNAS%20(Human)&i=NCBIGene:2778&t=2&r=0&q=0d5bf250-1182-4be7-a02f-010e908a1216
