### ISSUE TITLE
support graphs incorrectly labeled as lookups

### ISSUE THREAD

**Issue by cbizon** [NCATSTranslator/Feedback#738]
The question is "What chemicals may upregulate ADRB2 (human)" 

Run in CI.  PK = 780b3304-016b-41d9-b30a-25789e126bc2

Aragorn returns propranalol as a result (though this happens for more than one result).   

The UI shows several lookups for this answer:

<img width="1076" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/10744350/64cfd9ac-29b8-422f-8ffa-679a1a3241c1">

But none of the predicates seem to match the lookup:

<img width="1204" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/10744350/cf186fa3-03a9-4061-af68-02ab3ec1707b">

Looking at the same PK in arax makes it appear that the trapi is formatted correctly, with these 1-hops being included as support graphs, not directly bound to the qgraph edge.  i.e. they are part of inferred paths, not lookups.

So I think that this is a UI issue?

**Comment by gprice1129** [comment]
@cbizon I've verified this is an issue with the UI. I'll start looking into this right away. Thanks for pointing this out!

**Comment by gprice1129** [comment]
This should be fixed in CI now. @cbizon can you please re-test and close.

**Comment by cbizon** [comment]
Looks good!
