### ISSUE TITLE
Downloading the results of the Gammagard drug as the top prediction to treat inclusion body myositis results in a CSV file with a single cell populated with: ï»¿

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#739]
## Steps to reproduce:
Downloading the results of the Gammagard drug as the top prediction to treat inclusion body myositis results in a CSV file with a single cell populated with: ï»¿ 
af00f180-1916-4de2-adec-b49594fa90da

**Comment by dnsmith124** [comment]
We're actively tracking this issue, in the meantime the CSV download feature has been disabled

**Comment by sstemann** [comment]
OBE you can't download anymore
