### ISSUE TITLE
Non-drug therapies, including sources like iDisk

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#74]
Several SMEs have requested non-drug therapies when seeking treatments for a disease. The clinical KPs can provide a bit of data on non-drug therapies but not, e.g., dietary recommendations.

Related (closed) issue: [https://github.com/NCATSTranslator/Feedback/issues/32](https://github.com/NCATSTranslator/Feedback/issues/31).

**Comment by gglusman** [comment]
We're introducing such content with our Clinical Trials KG.

**Comment by andrewsu** [comment]
Service Provider created an API for [iDisk](https://academic.oup.com/jamia/article-abstract/27/4/539/5740032?redirectedFrom=fulltext) at https://biothings.ncats.io/idisk, which can be queried through BTE as described in https://github.com/NCATSTranslator/Feedback/issues/59#issuecomment-1353447890.

Service Provider also created an API for [SuppKG](https://arxiv.org/abs/2106.12741) at https://biothings.ncats.io/suppkg.  Querying through BTE is not yet available pending SmartAPI annotation (tracked in https://github.com/biothings/pending.api/issues/55).

**Comment by sierra-moxon** [comment]
From TAQA:
From @gglusman: some in clinical trials KG, blocker at the moment is blocking the verbal/text description to any kind of CURI -- still looking into it.

**Comment by GitHubbit** [comment]
We will include the semantic types from UMLS when we release the next version of Clinical Trials KP. The semantic types for Interventions will describe non-drug therapies as well. A list of semantic groups from UMLS can be found here: [https://lhncbc.nlm.nih.gov/semanticnetwork/download/SemGroups.txt](url)

**Comment by sierra-moxon** [comment]
Hi @GitHubbit :) - do you have an estimate of when the next version of Clinical Trials KP will be released?

**Comment by GitHubbit** [comment]
Hi Sierra! I am forecasting that it will be after the February relay, but it is next on my to-do list!
-Kamileh :)

**Comment by sierra-moxon** [comment]
@gglusman - will this ticket help you or is it good to close it and expect this kind of content from the clinical KP to be provided (and then we can open more tickets if something more needs to be added)?
