### ISSUE TITLE
One Knowledge Source in EPC Modal but two Icons

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#741]
It looks like this edge is both text mined and curated but I only see one knowledge source:

<img width="749" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/b3f7480a-0b2d-4b78-a73a-b90d7245cad5">

<img width="737" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/a30870ac-baa7-464a-8886-94a24121d07a">

Happens twice in this result, different knowledge sources.  I feel like this makes you think the badges don't mean anything

https://ui.test.transltr.io/main/results?l=Apidra&i=PUBCHEM.COMPOUND:16136701&t=3&r=0&q=73bce986-35eb-4bb3-92f3-e2fc28e7464e

**Comment by dnsmith124** [comment]
This does appear to be a bug in the UI, looking into it now.

**Comment by dnsmith124** [comment]
This issue appears to be resolved in Test, closing.
