### ISSUE TITLE
Same path and EPC shows up in both Lookup and Inferred

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#742]
<img width="926" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/2f343297-b211-4ff6-9eed-4a35ad2c50ae">

<img width="728" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/4e2bc047-7e3a-4f97-95bb-662d87349ba5">

<img width="753" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/0d4453bc-36af-4811-b93b-851814705412">

It seems really strange to show it in both places.  it could be the same as #706 but i'm reporting it again 

https://ui.test.transltr.io/main/results?l=Apidra&i=PUBCHEM.COMPOUND:16136701&t=3&r=0&q=73bce986-35eb-4bb3-92f3-e2fc28e7464e

**Comment by dnsmith124** [comment]
@sstemann After looking at the raw results this appears to be the same as #706, not a UI bug 👍

**Comment by sstemann** [comment]
related to #706

**Comment by sstemann** [comment]
this looks resolved for ARAGORN.  This symptom still occurs if ARAs handle the same evidence differently and those get merged.
