### ISSUE TITLE
Hello Team, 

I am a postdoctoral fellow, working with Dr. Porter at NICHD/NIH. I am using the NCATS Translator for one of my projects where I have to compare results between two different analyses. However, I am struggling with downloading all the results at once. Is there a way, to download the results in Excel or any other tabular format?
Thank you
Khushboo 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#745]

**Comment by sstemann** [comment]
It looks like the UI URL did not come through, but the results PK mean it was this query:  https://arax.ncats.io/?r=b312f514-1939-40bc-bbc2-03bd891854d8

Can we get these results into a tabular format or is JSON the only option?

**Comment by edeutsch** [comment]
If you click on the [Summary] on the side, you will see the results in a tabular summary, but it is just the scores and drugs, not any of the more complex information below that:

![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/f2b84e31-9f6e-4ad4-96b1-bcb5cdb05786)

**Comment by gglusman** [comment]
I'm guessing the question is about downloading from Translator's official UI - not just the format.

**Comment by gprice1129** [comment]
Should we close this ticket?

**Comment by sstemann** [comment]
yes, @MarkDWilliams has been supporting this user directly.
