### ISSUE TITLE
Ranking MVP2: the notion of path length matters

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#747]

**Comment by sandrine-muller-research** [comment]
In this query the top answer is an inferred query of "affected_by" that invlves a chain going through increasing the expression of 2 genes. Even if there is a lot of evidence of that chaining, is less relevant to me than the look up with ATP (path length = 1).

**Comment by sstemann** [comment]
i ran this on Test (which is now Fugu), but you cannot use Potassium Ion, only Potassium.  All results are one-hop.  

https://ui.test.transltr.io/main/results?l=Potassium&i=CHEBI:26216&t=3&r=0&q=3cc31376-1333-46a0-9ab0-6499440ebf28
<img width="846" alt="image" src="https://github.com/user-attachments/assets/93487e70-a6e7-4e5f-96b1-699af9957b7d">

@sandrine-muller-research not sure if you have another case of this.  i think there are a lot of questions regarding rank, score, evidence that are wrapped up with O&O.  But without an actual example on this one there isn't much to pass off right now

**Comment by sandrine-muller-research** [comment]
Let's close this and I'll open another ticket if I find abother case (I have logged a few ranking issues already so perhaps we have already)
