### ISSUE TITLE
ATP1A2 does not have increased transport affected by

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#749]
## Steps to reproduce:
search for ATP1A2 result

**Comment by sandrine-muller-research** [comment]
In this query "what genes may be upregulated by..." we get :
![image](https://github.com/NCATSTranslator/Feedback/assets/22616936/f1159e0b-a96f-4baf-92e2-d4e24fd1a9bb)
with following evidence from ARAGORN/HMDB:
![image](https://github.com/NCATSTranslator/Feedback/assets/22616936/6800f549-1d71-4805-ac10-0689b5926a79)

ATP1A2 is a subunit of the K+ pump so the statement that ARAGORN returns "ATP1A2 has increased transport affected by K+" is incorrect.

**Comment by sandrine-muller-research** [comment]
I see this issue many times in the answer with other genes.

**Comment by sstemann** [comment]
@cbizon @uhbrar

**Comment by cbizon** [comment]
@EvanDietzMorris @eKathleenCarter The transport edge between ATP12A and K+ in the result above looks wrong.  It's coming from our parse of HMDB.  Can you take a look and make sure that we're handling these relationships correctly?

**Comment by sandrine-muller-research** [comment]
I think it is important to correct those edges if possible I'll try to find other examples

**Comment by sandrine-muller-research** [comment]
I performed a few tests to check if this edge was still there and the only thing returned was the `biolink:physically_interacts_with` which is accurate. See one query showing the only edge [here.](https://arax.ci.transltr.io/?r=177bd3f6-2be0-4d5f-b08a-99228db523b4)
