### ISSUE TITLE
small molecules are returned while genes are asked

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#754]
## Steps to reproduce:
What gene may be upregulated by acetylcholine?
select small molecule filter

**Comment by sandrine-muller** [comment]
These are two results returned by ARAX as lookups from semmed:
![image](https://github.com/NCATSTranslator/Feedback/assets/153299800/bd1988c2-36e5-4ccd-a616-9494fac094cb)

**Comment by sierra-moxon** [comment]
@edeutsch @saramsey @andrewsu - should we do another SEMMEDDB curation effort for MVP2,3?

**Comment by edeutsch** [comment]
Do we think this is really a problem? Angiotensin II is complicated. okay, it's not a gene. And maybe not a protein depending on how you define protein. But it is a small polypeptide hormone that comes from a gene after substantial processing. And I think we all agreed to officially conflate genes and proteins. So I'm thinking that if Angiotensin II is regulated by acetylcholine, then it is well worth showing, and it is a very minor offence to call Angiotensin II a small molecule, when it is really a polypeptide or maybe a microprotein or maybe a hormone or something that is ultimately a gene product.

**Comment by andrewsu** [comment]
I agree with @edeutsch's comment -- on the scale of issues we're juggling, I think this can be a "won't fix"...  

Given we have a proposal and a "second", I'm going to close the issue.  But feel free to reopen if someone feels passionately about this...
