### ISSUE TITLE
Attributes to distinguish FDA-approved drugs (and pipeline drugs) from environmental toxicants

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#76]
One of the QotM SMEs requested a Translator functionality to sort a list of chemicals by, e.g., those that are FDA-approved or in the pipeline and those that are environmental toxicants. This issue is similar to the ChEBI role discussion, but it is somewhat distinct, in that I'm not sure 'environmental toxicants' are represented in ChEBI.

**Comment by sierra-moxon** [comment]
@vdancik - MolePro provides "FDA approval status" already right?

**Comment by sierra-moxon** [comment]
from TAQA:

What are the expectations for bubbling up node attributes (and edge attributes) to the ARS/UI.
BTE especially is federated, retrieving from APIs, and can get more information on the fly.
Other resources are static and need to change ETL pipelines to comply.  We do need standardized attributes for each kind of node, but it is a bigger lift for some than others.

we need consistent properties, but where do we store them, and how do we get there?  Maybe one version is to have the KPs do this (repetitively), and another is to bundle everything together; have one consistent place to have it.

**Comment by karafecho** [comment]
Clarification that Translator can distinguish FDA-approve / in-pipeline drugs from drugs that are not FDA approved or in the pipeline. MolePro's research indicates that data on environmental toxicants are currently not available in a structured format.
