### ISSUE TITLE
lookup result not accurate

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#763]
## Steps to reproduce:
What genes may be downregulated by:Lepirudin
search for TNFSF4

**Comment by sandrine-muller-research** [comment]
When looking at the lookup results, I am struggling with understanding what is reported here through Text mining API:
![image](https://github.com/NCATSTranslator/Feedback/assets/22616936/8a4cab57-cace-4605-bcfc-ded89501d889)
VEGF is in bold which does not support the gene in the lookup TNFSF4. In the text reported, the closest match to TNFSF4 would be TNF-alpha although the gene name for TNF-alpha is TNF not TNFSF4 that maps to another protein.
I have not investigated further but it looks to me we have 2 issues:
- UI display with correct bolded words
- Text mining incorrect gene mapping

**Comment by gprice1129** [comment]
@sandrine-muller-research thanks for reporting this! There appears to be a bug in the UI that causes at least some of the problems here. We are working on it.

**Comment by gprice1129** [comment]
@sandrine-muller-research we have verified the fix on Test. Going to close the issue but please re-open if you encounter the problem again.
