### ISSUE TITLE
Example of issue with ranking (O&O): MVP2 Bivalirudin

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#765]
## Steps to reproduce:
What genes may be downregulated by:Bivalirudin?

**Comment by sandrine-muller-research** [comment]
F2 and thrombin are targets validated in multiple databases and not coming as top answers. Instead top answers (with same scores than F2 and thrombin = ties) are only based on text mining evidence (less confident IMO).

**Comment by sandrine-muller-research** [comment]
It is not very clear why PLATELET GLYCOPROTEIN GPIIB-IIIA COMPLEX comes before than F2:
![image](https://github.com/NCATSTranslator/Feedback/assets/22616936/f5d1fe87-6703-40eb-adb7-35ed770c6bc2)

**Comment by sstemann** [comment]
I'm not sure how the rank is calculated other than its from Appraiser.  in the flattened Excel  
[Bivalirudin_test_2024_7-5_17_43_0e24a207-aa29-42ef-92c8-f3492d2cba4a.xlsx](https://github.com/user-attachments/files/16112622/Bivalirudin_test_2024_7-5_17_43_0e24a207-aa29-42ef-92c8-f3492d2cba4a.xlsx)


|objectNode_name|Platelet Glycoprotein GPIIb-IIIa Complex (MESH:D019039)|Platelet Glycoprotein GPIIb-IIIa Complex (UMLS:C0016011)|thrombin (UMLS:C0040018)|F2 (NCBIGene:2147)|
|--------|--------|--------|--------|--------|
|rank|2|3|4|5|
|sugeno_score|1|1|1|
|comp_confidence_score|1|1|1|1|
|comp_novelty_score|0|0|0|0|
|comp_clinical_evidence_score|0|0|0|0|
|weighted_mean_score|0.48|0.48|0.48|0.48|
|normalized_score|100|96.8|18.8|100|
|ARAX_score|1|0|0|0.93|
|unsecret_score|0|0.99|0|0.17|
|improving_agent_score|0|0|0|0|
|biothings_explorer_score|0|0.34|0.21|0.86|
|aragorn_score|1|1|1|1|

**Comment by sharatisrani** [comment]
@sandrine-muller-research questions are fundamentally questions of reasoning, so added that label.  the ARA's are newer at MVP2 reasoning than MVP1 reasoning.

@MarkDWilliams to clarify the same question from several other issues - how come the ranks are sequential when the scores are the same.  Or should we be asking @gaurav

**Comment by gaurav** [comment]
> Or should we be asking @gaurav

I know nothing about the ranking, so I can't help with that. But I know there are multiple F2 cliques (#764), which I'm hoping to close by Guppy. I'm going to remove myself from this ticket, but please add me back in if there's a node normalization issue not already captured by #764!

**Comment by sandrine-muller-research** [comment]
[retested](https://ui.test.transltr.io/main/results?l=Bivalirudin&i=CHEBI:59173&t=4&r=0&q=76bd451f-cfb7-4a07-acef-ce8cc19106fe) today

@sharatisrani F2 and thrombin do appear so the "reasoning" works although it should clearly be look up edges. In this issue I am trying to understand why F2 does not arrive first? The first result from UI is PLATELET GLYCOPROTEIN GPIIB-IIIA COMPLEX that is only supported by text mining edges while F2, which arrives in 4th position, is supported by 10 paths from which 3 are look ups. 

@sstemann thank you so much for posting this table, really useful to study more in details. (in the UI it seems I have a slightly different ranking now.) and I agree with you I am unclear how the ranking is done in those conditions. Shouldn't it be the number of total paths supporting and/or if they is any look up edges?

**Comment by sstemann** [comment]
this got tagged for Guppy, what is going to change to resolve this? @sierra-moxon

**Comment by MarkDWilliams** [comment]
@sharatisrani the sequential ranks are due to the way that Rosina's scoring/ranking code deals with ties.  The logic is all in the scoring.py file in the ARS code, but if you have questions about the algorithm, I believe Prateek wrote it and would be the best person to talk to.

**Comment by sstemann** [comment]
@sandrine-muller-research i think then this is a question for @Rosinaweber and @pg427.  in the table, it seems like F2 has more ARAs returning it.

**Comment by sharatisrani** [comment]
Re-running this Q via the UI, the results are still ~unchanged.  So will go into the O&O tables and look at what's coming back and "debug" things, also knowing that some things will change (eg rank assignments).  More this weekend.

**Comment by sandrine-muller-research** [comment]
Thank you @sharatisrani Today's retest is [here](https://ui.test.transltr.io/results?l=Bivalirudin&i=CHEBI:59173&t=4&r=0&q=dd6d2da9-7a2d-4d8d-b5d1-42b33cd1ad99). 
 Linked with issue #929 for ranking of top results.

**Comment by sharatisrani** [comment]
Closing the issue.

**Comment by sstemann** [comment]
this is in Prod with Fugu

https://ui.transltr.io/results?l=Bivalirudin&i=CHEBI:59173&t=4&r=0&q=535628d2-58ed-4699-a659-c397ffd0548c

![image](https://github.com/user-attachments/assets/4806017a-89b8-4839-84a7-c80473120895)
