### ISSUE TITLE
Improving Agent as Lookup EPC

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#769]
I'm not sure I understand this EPC

1. Run MVP1 in Test UI for Autism https://ui.test.transltr.io/main/results?l=Autism&i=MONDO:0005260&t=0&r=0&q=eaf6e3f6-ce4e-4f65-8a91-e8e389c61e2e
2. Use Indicated for Disease filter
3. Expand (6r)-folinic Acid
4. The second lookup path, the Treats edge shows:
 
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/a0b46871-5ebc-4f9a-8b19-fe4e13fa8e93)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/a063e713-364d-4501-9675-89fe80a7b387)

5.  In the ARAX GUI it seems to have a one-hop support graph - here is the result graph
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/8af76d7f-54a9-4854-a82e-38d3da104de7)

6. here is the support graph
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/6eea7599-52c5-4bcc-8c78-dfd13f56c184)

i'm not sure how it should be displayed - if this is an inferred edge really and should be in the second pane of the result?

@gprice1129 @dnsmith124 @brettasmi

**Comment by Genomewide** [comment]
@brettasmi the support edges for this appear to be in the wrong place. The support graphs at the analysis level are there to show the edges used to calculate the score. The support graphs for the edges are those found in an edge attribute and they are where we look for the paths that support the inferred edge. 
So, can your team fix that so they show up there?

**Comment by gprice1129** [comment]
This no longer seems to occur in production. Closing.
