### ISSUE TITLE
Many results are returned more than once for What treats headache

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#771]
Query: What drugs may treat headache? 
Results from https://ui.test.transltr.io/: 
https://ui.test.transltr.io/main/results?l=Headache&i=HP:0002315&t=0&r=0&q=615645d1-78c0-48fd-b3e8-1c9a4ea47a3a

Many of the results are returned more than once, with different number of paths and scores.

- Ibuprofen is returned twice: PUBCHEM.COMPOUND:3672 with 8 paths and CHEBI:5855 with one path.
- Acetaminophen: PUBCHEM.COMPOUND:1983 with 10 paths and Paracetamol CHEBI:46195 with one path.
- Nitroglycerin: PUBCHEM.COMPOUND:4510 with 4 paths and CHEBI:28787 with one path

Same story with Sumatriptan, Ergotamine, Almotriptan etc.

Shouldn't the duplicated results be collapsed into one answer?

**Comment by sierra-moxon** [comment]
@gaurav - I imagine this is a chemical entity id_prefixes issue?  (we discussed in DM call today that the revised id_prefixes in Biolink won't be release for another ~ 4 weeks.  Should we just slot this in for after that refactor, or is there anything else we can do here?)

**Comment by gaurav** [comment]
I'm not seeing a lot of duplicates on Test now: https://ui.test.transltr.io/main/results?l=Headache&i=HP:0002315&t=0&r=0&q=6067fe39-a0aa-4118-81fa-d2426be8a61f

I specifically checked the ones in the original ticket, and all the remaining "duplicates" look okay to me:
* Ibuprofen, (r)-(-)-ibuprofen, Ketoprofen
* Sumatriptan, Sumatriptan succinate
* Ergotamine, Dihydroergotamine, Ergotamine Bitartrate, Dihydroergotamine Mesylate, Caffeine / Ergotamine
* Almotriptan, Almotriptan Malate

So it looks like this was a drug-chemical conflation issue that has now been fixed. I'll go ahead and close it, but please reopen or open another ticket (here or on https://github.com/TranslatorSRI/Babel/issues) if any of those terms should be conflated or if we're over-conflating terms.
