### ISSUE TITLE
Amino acid sequence instead of human readable label for TNF-alpha

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#773]
Query: What drugs may treat allergic asthma?
https://ui.test.transltr.io/main/results?l=Allergic%20Asthma&i=MONDO:0004784&t=0&r=0&q=051c9c6e-9bdf-46dd-b35e-28cf5ee44d03

On page 2, "H-lys-gly-asp-arg-leu-ser-oh" is returned as an answer. Following the link to PubChem, this is in fact TNF-alpha. Is this a node normalizer issue?

**Comment by gglusman** [comment]
Doesn't seem like it. Node Norm gives TNF-alpha as preferred name:

```
  "pubchem.compound:44356648": {
    "id": {
      "identifier": "PUBCHEM.COMPOUND:44356648",
      "label": "TNF-alpha"
    },
```

**Comment by sstemann** [comment]
this looks resolved with the latest NN

https://ui.test.transltr.io/main/results?l=Allergic%20Asthma&i=MONDO:0004784&t=0&r=0&q=28951c02-86d8-4b31-b0f0-c50c4dafba6c

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/50a87060-3e79-46e8-bf46-f3653d8fe6ab)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/48020381-ed58-42a4-a36c-c73c59f88f21)
