### ISSUE TITLE
X treats 'adverse drug response' to X

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#774]
HPO has the rather general term '[adverse drug response](https://hpo.jax.org/app/browse/term/HP:0020172)', which is probably not particularly useful as a query in Translator. I just [did that search](https://ui.transltr.io/main/results?l=Adverse%20Drug%20Response&i=HP:0020172&t=0&r=0&q=45cda5e9-6a5b-4083-8662-0d0829cde18d) and found that indeed most responses are rather bad.

One obvious bad pattern is the misinterpretation of "Adverse drug reactions (ADR) due to antipsychotic therapy" as "antipsychotic therapy treats adverse drug reactions", and the somewhat trickier to parse, "To characterize reported adverse drug reactions (ADRs) in children and adolescents treated with antipsychotics..." (the children are treated, not the ADRs).

Many of the results are about other terms (e.g., drug dependence, drug overdose) that are presumably related to the query term.

**Comment by sierra-moxon** [comment]
@gglusman @gaurav @MarkDWilliams - should we add this term to the blocklist(s)? 

I did note that the second result in the return linked above does appear to be a row from CTD, where at least the drug is being tested to combat "adverse drug response", but that is not a very specific term and the study is only talking about a much narrower phenotype of a particular kind of ADR.  In general, this seems like too broad a term to use in queries.

@bill-baumgartner @mikebada - just ping'ing you here in case you want an example of a possible complex text-mining issue?

**Comment by gaurav** [comment]
I've filed the Autocomplete part of this at https://github.com/NCATSTranslator/Blocklists/issues/54 and should be able to do it in Fugu.

**Comment by sierra-moxon** [comment]
from TAQA: coming in the autocomplete blocklist in the next upgrade of NameResolover (probably in Guppy unless CI needs a push).

**Comment by sstemann** [comment]
fix is in prod 
![image](https://github.com/user-attachments/assets/354eb685-e4c1-423e-a85c-1c39f3b8c9ff)
