### ISSUE TITLE
Number of Path Calculations

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#777]
It says 3 paths but when I expand there are many more

https://ui.test.transltr.io/main/results?l=Marfan%20Syndrome&i=MONDO:0007947&t=0&r=0&q=66fef4ee-80da-46fc-af19-17080072df07

Losartan Potassium
Hyzaar

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/6e04cfc6-300f-4884-b580-c2683756da10)

Second example - says one path, looks like 3 https://ui.test.transltr.io/main/results?l=CACNA1A%20(Human)&i=NCBIGene:773&t=1&r=0&q=cd9ce523-b234-4b62-8396-0c9f98d54fef
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/80bb9dfa-bef3-41af-abea-541855e2feaa)

**Comment by dnsmith124** [comment]
It looks like sometimes the path counts are not updated when a result is updated after additional results are loaded. I've pushed a fix that resolves the issue that appears to be working properly in CI. 

Closing
