### ISSUE TITLE
Compounds Part of some version of the same Compound that has part Starting Compound  - Is this intentional?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#778]
https://ui.test.transltr.io/main/results?l=Marfan%20Syndrome&i=MONDO:0007947&t=0&r=0&q=66fef4ee-80da-46fc-af19-17080072df07

There are many paths that read

atenolol is part of 
- atenolol 100 MG Oral Tablet
- atenolol 50 MG Oral Tablet
- atenolol 5 MG/ML
- etc

Then those are part of the first node atenolol - doesn't seem valuable.  The EPC is all the same:
first hop - RX Norm
second hop - RX Norm
last hop - Semmed link to https://pubmed.ncbi.nlm.nih.gov/19430350/

Do we need this?  according to its top level Inferred its ARAGORN.  I can't get the ARAGORN results to load in ARAX https://arax.ncats.io/beta/?r=66fef4ee-80da-46fc-af19-17080072df07

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/f402e9b4-7e08-4d92-9ac1-9552f6fa76ab)

**Comment by sierra-moxon** [comment]
from relay:
we think this should be fixed; just needs a quick test once ARS is back to business.

**Comment by sstemann** [comment]
comes up differently so this is probably fixed.  now it looks like this:

https://ui.test.transltr.io/main/results?l=Marfan%20Syndrome&i=MONDO:0007947&t=0&r=0&q=31c03941-8b4d-48df-9e78-a0f4021882b3

<img width="841" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/1ecb5332-7c82-4783-9c0d-335a783dabe2">
