### ISSUE TITLE
MVP2 - What genes' activity is up/downregulated - Changes to the input node

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#782]
https://ui.test.transltr.io/main/results?l=Metformin&i=PUBCHEM.COMPOUND:4091&t=3&r=0&q=ffb1d29d-2e2e-4aff-85ba-09c12cf7736c

if you expand 
ATP8A2 PROTEIN, HUMAN
APP
ROS1
NOS3

You will see that the chemical input node has changed for the Unsecret results 

<img width="749" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/81c9e344-c9d2-495c-b23e-a89fc15ec050">

**Comment by kaiwenho** [comment]
The "M [Preparations]" concept, which has a UMLS semantic type of Classification (STY:T185), was causing the problem. 

```
"UMLS:C2267095" ("M [Preparations]") -"biolink:subclass_of"-> "UMLS:C0025598" ("metformin")
"UMLS:C0025424" ("Mercury") -"biolink:subclass_of"->  "UMLS:C2267095" ("M [Preparations]")
```
We have implemented a filter to avoid using nodes with this UMLS semantic type in the reasoning process. This should resolve all related issues. The update is in Unsecret [CI](https://ui.ci.transltr.io/main/results?l=Metformin&i=CHEBI:6801&t=3&r=0&q=a9cbd741-ac7e-4e33-acd2-880050e03a82) and [Test](https://ui.test.transltr.io/main/results?l=Metformin&i=CHEBI:6801&t=3&r=0&q=3bcf43c2-9044-4f11-9c21-26471d669c86).

**Comment by cbizon** [comment]
I ran the query in TEST and can confirm that this is fixed.
