### ISSUE TITLE
Why is this one scored 5.0?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#783]
https://ui.test.transltr.io/main/results?l=Maturity-onset%20Diabetes%20Of%20The%20Young&i=MONDO:0018911&t=0&r=0&q=f8de3997-f479-49c7-b9ed-b15dc9db9ae4

I have no filters on the UI, but substance "Name Unknown" (https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL511749/)  with 2 pieces of evidence has a 5.0?

Looks like it's coming from Improving Agent 
<img width="945" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/8876c740-72e0-46b1-be5f-efc81f433fb2">

<img width="899" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/947c5047-1ce5-4885-860f-765e99d4cf07">

**Comment by cbizon** [comment]
I reran this one now that NN is updated and I no longer see NameUnknown.  @sstemann do you agree?

**Comment by sierra-moxon** [comment]
from relay:
we think this is fixed, removing octopus tags and review tags. 
Mark puts Nameunkown as a default.  NN does not return a name, none of the ARAs return it, just return the CURIE.

**Comment by MarkDWilliams** [comment]
The NameUnknown problem should be resolved by this PR
https://github.com/NCATSTranslator/Relay/pull/625

**Comment by sstemann** [comment]
while the NN issue is resolved - I'm still unclear about why this particular result is a 5.0 and ranked 2.  It is only returned by Improving Agent, so I would have thought confidence/sugeno would have taken into account the other results that are shared by multiple ARAs and ranked this below that.

@sharatisrani

**Comment by sstemann** [comment]
this result is gone from Test and Prod so hard to investigate
