### ISSUE TITLE
Messenger RNA Evidence for MODY

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#784]
https://ui.test.transltr.io/main/results?l=Maturity-onset%20Diabetes%20Of%20The%20Young&i=MONDO:0018911&t=0&r=0&q=f8de3997-f479-49c7-b9ed-b15dc9db9ae4

the messenger RNA answer, via the UI, only has evidence "Unsecret Agent"
<img width="881" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/a3274339-9ddd-4f95-8453-9a80b9397351">

<img width="704" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/bb5665d5-024b-4ee1-9a0e-00440f3dadc1">

in the ARAX GUI the Support Graph says Genes are part of the inference, maybe Genes was general and blocked but the "lookup path" remains?  In general though, isnt this just too generic?

<img width="884" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/5cc27027-4d5f-4fec-8963-a30e4edab522">

**Comment by cbizon** [comment]
Seems like 2 issues:
1. Add Messenger RNA to block list (@MarkDWilliams ?)
2. The provenance here shouldn't say Unsecret I think.  Not sure if this is the underlying data or the UI (@webyrd , @kaiwenho can you comment please?)

**Comment by cbizon** [comment]
I also think we should add "Promoter" and "Double Stranded Rna" to the block list (found in MODY results)

**Comment by kaiwenho** [comment]
I agree with @sstemann that 'Genes' was general and blocked. `Messenger RNA -treats-> Maturity-onset Diabetes Of The Young` is the inferred edge generated by Unsecret, with the supporting edges
`Messenger RNA -affects-> Genes` 
`Genes -causes->  Maturity-onset Diabetes Of The Young`
and both supporting edges are coming from semmeddb. I am assuming these two 'bad' edges were blocked by ARS, since in the ARAX GUI the supporting edges are still there, but they are not in the UI. However, the inferred edge has not been blocked/removed even all (2 in total) supporting edges were gone (/blocked).

**Comment by cbizon** [comment]
@MarkDWilliams if all of the paths are removed, shouldn't the overall result be removed as well?

**Comment by cbizon** [comment]
Also add "Response Elements" which I found in running "treats Marfan Disease"

**Comment by cbizon** [comment]
Also "Elements"

**Comment by sierra-moxon** [comment]
copper atom too?

<img width="1082" alt="Screen Shot 2024-06-04 at 3 48 57 PM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/242ddd9e-fe65-47ac-9dbb-199d26af56ba">

**Comment by sierra-moxon** [comment]
rerun results: https://ui.test.transltr.io/main/results?l=Maturity-onset%20Diabetes%20Of%20The%20Young&i=MONDO:0018911&t=0&r=0&q=81aba51f-2b8f-46b7-9b80-da71caadac4a

**Comment by sierra-moxon** [comment]
from the relay:
Many of the "rerun results" above should be on the block list.
If a result shows as an inferred path but contains a blocked item, then ARS will return the blocked edge; if ARS returns all evidence, then it removes all of it but isn't touching the primary knowledge source edge, which then shows up as a lookup (cause no support graphs)...

todo:
just get rid of everything - no bare assertions without support graphs.

**Comment by MarkDWilliams** [comment]
I believe I have a fix for this now.  Just to make sure we're all on the same page about it, with this fix

- If all of the support graphs on an edge get removed for blocklist reasons, we remove that edge
- If that edge is part of any analyses, it is removed from there as well
- If removing edges from an analysis leaves us with an analysis that has no edges, we remove that analysis
- If removing that analysis leaves us with a result which has no analyses, we remove that result.

All said, just to give an idea of numbers it looks like these are the differences in the number of things removed from Unsecret's merged_response pre vs post fix:
Nodes: 25 -> 25
Edges: 289 -> 386
Results: 24 -> 105
Aux graphs: 128 -> 128
Analyses: 16->99

**Comment by cbizon** [comment]
This sounds good to me!

**Comment by sierra-moxon** [comment]
retested on test this morning; seeing copper atom, etc. in the results. For messenger RNA, I still see the one lookup path.

**Comment by sstemann** [comment]
trickle up is working in Test!
