### ISSUE TITLE
Reads Diabetes <Treats or Applied or Study to Treat> Compound Name

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#786]
https://ui.test.transltr.io/main/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&r=99ac263a&q=8ccea6d0-5bd1-4969-b41c-45581214283e

MVP1 in Test > Glyburide the paths look like the diease is treating a compound - I can't view the ARAGORN results in the ARAX GUI.

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/be89872a-0b99-43a1-8d16-0af1a50658f9)

**Comment by edeutsch** [comment]
> I can't view the ARAGORN results in the ARAX GUI

why not? Seems to work okay for me?
https://arax.ci.transltr.io/?r=a22c86b0-c93c-4001-920f-d71aa7415a47

![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/3a35de59-1817-4735-bb28-c116a86b8786)

**Comment by cbizon** [comment]
Yeah, this one loaded for me in ARAX as well.   The results are a bit confusing, I think because of the way subclasses are being handled.  So I won't say for sure yet that the ARAGORN result is properly formatted.  But I don't see any results with the treats_or_... edges pointed the wrong way:

![image](https://github.com/NCATSTranslator/Feedback/assets/10744350/813a8307-63fb-498b-b4cb-02a4de3d0dbf)

**Comment by cbizon** [comment]
I think that this is probably an application of the rule:
(A)-[treats_or]->(B) 
AND
(A)-[similar_to]->(C)-[treats_or]->(B)
SUGGESTS
(A)-[treats]->(B)

But it looks funny because while B=Diabetes mellitus, we are getting some subclasses of that back for the two [treats_or] links.

**Comment by sstemann** [comment]
> > I can't view the ARAGORN results in the ARAX GUI
> 
> why not? Seems to work okay for me? https://arax.ci.transltr.io/?r=a22c86b0-c93c-4001-920f-d71aa7415a47
> 
> ![image](https://private-user-images.githubusercontent.com/12707718/334886808-3a35de59-1817-4735-bb28-c116a86b8786.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMDMxNTQsIm5iZiI6MTcxNzAwMjg1NCwicGF0aCI6Ii8xMjcwNzcxOC8zMzQ4ODY4MDgtM2EzNWRlNTktMTgxNy00NzM1LWJiMjgtYzExNmE4NmI4Nzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDE3MTQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZjRmZTc0YTc3M2UyOWQ1NzhmMWQxOTQxNWFmMWQ3ODhkNWUwNzBkY2I3MmRkMDdkYWRlZGQxMDBlYzM3NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-hQf0l9jOJdEP9HQmK1N1KTcQgqZKvGTRlrB5wCGjV8)

my apologies - it was these PK, which were run in UI - CI 
294a214d-674c-410d-86cb-1932b7447d03  
9a0f94e2-f0eb-4560-8150-d77bed72bf0b

**Comment by edeutsch** [comment]
For the first one 294a214d-674c-410d-86cb-1932b7447d03, the validator reports invalid TRAPI:
https://arax.ci.transltr.io/?r=294a214d-674c-410d-86cb-1932b7447d03

![image](https://github.com/NCATSTranslator/Feedback/assets/12707718/4cdb9d55-7502-4bcb-b3e9-c339cb9ae86f)

It looks like there are KG Edge.object entries with no corresponding KG Node entry. Invalid TRAPI is known to cause rendering problems in the ARAX GUI.

Would be good to fix the TRAPI and then it should render.

**Comment by cbizon** [comment]
I don't think that there is an edge pointing the direction that the UI is showing in the results.  @Genomewide do you think this is a UI issue?

**Comment by Genomewide** [comment]
Looking at the raw data, I think it could be.  I don't see any edges that have the disease treating the drug.  @dnsmith124 @gprice1129 thoughts?

**Comment by sstemann** [comment]
resolved in TEST
