### ISSUE TITLE
PathWhiz/Reactome in Paths

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#788]
Is there another way to display the Reactome Node label in the UI?

<img width="822" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/b354defe-4060-49ca-93cc-bcf8f251afc5">

https://ui.test.transltr.io/main/results?l=Aceruloplasminemia&i=MONDO:0011426&t=0&r=0&q=77003cf0-f9ff-4864-bc02-b89f2c216c82 > Oxygen Atom

**Comment by dnsmith124** [comment]
@sstemann can you clarify what you're referring to here?

**Comment by sierra-moxon** [comment]
second path from the top, the first grey node in the path starts with "Slc4..." which is a name for a particular set of steps in the (grouping term) "Iron uptake and transport" event at reactome.  

<img width="1432" alt="Screen Shot 2024-05-31 at 5 39 07 PM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/709cb5de-2703-4972-afbf-daa76b02dd45">

**Comment by dnsmith124** [comment]
@sierra-moxon thank you for the clarification!

@sstemann @Genomewide how would you prefer to see these sorts of labels displayed?

**Comment by Genomewide** [comment]
the logic of this seems weird to me as it is.  A pathway that uses oxygen and also iron, and iron treats a disease is weird.  

Where is this reactome data coming from? Is this a Flanick question? I would speak to the experts first before thinking about what to display here.

**Comment by marcdubybroad** [comment]
> the logic of this seems weird to me as it is. A pathway that uses oxygen and also iron, and iron treats a disease is weird.
> 
> Where is this reactome data coming from? Is this a Flanick question? I would speak to the experts first before thinking about what to display here.

The Genetics KP has reactome pathways/disease genetic association data; unclear if this is where this result is coming from.

**Comment by sstemann** [comment]
@uhbrar or @cbizon is this data in the ARAGORN responses coming from Genetics KP?

**Comment by cbizon** [comment]
From the above snippet, it looks like it's coming from pathwhiz via KG2.  FWIW, I don't like (certain of) these answers and have some code to test this week to remove some of the worst ones.

**Comment by sstemann** [comment]
should I retest in Fugu @cbizon ?

**Comment by cbizon** [comment]
Yes, please @sstemann

**Comment by sstemann** [comment]
@cbizon it's still an issue in Fugu/Test

https://ui.test.transltr.io/main/results?l=Aceruloplasminemia&i=MONDO:0011426&t=0&r=0&q=0e83e4a4-0af7-4b6d-8287-53fecd44b8f2

![image](https://github.com/user-attachments/assets/0d44d42e-7bce-4a0e-9636-0eee2232c3d2)

**Comment by sstemann** [comment]
@cbizon  I ran this query on 8/12 after the ARAGORN cache refresh.  At a minimum, it's still happening with Xeroderma Pigmentosum.  It also looks like ARAGORN has MANY support graphs.  

https://ui.test.transltr.io/main/results?l=Xeroderma%20Pigmentosum&i=MONDO:0019600&t=0&r=0&q=689fdfb0-b2fa-411e-8a4c-34ef879a1787

![image](https://github.com/user-attachments/assets/676a857b-e496-4dba-891a-3f2ba014c623)

![image](https://github.com/user-attachments/assets/cbabea8c-e4d8-45b1-9e11-80351664eabc)

ARAGORN returned 0 for Aceruloplasminemia in Test
https://ui.test.transltr.io/main/results?l=Aceruloplasminemia&i=MONDO:0011426&t=0&r=0&q=6e00c665-0d9c-43e9-8998-b5ba235cf83f

https://arax.ci.transltr.io/?r=6e00c665-0d9c-43e9-8998-b5ba235cf83f

![image](https://github.com/user-attachments/assets/0b3055c5-92e9-418f-8a4c-87ba664d8599)

**Comment by cbizon** [comment]
It looks like the filtering has removed all the ones where "Iron" was a component, but not ones with Caffeine or Levdopa.  I'll take a look at the filtering values and see if we want to adjust.

**Comment by cbizon** [comment]
Looking deeper, I think we may want to remove PathWhiz nodes, or try to find which chemicals into these reactions are involved in so many reactions as to be useless.   The rule was really developed with GO terms in mind, and extending it into pathwhiz reactions is causing these messy results.

That said, I don't think that oxygen will go away as a result, because we have many paths where oxygen is applied or studied to treat a phenotype of the query disease.   So if we don't ever want to see oxygen as a result we probably need to add it to a block list.
