### ISSUE TITLE
Were these paths supposed to be merged? 

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#789]
The node identifiers on the start middle and end nodes look the same, the predicates look the same, the evidence on the predicates look the same

<img width="842" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/0a0cea6c-27c5-4972-ad36-753d5cd8d49d">

https://ui.test.transltr.io/main/results?l=Aceruloplasminemia&i=MONDO:0011426&t=0&r=0&q=77003cf0-f9ff-4864-bc02-b89f2c216c82

**Comment by dnsmith124** [comment]
I don't believe these paths should be merged, if you mouse over the nodes that begin with Fech Binds Fe... their names differ after the ellipsis, and they have different curies. 
For example:
`Fech Binds Fe2+ To Prin9 To Form Heme (dictyostelium Discoideum)` 
vs 
`Fech Binds Fe2+ To Prin9 To Form Heme (rattus Norvegicus)`

I just moused through them and don't see any duplicates.

**Comment by sierra-moxon** [comment]
from TAQA:
[Gaurav] - these would be deemed a cluster using the method I showed in O&O last week 🙂 - see https://github.com/NCATSTranslator/Feedback/issues/863 as example
[Chris] - the filter we put on to remove these kinds of pathways should be in TEST via Fugu.

**Comment by sandrine-muller-research** [comment]
[Retested today](https://ui.test.transltr.io/main/results?l=Aceruloplasminemia&i=MONDO:0011426&t=0&r=0&q=a273119e-66b3-44be-ae10-c95bd30c1b8e)
The nodes in the middle look different but do not seem right/normalized:
<img width="727" alt="image" src="https://github.com/user-attachments/assets/006c9d13-e0c1-4d0f-be97-ac164320015a">
Result comes from ARAGORN. I went ahead and tried to look at the graphs in ARAX but I get no output:
<img width="1049" alt="image" src="https://github.com/user-attachments/assets/1b7a5771-fc5d-44c0-922c-bcf597d27c13">

This issue need further retesting at another time.

**Comment by sstemann** [comment]
i'm not seeing any improvements to these paths returned from ARAGORN in Fugu/Test.  

https://ui.test.transltr.io/main/results?l=Aceruloplasminemia&i=MONDO:0011426&t=0&r=0&q=0e83e4a4-0af7-4b6d-8287-53fecd44b8f2

Its the same in CI.  Looks like this is not fixed in Fugu or queued up to be deployed to Test.
https://ui.ci.transltr.io/main/results?l=Aceruloplasminemia&i=MONDO:0011426&t=0&r=0&q=0886d892-dde0-48f7-847d-e0454e96803c

**Comment by sstemann** [comment]
it looks like these "FECH binds Fe2+..." nodes are all unique.  So I think this is now closed.

https://ui.transltr.io/results?l=Aceruloplasminemia&i=MONDO:0011426&t=0&r=0&q=cf3952b5-8df4-492d-a06d-ff0b09758d15
