### ISSUE TITLE
How many publications to display in the UI, what information to provide (options to select abstract, PMID, title, authors, full pub?)

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#79]
The QotM surfaced a (known) issue related to publication support. Specifically, how should Translator balance the variance among users, in terms of the amount (just a few papers, as many as you have) and type (PMID, PMID + abstract, PMID + full publication) of publication support they want to see? Specificity of publications that are provided? How do users apply publication support? Confidence in edge? In depth exploration? Both, depending on where the publication support is originating?

**Comment by sierra-moxon** [comment]
from TAQA:
- some F&F users say there are too many papers (might need to read or skim all the papers to understand the statement). 
- not something UI can decide; hard to choose just one publication to display.
- maybe it's a user education issue?  
- are the papers sorted?  - not yet, the date would be one to sort on, but its provided in too many formats to be able to sort.

**Comment by sierra-moxon** [comment]
For UCWG: What does a user want when they see a "publication" or a large number of publications for a statement?  UI is hesitant to exclude publications, but would like direction on how to filter large number of publications on a statement that would be most helpful for a user.

**Comment by karafecho** [comment]
Related, there is a a bias toward recent publications on 'hot' topics or heavily researched topics, e.g., COVID, cancer and a desire by users to filter by type of publication (e.g., case study, review). Filter options would help to address these issues.

**Comment by sandrine-m** [comment]
I'll bring the issue to the UCWG at next meeting. Thank you!

**Comment by sierra-moxon** [comment]
From UCWG:
- can we categorize the pubs by the diversity of publication? (maybe from many different journals - rank these higher) ?
- based on author lists, knowledge should be reproduced from many different labs to be considered "better evidence" ?
- could use MeSH terms to compare pub content automatically -- "more similar" = "more better"

**Comment by sierra-moxon** [comment]
@bill-baumgartner - some discussion about this particular ticket at the UCWG (summarized above).  It sounds like TMKP already has a data source that stores publication attributes consistently and which is being used already in the UI. 

Does this data source also have MeSH terms?  Does it already have any calculations or comparison of attributes between publications?  Can we use the data in the data source to write some code that would compare x number of publications from a single edge, for breadth and depth of knowledge (calculated by similarity of MeSH terms, author lists etc)?  This may be too hard to answer without context :) -- we could discuss at TAQA if needed.

**Comment by tursynay** [comment]
UCWG does not have any action items for this issue, however to be discussed at the relay

**Comment by bill-baumgartner** [comment]
@sierra-moxon apologies for not seeing this earlier. We don't currently provide MeSH terms in our publication metadata API, but that would be an easy addition. We also don't supply any comparison calculations between publications but would be willing to modify the API based on the needs to the UI/Consortium.

Current metadata provided:
* document id
* year published
* month published
* day published
* journal
* journal abbreviation
* volume
* issue
* article title
* article abstract

**Comment by sierra-moxon** [comment]
Thank you so much @bill-baumgartner  @sandrine-m and Paul C and the UCWG for the ideas here.  I've put this into the "TACT" meeting bucket so that we can get an executive decision on whether the strategy for "fixing" this issue is reasonable.  @tursynay

**Comment by sstemann** [comment]
@sierra-moxon can this one be closed?  the UI is leveraging the TMKP service.  I'm not sure what the TACT team or strategy is for the other parts but i'm not sure it's still a "UI - display" issue.

**Comment by sierra-moxon** [comment]
closing.
