### ISSUE TITLE
Display ARS results derived from CQS in UI

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#791]

**Comment by karafecho** [comment]
The CQS was somehow never registered in the infores catalog, which the UI uses to verify that a source is valid. As a result, any results that are returned to the ARS by the CQS are not being displayed by the UI. There is a PR to add infores:cqs to the catalog. This ticket is to request that the UI retains edges derived from the CQS after (or before) the PR is merged. Thanks! Kara

**Comment by karafecho** [comment]
PR for adding `infores:cqs` to infores catalog was merged into main on 6/9/2024.

**Comment by dnsmith124** [comment]
@gprice1129 I believe this requires an update to the infores catalog from us, but I may be mistaken

**Comment by karafecho** [comment]
@gprice1129 : No action required on your part. The CQS is now registered in the Infores Catalog, although I just created a PR to add agent type "computational model": https://github.com/biolink/information-resource-registry/pull/16. Thanks!
