### ISSUE TITLE
Bring paths to the top of the list that meet a criteria from a facet

### ISSUE THREAD

**Issue by mbrush** [NCATSTranslator/Feedback#794]
### The Problem: 
The current behavior of the "Reasoning Agent" filter is to show only Results from the selected ARA, but show  paths/EPC info from **all** ARAs that also returned this result. 
 
For example, when I look at the "Botulinum Toxin Type B" result for the query "_What may treat Cerebral Palsy"_, and filter to show only ARAX results - I see many **support paths that were not used by the ARAX agent** (the circled paths below are those used by BTE, which also returns this result):

![image](https://github.com/NCATSTranslator/Feedback/assets/5184212/2dcd0796-f9a0-4e3f-88b9-d372b6801b19)

Also, other EPC that shows up in the results view or popup tables comes from BTE, not ARAX- even when an "ARAX results only" filter is on.

-----

### Proposed Improvement:

IMO, a much more useful behavior would be to also filter support paths (and other EPC info) to include only that used / provided by the selected ARA. 

This is because the value of a "Reasoning Agent" filter to me is to be able to see not only what answers came form a given ARA, but more importantly **what evidence  and provenance each ARA used in doing so** - which the current behavior does not support. The proposed change would also make it much **easier for testers to understand where problematic paths / provenance is coming from**, without as much back and forth between the UI and ARAX interface.  This behavior would also helps educate developers, testers, and end users about how each ARA operates, and the types of paths/evidence they like to use.
 
Unless there is value to retaining Paths/EPC from all ARAs upon filtering for results from a single ARA, can we change the behavior of this "Reasoning Agent" filter?

**Comment by dnsmith124** [comment]
I think the requested adjustment to this feature is very sensible, but in terms of prioritization I wonder how much value the Reasoning Agent filter has for a normal user compared to a tester within the consortium? 

It would be a fairly complex expansion of the filter, particularly considering when multiple ARAs are enabled/disabled, and we'd need to decide how to display the excluded paths (if at all).

**Comment by dnsmith124** [comment]
@Genomewide see above

**Comment by gprice1129** [comment]
UI team needs to discuss internally before assigning to a release.

**Comment by Genomewide** [comment]
@dnsmith124 Couldn't this be covered in the same way we have talked about the other facets? Bring those that fit the criteria to the top and make the others opaque.

**Comment by dnsmith124** [comment]
@Genomewide that's correct, I had commented the above before we discussed as a team potentially overhauling the facet behavior with regard to paths

**Comment by Genomewide** [comment]
We are adding a function that will work for all filters that bring paths to the top of the list that meet a criteria from a facet. In this case (ARAX selected) an edge that has info from BTE and Arax would come to the top if you select either of those.  Paths with only ARAX will also go to the top. Edges that only have BTE will not and will be opaque.

**Comment by sstemann** [comment]
i think "bring paths to the top of the list that meet a criteria from a facet" is happening this phase @dnsmith124 ?

**Comment by dnsmith124** [comment]
That's correct!

**Comment by dnsmith124** [comment]
This feature is complete and live in prod, closing ticket.
