### ISSUE TITLE
Cancer bias in Translator answers

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#80]
The QotM surfaced a (known) issue related to a bias toward cancer in Translator answers. Specifically, Translator results are sometimes skewed toward cancer and cancer-related findings. This is due, in part, to the fact that the scientific literature is flooded with cancer-related publications and also to the fact that cancer is overrepresented among Translator knowledge sources. Suggested that this issue might be minimized by applying more stringent filtering, scoring, and ranking.

**Comment by karafecho** [comment]
For instance, when searching for drugs that may treat disease X, chemotherapeutics such as carboplatin, cisplatin, 5-flurouracil, vincristine, doxorubicing, vinblastine seem a bit overrepresented in results. Now, these may be "correct" answers, but it may be best to let the user decide.

**Comment by sandrine-m** [comment]
This could be linked to issue #149 : a user may want to filter out or group by drug function/role...etc.

**Comment by sharatisrani** [comment]
Agreed with @sandrine-m , hence adding back UI feature request and removing it is an ordering issue.

**Comment by sandrine-m** [comment]
@sharatisrani will the grouping(= organizing) be part of the O&O? some users may want to group instead of filter?

**Comment by sharatisrani** [comment]
Grouping-organizing is supposed to be a UI issue.  In future release, it will create some additional work for O&O team, but for this release we are just returning all the results to the UI.

**Comment by sandrine-m** [comment]
@sharatisrani If Milestone is Fall, is it fair to add back the O&O?

**Comment by sstemann** [comment]
@sandrine-m @sharatisrani is this information available in the TRAPI response to the ARS and UI or via the annotation service?  I dont remember seeing this in the TRAPI response.

**Comment by sandrine-m** [comment]
My guess is that ChEBI roles facet is part of the annotation service but I just asked for confirmation. The issue I am seing here is that I do not think the ChEBI role facet will solve this issue (as to the extent of my knowledge; cancer is not a term under ChEBI role (@cbizon might be able to answer more accurately), mostly if the user (@karafecho, please feel free to comment here) is looking to filter out _compounds studied in cancer_. 
I think @karafecho is raising an important feature : can we filter (I would add group here) by **clinical relevance** _and_ **context type** (context could be disease, species, cell type... etc). That would need a workflow strategy perhaps?

**Comment by cbizon** [comment]
It looks like CHEBI contains this role with a different name: CHEBI:35610 - antineoplastic agent

**Comment by cbizon** [comment]
In terms of grouping, we've recently made some updates to our enrichment methodology that I would like to show to the O&O group soon that may be a helpful way to find groupings.

**Comment by sandrine-m** [comment]
Tested on this query on [UI CI](https://ui.ci.transltr.io/results?l=Familial%20Pityriasis%20Rubra%20Pilaris&i=MONDO:0008251&t=0&q=19f03de9-d166-413a-9495-8e438869caa1) that does contain the antineoplastic agent as a ChEBI role facet. 
There are so much terms uder the ChEBI roles that I cannot filter for Antineoplastic Agents. It Would be nice if UI could have the option of "select all" and then we deselect the ones we are not interested in. 

Also related to #149 is the UI showing all the hierarchy tree in there, or is there a criteria applied here? If it comes out from the annotation service maybe @newgene can help?

**Comment by sandrine-m** [comment]
I would tend to say that, based on what @karafecho explained, the user would have liked to be able to exclude cancer drugs rather than select only those. Could we do that in the UI currently? (please @karafecho feel free to shime in here)

**Comment by karafecho** [comment]
I think the UI now supports the ability to select ChEBI role classification, so I think we can close this issue.
