### ISSUE TITLE
What may downregulate GCG - does not return semaglutide 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#800]
## Steps to reproduce:
semaglutide not showing as inhibitor of GCG

**Comment by sstemann** [comment]
This ticket was logged on June 12th.  We deployed Octopus to Prod on June 13th.  In Prod and Test, the user's expected answer - semaglutide - is returned.  

I think we should consider closing this ticket and create a QA Pair for this relationship  @maximusunc i forget how to add to QA Pairs now?

https://ui.transltr.io/main/results?l=GCG%20(Human)&i=NCBIGene:2641&t=2&r=0&q=2bfd5f88-622e-4254-b5b8-f0cc82f5cfde

https://ui.test.transltr.io/main/results?l=GCG%20(Human)&i=NCBIGene:2641&t=2&r=0&q=36b7cada-fcdb-4d66-8e6e-b0eb4f2262e4
