### ISSUE TITLE
no supporting paths

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#801]
Testing what may treat sepsis https://ui.test.transltr.io/main/results?l=Sepsis&i=HP:0100806&t=0&r=0&q=d2f631c2-11d6-4ffd-90b1-935f81c7bcdf

Result 1: "Statin" shows one "inferred" path based on text-mining, but the inferred path has no supporting paths.
![image](https://github.com/NCATSTranslator/Feedback/assets/3977332/6f70024d-0270-4fd5-a58a-840e8b485233)

**Comment by sstemann** [comment]
i'm not seeing this in Test or CI this week.   if you agree Gwenlyn should we close this ticket?

https://ui.test.transltr.io/main/results?l=Sepsis&i=HP:0100806&t=0&r=0&q=1357341d-e369-463e-bb6a-6c17f7c3908d

https://ui.ci.transltr.io/main/results?l=Sepsis&i=HP:0100806&t=0&r=0&q=969488ab-dc39-4b32-9545-9392523a0f1a

**Comment by gglusman** [comment]
Looks good!
