### ISSUE TITLE
pagination+filtering display error

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#804]
Testing what may treat sepsis https://ui.test.transltr.io/main/results?l=Sepsis&i=HP:0100806&t=0&r=0&q=d2f631c2-11d6-4ffd-90b1-935f81c7bcdf

Action 1: go to a later page, e.g., page 2 of results
Action 2: click on the 'chemical categories' to expand
Action 3: click on 'Phase 2 Drug' to select
Result:
![image](https://github.com/NCATSTranslator/Feedback/assets/3977332/ad5e0515-8685-44a2-bda9-0e7936b65169)
Notice "no results" even though there should be seven results, and "Showing 11-7 of 7".
Action 4: click on the 'Previous' button
Result: Proper display of the seven results on Page 1.

**Comment by dnsmith124** [comment]
This is a known bug that has been addressed, but the fix has not been deployed to Test yet. Will update and close once the fix has been deployed to Test.

**Comment by dnsmith124** [comment]
This fix has been deployed to Test, retested and confirmed to be resolved. 

closing.
