### ISSUE TITLE
cadmium atom treats "hitchhikers thumb" in a MVP1 query for "what may treat common cold" 

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#807]
https://ui.ci.transltr.io/demo/results?l=Common%20Cold&i=MONDO:0005709&t=0&r=08q=37843a7f-ba4d-42f-a1ea-cec7c8536600&q=ff6f8d37-4228-4e0f-80a6-cc765155f53a

<img width="1649" alt="Screen Shot 2024-06-28 at 4 13 28 PM" src="https://github.com/NCATSTranslator/Feedback/assets/4561292/a5b3f852-5449-4f57-b90f-8e87a3b45c3e">

@kaiwenho - I see Unsecret in the knowledge sources -- feel free to pass back to me if this is actually from another provider and I made a mistake in the assignment? :)

**Comment by kaiwenho** [comment]
Thanks, @sierra-moxon! I am not sure if this answer is coming from Unsecret, because I could not replicate the page you shared with the same query in Translator UI CI env: https://ui.ci.transltr.io/main/results?l=Common%20Cold&i=MONDO:0005709&t=0&r=0&q=545f3975-6041-43b2-a704-c17b96fed889. Did you make the query just before opening this issue?

**Comment by kaiwenho** [comment]
@sierra-moxon If you check other answers, all of them are about 'drugs may treat hitchhikers thumb', from BTE as well. 
<img width="1412" alt="Screenshot 2024-06-28 at 9 18 13 PM" src="https://github.com/NCATSTranslator/Feedback/assets/67288473/f615013a-c1ea-4f1f-875e-9fb0add1a95d">
I assume the issue might come from the name solver which came back the wrong curie for common cold.

**Comment by sstemann** [comment]
i cant recreate this issue either

https://ui.test.transltr.io/main/results?l=Common%20Cold&i=MONDO:0005709&t=0&r=0&q=ee127a65-9781-47da-a00d-c1c2ebf9271d

https://ui.ci.transltr.io/main/results?l=Common%20Cold&i=MONDO:0005709&t=0&r=0&q=a263994d-ca75-4b81-896d-6c97da36c034

@sierra-moxon would you consider closing?
