### ISSUE TITLE
Gene Symbols and SemMedDB

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Feedback#82]
Issues with gene symbols and questionable results (e.g., 'human rabies biolink:related_to PsA gene set') surfaced yet again with this month’s challenge question (QotM NCATSTranslator/testing#5), with symbol mismatch and confusion when multiple symbols are assigned to a single gene. These issues, which the UI team tracks, often arise in answers derived from SemMedDB. 

Chris B., Andrew S., and Bill B. agreed to use the UI team’s list of mismatches to explore whether [PubTator](https://www.ncbi.nlm.nih.gov/research/pubtator/) and Text Miner can be leveraged to improve the specificity of SemMedDB answers.

**Comment by andrewsu** [comment]
I'm going to close this issue in favor of a new issue I just created at https://github.com/NCATSTranslator/Feedback/issues/413 that I think addresses the overarching NER issue here.
