### ISSUE TITLE
Apoaequorin MESH:C060014

### ISSUE THREAD

**Issue by codewarrior2000** [NCATSTranslator/Feedback#825]
Entering "Apoaequorin" as a search term isn't triggering an autocomplete in the UI. The [Name Lookup ](https://name-lookup.transltr.io/lookup?string=Apoaequorin)does have a listing for "Apoaequorin".

From [WebMD](https://www.webmd.com/healthy-aging/apoaequorin-what-to-know):
Apoaequorin is a "calcium-binding protein," and research links calcium to brain health and memory. An imbalance of calcium in brain nerve cells called neurons might play a role in aging the cells, destroying them, and disrupting signals between them.

But could swallowing calcium-binding protein based on jellyfish somehow benefit your human brain? Research suggests it doesn't. The apoaequorin in Prevagen likely gets digested by your [stomach](https://www.webmd.com/pain-management/guide/abdominal-pain-causes-treatments) before any of it stands a chance of reaching your brain.

<img width="869" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/1629353/d368c2dd-c1ef-40da-a569-6f3db7b12683">

**Comment by sstemann** [comment]
i believe the UI is filtering the lookup to small molecule, which is not on this CURIE.

**Comment by codewarrior2000** [comment]
@sstemann Thank you, I did not know about the filtering the lookup to small molecule. I'll just close this issue.
