### ISSUE TITLE
The page errors 
(https://ui.ci.transltr.io/demo/results?l=NGLY1&i=NCBIGene:55768&t=2&r=0&q=14948210-8b07-4c59-a1e0-67aa57fd93a3) 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#826]
## Steps to reproduce:
Select "What chemicals may decrease the activity of" Question 
then select 
NGLY1 as the gene
the page returns error

**Comment by sstemann** [comment]
If you use CI to test, please be aware it is unstable.  It's best to post this on Slack and not create a ticket.
