### ISSUE TITLE
UMLS identifier shown instead of the object name in the UI results.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#83]
## Steps to reproduce:
ui.transltr.io/results?q=759e2999-a340-47d1-b866-ae27b78c7e0a

## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20221216192257641215.jpeg)

**Comment by sierra-moxon** [comment]
from @Genomewide -
For the rows in question, where the Umls identifier is shown instead of the name, we have these symptoms:

- It has a description but no name.  
- SRI-name resolver returns an empty array.  
- Synonyms on ARAX has the name. 

posted by Andy

**Comment by sierra-moxon** [comment]
When viewing the results on ARAX, I find UMLS results coming from BTE, but the metadata for the node doesn't have many details:

![Image](https://user-images.githubusercontent.com/4561292/210650822-49f842f5-e861-4631-b3ab-2c8505dce47b.png)

If I look at the metadata on any of the edges connecting to the UMLS node, I see SEMMED in the provenance tracking:

![Image](https://user-images.githubusercontent.com/4561292/210651166-0993dcd0-6fc8-4323-b366-72a4c70e78e4.png)

**Comment by sierra-moxon** [comment]
@andrewsu - checking the status of the PR on your ticket above, it looks like the PR is ready to merge.   shall we close this issue here?

**Comment by andrewsu** [comment]
If it's okay with you, I'd prefer to keep it open until it's merged and deployed, just to make sure it doesn't fall through the cracks.

Noting also that this relates to https://github.com/NCATSTranslator/TranslatorArchitecture/pull/84, which would make it the ARS's responsibility to perform Node Normalization on responses from ARAs.  It seems reasonable that this step would also eventually include Name Resolution in the ARS, which would take precedence over the BTE-specific solution above.

**Comment by andrewsu** [comment]
PR was merged yesterday, which means it should be deployed to CI/dev soon...

**Comment by andrewsu** [comment]
PR deployed to prod, so closing this issue
