### ISSUE TITLE
Node Norm - Two lactases

### ISSUE THREAD

**Issue by cbizon** [NCATSTranslator/Feedback#833]
Running "What treats lactose intolerance" returns two answers with Lactase as the answer

One is CHEMBL2108505

The other is MESH:D043322

Should these be merged?

**Comment by gaurav** [comment]
I added a manual conflation to [fix this in NodeNorm CI](https://nodenorm.ci.transltr.io/1.5/get_normalized_nodes?curie=CHEMBL.COMPOUND%3ACHEMBL2108505&curie=MESH%3AD043322&conflate=true&drug_chemical_conflate=true&description=false&individual_types=false) when DrugChemical conflation is turned on (see https://github.com/TranslatorSRI/Babel/issues/309), so this is fixed for now (I'll close it here). I'm still tracking the question of why we don't conflate these entries together at https://github.com/TranslatorSRI/Babel/issues/131 -- we've noticed issues with cliquing around CHEMBL compounds before.
