### ISSUE TITLE
Node Missing Name, Edge Missing EPC in the UI

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#839]
MVP1 > Common Cold - i can't figure out what level the root cause is, so asking the UI to investigate first

CI:  https://ui.ci.transltr.io/main/results?l=Common%20Cold&i=MONDO:0005709&t=0&r=0&q=a263994d-ca75-4b81-896d-6c97da36c034

The blank node links out to https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:2386 
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/3c34ae20-cae6-47a5-989c-6df1303d0758)

The edge, when clicked in the UI is a blank screen:
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/a7dc4160-8ba5-447a-ad2f-4b6a202f3664)

Test:  https://ui.test.transltr.io/main/results?l=Common%20Cold&i=MONDO:0005709&t=0&r=0&q=ee127a65-9781-47da-a00d-c1c2ebf9271d

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/f4121af9-a984-4723-9159-dbdaa7a3036b)

**Comment by dnsmith124** [comment]
When checking out this result in Arax, Aragorn appears to return the name for that node `paracetamol`. The raw results the FE receives from the BE have `null` for both the result name and individual node's name. @gprice1129 could you take a look?

**Comment by gprice1129** [comment]
@dnsmith124 @sstemann I fixed this bug and it should be going into Test today.

**Comment by gprice1129** [comment]
The bug is fixed and in Test. There does not seem to be a name that comes back that is associated with this result but it now correctly shows the CURIE and the edge is clickable. Closing.
