### ISSUE TITLE
ChEBI role classification seems off

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#842]
What drugs may treat conditions related to seasonal allergic rhinitis?

https://ui.test.transltr.io/main/results?l=Seasonal%20Allergic%20Rhinitis&i=MONDO:0005324&t=0&r=0&q=6fff0b27-c22a-4b6b-982d-d8b03eb29421

Goserelin is classified as "anti-allergic agent" in the UI, using ChEBI role classification. I thought this was curious since Goserelin is a [gonadotropin releasing hormone agonist](https://en.wikipedia.org/wiki/Goserelin). Looking at the ChEBI entry for Goserelin, the only ontology term listed is “organic molecular entity”: https://www.ebi.ac.uk/chebi/searchId.do?chebiId=5523

Also searched the ChEBI anti-allergic compounds list (https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=50857) for CHEBI:5523; it's not present.

There are other results from the same query that are classified as anti-allergic that are also not on the list from ChEBI:
Epanolol, Acebutolol, Atazoline…..

**Comment by sstemann** [comment]
@gprice1129 @dnsmith124 my first thought is that this was some sort of annotation server down malfunction but i replicated the same test today and am seeing Goserline as an anti-allergic agent just like Kristina reported.  It doesnt look fleeting.  I don't see this annotation in the annotation server entry for CHEBI:5523.  Can you please let us know what's going on here?

https://ui.test.transltr.io/main/results?l=Seasonal%20Allergic%20Rhinitis&i=MONDO:0005324&t=0&r=0&q=133c7ae3-6bdc-4769-a758-2db8ea79d99c

https://biothings.ncats.io/annotator/CHEBI:5523

**Comment by Genomewide** [comment]
@gprice1129 remind me of the process when an ID is matched related to displaying the term or the parent of the term.

**Comment by gprice1129** [comment]
The fix for this is now in Test. I confirmed that the reported issue no longer happens. Going to close.
