### ISSUE TITLE
User Test Disclaimer Language, Design for Adding Arrow Directions to Result Graph View

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#847]

**Comment by sstemann** [comment]
I think this is a UI report, but scoring might be wrapped up in here somehow, hoping you two can take a look first?

**Comment by dnsmith124** [comment]
Two issues here per the title: 
1. User is misunderstanding the `Please note that refreshing...` disclaimer
2. User wants edge directionality to be visible in the graph view

For #1: It isn't clear from the disclaimer that results are being loaded in as they are provided. @Genomewide @reeserosedesign I think it could be worth user testing this language to determine if we can better explain what's actually happening under the hood, I think that's the user's confusion here. 

For #2: I think this is a reasonable request, @Genomewide @reeserosedesign can we prioritize a quick design for this?

**Comment by sierra-moxon** [comment]
@dnsmith124 - do you think this is a "Guppy" issue?

**Comment by dnsmith124** [comment]
@sierra-moxon that sounds appropriate given the user testing needs for the first portion of this ticket!

**Comment by sstemann** [comment]
Original Text of Ticket:  The footnote:     “Please note that refreshing this page may cause the order of answers to change. Results you have already viewed may also be updated with new data.”    What if I am still exploring the interesting results and had a network reset? Why can’t I get my page back? The results are sorted by score, hence the top results should always return, no matter what!For the graphview:    The edges are currently undirected. It might be nice to show the direction of edges between the nodes to avoid running back to the other view options for the direction

**Comment by dnsmith124** [comment]
Regarding the result refresh disclaimer issue: this text has been updated to be more clear in the recent UI facelift that is now live in Test. 

Regarding edge directionality in the graph view: the UI team is tracking this issue internally and plans to implement it as a feature.

**Comment by sstemann** [comment]
Disclaimer issue is in Prod with Fugu.

Edge directionality is now #933
