### ISSUE TITLE
"In Clinical Trials" as a Lookup and One-hop Support Graph

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#848]
It looks like we are using in clinical trials for both lookups and one-hop support graphs.  I _think_ that if there is a phase 3/4 clinical trials the correct predicate to use is Treats 

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/9b90443f-972b-424c-8cab-7d8078802387)

But we're seeing it both as a lookup (in this case by BTE https://ui.test.transltr.io/main/results?l=Sepsis&i=HP:0100806&t=0&r=0&q=1357341d-e369-463e-bb6a-6c17f7c3908d)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/7670e4f9-a5f6-4a7f-a282-0f203cbd20f7)
![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/5347e079-85e7-4a16-b136-97eb86dd7083)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/36d2581f-84ca-499e-9229-6d658d8bdd7f)

and as a support graph (in this case by Improving Agent https://ui.test.transltr.io/main/results?l=Crohn%27s%20Colitis&i=MONDO:0005532&t=0&r=0&q=3642d7b7-2879-4e61-99b2-6bbc78949ea4)

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/a4e1dc16-6ff1-4bc3-89c4-d14a98e09b58)

neither have the CT links directly

**Comment by sstemann** [comment]
adding this spawned from #846

**Comment by gglusman** [comment]
The original definition for when to make a 'treats' assertion was for "a trial that successfully passed Phase 3, or a Phase 4 trial". But, the clinical trials database has no such notion as "successfully passed", so in the Clinical Trials KG I'm relying only on presence of Phase 4 to make 'treats' assertions.

**Comment by sierra-moxon** [comment]
@gglusman - do you imagine these results from BTE also be subsumed by CTKP? 
@andrewsu - does "Guppy" tag make sense here in light of the TACT discussion this morning?

**Comment by gglusman** [comment]
I am rather confused by the evidence being displayed. The lookup-edge claim is that cefazolin is in clinical trials for sepsis, and there's a 'treats' edge together with it. All the evidence displayed, though, is about product approvals from DailyMed, not a single one is from clinicaltrials (yes, I did scroll down the list):
![image](https://github.com/user-attachments/assets/b0600e8f-d2cd-4368-9469-c290cea523d7)

This is a straight ingest from ChEMBL, so yes, this would be covered by CTKP. If there are phase 4 trials as suggested, there will be a 'treats' assertion already present in the KG.

**Comment by sierra-moxon** [comment]
Discussed CTKP in TACT today and there will be a push to harmonize CTKP ingests (vs. Chembl/others) in the next sprint.  
@andrewsu - maybe the only change with that would be that we'd see the "in clinical trials" edge from CTKP as a support to a "treats" assertion from BTE.  (I know we're planning on hearing from CQS folks next architecture meeting - another reason to move this to hammerhead).

**Comment by andrewsu** [comment]
Looks like the desired behavior is being observed (at least on test):
* UI: https://ui.test.transltr.io/results?l=Sepsis&i=HP:0100806&t=0&r=0&q=83d93e4a-2a96-447c-af63-0211cb8f55d0
![image](https://github.com/user-attachments/assets/fd346329-a3aa-46e9-abb1-ca26bb345590)

* ARAX UI: https://arax.ci.transltr.io/?r=a0a10664-0386-427f-a0c5-a99194cabbc5
![image](https://github.com/user-attachments/assets/63fc7a5b-d3d2-438e-ba4f-ba20ee2b4f77)
support graph: 
![image](https://github.com/user-attachments/assets/5d9527f6-bd06-427f-af93-fe3857555100)

I think this satisfies the "ask" of BTE, but let us know if not!

**Comment by gglusman** [comment]
@andrewsu That 'in_clinical_trials_for' support edge comes from ChEMBL, not from CTKP. I'm not sure this answers Sierra's ask.

**Comment by andrewsu** [comment]
@gglusman I interpreted this issue as _primarily_ about the structure of the `treats` and `in_clinical_trials_for` edges.  But yes, you're right, the source of these edges (CTKP vs chembl) is also mentioned here. Is the Automat CTKP already available in the ITRB environment?  It looks like the [smartAPI annotation](https://smart-api.info/registry?q=e51073371d7049b9643e1edbdd61bcbd) only shows a non-ITRB dev instance.  If that's right, I suggest we close this issue and leave the data source swap for a different issue, synced with the next sprint.

**Comment by gglusman** [comment]
The Plover CTKP will be available in ITRB/CI next Friday.

**Comment by andrewsu** [comment]
Just so we can separate the two topics here, I'm going to close this issue that is _primarily_ about the structure of results, and I created a [new issue](https://github.com/biothings/biothings_explorer/issues/861) to track the swap of data sources for `in_clinical_trials_for` edges. Please let me know if that doesn't fully address the concerns!
