### ISSUE TITLE
Update KG2 for KL/AT (Fugu), Unsecret Update latest KG2 (Guppy)

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#850]
Could be minor but is there another option instead of "UNKNOWN"?

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/59ae949f-7d3d-4636-9cdd-4c2b5a7b75d1)

https://ui.test.transltr.io/main/results?l=Metaphyseal%20Chondrodysplasia,%20Jansen%20Type&i=MONDO:0007982&t=0&r=0&q=0351d580-45b7-4c7b-8cb1-c56a798f7d66

@mbrush tagging you for this DISEASES source KL/AT tagging.  I think it's ARAX > KG2 > Diseases

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/b18ea3d3-d817-4527-b9bd-ad55315d501d)

**Comment by dnsmith124** [comment]
In the case of this edge the UI's FE receives a knowledge level of "unknown" for this source, tagging @gprice1129 for input on how to proceed.

**Comment by sierra-moxon** [comment]
I believe @saramsey and Erica are working on a new release of RTX-KG2 with KL/AT filled in that should be released in Fugu (Sprint 4).

**Comment by gprice1129** [comment]
@mbrush this is KL mixed, please advise.

**Comment by saramsey** [comment]
See these issues to track our team's progress toward providing KL/AT in the RTX-KG2 KP:
https://github.com/RTXteam/RTX-KG2/issues/358
https://github.com/RTXteam/RTX/issues/2319

My understanding from @ecwood is that the code updates for providing KL/AT edge attributes in the KG2pre graph build are already completed. Now the downstream work (@amykglen and @sundareswarpullela can comment) to provide those edge attributes in KG2c and in responses returned by the RTX-KG2 KP, is happening. We are aiming to roll this out in Sprint 4 (7/26 release-to-test deadline).

**Comment by saramsey** [comment]
This is fixed in CI, and the fix should be in the updated RTX-KG2 that is slated to be deployed to ITRB TEST early next week. See #818 for more details about that deployment.

**Comment by sstemann** [comment]
this is still in the UI in Fugu, my guess is that Unsecret needs to ingest the latest KG2 with these changes, but I can't see the support graphs in the ARAX GUI anymore.  

Unsecret Only Results
![image](https://github.com/user-attachments/assets/69ac0d39-f683-435b-b2cd-42cd48027acb)

Disease Edges
![image](https://github.com/user-attachments/assets/d69376d9-4dca-4483-92b3-38251a630a93)

In this specific query, ARAX does not have results.

https://ui.test.transltr.io/main/results?l=Metaphyseal%20Chondrodysplasia,%20Jansen%20Type&i=MONDO:0007982&t=0&r=0&q=6cc2f6d5-75b4-4f1d-8eac-34d9f61c6477

![image](https://github.com/user-attachments/assets/b841029d-2641-419a-a189-11778231784b)

It looks fixed for ARAX
https://ui.test.transltr.io/main/results?l=Aceruloplasminemia&i=MONDO:0011426&t=0&r=0&q=0e83e4a4-0af7-4b6d-8287-53fecd44b8f2

![image](https://github.com/user-attachments/assets/4db81ae4-6e92-4fb2-9a00-9c5c42ba36aa)

![image](https://github.com/user-attachments/assets/3c81135e-5fa0-46f4-8db9-55449170d04b)

**Comment by kaiwenho** [comment]
> this is still in the UI in Fugu, my guess is that Unsecret needs to ingest the latest KG2 with these changes
Yes. Unsecret will have this solved by the end of the current sprint (Guppy) via importing KGs that contain information of KL and AT.

**Comment by kaiwenho** [comment]
> this is still in the UI in Fugu, my guess is that Unsecret needs to ingest the latest KG2 with these changes
Yes. Unsecret will have this solved by the end of the current sprint (Guppy) via importing KGs that contain information of KL and AT.

Unsecret has updated the KGs in CI. The AT and KL for each edges (inferred or component) can be seen.

**Comment by sierra-moxon** [comment]
closing as complete!
