### ISSUE TITLE
Inferred Edge Should Match Fully Qualified Query Graph Edge - MVP2

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#855]
I dont fully understand why the predicates differ so frequently, when I read them in the UI, I'm not sure I understand how substantially different to the reasoned answer 

"Tamoxifen Causes Decreased Activity Or Abundance Of Arid1a" vs "Tamoxifen Affects Decreased Activity Or Abundance Of Arid1a"

then the more general "Tamoxifen Affects Arid1a"

<img width="629" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/79a8f1e9-dd85-4091-aa02-eb0df7ef4162">

https://ui.test.transltr.io/main/results?l=ARID1A%20(Human)&i=NCBIGene:8289&t=2&r=0&q=1d650508-5292-4faf-a52c-21954c89fb36

When I look at it in the ARAX GUI
**ARAGORN** 
- Lookup via TMKP
<img width="872" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/314dae48-f738-4037-a474-2fe009596f74">

- Inferred via Prediction - Affects Decreased Activity Or Abundance Of
<img width="857" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/717d0384-63ea-4129-aa08-bf355fb0bc53">

The support graph of the prediction - looks to be a TMKP lookup
<img width="857" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/059edc0f-817c-4cdd-af46-6aeebd70e15f">

**ARAX**
- lookup via TMKP
<img width="866" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/5cf33379-dbc0-4dd8-b913-4872b1d90749">

BTE
- lookup via TMKP
<img width="863" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/741f0a5e-9d7f-4d06-93d8-5be7f8ea7fdb">

- the other edge is inferred, prediction Affects
<img width="864" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/7a47337c-0c5d-4666-a2dc-98262ae4497e">

all but one of these SG edges are TMKP
<img width="871" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/beda6588-d2f0-4953-9bea-b829689b345d">

Unsecret
- lookup via TMKP
<img width="861" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/41366bbe-7094-4347-81fb-b09c03c49794">

- Inferred 1 - Causes Decreased Activity Or Abundance Of
<img width="865" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/1d495ae0-7d28-4e44-8a0d-7667ec36cc5d">

- Inferred 2 - Causes Decreased Activity Or Abundance Of
<img width="857" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/e4ce49f3-cea3-4d25-86c2-82da55b04df1">

**Comment by sstemann** [comment]
@sierra-moxon i'm not sure if any one thing is actually wrong here, but do you have guidance?

**Comment by sierra-moxon** [comment]
I believe these are all the same result and need to be merged. 

How do we get to a merge? 
- @cbizon - do you know why the inferred edges here do not have `qualified_predicate: biolink:causes`?

In the back of my mind, it seems a little odd that we have inferred edges that seem to be just reiterating the lookup edges.  Am I misunderstanding these results?

**Comment by sstemann** [comment]
i believe ARS treats these edges as unique and doesnt merge them but defer to @MarkDWilliams @gprice1129

**Comment by gprice1129** [comment]
The predicate variation (especially `Decreased Activity Or Abundance Of`) seems to be a mistake from the ARA/KP. We will look into why the edges in the first screenshot are not being compressed.

**Comment by dnsmith124** [comment]
After reviewing the pk again in the UI the edges in the first screenshot are now being properly compressed

**Comment by sierra-moxon** [comment]
from TAQA:
lets try this in CI and see if it works - we think  BTE was fixed to use the qualified_predicate in the query.  e.g. we think BTE, Aragorn will respond to a query with qualified_predicate (but we need to test via ARAX and make sure no ARAs are always left out). 

then we need the UI to pass the qualified_predicate to the ARs.

**Comment by colleenXu** [comment]
For BTE:
* as described [here](https://github.com/NCATSTranslator/Feedback/issues/744#issuecomment-2237684309), BTE should now be able to accept queries with qualified_predicate set. 
* we are actively working on [setting the inferred edge qualifier set](https://github.com/biothings/biothings_explorer/issues/834) and [handling "direct" edges](https://github.com/biothings/biothings_explorer/issues/839).

**Comment by sierra-moxon** [comment]
retested on CI today, far fewer predicates, more merging. did not spend too long evaluating results but the original issue to me, is fixed.
