### ISSUE TITLE
In the header in the UI, it seems a little odd that the "Send Feedback" and "Help" buttons take the user to a new tab, but the rest of the buttons don't.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#857]

**Comment by dnsmith124** [comment]
I don't think there's anything inherently wrong with the interaction itself, it's fairly common in nav menus for some links to open in new tabs and others not. 

@reeserosedesign could we look into possibly updating the links to provide some sort of indication that a link may be opened in a new tab? I think that would resolve this issue.

**Comment by Genomewide** [comment]
yeah, that would be fine. The feedback button works that way based on requests from users.  An indication like the box with an arrow give a waring though and keep the requested function.

**Comment by gprice1129** [comment]
We are going to close this until we get more feedback from users that this is unexpected behavior.
