### ISSUE TITLE
There is a column header for "evidence", but then every row also says "Evidence". Could we remove that from each row?

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#858]

**Comment by dnsmith124** [comment]
We have a visual overhaul planned for the upcoming sprint that includes this requested change.

**Comment by sstemann** [comment]
i see this change in CI but not in test with 8/12 update

![image](https://github.com/user-attachments/assets/83a16d3a-194c-4249-8cf1-33a8180930b1)

**Comment by sstemann** [comment]
its in test!  https://ui.test.transltr.io/results?l=Cystic%20Fibrosis&i=MONDO:0009061&t=0&r=0&q=fd47fed3-4010-4a7d-8171-407ccc040bcc

![image](https://github.com/user-attachments/assets/35d847d1-0de1-4376-88dc-0514e41954bc)

**Comment by dnsmith124** [comment]
As @sstemann confirmed this is live in Test, closing!
