### ISSUE TITLE
Add tooltip to User Preferences page > Graph Visibility > Sometimes

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#859]

**Comment by dnsmith124** [comment]
"Sometimes" means that when a result has more than just a single 1 hop path, the graph will show, otherwise it will not. A tooltip for this preference is in order to explain this!

**Comment by sierra-moxon** [comment]
from TAQA: overhaul of Fugu tooltips is coming.

**Comment by sstemann** [comment]
OBE this option is gone, since now the Graphs and Paths are tabbed.
