### ISSUE TITLE
Autocomplete in the browser did not recover from a lost connection/timeout/failure from the name resolver

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#86]
## Steps to reproduce:
type-ahead service went down, and was unable to search. The error message should have told me the type-ahead service was down, but instead said "No disease selected, please select a valid disease." when I entered "atherosclerosis" and pressed "Search". 

Actually, https://name-resolution-sri.renci.org/lookup?string=atherosclerosis&offset=0&limit=30 correctly returned {"MONDO:0005311":["atherosclerosis","Atherosclerosis","ATHEROSCLEROSIS","atherosclerosis","AS - Atherosclerosis","Atherosclerosis, NOS"...
But https://nodenorm.transltr.io/1.3/get_normalized_nodes gave 503 with a payload of 

{"curies":["MONDO:0005311","MONDO:0002277","MONDO:0002275","UMLS:C0004155","UMLS:C0455407","MONDO:0001876","MONDO:0000980","UMLS:C0577631","UMLS:C0860143","UMLS:C3650186","MONDO:0021661","MONDO:0005010","MONDO:0006694","UMLS:C3687009","UMLS:C3650145","HP:0004416","UMLS:C0852950","UMLS:C5400433","UMLS:C5567242","MONDO:0030702","UMLS:C1328405","UMLS:C0729733","UMLS:C4524149","UMLS:C2883029","UMLS:C0856765","UMLS:C4759301","HP:0004943","UMLS:C1736144","UMLS:C0860140","UMLS:C0751007"],"conflate":true}

**Comment by sierra-moxon** [comment]
Most of the content of this is duplicated in #42 but I also wanted to note the timeout issue - does the UI autocomplete state get refreshed on each submission of a query, or is there some additional complexity here that should be investigated?  I haven't been able to reproduce myself.  I can close it for now unless someone else wants to try and reproduce?

**Comment by dnsmith124** [comment]
Regarding the error message, I've added a more informative error message should the node normalizer or name resolver go down and result in the autocomplete not working, but I'm hesitant to tell the end user directly that one of the services itself is down for a variety of reasons. For now a more informed user can check the browser console, which should show any errors (such as the NN throwing a 503). 

To answer your question @sierra-moxon, the UI autocomplete is refreshed when a term is selected and when a user types into the search box, so there's no additional complexity that needs to be investigated in my opinion. 

I think this is more an issue of supplying the user with a more specific error message when the autocomplete isn't working or doesn't return results, which will be resolved in an upcoming build. Feel free to close this one out!

**Comment by sierra-moxon** [comment]
thanks @dnsmith124  :)
