### ISSUE TITLE
I was not able to login and received.

UnauthorizedError
401 Authentication session not found

As far as I can tell I a have authorized the OAuth source in my GitHub account.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#860]
## Steps to reproduce:
Attempt login using GitHub OAuth

**Comment by sierra-moxon** [comment]
@dnsmith124 - 🤞 this is a user that you already have contact with?  I am able to authenticate with google, but have not tried with GH.

**Comment by sstemann** [comment]
this was resolved via UNA fixes in CI, Test and Prod and confirmed over email.
