### ISSUE TITLE
UI error when loading the final results

### ISSUE THREAD

**Issue by jdr0887** [NCATSTranslator/Feedback#861]
![Screenshot_2024-07-12_13-45-55](https://github.com/user-attachments/assets/86332807-6a55-4247-ba98-ed8ab0d9a19c)

The UI works find up until the processing is all done & then I click the final loading results button & then I see "Unexpected Application Error!"

This is on Ubuntu with Firefox.

**Comment by gprice1129** [comment]
@jdr0887 what environment is this in?

**Comment by gprice1129** [comment]
Was due to the UI not being on the latest version of the infores catalog which was causing issues with CQS tag generation. Fixed in CI, closing.
