### ISSUE TITLE
UI - "Unexpected Application Error"

### ISSUE THREAD

**Issue by bill-baumgartner** [NCATSTranslator/Feedback#862]
**Environment:** CI
**Query:** What treats Ehlers-danlos Syndrome?

**Description:**
The query was running. It had returned some results. I switched away from the tab for a while to wait for more results. When I returned, I clicked on "Load more results" and the error message below was displayed. The error continued to be displayed when refreshing the page.

**How to reproduce the issue:**
I was able to reproduce the issue by running the query again. When I clicked on "Load more results" the same error appears. 

* **First attempt:** https://ui.ci.transltr.io/main/results?l=Ehlers-danlos%20Syndrome&i=MONDO:0020066&t=0&r=0&q=5a93daec-4113-4a9a-8cc8-94f411a0dee8
* **Second attempt:** https://ui.ci.transltr.io/main/results?l=Ehlers-danlos%20Syndrome&i=MONDO:0020066&t=0&r=0&q=d53cb0ae-fcd2-4c85-9736-fea747486453

<img width="1474" alt="Screen Shot 2024-07-12 at 12 50 56 PM" src="https://github.com/user-attachments/assets/ccd3c7ee-6d90-496f-bbab-2a0989f7ac8b">

**Comment by gprice1129** [comment]
Was due to the UI not being on the latest version of the infores catalog which was causing issues with CQS tag generation. Fixed in CI, closing.
