### ISSUE TITLE
All results coming from BioThings Explorer are showing no evidence/provenance other than BTE itself.  We should be seeing deeper EPC than this.
 - Tyler Beck

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#864]
## Steps to reproduce:
Search for: What drugs may treat conditions related to: Leukoencephalopathy With Brain Stem And Spinal Cord Involvement-high Lactate Syndrome (LBSL)

## Screenshots:
![screenshot](https://raw.githubusercontent.com/TranslatorSRI/IssueScreenshots/main/screenshot_20240716151237681762.jpeg)

**Comment by sierra-moxon** [comment]
closing as complete.
