### ISSUE TITLE
Should Semmed Treats One-Hops be Lookup Paths in the UI? Direct Paths in the ARA?

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#870]
Test UI (Eel) > MVP1 > Common Cold

https://ui.test.transltr.io/main/results?l=Common%20Cold&i=MONDO:0005709&t=0&r=0&q=44402a77-4114-4ac4-8438-dbd39a8b97aa

https://arax.ncats.io/?r=44402a77-4114-4ac4-8438-dbd39a8b97aa

PK:  44402a77-4114-4ac4-8438-dbd39a8b97aa

Look at any of these results:
Zinc Lozenge 
Nasal Decongestants
Decongestants
Pseudoephedrine 

![image](https://github.com/user-attachments/assets/6c1c06c7-face-4bf2-8381-577e0f8d520d)

![image](https://github.com/user-attachments/assets/08e60998-7002-4846-a30e-c073f019dbbc)

![image](https://github.com/user-attachments/assets/a72a4cce-2bf3-4785-b9da-848c6f63158c)

In the ARAX GUI you can see these direct paths with only Semmed EPC from:

ARAGORN
![image](https://github.com/user-attachments/assets/3abcb3e0-ad2c-4144-a957-527394cff379)

ARAX
![image](https://github.com/user-attachments/assets/167aafde-b8f4-4f72-8802-bdea0878668c)

Unsecret 
![image](https://github.com/user-attachments/assets/216c1bf1-11dd-4983-8df8-e57733ff1094)

BTE has 0 results for this query

These examples are not in Improve.

**Comment by sstemann** [comment]
related to #854

**Comment by cbizon** [comment]
The TMKP edge looks like it's coming from BTE:
![image](https://github.com/user-attachments/assets/6ab56ef4-81a2-43e4-92ea-c7b53c3df2c0)


I think that instead of having this edge bound directly to the query edge, there should be an inferred "treats" edge (matching the input query predicate) and this edge should be support for that edge.

**Comment by cbizon** [comment]
I think that this is a duplicate of #871 and can probably be closed as such

**Comment by cbizon** [comment]
( I dont see a duplicate tag )

**Comment by saramsey** [comment]
closing since this is a dup of #871

**Comment by sstemann** [comment]
this one is about if its a Lookup or an inferred path. #871 is about which of the treats predicates to use.

**Comment by colleenXu** [comment]
Do I need to be assigned to this issue? It looks like some comments may have been deleted, and BTE isn't actually involved in this issue (no response).

**Comment by cbizon** [comment]
Sorry @colleenXu my fault

**Comment by sstemann** [comment]
seems like the answer here was yes and it seems pretty consistent

https://ui.test.transltr.io/demo/results?l=Common%20Cold&i=MONDO:0005709&t=0&r=0&q=c5aa86ad-8d24-4cf2-a01a-36aaa00e2224

**Comment by sstemann** [comment]
looks resolved on Prod
