### ISSUE TITLE
MVP1 Inferred Edges Return with Semmed edge as a support graph 

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#871]
Test UI > MVP1 > Cystic FIbrosis

https://ui.test.transltr.io/main/results?l=Cystic%20Fibrosis&i=MONDO:0009061&t=0&r=0&q=01f390c0-0d65-4dcc-a6ea-4b1749ec10b2

Find the result Iron
![image](https://github.com/user-attachments/assets/ef6a9c56-e862-495b-b6fd-4805dc3d5ee7)

![image](https://github.com/user-attachments/assets/f98fe076-c954-41a9-9a1f-f6b1122f278a)

![image](https://github.com/user-attachments/assets/0280e7f8-3e83-4a7f-8259-d6069b398145)

![image](https://github.com/user-attachments/assets/3eaf4569-7956-4e71-a643-52b5234ad368)

![image](https://github.com/user-attachments/assets/7290556d-9e82-4381-ac74-0b0138aa0d25)

ARAX - Treats - no support graph
![image](https://github.com/user-attachments/assets/265faccd-1b6c-4b20-beab-2d7c2de153d8)

BTE - Treats_or_applied_or_studied_to_treat - no support graph
![image](https://github.com/user-attachments/assets/a50c8dbb-743c-41f9-835a-5d04f324115e)

Unsecret - Treats - no support graph
![image](https://github.com/user-attachments/assets/57bf0e8c-9fed-4fc0-82d0-f7fe8405f524)

ARAGORN had 0 results, Iron is not in the Improve Set

**Comment by cbizon** [comment]
The predicate for the semmed edge itself should be "treats or applied or studied to treat".   I think that this has not been done in RTX KG2, and that is causing the error in both ARAX and UnSecret.

For BTE the problem is different - rather than returning the (correct) semmed edge as a direct lookup bound to the query graph edge, it should be returning an inferred treats edge with the semmed edge as a support graph.

**Comment by saramsey** [comment]
This should be fixed in Sprint 4,
![Screenshot 2024-07-19 at 1 02 56 PM](https://github.com/user-attachments/assets/21d41904-89f1-49e7-9927-295a5a76338f)

tagging @ecwood who can confirm.

**Comment by saramsey** [comment]
For this to be fixed in ITRB TEST presently, it would have to have been in the Eel release; but there was (AFAIK) no new release of RTX-KG2 in the Eel release, so we have to wait for Fugu, I think.

**Comment by sstemann** [comment]
there is an Eel release of KG2 in Test versioned v2024.06025.1-test.  But since this is occurring in Test, looks like it still needs to go to Eel

**Comment by saramsey** [comment]
Hi @sstemann yes, this fix made it into Fugu, but not Eel. Here you can see the fix in Fugu:

![Screenshot 2024-07-28 at 2 57 24 PM](https://github.com/user-attachments/assets/02f646d5-0504-4daa-a099-cad116d8f9ad)

**Comment by saramsey** [comment]
We are not able to patch Eel at this point, as far as I know.

**Comment by saramsey** [comment]
> there is an Eel release of KG2 in Test versioned v2024.06025.1-test. But since this is occurring in Test, looks like it still needs to go to Eel

What I meant to convey is that in the Eel release of Translator, we were not able to put out a new version of RTX-KG2. Thus, the "treats" fix (for the RTX-KG2 KP) is in Fugu, not in Eel.

**Comment by sstemann** [comment]
these two edges for the same direct path have the same 11 pubs from Semmed

is this by design?
![image](https://github.com/user-attachments/assets/8b6dc4a2-33fd-4cfe-8e5c-dfb892ab0b68)

Free text search > Iron

https://ui.test.transltr.io/main/results?l=Cystic%20Fibrosis&i=MONDO:0009061&t=0&r=0&q=9c685631-2386-4ade-a97a-8f939e6b2f54

ARAX says Treats with the 11 pubs
![image](https://github.com/user-attachments/assets/663c612a-48e1-4947-9174-9668f55b72d6)

BTE says treats_or_applied_or_studied_to_treat with the same 11 pubs

![image](https://github.com/user-attachments/assets/3466903d-8cb4-42e9-88b8-87ea6d6aac2a)

**Comment by sstemann** [comment]
i'm not sure who said Guppy and who said Fugu @saramsey @colleenXu

**Comment by colleenXu** [comment]
(1) It appears that both edges have the same primary knowledge source (semmeddb), which would explain the same data. Different formatting/predicates may be due to the aggregator source (rtx-kg2 vs biothings/service provider/bte). 

(2) It looks like Sierra assigned those labels. I don't recall saying anything about what release our team's fix would be in (Jackson brought this up today in our bte-itrb Slack channel).

**Comment by sierra-moxon** [comment]
this comment is how the labels were assigned: "there is an Eel release of KG2 in Test versioned v2024.06025.1-test. But since this is occurring in Test, looks like it still needs to go to Eel"

**Comment by sstemann** [comment]
@colleenXu thank you for the review and update, any plan for BTE to change the format of the predicates?

**Comment by colleenXu** [comment]
@sstemann 

There is now a [fix](https://github.com/biothings/biothings_explorer/issues/839#issuecomment-2290864075) deployed to CI. BTE should now return "an inferred treats edge with the semmed edge as a support graph" - [which is what Chris Bizon recommended](https://github.com/NCATSTranslator/Feedback/issues/871#issuecomment-2240027490).

**Comment by sstemann** [comment]
looks resolved in Prod
![image](https://github.com/user-attachments/assets/0bd1ac38-369b-4a57-af31-23fc1c328853)
