### ISSUE TITLE
Inferred Edge Should Match Query Graph Edge - MVP1

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#872]
UI Test > MVP1 > Cystic Fibrosis
https://ui.test.transltr.io/main/results?l=Cystic%20Fibrosis&i=MONDO:0009061&t=0&r=0&q=01f390c0-0d65-4dcc-a6ea-4b1749ec10b2

Look for Result Ritonavir 
![image](https://github.com/user-attachments/assets/23c90425-e6b4-47dc-8d50-37b306504110)

![image](https://github.com/user-attachments/assets/f89ee899-58ff-46ca-878b-ca9df9e7af1c)

![image](https://github.com/user-attachments/assets/bf98726f-71f7-4a6d-840c-15ea2c891973)

ARAX - Treats Or Applied Or Studied To Treat - Support Graph
![image](https://github.com/user-attachments/assets/19192709-5740-4215-b3ef-bd5a295d69a1)

BTE - Treats Or Applied Or Studied To Treat - DIrect
![image](https://github.com/user-attachments/assets/b24c8b27-a39c-4f55-a313-f756e9a73ea3)

ARAGORN responded with 0 results, Ritonavir was not in the results from Improve or Unsecret.

**Comment by sstemann** [comment]
related to #871 and #870

**Comment by cbizon** [comment]
It looks to me from the ARAX interface that both ARAX and BTE are returning an edge with a "treats or applied or ..." rather than the requested "treats" edge.  I think that if these don't match then there's an inference and this should be shown as a support graph rather than the top level result.

**Comment by sstemann** [comment]
@cbizon i included you as architecture because I wasn't sure where this decision about treats/inferred lives.

**Comment by cbizon** [comment]
Oh, gotcha, thanks

**Comment by sierra-moxon** [comment]
closing as complete with Colleen's comment and Chris's comment about splitting the other work into a different ticket.
also retested on CI b/c I wasn't sure if TEST was ready for testing yet, and CI is no longer showing the longer predicate in the inferred area, just the support path area.

**Comment by sstemann** [comment]
this is resolved in Prod, Fugu
