### ISSUE TITLE
Anabolic Agents showing up as a result for what drugs may treat Postmenopausal Osteoporosis

### ISSUE THREAD

**Issue by kvnthomas98** [NCATSTranslator/Feedback#878]
In the `ui.test.transltr.io` system, 
I ran a test query "What drugs may treat conditions related to Postmenopausal Osteoporosis?.

Here are the [results](https://ui.test.transltr.io/main/results?l=Postmenopausal%20Osteoporosis&i=MONDO:0008159&t=0&r=0&q=826bb654-01b7-4292-a30f-33e91c1ddbe2rl)

One of the top results is `anabolic agents`. Is this too general of a result?

**Comment by sstemann** [comment]
this is in Prod with Fugu
