### ISSUE TITLE
predicates from https://drug-interactions.medicine.iu.edu/Main-Table.aspx may be misinterpreted?

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#88]
from @Genomewide:

I use P450 as a test for genes that have a large number of interactions.  I found a set of edges whose predicates are mislabeled.  They point back to this site https://drug-interactions.medicine.iu.edu/MainTable.aspx and publications. I have at least one example where the site [Translator UI] calls ethanol as "biolink:increases_activity_of" when the site [ https://drug-interactions.medicine.iu.edu/Main-Table.aspx] says it is a substrate.

I have also seen where "interacts with" get misinterpreted because it is a drug-drug interaction where one drug causes another to be metabolized differently.

Here is the data from one of the examples (as I condensed it)

edgeKey	e00
edgeId	ea7522d9bbaf
agent	ara-aragorn
object	NCBIGene:1571
predicate	biolink:increases_activity_of
subject	PUBCHEM.COMPOUND:702
subjectName	ethanol
subjectCats	["biolink:SmallMolecule"]
subjectCat	biolink:SmallMolecule
objectName	
objectCats	["biolink:Protein"]
objectCat	biolink:Protein
ResultGroup	0-ara-aragorn
KSagg	["infores:molepro";"infores:molepro"]
KSaggAll	["infores:aragorn";"infores:molepro";"infores:molepro"]
KS	[""]
KSprimary	["infores:drugbank"]
KSoriginal	[""]
pubID	["https://drug-interactions.medicine.iu.edu/Main-Table.aspx";"PMID:10872641";"PMID:11996015";"PMID:7802633";"PMID:11996013";"PMID:12707490";"PMID:8659683"]

**Comment by sierra-moxon** [comment]
@sandrine-m @vdancik - the provenance in this example seems to point to MolePro, though I am not sure if the data is coming from Drugbank or https://drug-interactions.medicine.iu.edu/Main-Table.aspx.  I can try to recreate this query in ARAX to give more information, but tagging you both here in case it is immediately familiar to you. :)

**Comment by sierra-moxon** [comment]
from TAQA: likely DrugBank will be discontinued in the next version of MolePro.  It's likely that MolePro is the last KP that has this data.  25% of the drug relations will be lost (drug-gene relationships) across Translator.  Sarah S will bring it up on the next internal call to see if NCATs can advocate for a license. 

Andy will post an ARS identifier, Vlado doesn't think we have drug-drug interactions from DrugBank in MolePro

**Comment by vdancik** [comment]
@sierra-moxon @Genomewide Looking at DrugBank's website  https://go.drugbank.com/drugs/DB00898#enzymes, enzyme # 6, (Cytochrome P450 2E1) it appears that MolePro correctly represents information as `PUBCHEM.COMPOUND:702 increases_activity_of NCBIGene:1571` since DrugBank annotate action as `inducer`.
