### ISSUE TITLE
"Basis" showing up as a response for "What drugs may treat T-wave Alternans?"

### ISSUE THREAD

**Issue by sundareswarpullela** [NCATSTranslator/Feedback#881]
Upon running the query: What drugs may treat T-wave Alternans? 

`Basis` which is not a drug, shows up as the top treatment with a score of 5.0. The result is from SEMMEDDB. 

![image](https://github.com/user-attachments/assets/3beecd45-b50c-4cb4-b350-63e6d38d3496)

Link to responses: https://ui.test.transltr.io/main/results?l=T-wave%20Alternans&i=HP:0012266&t=0&r=0&q=4d9b00ad-8627-43c7-a353-8d961aeef5ca

**Comment by andrewsu** [comment]
Just tagging related issues https://github.com/NCATSTranslator/Feedback/issues/730 and https://github.com/NCATSTranslator/Blocklists/issues/43

**Comment by sierra-moxon** [comment]
closing as duplicated (this ticket will be linked to #730 so that we keep track of the nice testing @sundareswarpullela! - thank you for doing this. I also added you to that ticket so you can follow progress).
