### ISSUE TITLE
Bug: MVP2 Chemical Selector is restricted to the first result only

### ISSUE THREAD

**Issue by sandrine-muller-research** [NCATSTranslator/Feedback#885]
Original:  Examples - search Potassium Ion or Potassium chloride (which is a treatment for hypokalemia)

see @andrewsu 's comment [here](https://github.com/NCATSTranslator/Feedback/issues/750#issuecomment-2253165494)
It looks like node norm makes the distinction. But [NameRes does not output anything](https://name-resolution-sri.renci.org/reverse_lookup?curies=PUBCHEM.COMPOUND%3A813). @gaurav do you have any clue of why this is happening?

**Comment by gaurav** [comment]
Hi Sandrine! This is because of two things:
1. NameRes only provides `/reverse_lookup` for the preferred IDs of cliques. Since [the preferred clique](https://nodenormalization-sri.renci.org/get_normalized_nodes?curie=PUBCHEM.COMPOUND:813&drug_chemical_conflate=true) with PUBCHEM.COMPOUND:813 is CHEBI:29103, you [need to use that when querying NameRes](https://name-resolution-sri.renci.org/reverse_lookup?curies=CHEBI:29103).
2. When generating the NameRes index, we keep gene-protein conflation off but we turn drug-chemical conflation on (because otherwise autocomplete ends up with a gazillion different variants of "paracetamol"), so yes, in this case NodeNorm and NameRes disagree on the clique. If it would be useful to do NameRes searches with particular conflations turned on or off, please let us know at https://github.com/TranslatorSRI/NameResolution/issues/56 -- but it's unlikely we'd be able to fit it into this year's round of development unless it was _very_ urgent.

**Comment by sandrine-muller-research** [comment]
Thank you @gaurav ! Not very urgent indeed, I am closing.

**Comment by sstemann** [comment]
@sandrine-muller-research did you intend to Close this ticket?

**Comment by sandrine-muller-research** [comment]
@sstemann yes, my understanding was that this is low priority and it will be a "won't fix" type of issue? I am unclear of what "won't fix" issues should become.

**Comment by sierra-moxon** [comment]
from TAQA:
- with chemical conflation turned on, we won't have ions to search by?
  - multiple ions in name lookup and still findable
  - potassium as an ion vs a cation 
  - we have one in NN but not the other
  - when we do chemical searches, we only show the top result (name lookup returns multiple results, in the dropdown we only get to select the top result) 
  - we could investigate why only the top result is showing up in the UI 
- Na, K, etc, none can be returned
- we do want to search by ions
- these are too specific -- potassium ion vs. potassium salt -- we need it to be generalized here in the search or the result. 
- when we search for sodium we only have sodium tetradecyl sulfate

we should look at why name lookup will only return one result for chemicals.

**Comment by gaurav** [comment]
- [ ] We might also want to conflate e.g. "Potassium cation" with "Potassium" so that there are fewer non-specific results.

**Comment by dnsmith124** [comment]
This is the result of a UI bug, which has been resolved in CI and will be deployed to Test early this week. I'll update the ticket once the fix is live in Test

**Comment by sandrine-muller-research** [comment]
Thank you @dnsmith124 !

**Comment by sstemann** [comment]
i'm not sure if this is the same behavior in CI, but based on yesterday's UI deployment to test, I retested this 8/13 1130AM ET

Left is the Test drop-down and right is the Prod drop-down

![image](https://github.com/user-attachments/assets/badfd96a-60d7-4f47-a267-87f9a56d8160)

so the choice (and many other related potassium choices) is there in the drop-down

but ARAs all return 0

https://ui.test.transltr.io/main/results?l=Potassium%20Ion&i=CHEMBL.COMPOUND:CHEMBL1233793&t=3&r=0&q=68c47bcc-28d3-4151-8a7d-55e5ee9285d2

![image](https://github.com/user-attachments/assets/89bf2b33-c11e-4bfa-9372-5e2a2f0e4651)

one of my questions is - do ARAs support Chembl CURIEs here?  (in the original template the input CURIE type was not specified but all of the examples are pubchem https://github.com/NCATSTranslator/TranslatorArchitecture/issues/81 - and in potassium we use Chebi)

if the CURIE source doesn't matter to ARAs, is it worthwhile to have all of these forms of potassium in the dropdown?

@dnsmith124 @gprice1129 @sandrine-muller-research @cartmanbeck

**Comment by dnsmith124** [comment]
@sstemann for the UI's part, the change was to resolve a bug that was causing only the first result to show up when searching for chemicals. All the results shown in the drop-down now were still available, they just had to be searched for explicitly with the exact matching characters.

**Comment by sandrine-muller-research** [comment]
@sstemann on on the ARAX UI, when I search for synonyms, the SRI nodeNorm returns the PUBCHEM ID as the preferred one:
<img width="1238" alt="image" src="https://github.com/user-attachments/assets/6c3352fb-77b6-4d14-a8fa-e243fb8a133d">
 The ChEBI is in the same clique but I could not find the ChEMBL ID.

**Comment by dnsmith124** [comment]
Now that this ticket is referring specifically to the chemical autocomplete bug that was present in the UI and that issue has been resolved, I believe we can close out this issue. 

Closing.
