### ISSUE TITLE
Inferred Edge Should Match Query Graph Edge - MVP2

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#894]
At a TAQA meeting, I noted that there are times when the inferred edge has two predicates in the UI. I was informed that if the UI sent the query graph with the fully qualified predicate for MVP2, then the ARAs would returned the fully qualified predicate which would be displayed as one edge in the UI.

In CI, Gus updated the qgraph to include   
{
              "qualifier_type_id": "biolink:qualified_predicate",
              "qualifier_value": "biolink:causes"
}

Via testing, its apparent that BTE is not responding as expected to the fully qualified predicate.  While the results are not degraded, the ARA should respond with the inferred edge to match the fully qualified predicate and are not. 

so it looks like this for what decreases activity of a Gene:
https://ui.ci.transltr.io/main/results?l=BRCA2%20(Human)&i=NCBIGene:675&t=2&r=0&q=f9e5facd-7f98-4c62-800b-0d0e9bf309dd
Should be Causes Decreased Activity Or Abundance Of
![image](https://github.com/user-attachments/assets/18bae971-98e1-495a-8f4c-097603eea401)

and like this for what is increased by a drug (BTE is the only ARA returning inferred graphs here):
should be Increased Activity Or Abundance Caused By
https://ui.ci.transltr.io/main/results?l=Potassium&i=CHEBI:26216&t=3&r=0&q=7e8cc9fb-bdd1-4641-9307-f4c966f56c5c
![image](https://github.com/user-attachments/assets/dde16402-b1b0-433b-905f-bb1bef870862)

Adding another example for the other MVP2
What genes' activity may be decreased by: Benazepril
CI:  https://ui.ci.transltr.io/main/results?l=Benazepril&i=CHEBI:3011&t=4&r=0&q=05ca2afc-5b43-4981-9f98-cd8219a62f97

![image](https://github.com/user-attachments/assets/9f02d63a-a38e-4d76-8e77-e1ac6412a1b3)

**Comment by tokebe** [comment]
We're currently [tracking a bug](https://github.com/biothings/biothings_explorer/issues/834) that causes result edges not to have the proper qualifiers added. 

We're also [tracking another bug](https://github.com/biothings/biothings_explorer/issues/839) that causes some mismatches in edges that BTE will return as results as compared to the query edge. The intended behavior is that any direct-edge answer that matches the query edge (same or descendant predicate, matching qualifiers) will not be nested behind an inferred edge. Is this acceptable, or does it cause problems for BTE to return non-inferred edges in some results?

Between the two of these, this issue should be addresses once fixes are tested+deployed.

**Comment by sstemann** [comment]
sounds like a Guppy fix, so adding the label, please update if that timing is too aggressive.

**Comment by colleenXu** [comment]
I think the main part of this issue is now addressed in CI with [this fix](https://github.com/biothings/biothings_explorer/issues/834#issuecomment-2282340410). 

For an example, see this recent run https://ui.ci.transltr.io/main/results?l=Potassium&i=CHEBI:26216&t=3&r=0&q=8285b0ac-9200-4c50-8aab-27c2cc331536 (from https://github.com/NCATSTranslator/Feedback/issues/914#issuecomment-2282358299).

**Comment by sstemann** [comment]
1.  In CI and Test - what genes may Potassium decrease activity of - seems resolved per @colleenXu comment above and this URL in Test:  https://ui.test.transltr.io/main/results?l=Potassium&i=CHEBI:26216&t=3&r=0&q=4c686a03-6f68-41fa-b6eb-247dada9d091

1a. But if you look at the PK (4c686a03-6f68-41fa-b6eb-247dada9d091) of this URL in the ARAX GUI (https://arax.ci.transltr.io/?r=4c686a03-6f68-41fa-b6eb-247dada9d091)  there seem to be many BTE errors - so checking if this is by design/known issue (I think not, because in Test BTE only returns 34 results total, and in CI BTE returns 500 results)
![image](https://github.com/user-attachments/assets/a2922558-fb47-4ac4-84ba-d61354ed2fd6)

2.  In Test - what chemical may decrease ACE still returns the unqualified predicate from BTE. 
https://ui.test.transltr.io/main/results?l=ACE%20(Human)&i=NCBIGene:1636&t=2&r=0&q=f0cea81e-9920-44cf-be90-570cc70a4b75

![image](https://github.com/user-attachments/assets/3874cb6b-d199-4cfa-8f6e-d94f5f0b59ed)

![image](https://github.com/user-attachments/assets/cd6929ce-a6dd-4c63-993a-25014fdb493f)

3. This version of MVP2 seems to work in CI (due to ARS Error 444, you can't see it in the CI-UI), but this PK was initiated in the CI-UI
https://ui.ci.transltr.io/results?l=ACE%20(Human)&i=NCBIGene:1636&t=2&r=0&q=c66caed2-81ea-4847-9f69-918beeabfedf

https://arax.ci.transltr.io/?r=c66caed2-81ea-4847-9f69-918beeabfedf

![image](https://github.com/user-attachments/assets/ecc40e74-75a1-409a-96bc-02d20728da91)


Not sure if we can get the MVP2 - gene input version - fixed and to Test?

Not sure about the issue in 2

**Comment by tokebe** [comment]
The errors you describe in 1a are currently being tracked in https://github.com/biothings/biothings_explorer/issues/842, and relevant bugfix is on CI.

I wouldn't want to deploy CI -> Test right now given some issues we're working to address in CI at the moment.

**Comment by colleenXu** [comment]
Adding: 

The "inferred qualifier set" issue is being tracked in https://github.com/biothings/biothings_explorer/issues/834#issuecomment-2282340410 and the relevant fix is ONLY in CI right now. **This affects MVP2 queries in both directions (chem input and gene input).** 

@sstemann you mention the Test instance. Is there a showstopping/urgent need to address this Feedback issue and make a patch to Test? 
As Jackson mentioned, there are other problems we're working on in CI right now....and I think we'd like to finish addressing/fixing these other problems before requesting a Test patch.

**Comment by sstemann** [comment]
i do not consider this a showstopper.  thank you for checking.

**Comment by colleenXu** [comment]
Once we've confirmed that the Prod deployment was successful, we can close this issue. 

It's addressed by [834](https://github.com/biothings/biothings_explorer/issues/834#issuecomment-2282340410) ([my note](https://github.com/NCATSTranslator/Feedback/issues/894#issuecomment-2287837901)) and [842](https://github.com/biothings/biothings_explorer/issues/842) ([Jackson's note](https://github.com/NCATSTranslator/Feedback/issues/894#issuecomment-2286785806))

**Comment by sstemann** [comment]
woo!  thank you!  https://ui.transltr.io/results?l=BRCA2%20(Human)&i=NCBIGene:675&t=2&r=0&q=74f05ada-c336-4573-9878-5bda0b7c0e75
