### ISSUE TITLE
 "Adrenal Cortex Hormones" as a treatment (from BTE) from Semmed

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#904]
One more thing: the latest run returns "Adrenal Cortex Hormones" as a treatment (from BTE), returned as the third result. The path is inferred and the supporting paths are all of the type "adrenal cortex hormone - treats - _phenotype of Lyme Disease_". Looking at the literature evidence for (as an example) "adrenal cortex hormone - treats - fatigue", the papers all mention "corticosteroids". I'm wondering why the result node isn't labeled "corticosteroids" (instead of "Adrenal Cortex Hormones"). To me, "Adrenal Cortex Hormones" means the endogenous hormone, and not the pharmaceutical drugs that are called "corticosteroids" because they have corticosteroid-like effects, which I assume is what's referred to in the papers.

![Screen Shot 2024-07-08 at 11 20 16 AM](https://github.com/NCATSTranslator/Feedback/assets/1442197/a4473845-ceec-4760-910a-f6eaf5dabaa3)

_Originally posted by @khanspers in https://github.com/NCATSTranslator/Feedback/issues/175#issuecomment-2214911373_

**Comment by sstemann** [comment]
@tokebe this still happens in the latest Eel release, it looks like a Semmed issue that's coming through BTE.  Could you please take a look?

https://ui.transltr.io/main/results?l=Lyme%20Disease&i=MONDO:0019632&t=0&r=0&q=2b9fae93-54fa-4408-a036-93f6f09ba437

**Comment by andrewsu** [comment]
just to keep @tokebe focused on some other ongoing work, I'll look into this one...

**Comment by andrewsu** [comment]
yes, semmeddb is recognizing "corticosteroids" as "Adrenal Cortex Hormone" (`UMLS:C0001617`); example: https://biothings.transltr.io/semmeddb/query?q=predication.pmid:171776.  Nodenorm is then [resolving](https://nodenorm.test.transltr.io/get_normalized_nodes?curie=UMLS:C0001617) that to `MESH:D000305`. 

I'm certainly not an expert here, but based on this [definition from wikipedia](https://en.wikipedia.org/wiki/Corticosteroid), that mapping may be good and fine?

> Corticosteroids are a class of [steroid hormones](https://en.wikipedia.org/wiki/Steroid_hormone) that are produced in the [adrenal cortex](https://en.wikipedia.org/wiki/Adrenal_cortex) of [vertebrates](https://en.wikipedia.org/wiki/Vertebrates), as well as the synthetic analogues of these hormones.

So I'm going to close this issue on the rationale that these two labels are effectively the same thing, but feel free to re-open if others disagree...
