### ISSUE TITLE
include link outs to nodes based on their identifiers in UI results

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#91]
see #57  for more details.

in TAQA: we want link outs to external databases on nodes based on their CURI identifier. 
e.g. this node is from DrugBank, make a link to DrugBank, and then it's done.
this would be a CURI->URL expansion (we can get a Biolink jsonld file with all the approved prefix->URI expansions here: https://github.com/biolink/biolink-model/blob/master/prefix-map/biolink-model-prefix-map.json)

**Comment by dnsmith124** [comment]
Node link outs to external databases can now be found in the node's tooltip by hovering over it. Link outs have been mapped according to the approved expansions in the file above. 

Marking complete!
