### ISSUE TITLE
cannot search for potassium chloride

### ISSUE THREAD

**Issue by sandrine-muller-research** [NCATSTranslator/Feedback#917]
Potassium chloride is a treatment for hypokalemia:
![image](https://github.com/user-attachments/assets/9b39bc1f-263a-49da-8c9f-89621c45aaf1)

**Comment by sstemann** [comment]
i'm not sure we want to allow this, when we open up this selection, we much more frequently run into 0 results, this is related to the testing done on #885 

<img width="767" alt="image" src="https://github.com/user-attachments/assets/007c1f7e-ac21-4ece-ab5e-eb284b79fa30">

**Comment by sandrine-muller-research** [comment]
Oh! ok! 
FWIW, [Potassium chloride](https://www.ncbi.nlm.nih.gov/books/NBK557785/#:~:text=Potassium%20chloride%20is%20a%20medication,management%20and%20treatment%20of%20hypokalemia.) (KCl) is a medication in the treatment of hypokaliemia.

**Comment by sstemann** [comment]
duplicate/fixed by #885 moving this use case to that ticket
