### ISSUE TITLE
Streamline attributes on each node so that they are consistently available for the UI to display, filter or search levels.

### ISSUE THREAD

**Issue by sierra-moxon** [NCATSTranslator/Feedback#92]
see #57 for more details

From TAQA:
node attributes aren't consistent across results, some nodes have very few attributes at all, definitely not consistently searchable/displayable by the UI.

A discussion for architecture.

**Comment by sierra-moxon** [comment]
see also #76

**Comment by cbizon** [comment]
The Annotation Service is continuing.   I am transferring ownership of this issue to Andy and Chunlei.

**Comment by Genomewide** [comment]
Very close to being done, but will leave open until implemented.
