### ISSUE TITLE
It is good that the search terms/diseases listed when one starts writing "progeria" are related (Werner Syndrome and Hutchinson-gilford Progeria Syndrome are both segmental progeroid disorders).  However, they are quite different and the results for one wouldn't necessarily apply to the other.  Need a way of indicating with the suggested disease list pull down that no results are found for a particular disease (such as Hutchinson-gilford Progeria Syndrome).  Thanks Shepherd Schurman 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#93]
## Steps to reproduce:
Enter into search field: progeria
Select and search: Hutchinson-gilford Progeria Syndrome
Results come back for "Werner Syndrome" (and the search term is replaced), which is not the same disease as Hutchinson-gilford Progeria Syndrome

**Comment by capasfield** [comment]
Reviewed at TAQA. This is a known issue in Andy's group. There are mutliple tickets on this issue. It should be a high priority as users think their query has been changed. Sierra thinks this may be an easy (easier) fix. 

Sierra to find ticket that relates and assign it to Andy, David and Gus. Sierra will then close this ticket.

**Comment by sierra-moxon** [comment]
https://github.com/NCATSTranslator/Feedback/issues/44 is the issue with synonyms used as search terms being overwritten with the real term in the search bar.

**Comment by sierra-moxon** [comment]
closing for now.
