### ISSUE TITLE
INFG 1B category is incorrect

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#930]
## Steps to reproduce:
top result: interferron gamma 1b

**Comment by sandrine-muller-research** [comment]
The category should be protein like the [ChEMBL card](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1201564/) link states.Result from ARAX:
![image](https://github.com/user-attachments/assets/4a8af526-0b8a-4d3f-af81-394dd17ae812)
![image](https://github.com/user-attachments/assets/61054bb0-df56-47d9-8d6f-2e5cad80697b)

**Comment by sandrine-muller-research** [comment]
My bad, the protein is synthesized by E. Coli and used as an FDA approved drug
