### ISSUE TITLE
User wants edge directionality to be visible in the graph view

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#933]
User wants edge directionality to be visible in the graph view

I think this is a reasonable request, @Genomewide @reeserosedesign can we prioritize a quick design for this?

_Originally posted by @dnsmith124 in https://github.com/NCATSTranslator/Feedback/issues/847#issuecomment-2217990851_

**Comment by dnsmith124** [comment]
Arrows have been added to indicate edge directionality in the graph view in CI, will update once this has been deployed to TEST

**Comment by dnsmith124** [comment]
Feature live in Test, closing
