### ISSUE TITLE
I guess this is consistent and there is no evidence document listed yet for the results of "Werner Syndrome"?  Haven't tried other diseases as yet.  Thanks.  Shepherd Schurman

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#94]
## Steps to reproduce:
Search "Werner Syndrome"
Observations:
1. Under Evidence for all results- all results have "(0)" next to "View All Evidence"
2. Using Filters and with select bar farthest left "1" and checking box for Minimum Number of Evidence, get No Results

**Comment by capasfield** [comment]
Reviewed at TAQA. Work is already underway by Andy's team. Close issue.
