### ISSUE TITLE
Pathfinder Support Graph Display 

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#940]
I ran Pathfinder for Cystic Fibrosis and Joubert Syndrome

https://ui.ci.transltr.io/pathfinder/results?lone=Cystic%20Fibrosis&ltwo=Joubert%20Syndrome&ione=MONDO:0009061&itwo=MONDO:0018772&t=p&r=0&q=114f0fad-0b21-4248-94f0-fa0daa8dbd37

If you expand the first result - direct path, it looks like the support graphs (with genes) are displayed (i was expecting only direct paths)

<img width="586" alt="image" src="https://github.com/user-attachments/assets/980b9fa1-efd3-40bc-b37f-6768b8932175">

If you expand the second result - with gene intermediary, all of the paths EPC are "BTE" only 
<img width="566" alt="image" src="https://github.com/user-attachments/assets/b064faa6-7664-41b3-8690-22dd09a3af2e">

<img width="730" alt="image" src="https://github.com/user-attachments/assets/c94bcb16-0e21-4aa7-a4d5-e7ebc70d6aca">

It seems like the actual EPC is in the direct path.

**Comment by dnsmith124** [comment]
After reviewing this with Gus the data that's coming back from BTE appears to be correct--they seem to be intending to return predicted edges as in the first result. So the first result is actually being displayed as BTE intended.

Both of the edges in each path in the second result are also marked as predictions in the data, but presently the UI does not support displaying more than 1 support graph per path, so they are appearing like direct edges. This will require a change to the UI backend to fix

**Comment by Genomewide** [comment]
Another example:
https://ui.ci.transltr.io/pathfinder/results?lone=MAPK8IP3&ltwo=Amantadine&ione=NCBIGene:23162&itwo=CHEBI:2618&t=p&r=0&q=58abd604-0797-42ca-83b5-1b1ee6f8804b

<img width="1103" alt="image" src="https://github.com/user-attachments/assets/940e9440-8737-403e-a9c9-02fc21d82a91">


ARAX graph:
<img width="1636" alt="image" src="https://github.com/user-attachments/assets/de07770a-4457-4e9c-984d-cf1a41e70843">


In ARAX bottom edge
<img width="1636" alt="image" src="https://github.com/user-attachments/assets/6b6b0ac8-f765-496d-86ca-f0e1631cab9b">



Left edge:
<img width="1646" alt="image" src="https://github.com/user-attachments/assets/c7d50836-9e51-4852-ab13-2e1b9129e7a6">

Right edge:
<img width="1635" alt="image" src="https://github.com/user-attachments/assets/64c4f515-aaba-41d3-9baf-952086ea9f8b">

Inferred 'related' does not make sense to me for this?

**Comment by dnsmith124** [comment]
Gus has made changes to how the UI processes pathfinder data to remove these inferred related to edges, which have little practical value, and display only their support paths. This along with some optimizations I've made to the front end's processing of paths and the generation of graphs have resolved this issue. 

Generally I wait until changes have been deployed to test to close a ticket, but since pathfinder is currently only live in CI I'm going to go ahead and close this (as the changes have been deployed to CI)
