### ISSUE TITLE
Knowledge Collaboratory KP mostly responding with 500 error

### ISSUE THREAD

**Issue by isbluis** [NCATSTranslator/Feedback#946]
Queries from ARAX to Knowledge Collaboratory KP have resulted in http/500 errors for several weeks; we have logged over 40,000 such failures across all four maturities.  This greatly slows down the ability (of ARAX and Translator) to respond, as it seems to take a full 30 seconds to get the error response.

Example:
https://arax.ncats.io//index.html?r=293795
![image](https://github.com/user-attachments/assets/d5833abe-8f01-42ff-b0c3-944871c5f4d5)

Error count since 8/17:
![image](https://github.com/user-attachments/assets/12ebd0df-42f1-464b-ba9b-0d834d4bda64)

**Comment by sstemann** [comment]
@CaseyTa can you please review and let us know if this is something your team will take a look at or if it should go somewhere else

**Comment by micheldumontier** [comment]
one of the docker services related to nanopublication querying was crashing on every request. restarted the server, and seems to be responsive. please check again.

**Comment by isbluis** [comment]
This seems to be mostly- error-free for the past 8 days (there are still a few popping up, mostly in _CI_).
Closing.
