### ISSUE TITLE
OpenPredict KP often responds with 504 error in Test

### ISSUE THREAD

**Issue by isbluis** [NCATSTranslator/Feedback#947]
About 40% of queries from ARAX to OpenPredict KP have resulted in http/504 errors in Test; we have logged over 5,300 such failures for the past several weeks. This greatly slows down the ability (of ARAX and Translator) to respond, as it seems to take a full 60 seconds to get the error response.

Example:
https://arax.ncats.io//index.html?r=277461
![image](https://github.com/user-attachments/assets/055b4eb9-1bc5-47c8-a2eb-b87ebfb20d40)

Error count since 8/17 in Test:
![image](https://github.com/user-attachments/assets/3ffa388b-bed7-4be2-942a-4790bd4c645c)

**Comment by sstemann** [comment]
@casey can you please let us know if you're the right person to assign this one to?

**Comment by isbluis** [comment]
Hi @sstemann : I think you may have tagged the wrong Casey in the previous comment, above?

But my apologies if I am mistaken.

![image](https://github.com/user-attachments/assets/04a63ba2-9cc7-48f7-a8ba-a55b6fcb6280)

**Comment by sstemann** [comment]
you are right!  i assigned it to @CaseyTa but auto-selected to quickly.  @CaseyTa could you please take a look?

**Comment by CaseyTa** [comment]
@isbluis Are you still having this issue? I went to the example query and copied the query you're sending to OpenPredict from query edge `e0` and sent it to OpenPredict in all ITRB environments, and all respond within 1-2 seconds with status 200.

**Comment by isbluis** [comment]
@CaseyTa I have not seen these errors in the past few weeks; most were happening when I filed the initial report, and the _Test_ environment was on high load.  Closing , and will re-open if the issue resurfaces..
