### ISSUE TITLE
confirm "knowledge_type": "inferred" should return lookup answers

### ISSUE THREAD

**Issue by sharatisrani** [NCATSTranslator/Feedback#95]
(TRAPI query) When "edges" includes property {"knowledge_type": "inferred"}, then at least one ARA (ARAX) returns no results.  When that qualifier is removed, ARAX returns 500 results.  Is this the opposite of expected behavior?

No other ARA returns any results with our without that property.  Should this be an issue?

**Comment by capasfield** [comment]
Reviewed at TAQA. 

Known issues can return with an inferred result but it is not required. We have not explicitly merged inferred and non-inferred results. 

Discuss in the architecture call.

**Comment by dkoslicki** [comment]
Chiming in about the original issue since I just saw it had to do with ARAX: I'm 99% sure the reason why you're seeing no results with  {"knowledge_type": "inferred"} is that our ML model wasn't trained with whatever disease this query was about.

**Comment by sierra-moxon** [comment]
TAQA:
from architecture:
"lookup" results should be returned from "inferred" queries as well.
[PR was submitted and accepted.](https://github.com/NCATSTranslator/TranslatorArchitecture/pull/88) 
"biolink:knowledge_level" (recently accepted in DM call, but not implemented widely yet) is important here; it could be that we no longer need the "inferred" tag (at least in the UI) if we use "knowledge_level"

**Comment by dkoslicki** [comment]
The PR wasn't quite accepted yet, as there's a bit of clarification that I understand will be addressed on the next architecture call

**Comment by sierra-moxon** [comment]
@cbizon - PR is in the architecture team's court. :)

**Comment by andrewsu** [comment]
This issue has migrated sufficiently that I think it overlaps with #281. I'm going to take the initiative to close this ticket, but feel free to reopen if anyone thinks there is something different/unique here.
