### ISSUE TITLE
Inferred path with (extra?) "drug x - Same as - chemical x" hop

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#951]
In the results from the query "What drugs may treat conditions related to [Leukemia](https://monarchinitiative.org/MONDO:0005059)", one of the drugs returned is Anistreplase with several inferred paths. The first hop in one of the paths is "Anistreplase (drug) - Same as - Anistreplase (chemical)". I haven't seen this before, so I'm wondering if it's a bug that this is shown in the UI?  

Drug: (https://go.drugbank.com/drugs/DB00029) 
Chemical: https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL2108250/

<img width="1501" alt="Screen Shot 2024-09-19 at 9 39 22 AM" src="https://github.com/user-attachments/assets/914fbfe8-5343-41e1-8ec0-cd12160f1dec">

It's coming from ARAX/DrugBank.

https://ui.test.transltr.io/results?l=Leukemia&i=MONDO:0005059&t=0&r=0&q=012e64bb-8aa6-43b9-bc8c-a8f17d0ecbb3

Will update this ticket if I find other examples.

**Comment by sstemann** [comment]
looks like it's coming from ARAX, i'm not sure who to assign it to so asking @edeutsch to take a look

<img width="582" alt="image" src="https://github.com/user-attachments/assets/57b1f13c-8dc7-4398-a204-43df4524236f">

**Comment by edeutsch** [comment]
The current RTX-KG2 has some Drug - same_as - Chemical edges. Is that specifically disallowed?

In any case, the next RTX-KG2 in dev and CI no longer has these, so this will disappear in coming releases to TEST and PROD.

**Comment by khanspers** [comment]
Anistreplase is no longer returned as a result in [test](https://ui.test.transltr.io/results?l=Leukemia&i=MONDO:0005059&t=0&r=0&q=6467fc16-f157-40cf-ae99-2766cd58069a). Closing.
