### ISSUE TITLE
direction of arrows on "Translator Workflow" in homepage

### ISSUE THREAD

**Issue by gglusman** [NCATSTranslator/Feedback#955]
In https://ui.ci.transltr.io/, the arrows go left-to-right, as they should.
In https://ui.test.transltr.io/ and https://ui.transltr.io/ though, they go right-to-left:
![image](https://github.com/user-attachments/assets/7d4a3b90-14fa-4d03-8da8-81be6b72b8c8)

**Comment by dnsmith124** [comment]
I actually noticed this during the relay, and the fix @gglusman noticed in CI was implemented then. I'll update the ticket when the fix has been deployed to Test.

**Comment by dnsmith124** [comment]
This fix has been deployed to prod, closing!
