### ISSUE TITLE
Clicking on any evidence or relationship does not yield any information ("No Evidence Available"). 

The View All Evidence count on page 1 is 0, yet there are at least 13 pages of evidence. 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#97]
## Steps to reproduce:
Disease: Ataxia Telangiectasia

**Comment by sstemann** [comment]
fixes are in progress from the UI team and the consortium to provide the data

**Comment by gprice1129** [comment]
@sierra-moxon not clear if this should be closed or not.

**Comment by sierra-moxon** [comment]
I can no longer reproduce on https://ui.ci.transltr.io/ - I see evidence reported and the paths are clickable and I can get to evidence on the paths.  closing.
