### ISSUE TITLE
ChEBI Name insulin (human) for ChEBI ID CHEBI:5931 is labelled "Insulin Beef" by the ARAs

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#973]
Search "What genes may be upregulated by Insulin (human)?" CHEBI 5931 and in Test, the results are for "insulin beef"

https://ui.test.transltr.io/results?l=Insulin%20Human&i=CHEBI:5931&t=3&r=0&q=466f8a3b-43c1-40e3-a257-0280e357f4ae

![image](https://github.com/user-attachments/assets/f863063c-f460-4767-9ae7-ec0eddeb0dce)

It looks to affect all results that make it to the UI.  there are 878 results total, and when you text search for "insulin beef" all 878 are returned.

In Prod, the search is for "Insulin" (without the human part), but it's the same CHEBI 5931.  

The results however, aren't for "insulin beef" which seems like the behavior we do want.  If you search "beef" no results match.

https://ui.transltr.io/results?l=Insulin&i=CHEBI:5931&t=3&r=0&q=b0d3c65f-5887-4a91-8188-c70853834b5d

![image](https://github.com/user-attachments/assets/21bb8285-41fb-48b4-90f8-ff48b3844720)

CHEBI 5931 also shows up in MVP1 Results as Insulin Beef in Test (but not in Prod).

https://ui.test.transltr.io/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&r=0&q=d7e7118c-4758-42de-933c-804b3fb6aa62

![image](https://github.com/user-attachments/assets/60704511-2f7b-49fc-9c4e-874bce2b9357)

UI team has reviewed and confirmed that the UI uses node names as provided by ARAs.  So I'm wondering why ARA's are using "insulin beef" when the [ChEBI page is "Insulin (human)"](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=5931).  If you investigate the PKs for the test runs, it's happening for ARAGORN, ARAX, BTE and Unsecret.

**Comment by MarkDWilliams** [comment]
It should be the case that the ARS replaces any names that don't match the preferred ones returned by node norm, except in cases where an ARA has a name for a node and node norm does not.  I'll take a closer look.  Not sure yet what's happening.

**Comment by sstemann** [comment]
Resolved in Prod 

https://ui.transltr.io/results?l=Diabetes%20Mellitus&i=MONDO:0005015&t=0&r=0&q=0c7973ea-6639-4495-b917-1eba628e7e23
