### ISSUE TITLE
As the site acquires more users or expands its linked search terms in abstracts - adding a link to similar, but distinct disorders, in the future (concussion, TBI, coma from head injury, etc.) (each of the responses to spinal muscular atrophy) would potentially be useful.

I do appreciate the unexpected terms which come in the search window though - it is definitely a helpful way at addressing this ontological issue. 

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#99]

**Comment by sierra-moxon** [comment]
From TAQA:
Chris:
- we are good at finding a specific term, but users think more broadly about terms.  There are a lot of related term to the particular term in the ontology.
- the user wants "concussion-related things" - may not be subclasses or superclasses.
Tyler: 
- not just diseases but could be chemicals too -- the seventh result was insulin with all the evidence, but there were a lot of other kinds of insulin (different compounds!  porcine insulin), but users might not make a distinction between these.
Andy:
- FAQ section could be helpful "why is the result not something I typed in"?  

TODO: put this in TACT.

**Comment by sierra-moxon** [comment]
@tursynay

**Comment by sierra-moxon** [comment]
from TACT in March: this is a nice feature but can not get to it before September 2023
